### PR TITLE
display ornaments as icon

### PR DESCRIPTION
**Pull request by sundevour**
image
it's not bad looking.
it looks different which i know is always scary,

and the downside is that some armor ornaments are *slightly* different size/angle from their unornamented counterparts
image
image

but this is a *great* change that will respect people's aesthetic choices more, and help them distinguish between their items better without using up any extra layout space

### CODE REVIEW

**Comment by bhollis** [comment]
I'm pretty onboard with it!! I know some people will complain because their neurons are locked to one look, but maybe they shouldn't use ornaments then?

**Comment by bhollis** [comment]
I also love that they made a different background for the ornamented versions, so you can at least tell.

**Comment by duckmanBR** [comment]
My Solstice armor is appearing as a empty glow socket...

**Comment by sundevour** [comment]
cool, checking on it

**Comment by sundevour** [comment]
none of mine is showing up that way. is yours y2 or y3? can i get your inventory API response?

**Pull request merged**
