### PR TITLE
Store/load ratings and reviews to IndexedDB

### PR DESCRIPTION
**Pull request by bhollis**
This caches ratings info for 24 hours in IndexedDB, and only fetches for new items or items that were fetched >24 hours ago. This not only improves load performance, but fixes a bit of a bug where ratings would never update once loaded.

### CODE REVIEW

**Comment by bhollis** [comment]
I also set a 5s timeout on individual DTR loads and return an error if any of them fail rather than continuing on.

**Comment by 48klocs** [comment]
The saving/loading from IDB looks good, but I'm a bit concerned with the fail on the first of the errors coming back from the API.

A 5 second timeout makes sense, but I'm not sure about stopping with the API requests after we run into the first failure. From what I've seen, the DTR API errors (sometimes a Cloudflare 502, sometimes missing CORS headers) can happen intermittently within a fetch cycle. In the case that I was looking at, I saw 40 requests go in a batch, and 6 failed. Retrying those 6 manually, I couldn't reproduce the error (neither could they), so it could be a CF anti-spam measure getting triggered or something else. Still trying to get a solid reproduction case put together for it.

**Comment by bhollis** [comment]
Can we increase our batch size so we don’t have to do so many requests?

**Comment by 48klocs** [comment]
I pinged them about bumping up the number of items we fetch in a single call. I have a feeling that that could alleviate some of the problems (my theory, not that I have anything backing it up, is that Cloudflare is dropping requests since fetches I guess kind of look like flooding).

**Comment by bhollis** [comment]
Cool. I'll put the try/catch per request back in there then.

**Pull request merged**
