### PR TITLE
Update Source Hashes

### PR DESCRIPTION
**Pull request by delphiactual**
#1578

### CODE REVIEW

**Comment by delphiactual** [comment]
This could be automated by using the `identifier` which are all in english no matter the selected language e.g. `SOURCE_VENDOR_NEW_MONARCHY`

**Comment by bhollis** [comment]
Why would the vendor hashes change by language?

**Comment by delphiactual** [comment]
they dont, but they did get updated to new hashes with this update. my comment was in regard to be able to use the identifier to automate this in case the hashes change in the future again

**Comment by bhollis** [comment]
That's weird, I would have expected the hashes to stay stable too. Definitely should switch to the names if they aren't.

**Comment by delphiactual** [comment]
Confirmed by vthornheart they were not meant to change, so no need to change to identifier...

**Comment by delphiactual** [comment]
vthornheart [8:23 PM] 
I did a little digging just to make sure that was the only spot, and if you refer to any DestinyActivityCategoryDefinitions or DestinyActivityModeDefinitions they have a potential to change as well.  I've added a bug to myself to make sure this gets fixed for D2, but just a heads up.

**Pull request merged**
