### PR TITLE
Redo ClickOutside

### LINKED ISSUE #5909: ClickOutside doesn't work when clicking outside content
Current beta, Chrome on Windows 10.

How to repeat.

- Go to the Progress tab
- Click on any Quest or Quest Item (say Chalice of Opulence)
- The detail sheet comes up
- Click anywhere else on that part of the page, and the sheet does not go away
- The only way to make it go away is to click on it again or to click in the left bar menu

This is different to the items in the Inventory tab, where clicking off them closes the detail sheet.  It's also different from what used to happen before the buttons were moved to the right rather than bottom of the detail sheet.

### PR DESCRIPTION
**Pull request by bhollis**
Fixes #5909.

A recent version of React reworked how event handlers behave, and this meant that the tortured stuff I was doing to make event listeners work through portals was no longer necessary, and we can listen at the document level to boot.

### CODE REVIEW

**Comment by nev-r** [comment]
repro:
- click item tile
- click :pencil2: **Add a note**

**Comment by nev-r** [comment]
repro: 
- hover a character's PL so the hover tip comes up
- now character banner clicks do nothing

**Comment by kyleshay** [comment]
nice! was just reading up again about ref callbacks. cool to see em in use.

**Review by kyleshay — APPROVED** [review]

**Comment by bhollis** [comment]
Well that's a bummer that it doesn't work. It seemed to at 1:30am. I had an earlier, much more complicated version that should solve the problems.

**Comment by bhollis** [comment]
OK wow the notes one is really interesting - what's happening is that the `document` click handler is firing *after* React has already rerendered the notes field and removed the element that fired the event. So by the time the handler fires, the event target actually isn't contained in the popup!

**Comment by bhollis** [comment]
OK, *now* it should actually work.

**Review by nev-r — APPROVED** [review]
spot testing looks good now

**Pull request merged**
