### PR TITLE
Set the number of slots to clear in farming mode

### PR DESCRIPTION
**Pull request by imeredith**
Allows the number of slots to be set for farming mode. My post master seems to fill up even with farming on so I'm hoping this will help.

This is my first time adding anything to DIM, so let me know how I can improve things. I'm not totally happy with the input box, I feel like it would be better with a +/- widget but this was easy to do.

image

### CODE REVIEW

**Comment by bhollis** [comment]
Thanks for the contribution! Farming mode is in a tricky place right now as the API is having a lot of trouble giving an updated view of your inventory in time. Plus, too many rewards at once in the loot stream these days. This might be a good solution. In general we try to avoid options and making everything configurable in favor of making stuff just work. I wonder if we should either just change the space rules in general (keep all unlocked and move the rest, for example) or retire farming mode for now while Bungie sorts out their API issues.

**Comment by imeredith** [comment]
I think this being configurable maybe makes sense in this case. In my case I would probably use 3 slots and 8 slots depending on what I was doing. But I would be ok if it just was 3.

I have noticed the issues with the API too. While farming mode is not something I have used recently much due to there only being one slot freed, I have friends that basically keep it running always, so I think it would be a mistake to remove. Even if its not totally reliable, its still better than nothing. 

At this point though I feel like farming mode for me is almost a misnomer, its more like "Please stop my postmaster from maxing out from me literally doing anything in the game as I get over 9000 blues every time I play the game"

So in this regards, the  other option I would be ok with would be for something to periodically check my postmaster, pull any blues directly to vault, and then pull the whole thing if its getting full. The advantage to this is that we would only need to check every few minutes at least, and if I threshold of say 15/21 items was set , hopefully that would give enough room for the API inconsistencies.

**Comment by bhollis** [comment]
I think rather than making this configurable we should change the rules. Something like only keeping locked/tagged items.

**Comment by imeredith** [comment]
Actually I would be totally into that. I'll make that change to the pr

**Pull request closed without merging**
