### PR TITLE
[i18n] Materials Exchange

### PR DESCRIPTION
**Pull request by delphiactual**
Added i18n to materials exchange

### CODE REVIEW

**Comment by bhollis** [comment]
Can we hold off on this? Materials exchange and other beta-only features are likely to undergo a ton of change and I don't want to put effort into translating stuff that's going to get reworked a bunch.

**Comment by delphiactual** [comment]
Sure, but I believe i18n should be part of all features from the beginning, instead of being tacked on. Strings can be adjusted and just not translated to other languages until after reaching stable.

**Comment by bhollis** [comment]
I agree that i18n is important, but I don't want folks to waste time translating strings that may be replaced.

**Comment by Korben85** [comment]
I would suggest to add the i18n even in beta mode. when someone only wants to translate when it is in an official release it's ok. I think it doesn't make a big difference and for me for example it's ok when a previous translation is gone or changed.

**Comment by bhollis** [comment]
OK, as long as folks are OK with their translations being deleted when we update strings.

**Pull request merged**
