### PR TITLE
Expanded font glyphs and picker with custom font

### PR DESCRIPTION
**Pull request by Gix3612**
Addressing issue [#8990](https://github.com/DestinyItemManager/DIM/issues/8990).

I didn't make all glyphs in the font available in the symbol picker. I didn't want to overfill the picker window so I kept the list limited to abilities and some other select symbols I thought users would find useful for names, notes, and tags. These were solely based on my opinion so I'm happy to change it and can even try to create new symbols for the font based on other's suggestions. Plus, anything not in the picker can still be inserted manually into a note field and will show up and be auto-completed in tags anyways.

Some of the glyphs have api counterparts so that they can be translated automatically, however, the table type used wasn't supported (or they were Objectives but didn't have a fromRichText to draw from). I added them to TranslateManually but put the api sources in comments to save time later in case anyone can add the needed support.

Many symbols are from the destiny-icons repository meaning they were created from high quality svg files, however, a large number of them (mainly the ability icons) were not available so I generated them from Destiny package files with an image-to-svg converter. That said, most of the images available were low resolution and generated very ugly svg files. I intent to go through and redraw the low resolution symbols, but given the scope of changes needed I elected to pack them as-is for now since they are still recognizable and will update the font file as I, or anyone else who wants to contribute, does so.

### CODE REVIEW

**Comment by robojumper** [comment]
Thanks for taking a stab at this. Some general comments:

* Everything in `src/data/` is automatically generated in https://github.com/DestinyItemManager/d2-additional-info and cannot be edited in the DIM repository itself.
* I don't think our symbols should be in the same `FontGlyphs` enum as the base symbols. A separate enum like `DimCustomSymbols` doesn't hurt I think; `translateManually` can just be a union of some `FontGlyphs` members and some `DimCustomSymbols` members.
* It'd be good to automatically generate the table lookups for DIM custom symbols in the same way as d2ai: https://github.com/DestinyItemManager/d2-additional-info/blob/727d01b012e7f51ab7f1015208dbfd67db2b0939/src/generate-symbols.ts
* The list of tables we can pull localization from can totally be expanded. 
* As I mentioned in #8990, I think the DIM project needs a way to generate this font file itself in some way because:
  * We must be able to re-generate the font file in the future when symbols are added or updated.
  * Custom symbols need to be stable; we need to guarantee that with future additions or removals the font contains the same symbols at the same code points
  * The source SVGs should be available so that they can be changed later.
* Expanding on the code points, Unicode has Private Use Areas in three different planes. Can we use a different plane for our symbols? I'd be concerned Bungie updates their font and we run into code point clashes.

**Comment by Gix3612** [comment]
Thanks for the feedback. 

I didn't know about the d2-additional-info. After a short look through it, if I'm understanding the workflow correctly, it looks like I need to add the glyph names to `src\generate-symbols.ts` and in order to create separate enums I need to make a second `src\generate-font-glyph-enums.ts` as something like `src\generate-custom-glyph-enums.ts` that points to the custom font and generates the `Dim-Custom-Symbols` file you mentioned. Will I still be modifying `src\app\dim-ui\destiny-symbols\destiny-symbols.tsx`, `config\i18n.json`, and `src\app\main.scss` in the DIM repository directly still or did I miss something in d2-additional-info to generate those?

Additionally, for testing purposes, when I generate the data with d2-additional-info will I need to pull the updated data to my Dim fork manually somehow or does the generation process automate that as well?

As for generating the font file itself, I had already planned to upload the good SVG icon files to destiny-icons as I finished them so they will be available to everyone. With generating the font file directly from the SVGs, I wouldn't even know where to begin myself, but changing the codepoint range to a new Private Use Area would be simple to do at that point anyways. I can also easily change it manually if we don't have anyone with the time and knowledge to create the font generator right now and as far as maintaining code points across updates we could use logic something like this:

1. Scan folders for icon SVG files.
2. For each file, compare it against `Dim-Custom-Symbols.ts` and reassign the existing code points there that match the file.
3. For unmatched files, append them to the end of the list with new code points.
4. Generate the font using this data.

Then when the `Dim-Custom-Symbols.ts` is generated again, it will lock in the newly added glyphs for future updates and with this method we would be able to implement the font generator after already using a manually created font to retroactively maintain the same code points.

**Comment by robojumper** [comment]
> Will I still be modifying `src\app\dim-ui\destiny-symbols\destiny-symbols.tsx`, `config\i18n.json`, and `src\app\main.scss` in the DIM repository

Yes, the first two only to localize the symbols we couldn't match to definitions for localization, the stylesheet change LGTM.

> Additionally, for testing purposes, when I generate the data with d2-additional-info will I need to pull the updated data to my Dim fork manually somehow or does the generation process automate that as well?

For testing purposes you have to copy it manually. When changes in the d2ai repo are merged, they're automatically synced over to the DIM repo though.

> With generating the font file directly from the SVGs, I wouldn't even know where to begin myself

Based on a cursory look at what packages are available, it looks like https://github.com/nfroidure/svgicons2svgfont has a good and flexible API to turn individual SVGs into an SVG font, and d2ai already pulls in a package to convert between font formats (so SVG -> WOFF2 ought to be possible) https://github.com/DestinyItemManager/d2-additional-info/blob/b102044085d0e8f411649d2308434117fcf9a358/src/generate-font-glyph-enums.ts#L22-L25

**Comment by bhollis** [comment]
Might be best to do these as slack/discord style codes, e.g. `:raid:` instead of a font?

**Comment by robojumper** [comment]
@bhollis that would certainly be possible and probably give us more future flexibility. The one drawback I can think of is that native `<input />` and `<textarea />` elements would not display our custom symbols, which could be very confusing because the Bungie-official symbols are shown and there's no real reason a user would expect different behavior between symbols.

**Pull request closed without merging**
