### PR TITLE
Delete generated manifest JSON

### PR DESCRIPTION
**Pull request by bhollis**
This PR removes all the generated manifest JSON files and images, plus the `processManifest.js` script.

It's best to look at the first two commits on their own - the third is just the big delete, and it's a ton of files.

A note about the images. I talked with @SunburnedGoose about this on Slack, but I think it's time to stop bundling the images. Some reasons:

1. It saves 30MB and ~5,000 files from the extension. That translates to less download time and wasted bandwidth and disk space for users.
2. The reason for bundling the images was to help some users whose firewall settings prevented loading the images, but still allowed bungie.net access. I don't doubt these folks exist, and they are likely vocal, but they have to be a very small part of our overall user base. Imposing this cost on everyone just for them seems unnecessary.
3. We don't want to have to continue building a release every time Bungie updates the manifest. But we know that a lot of the icon URLs change between manifest releases, even if the item itself didn't change. So we'd either have to release on manifest changes again, or the images would break more often than they do now (again, for this small segment of users).

That said, I could be convinced to keep a stripped-down version of `processManifest.js` that only produced the images, if we decide that's what we want.

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
We made a product that people like to use during the day when they are thinking about Destiny.  That means it's going to be used in a many unique environments.  It isn't much of a burden to maintain this ability to load images when pulling down the API data.

30mb package is only downloaded when we release updates.  This is a non-issue.  

To support these users, we need to create a stripped down JSON file that only maps the itemHash, progressionHash, etc and their iconUrl.  The JSON files for these backups will much smaller than their current versions so the memory footprint for these backups will likewise be much smaller than the current files.

If the users get an error loading an image, then we can look up the image in the backup manifest file, and load the local image.  We don't have to update this manifest file very often because the number of items in Destiny doesn't change very much unless there is a large update (SLR, Festival of Lights, Classified Items).  Those are in-frequent updates and we can maintain our usual steps of loading the 'missing-icon' icon in the cases where there is no backup image.

**Comment by bhollis** [comment]
@SunburnedGoose we don't even need a JSON file - we just have the same files as we would have mapped, and use the `bungie-image-fallback` directive like we do today. Like I said, I can put those back.

I disagree that it's worth it though. How many people have a network configuration at work that allows bungie.net but not bungie.net *images*? That's a weird setup! Does their workplace just ban all images in general? We don't know much about this specific case? Are there 2 people in this situation? 100? 1000?

**Comment by kyleshay** [comment]
It is true that it's odd people can hit the API but not load the images... we loading. Worth some investigation.

We _are_ hitting bungie.net images with [`http`](https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/store/dimBungieImageFallback.directive.js#L17) and not [`https`](https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimBungieService.factory.js#L177) like our api endpoints... possibly their networks are banning non `https` requests?

**Comment by bhollis** [comment]
Maybe somebody had a firewall rule banning http://bungie.net/* to try and stop Myth 2 players???

**Comment by SunburnedGoose** [comment]
All I can say is I got messages when I removed them in May '15, and when you removed them in Dec.  I'm not ready to get messages on the cusp of Rise of Iron. 

We can instrument the image miss directive with Google Analytics and see how many sessions suffer. We can talk about this again after we get data and the user base has settled a few weeks into September.

**Comment by bhollis** [comment]
Can you follow up with the people who sent you messages?

**Comment by SunburnedGoose** [comment]
No.

**Comment by bhollis** [comment]
Hokay then.

Do we have any examples of tracking events with Google Analytics in the codebase today? Can I have access to the GA dashboard?

**Comment by SunburnedGoose** [comment]
The code is already in DIM. I'll turn it on.

**Comment by bhollis** [comment]
OK, this change has been rewritten. We now only stop producing JSON from `processBungieManifest.js` - images are still downloaded. I've tested that image fallback still works. I did a full refresh of the images (delete common, redownload and sync everything, so the third commit now reflects the 1800 or so images that were either missing or outdated.

**Comment by bhollis** [comment]
I'm going to merge this into manifest-service. We can revisit the images once the analytics data comes in.

**Comment by SunburnedGoose** [comment]
One thing I'm not clear on.  When are the fallback image manifest files being generated?

**Comment by SunburnedGoose** [comment]
Looking this over and you're just downloading the images.  Where is the relationship between this cached icon path url, and the itemHash/perkHash being persisted?  

It can't be created by your new manifest service.  That's always up to date afaik.  You need a JSON file that maps the iconUrl that is generated at build time with an itemHash and I just don't see that anywhere.

**Comment by bhollis** [comment]
That's right, there is no such thing. If the manifest URLs update, then the
fallback images won't work anymore. We'd need to do a release (but just to
fix the folks who are using the fallback). Do you know how often it is that
the manifest updates change URLs for existing items and don't just add new
things?

I can do what you're suggesting by maintaining a whole fallback image map,
but it adds a bunch of complication to the code for this rare case.

Let's release with the GA events and see how often we do fallback before
building a big complicated workaround for this issue. I wish we really knew
what the problem was for these folks - I bet we could figure out a way
around it that didn't involve all this stuff.

**Comment by SunburnedGoose** [comment]
It thought the point of the GA setup was to measure before we removed.

**Comment by bhollis** [comment]
Yeah, definitely. That's why this PR was against the manifest-service
branch and not dev.

**Comment by SunburnedGoose** [comment]
Missed that, thanks!

**Pull request merged**
