### PR TITLE
Make DIM Fast Again: Replace Fontawesome SVG with font

### PR DESCRIPTION
**Pull request by as-com**
So it turns out that the slow rendering times were largely caused by Font Awesome... so I got replaced react-fontawesome's SVGs with webfonts where possible. This simple(ish) change (among others) dramatically decreases render times and improves responsiveness. 

Note that there may be lingering CSS/alignment issues that I didn't catch in my quick sweep.

### CODE REVIEW

**Comment by as-com** [comment]
@bhollis Indeed, this does increase the bundle size of the CSS, but in the end the SVG version of Font Awesome was contributing a very significant portion of CPU time used while rendering (I peeked into the source code of react-fontawesome and it was... bad). Even [Font Awesome's documentation ](https://fontawesome.com/how-to-use/on-the-web/other-topics/performance)says admits the SVGs are CPU-intensive.

Personally, I think the extra couple hundred kilobytes of fonts and CSS is worth the reduced CPU and memory usage. If the increased weight is a problem we can look into subsetting the webfonts and/or using [PurgeCSS](https://purgecss.com/).

**Comment by bhollis** [comment]
Do you happen to know why this variant of Fontawesome also includes several large SVGs into the bundle? I'm guessing they're SVG webfonts but I'm not sure.

I have no problem making the tradeoff back to fonts if it really does improve rendering speed, as long as we also keep the display right (the fonts were notoriously hard to size and position as well).

**Comment by as-com** [comment]
The SVGs are SVG webfonts - they're only requested when the browser doesn't support "normal" webfonts, which shouldn't happen for DIM.

**Comment by bhollis** [comment]
OK. I'll have to test this one out.

Would you mind moving all the React.memo changes to a separate PR? While I'm sure some of them are helping, excessive use of React.memo can actually slow things down as it forces a property-by-property comparison that may not always be appropriate.

**Pull request merged**
