### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by Korben85**
Hi, I sorted the keywords in the dimApp.i18n.js file alphabetically for a better overview.
I also added a new Translation in the settings screen.

Is it correct, when I add the language="KEY" into a label tag? If this is not working pls discard this change.

### CODE REVIEW

**Comment by bhollis** [comment]
Cool! I'm not sure about sorting the keys - they're loosely grouped by functionality right now, as an accident of how they were entered. @delphiactual, I'll wait for you to weigh in on it before I merge.

**Comment by delphiactual** [comment]
I'd rather leave them sorted by functionality until the list is more feature complete, then we can sort by alphabet...

**Comment by Korben85** [comment]
Okay,
so I'll close this request and work on the original (not sorted) file instead.
Just thought that it might be to much work later to sort the translations by alphabet.

**Comment by kyleshay** [comment]
we could namespace/prefix the keys by function. might be useful as the list starts to grow. seems to be working now though, just a suggestion.

**Pull request closed without merging**
