### PR TITLE
Revert "Don't automatically show dupes in Compare"

### PR DESCRIPTION
**Pull request by bhollis**
I got cold feet on this, I don't want to have to deal with people whining about it. I'll change things when Compare gets redone.

### CODE REVIEW

**Comment by kyleshay** [comment]
I think it's fine because it just requires clicking a button to compare dupes. I agree sometimes I want to compare two different weapons. it's really just what do we want as the default.. waiting until a full compare refresh is cool though. were not really taking anything away

**Comment by bhollis** [comment]
Yes but people will complain about it incessantly

**Comment by kyleshay** [comment]
ahaa, true true

**Comment by delphiactual** [comment]
https://www.reddit.com/r/DestinyItemManager/comments/jhgdix/compare_tool_doesnt_pull_all_weapons/

**Review by nev-r — APPROVED** [review]
fine with me. i would like buttons revamped and in a really great place before telling people to rely on them

**Pull request merged**
