### PR TITLE
Introduce the Sheet UI component

### PR DESCRIPTION
**Pull request by bhollis**
The Sheet is a touch-enabled component that slides up from the bottom of the screen, and can be closed by swiping it down off the screen (it also has a close button and responds to the Escape key). This sort of UI element has become popular on mobile recently, featuring a lot in iOS 12.

I intend to use this as the basis of revamping the mobile item popup, but for now I've applied it to the compare and loadout drawers, which are relatively simple to convert.

sheet-loadouts

### CODE REVIEW

**Comment by bhollis** [comment]
sheet-loadouts-ios

**Comment by duckmanBR** [comment]
There's any way to let it stay "half drawn"?
Example: On the compare tool on mobile.  Some weapons will make the window go full height.  That way you won't be able to add more items by clicking them on the inventory.  If I can pull just a little and it stay that way I'll be able to add the itens I want and then pull up again to compare them.

**Comment by kyleshay** [comment]
Amazing!!! Major building block for mobile ux!

Small thing, but you can open both a loadout and compare sheet at the same time

**Comment by inexorableAce** [comment]
Makes me want to swipe up to get to these things 🤔maybe there is potential there for that.

**Comment by kyleshay** [comment]
The other thing is that it is not possible to scroll the page when comparing or making a loadout, which makes it hard to add more than 1 or 2 armor types

**Comment by kyleshay** [comment]
Last thing, also v minor: on desktop we should consider just showing the X, and mobile just show the horizontal bar

**Comment by duckmanBR** [comment]
No problem on scroll inventory with compare/loadout open.
Android 7, Chrome Beta 71

**Comment by duckmanBR** [comment]
About opening both compare/loadout at the same time, that's already possible on prod (at least on mobile)

**Comment by bhollis** [comment]
The new pattern in iOS 12 includes both the bar and close button. My guess is their usability testing showed some people never understand swiping. 

The scrolling works around an issue where you can’t swipe the dialog because it scrolls the underlying body. Google “body scroll lock” for details. I’ll keep poking at it but for me the solution is using search to fill compare.

**Pull request merged**
