### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by bhollis**
A grab bag:

1. Fix GA logging for infuse/compare - infuse was firing on every page load.
2. Tweak item popups to have better colors, allow clicks through the transparent parts of the sidecar.
3. In the dropdown, don't allow clicking disabled entries
4. Fix padding for category strip on mobile

### CODE REVIEW

**Review by kyleshay — APPROVED** [review]
thank you!

**Comment by bhollis** [comment]
image

@kyleshay here's another one - the Postmaster was still a collapsible thing when we had the category strip enabled, now it's flattened out like everything else.

**Comment by jollyjap** [comment]
Is it possible to change the ‘Loadout’ button on sidecar to add the item to an a existing load out. You can already create a new loadout on the character drop down

**Comment by bhollis** [comment]
@jollyjap that's kind of already how loadouts work. Open a loadout for editing, then click the things you want to be in the loadout.

**Comment by jollyjap** [comment]
@bhollis I was suggesting that the “Create” Loadout button on. The sidecar could be used to add a single item to an existing loadout; rather than opening and load out and then searching for the item you want to add

**Pull request merged**
