### PR TITLE
Revamp login screen

### PR DESCRIPTION
**Pull request by bhollis**
Made a bunch of changes to both the design and functionality of the login screen:

1. Remove the "reauth" parameter - the big button always auto logs you in if you have a Bungie.net session, and the "log in with a different account" continues to do as you'd expect.
2. Add a link to the privacy policy.
3. If localStorage says you had previously had DIM Sync turned off, and you turn it on, present a warning, a backup button, and add a confirmation before you leave the page if you haven't backed up.
4. If you turn DIM Sync off when it was on, warn that that's a bad idea.
4. Clearer help links.
5. Moved the login help stuff into the fandom wiki.

Links to #6774

Original:
Screen Shot 2021-05-30 at 5 28 59 PM

New (default, no prior state):
Screen Shot 2021-05-30 at 5 29 09 PM

If you turn off DIM Sync:
Screen Shot 2021-05-30 at 5 29 16 PM

If you previously had DIM Sync off and you're re-logging-in:
Screen Shot 2021-05-30 at 5 43 22 PM

### CODE REVIEW

**Review by inexorableAce — APPROVED** [review]
These seem like great changes to me. Awesome stuff :D

**Comment by nev-r** [comment]
the "you had previously disabled" red error box, while red, feels pushed down into the footnotes basically. in the name of Making A Best Effort on behalf of users, i want to one or more or all of:
- turn auth button red
- turn dim sync button red
- move warning up next to auth button
- remove "(Recommended)"

idk just. something.

does it default off if previously off?

**Review by delphiactual — APPROVED** [review]

**Comment by bhollis** [comment]
We can certainly be more obvious about it. And yeah it will default to off if it was off previously.

**Comment by bhollis** [comment]
@nev-r thinking about it more, does the confirmation before leaving without a backup do the job? I feel like it's pretty hard to ignore the way I've set it up.

**Comment by bhollis** [comment]
Gonna let this bake but I'm open to more improvements

**Pull request merged**
