### PR TITLE
Fix floating season tag, remove max height

### PR DESCRIPTION
**Pull request by bhollis**
Removing the max height because people seem to dislike scrolling more than they like dragging items?

### CODE REVIEW

**Review by nev-r — APPROVED** [review]
wish this were a case where we could make the dragging resize the sheet instead of just bouncing it back

**Comment by bhollis** [comment]
#7721 is the only idea I had

**Comment by inexorableAce** [comment]
I dunno that I would do this yet. Perhaps once quick add has a way to tell items apart. I think for now we can sit on this. Perhaps consider a wider layout for weapons. But I don't think we need to do anything right away. Most feedback on the new loadout drawer layout has been positive. I while I don't disagree that big weapons loadouts could look / work better I don't know that this the answer either, not yet anyway. 

I'd sit on it for a bit personally.

**Comment by bhollis** [comment]
The wider layout for weapons that adapts to how many items there are will be tough!

**Pull request merged**
