### PR TITLE
add seasonalDupe as keyword

### LINKED ISSUE #5504: Exodus Dawn armor wrongful dupe
While this is up for debate, since the name and descriptions of the armor are the same, they count differently for quests and have different appearances. I'd argue they are therefore different and shouldn't be highlighted when searching for `is:dupe`.
image
image
image
image
image
image
image

### PR DESCRIPTION
**Pull request by delphiactual**
closes #5504

### CODE REVIEW

**Comment by delphiactual** [comment]
on hold pending another term

**Comment by Revadike** [comment]
Has this been dispatched to live yet? Because I still experience the issue with `is:dupe`.

**Comment by delphiactual** [comment]
because you want `is:seasonaldupe`

**Comment by Revadike** [comment]
hmm, sadly that isn't working either. It is still counted as dupe.

**Comment by Revadike** [comment]
Seems like a highlighting issue, because the item count does go down, yet they are still highlighted

**Comment by Revadike** [comment]
image
image

**Comment by Revadike** [comment]
DIM (Destiny Item Manager)
Version 6.28.1 (release), built on 9/7/2020, 5:19:27 AM

**Comment by delphiactual** [comment]
@Revadike do me a favor and post the object contents for both of those items please

**Pull request merged**
