### PR TITLE
Feedback for beta armor compare view

### PR DESCRIPTION
**Pull request by kyleshay**
Main feedback:

required:
- [x] use floor() instead of round()
- [x] non split-stat items are over 100%
- [x] less colors

for future consideration/issues:
- ~~back to dim button issues?~~
- filter on int/str, int/dis, dis/str on compare view

### CODE REVIEW

**Comment by wein3967** [comment]
I like the idea of filtering on stat splits (e.g. int/str). The "back to DIM" refresh issue has already been address, according to Reddit page. I'm all for 3 colors rather than a gradient.

**Comment by bhollis** [comment]
For colors, consider these links:

https://eagereyes.org/basics/rainbow-color-map
http://colorbrewer2.org/

I have trouble making out the purple text here:

screen shot 2016-05-02 at 10 19 05 pm

**Comment by kyleshay** [comment]
0 - 85 = red
86 - 90 = orange
91 - 95 = yellow
96 - 100 = green

happy to adjust, but it seems to make sense. i'd post an updated picture (i also made the colors sligggghtly more saturated, nothing crazy) but DIM isn't pulling down perks so the numbers are screwed up. maybe i should add a fix for that... disable % rating if we don't have perks. makes sense. hopefully perks will normally be there though.

screen shot 2016-05-03 at 2 43 10 pm
screen shot 2016-05-03 at 2 43 19 pm

**Comment by SunburnedGoose** [comment]
That is much better.  SO much better.

**Comment by kyleshay** [comment]
cool! say we're good to merge?

**Comment by wein3967** [comment]
I like this coloring a lot.

**Comment by SunburnedGoose** [comment]
Can you use a silver color for 100% rolls?  Something to make them stand out?

**Comment by kyleshay** [comment]
screen shot 2016-05-03 at 3 45 44 pm

what about a blue/diamond color?

screen shot 2016-05-03 at 3 44 17 pm

**Comment by SunburnedGoose** [comment]
Blue is much better.

SHIP IT!

**Comment by wein3967** [comment]
What! No flashing border ;)

**Pull request merged**
