### PR TITLE
Add "is:transmat" search filter for Transmat Effects

### PR DESCRIPTION
**Pull request by mikevb1**

### CODE REVIEW

**Comment by bhollis** [comment]
Nice. I was planning on just adding `itemCategoryHashes` to the item and checking in the filter, instead of adding a bunch of new properties, though.

**Comment by mikevb1** [comment]
Another thought I had was adding an `itemCategories` property, list of `DestinyItemCategoryDefinition`. That might be a bit better down the line than `itemCategoryHashes`.

**Comment by bhollis** [comment]
Yeah, the old `categories` was there for D1 compatibility - I've got a branch somewhere that modernizes it all.

**Comment by philkernick** [comment]
It would be good to be able to answer the question: Which ships have a rare transmat effect?

I don't think that this feature will allow it, but could be extended to do so.

is:rare is:transmat would show rare ships with any sort of transmats applied, but doesn't look at the rarity of the plug.

**Comment by bhollis** [comment]
Closing in favor of #3143.

**Pull request closed without merging**
