### PR TITLE
define classified items in the manifest instead of factory and add Skull Mask

### PR DESCRIPTION
**Pull request by v-fedorov**
Keeps the source a little cleaner if items are manually added into the items definition.

Also added icons and removed api key since https url is still public.
`sometimes the manifest js will throw an error on the url for some reason so just try again`

### CODE REVIEW

**Comment by v-fedorov** [comment]
Fixes #326

**Comment by SunburnedGoose** [comment]
Thanks for the effort though.  Always feel free to bounce an idea in the issues tracker.

**Comment by v-fedorov** [comment]
Yep no problem, you'll be seeing me around :)

**Comment by SunburnedGoose** [comment]
Send me your email address and I'll invite you into our slack space to chat.  You can PM me at  http://reddit.com/u/sunburned_goose

**Pull request closed without merging**
