### PR TITLE
Highlight account dropdown

### PR DESCRIPTION
**Pull request by bhollis**
Folks are having a lot of trouble finding the account dropdown. This is a simple attempt to highlight it.

screen shot 2017-09-09 at 2 53 04 pm

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Looks fine.  Here's something different.  What if you just showed the game/platform in the dropdown, and only showed the account name for the selected account?  There is a lot of information in that drop down.  I tend to scan by the game/platform over my gamertag.  Some people have the same name for all accounts and it doesn't help at all.

Thoughts?

**Comment by bhollis** [comment]
That'd be good. Ideally I'd have some nice icons to put on them.

**Comment by bhollis** [comment]
Let me merge this for now and get back to the other idea later.

**Comment by SunburnedGoose** [comment]
Yeah, not a blocker here.  Just throwing that idea out there.

**Pull request merged**
