### PR TITLE
update formula, simplify logic

### PR DESCRIPTION
**Pull request by kyleshay**
based on the work by @Apsu in issue https://github.com/DestinyItemManager/DIM/issues/303

the diff is borderline useless, [here is the just the updated code](https://github.com/DestinyItemManager/DIM/blob/0d1f04814a089bc91c18577ab54168db69061014/app/scripts/infuse/dimInfuse.factory.js#L26-L41)

### CODE REVIEW

**Comment by Apsu** [comment]
Cool! This is almost right, except that Math.round in Javascript doesn't actually do IEEE 754 "Round Half To Even" rounding, unfortunately. It does "Round Half Up". Here's a link to a pretty robust function that could be used for it, but there's various implementations of Guassian/Banker's/Half-Even rounding out there in various libraries: http://stackoverflow.com/a/3109234

There's even a few relatively simple ways to try to solve it for just 0.5 (0 decimal places in result), that might be good options.

**Comment by kyleshay** [comment]
ok, updated.

does the rounding seem right? 

rounding

**Comment by cdacamar** [comment]
That can be fixed:

```javascript
f = (n - i).toFixed(8);
```

**Comment by kyleshay** [comment]
:+1: thanks @cdacamar

**Pull request merged**
