### PR TITLE
Fix docker-compose file

### PR DESCRIPTION
**Pull request by benjsnellings**
Docker compose file had improper syntax and would not build.

### CODE REVIEW

**Comment by delphiactual** [comment]
@0sanity @LongLiveCHIEF

**Comment by benjsnellings** [comment]
This is the error message that you get when trying to run `docker-compose up`.
```
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 19, column 22
```

**Comment by LongLiveCHIEF** [comment]
What version of compose are you using?

**Comment by benjsnellings** [comment]
docker-compose version 1.23.2, build 1110ad01

I am also on

**Pull request merged**
