### PR TITLE
[WIP] Vault Organizer

### PR DESCRIPTION
**Pull request by bhollis**
image

This is a WIP sketch of how the Vault Organizer could work. I haven't spent much time on UX - just getting to the point where there's basic functionality. The code especially is still pretty darn messy. I'm hoping especially @sundevour and @vivekhnz will be able to really enhance this based on their knowledge of what hardcore and causal players will want. The basic functionality I wanted is:

* [x] Show items in a table
* [x] Filter to a particular weapon/armor type
* [x] Support arbitrary search queries as filters as well
* [x] Sortable column headers, with reasonable sorting for different types
* [x] Select which columns to show
* [x] Selection and bulk action
* [x] New home for spreadsheet downloads

Still TODO, feel free to claim one of these:

* [ ] Decent styling for the item type selector
* [ ] Refactor into more components (for example, the column selector and bulk actions)
* [ ] Better handling of data dependencies (e.g. determining columns)
* [ ] Support D1
* [ ] Bulk tagging
* [ ] Bulk moving
* [ ] Inline tagging
* [ ] Inline notes
* [ ] Better stat displays (Recoil, maybe mini bars)
* [x] Display perks in a reasonable way. I'd like to have this be basically a flat list of perks as icon+text, without worrying much about what rows and columns they're in, but I'm open to suggestion. No idea how to sort them for example.
* [ ] Clear selection on query change (it does it on type selector change now)
* [ ] Move column selector into a dropdown menu
* [ ] Restyle spreadsheet downloads (another menu button?) and remove from settings
* [ ] i18n at all
* [ ] Tweaked styles for some of the columns (wishlist, etc)
* [ ] Save column config to settings
* [ ] Put path in router so reload takes you to the same page

### CODE REVIEW

**Comment by bhollis** [comment]
OK, I've added some basic perk/mod stuff and other styling: 

image

Even though most of the TODOs are still there, I'm thinking I'd like to merge this, enabled for dev only. That way more folks can try it out and work on it. I can move the remaining items to an issue or milestone. Thoughts?

**Comment by imeredith** [comment]
I just tried it out and it looks like a great start. The reason  I was even looking at the repo today is that I am so frustrated by managing armour 2.0 - I would love to tie this into loadout optimizer so that I can tell when I get a new piece of gear that improves my stats of the specific loadouts I have. I currently have 6 sets -  arc, solar, void recovery and intellect builds, and its a nightmare to know what gear to keep and replace.

**Comment by rslifka** [comment]
I think it would be great to see how this is intended to be used, i.e. what problem is this solving? @imeredith mentions Armor 2.0 which I agree with.

For example:

1. After a play session, my inventory (and part of my vault) are now full of randomly rolled pieces of armor. The wishlist doesn't yet allow me to mark armor by stats, and having to see if the 50+ pieces I obtained while turning in Light-Infused Fractaline are better than what I have.
1. Well then, we have a tool for you! It's the Organizer!
1. First, you do THIS
1. Then you do THIS
1. Et voila, you've just marked all of this stuff junk in a fraction of the time.

...you know, something like this. I would love to see DIM more opinionated about how it is used. It might not be for everyone, but if it's designed for everyone, it might not be for anyone.

**Comment by rslifka** [comment]
*Weapons*
Wishlists are the solution here in terms of the deluge of weapons we get from the seasonal activity. Voltron et. al. make it easy to figure out what makes it past the first gate of "quickly delete or not". Now the second gate is "Is this better than what I already have?" That's one possibility of a set of use cases. How might the Organizer help here?

*Armor*
The more I think about this, the more I really do like the use cases centered around armor since we're absolutely drowning in armor these days and armor is not supported by wishlists, nor could it be because you're not interested in a static yes/no, you want to know if it's better than what you already have. How might the Organizer help here?

Maybe all this commentary is better in the Discord ;)

**Pull request merged**
