### PR TITLE
Add DestinySets and VendorEngrams.xyz to header

### PR DESCRIPTION
**Pull request by bhollis**
There are two other tools besides DIM that I use when playing D2 - DestinySets.com and VendorEngrams.xyz. Since I don't really want to duplicate them both inside DIM right now, I figure we should link out to them so DIM users know these tools exist.

/cc @joshhunt

### CODE REVIEW

**Comment by bhollis** [comment]
screen shot 2017-12-29 at 7 33 15 pm
screen shot 2017-12-29 at 7 33 21 pm

**Comment by bhollis** [comment]
Note: These links are not localized since they're the name of the site. I'm hoping having the full domain will make it clear they're not DIM.

**Comment by joshhunt** [comment]
😍

**Comment by duckmanBR** [comment]
Destiny Sets have localized versions, but I don't know if we can pass the language in the link...

**Comment by SunburnedGoose** [comment]
I would not make it so prominent in the headers.  Let's make a page that hosts other sites that we use with a small blurb. 

DestinyTracker
DestinySets
VendorEngrams
D2 Checklist

**Comment by SunburnedGoose** [comment]
Can we keep the hamburger menu for all resolutions.  You could add them there to avoid another page, while keeping them out of the header on desktop.

**Comment by duckmanBR** [comment]
I like the idea of a "other tools" or even "partners" page so we could explain/make it clear that ratings come from DestinyTracker, that the user could find what is missing on his/her collection on DestinySets or even flag with witch character he/she could contribute to VendorEngrams...

**Comment by bhollis** [comment]
OK, I'll close this and maybe somebody else can add a partners page.

**Pull request closed without merging**
