### PR TITLE
Loadout stats.

### LINKED ISSUE #7313: Loadout drawer shows stats of items as currently configured, not how they'd be with saved mods
### DIM Version

Version 6.92.1.1000886 (beta), built on 11/25/2021, 11:30:21 AM

### Browser Details

Version 97.0.4692.20 (Official Build) beta (64-bit)

### OS Details

Windows 10

### Describe the bug

1. I created a build in Loadout Optimizer.
2. The stats in the Loadout Optimizer window are displayed correctly.
3. Pressed the 'Save Loadout' button to get the Loadout tray at the bottom.
4. The stats here are incorrectly displayed for Resilience and Recovery for some reason and don't match what was displayed in the Loadout Optimizer window (step 2 above).

Screenshot - 
image

### Logs

_No response_

### LINKED ISSUE #7469: Stats don't match between Loadouts page / Mod Assignment, and Mod Assignment shows different mod assignments than what gets applied
### DIM Version

Version 6.95.0 (release), built on 13/12/2021, 12:35:34

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

https://www.youtube.com/watch?v=4cdW6A-_Vas

The above video is me going through and showing the bugs take place.

In summary: The stats shown in DIM do not match the actual/in-game stats from the built loadouts. Also, Taking Charge and Elemental Ordnance are being applied to the wrong armour piece, and not following the build on DIM? Not sure if exclusive to those mods, or i've created the loadout incorrectly, but yeah.

insipidAce#3333 made a good comment on the Discord server here which may relate to what's happening - https://discord.com/channels/316217202766512130/333464468241514497/919811656316518420

### Logs

_No response_

### LINKED ISSUE #7472: Stats on Loadouts page, Loadout edit drawer, and mod placement menu should reflect loadout stats
Right now those all show the items in the loadouts as they're currently configured - instead they should show the stats as the loadout was configured - with Stasis and mod changes factored in. Note that this still may not be the same as what was shown when creating the loadout in LO since that may have considered masterworked stats. We might want to show a note if that's the case.

We also could maybe consider not showing the loadout stats in all these various places and try to consolidate on just showing it on the Loadout page?

### PR DESCRIPTION
**Pull request by ryan-rushton**
This PR ensures loadouts have the correct stats when accounting for the subclass, items, and saved mods.

One thing to note with this is that the main function will add stats for all the mods passed in. That means if mods won't fit, we could have incorrect stat values. I personally think this is fine, and the user will get the correct the correct stats when they use the `Show mod placement` button.

A potential fix would be to run the assignment algorithm at all times and just eliminate the button. How we display mods at this point would be an open question.

Fixes #7472 
Fixes #7469 
Fixes #7313

### CODE REVIEW

**Comment by ryan-rushton** [comment]
I had another thought regarding in game consistency. These stats could differ to the in game stats once applied due to the fact we don't empty all sockets (both subclass and armor). Should we attempt to convey this or leave it as a known?

I think it still makes sense to show stats for the things a person has selected in the loadout. Maybe it makes sense to show a warning/info that stats in game will be different after application due to this? Thought?

**Review by nev-r — APPROVED** [review]
"show mod placement" might be better labelled "preview applied mods" or something like that, to help emphasize that it's the source of "truth" compared to loadout editor stat numbers. not sure about the answer to many of these questions. it's really hard to communicate the superimposed states of live, applied, and added.

anyway, these stats look a ton more accurate than current, which seem to be double counting or something

**Comment by bhollis** [comment]
I still think it'd probably be best to just not include stats on the Mod Assignment page :-)

**Comment by ryan-rushton** [comment]
> I still think it'd probably be best to just not include stats on the Mod Assignment page :-)

Yeah I can remove them, I am not too fussed on them being there or not

**Comment by ryan-rushton** [comment]
> anyway, these stats look a ton more accurate than current, which seem to be double counting or something

Yeah they are kinda double counting. The old method was pulling the live stats off the item, so if it had mods socketed it would use those. Now we are pulling the base stats and adding mods and masterworked where they exist according to the loadout.

**Comment by nev-r** [comment]
wouldn't that remove the last place to get accurate expected tiers

**Comment by ryan-rushton** [comment]
I don't think so. To get accurate expected tiers we should be doing the following

1. Get base stats from the items
2. Run the mod assignment algorithm to get the mod placements
3. Reconcile the above with the currently equipped mods and figure out gets kept on the items, creating a "final mod assignment"
4. Get the stats from the final mod assignment in 3
5. Add in the masterworked stats

That I believe would give the most accurate stat representation if you hit apply I think

**Comment by ryan-rushton** [comment]
Or do you mean removing the stats in the assignment drawer?

**Comment by ryan-rushton** [comment]
If you mean stats for the mod assignment drawer, then we are only missing 3 from my list above.

**Comment by nev-r** [comment]
i guess my argument is either placement sheet should have stats or main sheet should have placement & accurate stats

**Comment by ryan-rushton** [comment]
Yeah gotchya, I might merge this as is and we can iterate on what the stats should look like. I think this provides a better base to do that.

**Pull request merged**
