### PR TITLE
Always hide kill tracker perk in new perk display

### PR DESCRIPTION
**Pull request by kyleshay**

### CODE REVIEW

**Review by bhollis — COMMENTED** [review]
Is there a reason we want to hide it only if enabled? I'd intended to hide it always

**Comment by kyleshay** [comment]
I renamed the existing function -- that one looks to see if it is enabled and is used to determine to show the kill tracker count. yeah i think we'll always want to disable the perk display

**Comment by kyleshay** [comment]
for context, here is what the old perk display does: https://github.com/DestinyItemManager/DIM/blob/master/src/app/item-popup/ItemSocketsGeneral.tsx#L122

**Comment by bhollis** [comment]
Yeah I think we want to match that

**Pull request merged**
