### PR TITLE
Add a Contributor Guide

### PR DESCRIPTION
**Pull request by bhollis**
Just something simple that'll hopefully help new contributors. A link will show up in a banner whenever somebody goes to file a PR.

### CODE REVIEW

**Comment by kyleshay** [comment]
thanks for putting this together, would say this also closes #112

**Comment by kyleshay** [comment]
@SunburnedGoose would you mind giving this a once over since you were the owner of 112? Anything else to add?

**Comment by kyleshay** [comment]
@bhollis maybe we should also consider adding  a link to this guide to the [README](https://github.com/DestinyItemManager/DIM/blob/dev/README.md)?

**Comment by bhollis** [comment]
Good idea

**Pull request merged**
