### PR TITLE
Easier drag and drop on mobile

### PR DESCRIPTION
**Pull request by kyleshay**
I wanted to try a prototype of drag + drop on mobile =>

I could move the other interactions like infuse/take/etc to the drop targets also, but figured try this for now.

Still some minor quirks and needs a little more testing, but I wanted to get some feedback.

Also snuck in another minor tweak- If I dragged an item to equip, sometimes that would be treated as a swipe left, and it would update my active character.

rec

### CODE REVIEW

**Comment by sorahn** [comment]
TLDR:
Looks great, transitions are a little slow.

----------

Google has done some excellent work on duration and easing in their material guidelines.
https://material.io/guidelines/motion/duration-easing.html

I'm not saying to adopt the entire material design spec, but there are a couple key points.
> Transitions on mobile typically occur over 300ms, within this margin of variance:
> 
> Large, complex, full-screen transitions may have longer durations, occurring over 375ms
> * Elements entering the screen occur over 225ms
> * Elements leaving the screen occur over 195ms
> 
> Transitions that exceed 400ms may feel too slow.

Scroll down a little farther and check out the 'Deceleration curve' and the 'Acceleration curve' (including css `transition-timing-function`s)

So, recommendations:
```
transition-enter-duration: 225ms 
transition-enter-timing: cubic-bezier(0.0, 0.0, 0.2, 1);
```

```
transition-leave-duration: 195ms
transition-leave-duration: cubic-bezier(0.4, 0.0, 1, 1);
```

**Comment by bhollis** [comment]
I really like this. What do you think of making the drop targets a bit bigger and adding a `backdrop-filter: blur(10px)` for some "native" fanciness?

**Comment by bhollis** [comment]
@kyleshay what do you want to do with this? I'd love to at least try it in beta under a flag.

**Comment by kyleshay** [comment]
ok, ill rebase and throw a flag in for the beta

**Comment by duckmanBR** [comment]
Hey @kyleshay , now that I could test it, any chance of the popup appearing on top instead of below? just because my finger is on the way.
Also, if you don't do nothing the bar stays up and sometimes you need to activate it with another icon because simply tapping anywhere won't make it go away.

**Comment by kyleshay** [comment]
good suggestions, i'll push a fix later today. thanks for trying it out. think I need to make the drop targets a little bigger and more obvious when they're active/hovered

**Pull request merged**
