### PR TITLE
Overhaul the infusion calculator

### PR DESCRIPTION
**Pull request by bhollis**
I did a bunch of work on the infusion calculator! I believe it's much more useful now. In fact, I think it's so useful that I promoted its button into the move popup.

* Infusion auto calculator is much faster. It's so fast there's no reason to make you click a button anymore...
* Items in the infusion calculator don't grey out when a search is active anymore.
* Full cost of infusions is now shown, including exotic shards, weapon parts / armor materials, and glimmer.
* Show a better error message when trying to equip an item for the wrong class. Before it would say you weren't experienced enough.
* Add a button to the infusion calculator that moves the planned items to your character.
* Add a filter to the infusion calculator to limit the search to only rare (blue) items.
* The infusion auto calculator runs automatically, and now presents a list of different attack/defense values for you to choose from. Selecting one will show the best path to get to that light level.
* The infusion calculator greys out items that are already used or are too low light to use, rather than hiding them.
* The item move popup now has an entry for the infusion calculator, to make it easier to find.

[Demo video](http://i.imgur.com/TwJbHx2.gifv)

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Nice.  What's left besides merging?

**Comment by bhollis** [comment]
Take a look and see how you feel about the changes! There's a lot in there.

**Comment by SunburnedGoose** [comment]
Wilco.  I'll pull the PR locally and test it out.

**Comment by bhollis** [comment]
I've got some more changes - some are just fixes, but there are some visible changes:

* Visibly highlight the items that are used in the recipe.
* Add path length to the dropdown.
* You can now hold Shift and click an item to exclude it from calculations - for when you have an unlocked item that you still don't want to use for infusing right now.

**Comment by kyleshay** [comment]
wizardry! just scrolled through the code. looks awesome :+1:  thank you @bhollis!

**Pull request merged**
