### PR TITLE
Loadout creator refresh

### LINKED ISSUE #3587: Loadout Builder (Mobile) Needs Height Limitation with Background Scrolling
The Loadout Builder has some sizing issues on the mobile platform. If you can limit its maximum height to make sure there's enough room to see 1-2 rows of items in the background, that should be efficient enough. The background also needs to be scrollable to avoid having to save the Loadout every time you need to scroll to add another item.

Here's a video that shows the problem. Note that I started with a Loadout that was quite large and used to be editable before recent changes.  

[screenshot_20190202-131436](https://youtu.be/93CED9uBxbI)

### PR DESCRIPTION
**Pull request by bhollis**
Screen Shot 2019-03-19 at 9 08 21 AM

This is a work in progress refresh of the basic loadout creator tool. I'm looking for early feedback!

My goal is to make things easier to use, especially on mobile, while also making it easier to understand both how to create loadouts and what is available when creating them. I'm also adding the oft-requested "clear out everything else" option.

Some interesting points:

1. Added "+Equipped" to add equipped items even once the loadout creator is open.
2. Added a link to the Loadout Builder (renamed Loadout Optimizer to make more sense).
3. Quick bar of buttons to add loadout-compatible items, which brings up the item picker. This is to help mobile users and to make it more obvious what's available. The buttons disappear once you've added one item, which is a choice I'm not sure about.
4. Items in the loadout are displayed like they are in inventory, including the white box for equipped, instead of the spartan helmet. The idea is people will recognize the correspondence.
4. Quick-add buttons on each bucket allow for adding items using the item selector, which will do some smart filtering.
5. Unavailable items can be clicked to select another item with the same hash.
4. Drag and drop, and clicking on items in inventory still work.

Tapping an item still toggles whether it equips, but I'm looking for something a bit better. I'm also struggling a bit with the layout - I want it to look just like the inventory when full, but collapse down better when a bucket is empty. So far I can get one or the other reliably.

Intended to fix #3587, #2729 (partially), and #2230.

### CODE REVIEW

**Comment by inexorableAce** [comment]
I like it. "+equipped" seems a bit vague, specially with the other plus type buttons. Maybe "start from equipped" or something more explanatory. Otherwise this is awesome.

**Comment by bhollis** [comment]
@inexorableAce any thoughts on nicer button / form component styling?

**Comment by duckmanBR** [comment]
Liked!

1 - Agree with ace, but any other wording choice I can think is too big for a button.
3 - all those buttons will fill half the screen on mobile.  Maybe put then on a stack and when you click it 
 the button becomes the item bucket?

**Comment by bhollis** [comment]
@duckmanBR what do you mean by a stack? I tried lining them all up on the left but they end up too tall and you have to scroll.

**Comment by delphiactual** [comment]
PULL FROM {CATEGORY} TO `FOOOO`

**Comment by delphiactual** [comment]
Should we update the route for `loadoutbuilder` to `optimizer` as well?

**Comment by duckmanBR** [comment]
@bhollis, something like this (ignore the helmet becoming kinetic :sweat_smile:):
image image

And with the layout you're planning (with the bucket label and layout from inv) any full armor/weapon set loadout would require scrolling, no?

**Comment by inexorableAce** [comment]
It's going to require scrolling on mobile no matter what you do. Do not design around preventing scrolling you will fail. I'd probably opt for just removing those buttons altogether and having the sections for each type always visible with the plus button you have in them. That way when you press a plus to add you have the context of where you are and what you're doing no matter the layout and you see it happen no matter the layout cause you're right there.

**Comment by bhollis** [comment]
I was thinking that it’d work like that on mobile (vertical stack) but since the dialog can be super wide on desktop I wanted to use that space. I suppose another thing to try is making a very thin and tall sheet (basically the mobile interface all the time) though I think that’d be frustrating if it covered the vault or something.

**Comment by inexorableAce** [comment]
yeah we are on the same gave let the sections go the full with and let the wrap when on mobile. crude PS job attached. Im basically saying just remove the add buttons and let ALL the sections stay there even when empty with just a plus button in them. 

desktop
desktop

mobile
mobile

**Comment by bhollis** [comment]
That’s where I started, but it ends up super messy since there are so many types.

**Comment by bhollis** [comment]
Screen Shot 2019-03-21 at 11 22 59 PM

Here's kind of what it looks like on mobile now.

Here's an alternate where the buttons for empty sections are interleaved:

Screen Shot 2019-03-21 at 11 29 11 PM
Screen Shot 2019-03-21 at 11 29 29 PM

**Comment by inexorableAce** [comment]
The buttons inline at the top doesn’t take up much room at all now that I’m seeing it in practice and it feels a lot cleaner than interleaved. I’d go with what it looks like now opposed to interleaved.

**Comment by duckmanBR** [comment]
The main difference between on top x interleaved is that unless you start your loadout "from the bottom up" you're going to need to scroll up/down after the 3-4th section...

**Comment by inexorableAce** [comment]
Interleaved makes you scroll basically no matter what you do and makes it harder to find the buttons I think. Easier to have all your action buttons in one place.

**Comment by bhollis** [comment]
Cool! I do think we need a better button design - the form at the top is oddly spaced and the buttons end up too small on mobile...

**Comment by duckmanBR** [comment]
Maybe a mix of both then? All the buttons inline but when you "open" a section you separate them...
image

**Comment by inexorableAce** [comment]
Based on what Ben showed once you click a button and add something the big button goes away anyway and is replaced by the smaller circular add button in the section, so I think we’re good. It’s essentially the “mixed” view currently. 

Ben I’ll connect with you offline about button design so we can hash out the issues and think up something better. 👌

**Comment by Wh1rledPeas** [comment]
I was just trying this out tonight in beta. Huge thanks for making Loadouts work on mobile again!

One thing I noticed was the [+] Grab Item buttons seem inconsistent as they move around when things are added/removed. When the position of buttons change, it really slows down the user's experience because they always have to hunt for the button. It also feels inconsistent with their positioning in the normal inventory layout. I'm wondering if it would look/feel better if they were always below item # 1? Even if it's a short row until enough items are added to create a second row.

I also thought perhaps they would fit on the row with the section headers, to the left, so they're all lined up. The buttons all have a plus on the left already, albeit smaller. But that would be inconsistent with the inventory layout.

I also want to point out that the "save new" button is off-screen, with no horizontal scroller. Perhaps a diskette 💾 icon for "save" and a plus ➕ fie "save as". You could also get smooth and if the text in the name box matches an existing Loadout, show the save icon and if it doesn't match anything, show the save-as icon. That would eliminate the need for two buttons and provide immediate feedback, showing that they've typed a loadout name that's already in use.

**Comment by delphiactual** [comment]
Screenshot_20190323-232142

**Comment by bhollis** [comment]
I just made a push to make those buttons wrap better.

Please submit feedback and bugs as separate issues - they're hard to track as comments on closed PRs.

**Comment by Wh1rledPeas** [comment]
@bhollis: Sorry. I didn't think about that. The layout looks much better now. With all the buttons being the same size, it looks much cleaner too. 

@delphiactual: Yes. My text & screen sizes are increased to make up for my poor eyesight. (I'm 49, with cataract implants) I understand that my case isn't normal and do expect inconsistencies. Sometimes things become unusable when panels don't scroll. As long as the items wrap when the display edge is too tight, that's all I need.

**Pull request merged**
