### PR TITLE
Loadout Optimizer Rework

### LINKED ISSUE #3468: Loadout Builder filtering wrong items
image
I have only one chest piece with Enhanced Unflinching Sniper Aim, so any further locking shouldn't change the loadout.

Hand Cannon Reserves - changed the class/bond
image

Riven's Curse Mod changed Head/Arms/Legs/Class
image

It's not a mobile bug because I reproduced it on desktop.
Tried to debug further but had no time to do it.

### LINKED ISSUE #3571: Loadout builder could use option to filter on tag
Specifically I’d like to exclude anything with tag:infuse or tag:junk, but I can also see value in being able to prefer tag:favorite or tag:keep.

### LINKED ISSUE #3610: Loadout Builder out of memory
Current beta, Chrome on Windows 10.

How to replicate:
1. Select Loadout Builder
2. Wait for the "No Generated Builds Found" spinner to finish.
3. Uncheck "Exclude Mod Bonus"

It gets to 99% Generating Builds and then crashes the tab with "Aw, Snap!".

### PR DESCRIPTION
**Pull request by bhollis**
A few weeks ago I started working on the performance of the Loadout Optimizer, and I pretty quickly found myself in the middle of a major rewrite and redesign. This is the result - I plan on merging this after the release today, so we can get a full week of beta testing. I'll also record a screencast walking people through it.

The major strategy change is in how sets are generated. Before, we would brute-force generate every combination of items to form sets. This led to long load times and memory exhaustion as we built a set of millions or tens of millions of sets. It also made the display less than useful - in many cases we'd show long lists of the same stat mix. Worse, we weren't including the effect of alternate perks (choosing resilience instead of recovery, for example) and by default were excluding the effect of perks on stats entirely. Factoring those in (and adding Ghosts, which I did later) exploded the combinations into the billions.

In the new system, I first gather up all items and group them by their stats. I included them in multiple stat groups depending on their different perk options as well, which captures alternate configurations. Then, I find all the combinations that can be made given these stat groups. This tends to find thousands of combinations, not millions, and is fast enough to run at interactive speeds. I then present sets by "mix" - groupings of unique stat spreads per item. Each of those mixes remembers the items that have that stat profile per bucket, and we display the highest-light incarnation of that mix. You can use the "swap" buttons to lock a different piece in order to access other builds.

Beyond that, a lot of work went into moving things into line with React best practices, so most everything is reactive from minimal state, and things are memoized to reduce redundant computation.

First off, here are changes people may be upset about:

1. I don't show mods/masterwork anymore. There just wasn't enough room and it looked bad.
2. Locked items and perks aren't broken out by armor type anymore, so you can't easily just pick "legs perks". All the perks are in one big menu now, and you can search and scroll to find what you want.
3. "Stat mixes" can be repeated in the list (for example, a 8/3/3 build may appear multiple times) because I'm grouping by the individual pieces, not the overall stat mix. Each instance of the mix represents a unique combination of stats, even if the same result can be obtained from multiple combinations (for example, swapping a high-recovery helmet for a high-recovery chest). This could be confusing.

And here are the rest of the changes (there were a lot, so I may have missed some):

1. Generating sets is very fast (interactive speed), with a new strategy as explained above.
2. Ghosts are now included in the loadouts, purely for perk selection (they don't affect stats, but hey neither do class items).
3. All stat possibilities are considered, including selection of alternate perks. When an alternate perk should be used, it is highlighted in orange.
5. New layout on desktop and on mobile, which hopefully maximizes screen usage and utility. Narrowed down to a single collapsible section for filters (on mobile) and a sidebar on desktop.
5. All stat mixes are shown in a virtualized list, instead of having a "show more" button. This allows you to scroll to any point in the thousands of mixes but only pay the cost for whatever's on screen.
4. Filtered perks are highlighted in green.
5. You can shift-click on perks to lock them directly.
6. Stat filters only allow you to select stats within the bounds of possible stats.
6. The stat filters can be rearranged via drag and drop in order to change the way stat mixes are ordered in the list (e.g. if you prefer Recovery, drag it to the top and Recovery-heavy mixes will be shown first).
7. Power filtering can be done with a slider or direct input, instead of a dropdown.
8. Items can be searched using our full search language, so you can search "vigil of heroes" or "source:gambit". If no items match the filter, they are all included, so you won't accidentally end up with no combos. (_TODO: I should figure out how to tie this together with the search box in the header_)
9. Locking/excluding items and perks is now done through a searchable sheet, with items/perks from all buckets shown together. Perks in particular got a new search sheet with each perk shown in full detail.
10. Each stat mix shows the full perks grid with tooltips, and includes buttons for choosing alternate items with the same stats. The number of potential combinations is shown next to each mix, which really drives home how many possibilities there are.
11. Added icons to stats.
10. Just a ton of little design tweaks for things I noticed across the app, such as fixing the ammo type icon on perks, giving a shadow to the thumbs-up on perks, making sockets sized based on the item size setting, and properly scaling intrinsic perks relative to selectable perks in all cases (e.g. Gambit Prime armor that has multiple intrinsics).
11. Added a "create empty loadout" button and some help text in order to remind people that we have a from-scratch loadout creator.
12. All the CSS has been redone as CSS modules.

Screen Shot 2019-05-19 at 10 48 09 AM
Screen Shot 2019-05-19 at 10 48 19 AM
Screen Shot 2019-05-19 at 10 48 28 AM
Screen Shot 2019-05-19 at 10 48 44 AM
Screen Shot 2019-05-19 at 10 49 08 AM

localhost_8080_index html(iPhone 6_7_8) (1)
localhost_8080_index html(iPhone 6_7_8)

* Fixes #3610
* Fixes #3571 (by adding search filters, so just do "not:tag:junk")
* Fixes #3468

### CODE REVIEW

**Comment by bhollis** [comment]
I’m going to merge this to get live feedback, but please continue to give comments on the code and the functionality/design either through this issue or new ones.

**Comment by kyleshay** [comment]
awesome work ben!!! love the new page layout and the perf!

**Comment by kyleshay** [comment]
Having some issues dragging an item to "lock it" as well as if an item is already locked (using the lock equipped button) the 'X' button does not remove it from the locked list.

**Comment by inexorableAce** [comment]
Wow this is great! 

couple visual issues / usability things: 

- some builds have some odd wrapping this is Chrome / Win 10
image

- when excluding items, and locking perks would be nice if the card did not close after choosing. for mobile I can see what that would be a thing, but in my particular case I searched for exotics and wanted to lock all but the one I wanted (which I assume is a fairly standard practice. having to click, reopen, research, click and repeat was not awesome. Perhaps just show them as "selected" in some way on click, then allow the user to close the popup when ready. 

- for perk Locking and perks that appear in multiple places, would be nice to have a slot agnostic way to select them. the ammo finders in particular don't care where they are, just that I have them. really for most perks I don't care where they are, I just want them. So some way to say "any slot" for perk locking would be cool.

- I see what the green highlight means on perks (that's a perk I have locked that is not selected on the item) not entirely sure what the red highlight means. And neither have text to explain themselves in a key or on hover.

**Comment by bhollis** [comment]
> Having some issues dragging an item to "lock" or "exclude".

What issues are you having?

> If an item is already locked (using the lock equipped button) the 'X' button does not remove it from the locked list. (but does work for removing from the exclude list.)

Yikes, I'll look into that.

> Is the "Loadout optimizer" button supposed to do anything to the current items in the loadout? when they click it is it supposed to take them to the page and lock the equipped items in the current loadout", or is it just a shortcut link?

It's just a shortcut, to tie them together. I can add an issue to start with those items locked, that's a good idea.

> I wonder if we should highlight items that are "locked" somehow, that way people know why they can't click the button to "select another item with the same stats"? Maybe if an item is locked instead of showing the shuffling arrows show an X to clear the locked item? Or something similar. 

Good idea!

> Could we try experimenting with making the "choose a perk" popup window have tabs to jump between helmets/chest/etc? It is a lot to scroll

Yup, I thought about that as a TODO. My only hesitation is that it makes it an extra tap to get to where you're going, instead of quick scrolling. Thoughts?

> Regarding "Stat mixes" that are repeated in the list: should we just hide duplicate mixes when we go to render to make it less confusing to pick?

I'm interested in creative solutions to this one. It's kind of fundamental to how things work in the new optimizer - those aren't really duplicate mixes, they're mixes where each slot is contributing different stats in order to get to that mix. If I collapse them, I can't really have the "choose another" button, since if you choose an item with different stats it'd affect what's usable in *other* slots in order to get to the desired mix. This is something I'd like to noodle on but I've had trouble coming up with a satisfying answer.

> Should we do anything to prevent max being less than min? Maybe set min to max on change?

Yikes, that's a bug. I'll file an issue.

**Comment by bhollis** [comment]
> some builds have some odd wrapping this is Chrome / Win 10

Bummer, I thought I'd gotten rid of that. The virtual scroller library requires that you know the height of every row ahead of time. But I wanted to support wrapping as you resize the window. To do that, I implemented a thing where I render a single row and measure it, and then use that height. The tough part is that not all rows are the same width (due to differing perks) and things like scrollbars can affect how much space we get. Can you let me know your screen dimensions? That may help me figure out a solution. I'll file an issue anyway.

> when excluding items, and locking perks would be nice if the card did not close after choosing

Yeah, this is a good suggestion. I'd like to build something like that into the item picker in general (I'm trying to reuse common UI components across the app). One thing I'm not sure about is that it'd make quick selections tough since now you have to tap and then tap again to select. But maybe that's worth it?

> for perk Locking and perks that appear in multiple places, would be nice to have a slot agnostic way to select them

That makes sense. I can file an issue, but I'm not sure how to present this - another section that just lists all unique perks in one big list? It'd get confusing.

> I see what the green highlight means on perks (that's a perk I have locked that is not selected on the item) not entirely sure what the red highlight means. And neither have text to explain themselves in a key or on hover. 

Sounds like we do need a key (and/or icons). Green means it's a locked perk, and orange means you need to select that perk to get to the stat mix you want (e.g. select Recovery instead of Resilience). Originally I had text explaining that under items that needed it but it got to be a lot to display. Maybe a key on top?

**Comment by tcurtin** [comment]
Loving this!  Thoughts so far:

What I love:
- super responsive
- perk locking and searching both across all gear and in the perk lock screen works great
- nice workflow during the build: order tiers by importance, then start drilling into perks.  The available perks based on current choices showing as white absolutely makes this tool... when it works that way.

A few bugs or weird behaviors:
- It seems like once I've got some choices made (R/R/M min/max, etc) and open Lock Perk the options in white are things I can pick that are still available within my previous selections (YES - love it), but I'm finding many times when I choose a white perk then get a "No Generated Builds Found".
- Can the starting order for R/R/M be M/R/R the way it is in-game? (and/or if you're trying to get people to realize those are draggable into priority order the way it did for me... I guess that worked for me but might not be obvious enough to some people?)
- I'm not able to drag an item onto the exclude or lock boxes -- nothing happens
- Conversely, if I click the "shuffle" icon and choose an item, it does go to the lock box, but I can't click x to remove it.
- +1 to keeping the lock perk selection box open for multiple selections, I pretty much always want to go in there more than once in a row

A little less cut and dry:
- Not including applied mods in calculations for R/R/M stats sure does make things confusing when the stat values in DIM don't match what's shown by D2.  Moreso when one of the item's column 1 choices needs to switch.  I don't know if that's even solvable, but its confusing.
- It would be nice to be able to somehow see what perks are on the items I'm choosing when I click shuffle to pick a different item in a slot (the need for this probably goes away when only currently available perks show as white in "lock perks".)

Thanks - really like this new setup!

**Comment by tcurtin** [comment]
Another "would like to have but not sure how it could be best implemented" -- I'd like to be able to leave the Loadout Optimizer and then come back later to some saved setups.  (Or even just if I leave and then come back, the previous choices would have been saved... but multiple saves would be best.)

**Comment by philkernick** [comment]
Testing now.  It is vastly better than before.  Awesome work.

I've started reporting new issues for each problem.

**Comment by bhollis** [comment]
@tcurtin thanks for the feedback! Responses inline:

> * It seems like once I've got some choices made (R/R/M min/max, etc) and open Lock Perk the options in white are things I can pick that are still available within my previous selections (YES - love it), but I'm finding many times when I choose a white perk then get a "No Generated Builds Found".

Filed https://github.com/DestinyItemManager/DIM/issues/3821 - I think you were choosing a burn, not a perk, which doesn't yet grey out.

> * Can the starting order for R/R/M be M/R/R the way it is in-game? (and/or if you're trying to get people to realize those are draggable into priority order the way it did for me... I guess that worked for me but might not be obvious enough to some people?)

I thought the Reddit wisdom was that Mobility wasn't useful, but maybe Zero Hour has changed that? I don't really get to play much these days...

> * I'm not able to drag an item onto the exclude or lock boxes -- nothing happens

Another bug. Got a fix for that.

> * Conversely, if I click the "shuffle" icon and choose an item, it does go to the lock box, but I can't click x to remove it.

#3820 

> * +1 to keeping the lock perk selection box open for multiple selections, I pretty much always want to go in there more than once in a row

#3822

> * Not including applied mods in calculations for R/R/M stats sure does make things confusing when the stat values in DIM don't match what's shown by D2.  Moreso when one of the item's column 1 choices needs to switch.  I don't know if that's even solvable, but its confusing.

I'm afraid I don't understand this one. What do you mean by "Not including applied mods in calculations for R/R/M stats"?

For the "column 1 choices", we highlight in orange when you need to switch to achieve the stats shown.

> * It would be nice to be able to somehow see what perks are on the items I'm choosing when I click shuffle to pick a different item in a slot (the need for this probably goes away when only currently available perks show as white in "lock perks".)

Agreed. #3591 would help, as would #3590 (though I haven't landed on a satisfying display there).

**Comment by bhollis** [comment]
Followed up with fixes to most of the minor issues in https://github.com/DestinyItemManager/DIM/pull/3826. Two more to go - coalescing stat mixes and multiselect in the perk picker, but those will have to wait until Friday when I have time.

**Comment by bhollis** [comment]
A couple more fixes in https://github.com/DestinyItemManager/DIM/pull/3827.

**Comment by tcurtin** [comment]
> > * Not including applied mods in calculations for R/R/M stats sure does make things confusing when the stat values in DIM don't match what's shown by D2.  Moreso when one of the item's column 1 choices needs to switch.  I don't know if that's even solvable, but its confusing.
> 
> I'm afraid I don't understand this one. What do you mean by "Not including applied mods in calculations for R/R/M stats"?

Sorry just seeing this -- I meant since armor pieces can include Mobility, Resilience, Recovery mods in their mod slots, I have armor pieces that stock might be MRR of 031 or 022 depending on perk choice, but with (for instance) a mobility mod inserted become MRR of 131 or 122.  That means that what DIM calculates as the total MRR for all gear is often going to be too low because its missing the changes due to mods.  So if I create a loadout in DIM, it will end up being different than what D2 says when applied.

**Pull request merged**
