### PR TITLE
Search Triumphs, Collections, and Metrics, Tracked Triumphs

### PR DESCRIPTION
**Pull request by bhollis**
This is the first part of a presentation node revamp. To really ship this I feel like I need to commit to #4913 

First, there's an internal refactoring where we pre-process the presentation node into our own structure, instead of trying to render directly from the profile response. It was a fun idea when I was first thinking about this stuff, but at the end of the day having our own structures makes things a lot easier.

Then, with that structure available, I'm allowing search of the presentation node tree. This replaces the entire tree with a flattened version that shows matching collectibles/triumphs/stat-trackers along with the path in the tree to where they live. Collectibles can be searched with the full item search, everything else is just name/description matches.

Screen Shot 2020-09-02 at 11 48 33 PM
Screen Shot 2020-09-02 at 11 48 41 PM
Screen Shot 2020-09-02 at 11 49 54 PM
Screen Shot 2020-09-02 at 11 54 08 PM
Screen Shot 2020-09-02 at 11 50 10 PM

### CODE REVIEW

**Comment by nev-r** [comment]
should we allow a many to one relationship to prevent this stuff?
image

**Comment by bhollis** [comment]
That's a good question. What would you imagine it would look like? We can group by whatever.

**Comment by bhollis** [comment]
New feature - track and untrack triumphs in DIM Sync! There's no limit to how many you can track, for now - should there be? Somebody's gonna track every triumph.

image

You can't track a triumph that's already redeemed, but you can untrack it.

**Comment by bhollis** [comment]
OK now tracked triumphs get their own, special section:

image

**Pull request merged**
