### PR TITLE
Add perks display and allow toggling perks vs. talent grid

### PR DESCRIPTION
**Pull request by bhollis**
I saw this in IC, and I thought it was pretty cool, so I whipped it up. You can toggle via the little control, or the "p" key. I figure different folks might have different display preferences.

screen shot 2016-11-01 at 10 22 48 pm
screen shot 2016-11-01 at 10 22 56 pm

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
How do you read the other perks? Are the text perks the selected ones?

I'm thinking a space to present the description so you can tap on the pets
and read them would have been good.

**Comment by bhollis** [comment]
The perks are actually a whole separate definition that comes down with the object. Bungie chooses which ones to feature.

I'd rather just show the description directly that's what Bungie.net and IC do.

**Comment by SunburnedGoose** [comment]
Just showing the three recommended perks is barely useful. I need to see the rest of them, including scopes and I can't on a tablet atm. There is no way to hover over the perks.

**Comment by bhollis** [comment]
The lack of hover is a separate issue we already have filed.

**Comment by SunburnedGoose** [comment]
This solves that issue by giving the users text to read instead of icons that are not even consistent (small bore).  

Show all of the perks and scopes, or show none at all.  This three option is a throwback to year one when there were a lot of unnamed perks in the tree to upgrade attack/light.

**Pull request closed without merging**
