### PR TITLE
Use flexbox to make loadouts view flexible.

### LINKED ISSUE #445: Loadouts only showing one row of items
We've gotten a couple complaints that the loadout popup can't show multiple items.

### PR DESCRIPTION
**Pull request by bhollis**
This uses Flexbox to allow the loadouts view to grow as more items are added than can fit. I played with a few options here, and this is what I settled on. Unfortunately due to the HTML structure, it's tough to just do one big flowing line of items.

One thing I did here was to add double margin after each category of item, in order to visually separate primary from secondary from helmet, etc. What do you think?
image

When too much stuff is in there, flexbox really takes over. I decided to wrap the items within each bucket rather than wrap the buckets - this ends up being a much more efficient use of space, though it does end up creating some interesting gaps because the flex algorithm lays out the buckets first, then the contents.
image

This will fix #445.

### CODE REVIEW

**Comment by kyleshay** [comment]
*_* it's beautiful :+1:

**Comment by bhollis** [comment]
While I'm here, what do you think of getting rid of the borders on the close and equip icons?
image
vs now:
image

I agree that a redesign could do some good.

**Comment by kyleshay** [comment]
looks less busy with the borders :+1:

**Comment by SunburnedGoose** [comment]
I'll make the close background style more contrast-y.  It's all washed out (before and after).

**Comment by bhollis** [comment]
Cool!

**Pull request merged**
