### PR TITLE
Bulk refactor to convert all templates to external files

### PR DESCRIPTION
**Pull request by joshhunt**
One of the difficulties I've had when reading through the DIM code was how most of the HTML templates are unnecessarily inlined as strings in the source.

This PR represents a WIP proposal for splitting all the templates out into external files. The templates have been saved with the same filename into the same directory, just with the extension changed to `.html`. So the template that was previously in `app/scripts/compare/dimCompare.directive.js` is now in a seperate file in `app/scripts/compare/dimCompare.directive.html`.

When there were multiple templates in a single file, the additional ones were appended with a number. If you want to go ahead with this PR, I would want to update those to give them better names.

Also, there was very little formatting done on the HTML when splitting it out, so we might want to run them through a prettifier.

Thoughts?

## TODO:

- [ ] Agree on template location + name
- [ ] Rename templates when multiple for a single JS file
- [x] Prettify templates
- [ ] Fix Inventory item popup positioning

### CODE REVIEW

**Comment by joshhunt** [comment]
And no, I didnt do this all by hand 😄 

I wrote a codemod https://github.com/joshhunt/js-codemods/blob/master/dim-extract-templates.js  to automate all of this :)

**Comment by SunburnedGoose** [comment]
Nice work here.  It is an activity that will happen when we get webpack playing well with DIM.

**Comment by bhollis** [comment]
Nice. However, in the past we've avoided doing this because we don't have webpack or another processor working yet, so moving the templates out of the files means we have to do that many more HTTP requests to bootstrap the site.

Also, and this is probably more my personal preference, but I like having the templates right where the code is without having to switch between two files. I think we should switch over to using ES6 template strings for better ergonomics, but it's so nice to have the template right there while you're working on a component.

**Comment by joshhunt** [comment]
I've noticed as well there's a problem with the item popup in the inventory screen that's causing it to not get the correct position (`top` and `left` style attributes arent being set for some reason). Curiously, this problem isnt on the item popup on the Vendors page.

I'll have to look into this more.

**Comment by SunburnedGoose** [comment]
External templates benefit from editor support when you're able to use emmet, intellisense, linting when working with HTML.  You lose that with the template still being generated in a javascript.

**Comment by bhollis** [comment]
I suppose you do if you're not using emacs ;-)

-Ben

**Comment by SunburnedGoose** [comment]
Oh man, you emacs 1%'ers...

:)

**Comment by joshhunt** [comment]
What's the current state of the Webpack stuff? I've [done my fair share of Webpack](https://speakerdeck.com/joshhunt/using-webpack-at-scale), so I'm more than happy to help out with it.

**Comment by SunburnedGoose** [comment]
@joshhunt Can you join us over here at #869?

**Comment by bhollis** [comment]
Wanna rebase this onto the `webpack` branch, or close this?

**Comment by joshhunt** [comment]
I'm going to close this for now - significant work has been done with the Webpack stuff that would require this to be re-looked at.

**Pull request closed without merging**
