### PR TITLE
Also remove button if new items option is off

### PR DESCRIPTION
**Pull request by ericnelson0**
Issue #781 fix

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Question...  What happens if I earned new items while this is disabled?

**Comment by SunburnedGoose** [comment]
And then you enable the feature?  Can't edit on my phone :/

**Comment by ericnelson0** [comment]
That's a good question. I believe everything that is new since the last time it ran would show as new.

The items are still being marked as new, it's just the UI stuff that is being removed.

**Comment by SunburnedGoose** [comment]
They shouldn't. Only new since the setting was turned on.

**Comment by bhollis** [comment]
This broke new-item tracking. I've fixed it.

**Pull request merged**
