### PR TITLE
Loadout mods in beta

### PR DESCRIPTION
**Pull request by ryan-rushton**
Change the headers of of the mods to use itemTypeDisplayName and enable in beta.

image

Thoughts on putting a disclaimer that these cannot be equipped through the API?

### CODE REVIEW

**Comment by bhollis** [comment]
Looks great. A disclaimer will help prevent a lot (but not all) of the questions

**Comment by ryan-rushton** [comment]
Ok I might do it just to ease the pain a little for the guys in discord and reddit.

**Comment by ryan-rushton** [comment]
Done, let me know what you think of this.

image

**Comment by delphiactual** [comment]
I would not hide it under a pop-up

**Comment by ryan-rushton** [comment]
Totally fair, I didn't want to but the drawer feels really crowded. I will place it in a few places and get some opinions.

**Review by delphiactual — APPROVED** [review]

**Review by bhollis — APPROVED** [review]

**Pull request merged**
