### PR TITLE
Add DIM API keys to the DIM developer page

### PR DESCRIPTION
**Pull request by bhollis**
The first chunk of the DIM API usage changes!

This adds the ability for DIM developers to generate an "app" in the DIM API with their own API key that they can use to talk to the API from localhost. With the DIM API, I decided to treat it a lot like the Bungie.net API - there's one, public version of the API that all apps, even development apps, talk to. This means no more split storage between dev, beta and prod! For local developers, they can just click a button and get their own API key and app name registered with the API, which will be used when auditing where changes came from.

Screen Shot 2020-03-03 at 11 14 03 PM

Before anyone points it out, yes, you can just enter someone else's app name and use it to get their API key. I could add protection to this by binding your Bungie.net account to your personal app, but that'd make the setup process for devs more complicated, and I'm not sure it's really worth it. Be nice, don't impersonate anyone. If I have to lock it down further, I will, and I'll invalidate everyone's keys when I do it.

Oh, and I also added a link to the top of the developer page that you can use to clone your development settings to another browser - just open that link in the other browser and it'll auto set up DIM. Should make cross browser testing easier.

### CODE REVIEW

**Comment by bhollis** [comment]
I guess the code for obtaining a DIM API token made it in here as well :-)

**Comment by delphiactual** [comment]
```
ERROR in ./src/app/dim-api/dim-api-helper.ts 80:21-34
"export 'dedupePromise' was not found in 'app/utils/util'
 @ ./src/app/dim-api/global-settings.ts
 @ ./src/app/dim-api/actions.ts
 @ ./src/Index.tsx
ERROR in /home/travis/build/DestinyItemManager/DIM/src/app/developer/Developer.tsx
[tsl] ERROR in /home/travis/build/DestinyItemManager/DIM/src/app/developer/Developer.tsx(3,29)
      TS2307: Cannot find module 'app/dim-api/register-app'.
ERROR in /home/travis/build/DestinyItemManager/DIM/src/app/dim-api/dim-api-helper.ts
[tsl] ERROR in /home/travis/build/DestinyItemManager/DIM/src/app/dim-api/dim-api-helper.ts(5,10)
      TS2305: Module '"../utils/util"' has no exported member 'dedupePromise'.
```

**Comment by bhollis** [comment]
Yup this depends on the dedupePromise PR, I’ll merge this after that one.

**Comment by sundevour** [comment]
looks like `app/dim-api/register-app` additionally, not just the promise pr. i could not find a branch with this yet

**Comment by sundevour** [comment]
`This should be in the form of "yourname-dev"`

is really unclear to me, in terms of intention and severity of "should"

**Comment by bhollis** [comment]
Please do it so I know whose key it is?

**Pull request merged**
