### PR TITLE
Progress revamp

### PR DESCRIPTION
**Pull request by bhollis**
This is a very in-progress redesign of the Progress page, to help cope with the flood of new bounties ever since Forsaken. I have a *lot* I want to do here, but I'm trying to get this in shape to get what I can out before I go on vacation, and I'll finish the rest up when I get back.

The main things that need to be fixed before this can go:

* [x] Show expiration on bounties
* [x] Show rewards somewhere (on item popups or inline)

LMK if there are any other major objections. I'm not super happy with how different milestones and bounties end up looking, but given how things are going I'd rather get something out now than wait a month.

localhost_8080_index html (1)

### CODE REVIEW

**Comment by sundevour** [comment]
personally not huge on 3 screens instead of one for a "what still needs doing" check. but just a matter of opinion/usecase i guess.

**Comment by inexorableAce** [comment]
i think you might get some of the people that want the huge 3 char overview like Sun. But, you only play 1 character at a time... this is a much easier view for focusing on what you need to do for the character you're on. 

I really like that its now sorted by whats closest to being done. low hanging fruit is always attractive and its likely what you're working toward making it easy to keep track. 

how does this work on mobile? just like vendors and such I guess?

**Comment by duckmanBR** [comment]
the icon size will be fixed or follow the app setting?

**Comment by bhollis** [comment]
Yeah icons follow item sizing. Mobile works exactly like vendors - the character tiles are swipable but the whole page isn’t.

**Comment by kyleshay** [comment]
Awesome!! 

Hmmm, what if we added a 4th option (similar to the vault) for account-wide things? It would simplify what is on each character to just bounties and quests. Would it help make the checklists easier to manage? It would feel like there is less stuff.

The account-wide it would have the stuff that is currently duplicated between everything?

**Comment by tcurtin** [comment]
This looks great!  The use cases I feel like DIM can best solve here are: what bounties expire first, and what other bounties can I hit when I go do activity X.  So the ability to choose sort by expiration (the "newest" sort in D2 kind of kills me), and the ability to search for "gambit" in descriptions, for instance.

Also, it'd be great if sort order and filter were preserved when bouncing back and forth from the tab.  (D2 lets you sort but then goes back to default the next time you go to the page?)

As always, great work!  D2 without DIM isn't worth playing.

**Comment by bhollis** [comment]
@tcurtin I want to add sorting, searching, and view options later. Didn’t quite get time for it. 

@kyleshay I considered an account wide option first, but it awkwardly split the things you had to care about when looking at your character. Especially since that selection would show significantly different content.  In the end merging it all seemed nicer.

**Comment by philkernick** [comment]
Spectacular to see this come out from under the covers.

There are two different use cases that eventually would be great to service.

1. What can I do to get powerful drops (as per #3240).
2. What can I do **now**.  By this I mean set a filter to Gambit and only things that can be progressed in gambit are shown.  Ditto for Crucible/Vanguard.  Not sure if the API returns enough to make this happen, but we can dream.

**Comment by bhollis** [comment]
Thanks @philkernick! I’ll keep these in mind for future iterations. I’d totally wanted to implement search by reward as part of this, but hadn’t thought of search by activity. I’ll add that to the list!

**Comment by philkernick** [comment]
I can also see an "activity aware" view.  Something that leverages the discussion in #2959.

**Comment by bhollis** [comment]
OK, take it for a spin in Beta in a few minutes. I'll be able to continue making improvements on this in a few weeks.

**Pull request merged**
