### PR TITLE
Use flexbox and some other tricks to simplify character heading CSS

### PR DESCRIPTION
**Pull request by bhollis**
It's now pretty much "responsive" in that it'll adapt to the size of its container without having to define different classes for different column sizes. Inspired by @kyleshay's awesome character stats display. :tada:

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Does this remove the ability to have a fixed 3x3 character inventory?

**Comment by bhollis** [comment]
No. It just means we don't have to special-case any CSS in the header for 3x3, 4xN, whatever. You just need to set the overall column size (as we do) and the rest fits automatically.

**Comment by bhollis** [comment]
To clarify, this has zero visible effect on the app.

**Comment by kyleshay** [comment]
:+1: thank you! i like this much more. way cleaner

**Pull request merged**
