### PR TITLE
Adds toggle to display light values on items

### PR DESCRIPTION
**Pull request by chrisfried**
screenshot 2015-09-10 15 02 14
screenshot 2015-09-10 15 02 26

### CODE REVIEW

**Comment by chrisfried** [comment]
Setting is disabled by default.

**Comment by kyleshay** [comment]
hi @chrisfried !! love it- and love that there is a setting!!

**Comment by SunburnedGoose** [comment]
Echo @kyleshay.  :)

**Comment by jflayhart** [comment]
Love this. Clean, shows me what damage is on what item, but I wonder about the Atk/Def stats in the popup title bar. I personally think, per #228 we should move all of that to the item details window.

**Comment by jflayhart** [comment]
I do wonder if it would look better with the damage tags inside the border of each item...

**Comment by kyleshay** [comment]
good point jflay, since thats what we're doing pre-checkbox. would that just be removing:

https://github.com/chrisfried/DIM/blob/item-stat-toggle/app/styles/main.css#L509-L510

**Comment by chrisfried** [comment]
I copy-pasted the .counter class used for stacks. I prefer it where it is, but here it is with those values set to 0:
screenshot 2015-09-10 15 25 00

**Comment by chrisfried** [comment]
Merge it as is, or merge and set those -2px to 0s, it matters not to me.

**Comment by dustinrue** [comment]
I like original design setup as it looks cleaner

**Comment by jflayhart** [comment]
Thanks for the SS for comparison. There's no right or wrong here, I agree, merge as is. Can always change later, but it looks fine how it is.

**Comment by lukefx** [comment]
:+1: awesome!

**Comment by SunburnedGoose** [comment]
I really liked the initial design.  Having the badge in the border feels crowded.

**Comment by kyleshay** [comment]
that being said, should we change these values to -2px, so that the burn indicators without the numbers show up outside/ontop of the border as well?

https://github.com/DestinyItemManager/DIM/blob/dev/app/styles/main.css#L571-L572

**Comment by SunburnedGoose** [comment]
Sure.

**Pull request merged**
