### PR TITLE
Functional loadout drawer

### PR DESCRIPTION
**Pull request by bhollis**
This switches the loadout drawer to a functional component powered by an internal reducer. I also removed the overcomplicating "conflicting loadouts" functionality in favor of just not letting you save a loadout if it clashes.

### CODE REVIEW

**Comment by sundevour** [comment]
is the intended rule "no loadouts with the same name, unless they are for different classes"?

**Comment by sundevour** [comment]
steps:
• create loadout
• name X
• global
• click save
• click edit pencil on X
"save new" is enabled for me, and created a second loadout when clicked
if i edit either of those, they won't let me click "save new"

**Comment by sundevour** [comment]
or actually various things like
• create loadout
• name X
• global
• click save
• click edit pencil on X
• change to titan
"save new" is enabled for me

most of the detections seem to only kick in after there's 2 conflicting loadouts

**Comment by bhollis** [comment]
It does seem like the rule isn't working right for "Save New"

**Comment by sundevour** [comment]
behavior all seems right now. i'm getting two exhaustive deps errors from eslint though

**Pull request merged**
