### PR TITLE
Performance improvements to loadout builder

### PR DESCRIPTION
**Pull request by bhollis**
This is just a bunch of minor changes aimed at reducing recomputation and object allocation. Speeds up loadout builder by about 25%.

### CODE REVIEW

**Comment by delphiactual** [comment]
Capping out at T9 instead of multiple T12... Also seems to hang during the final calc ~90%

**Comment by bhollis** [comment]
Hmm, this commit has been hanging out a while. Let me test it again.

**Comment by bhollis** [comment]
I'm having a lot of trouble figuring this out. The code is super hairy to begin with, and even undoing each piece of this, it's still broken. Undoing *all* of it I get T12 again. No idea what the issue is.

**Comment by delphiactual** [comment]
It looks the what it is reporting as T9 are in fact T12...

**Comment by bhollis** [comment]
OK, I managed to find it. That code is super super tricky.

**Comment by delphiactual** [comment]
Yep, this is working much better than before

**Comment by bhollis** [comment]
Working better than before when it was broken, or in comparison to before this PR at all?

**Comment by delphiactual** [comment]
before this PR at all

**Comment by kyleshay** [comment]
Wow, awesome work Ben! :D

**Pull request merged**
