### PR TITLE
Replace list of sockets in category with list of socket indexes

### PR DESCRIPTION
**Pull request by bhollis**
This replaces the materialized list of sockets per-category with just the socket indexes, and adds some helpers for dealing with them. This is a bit more awkward to handle, but has some benefits in that we don't have the same Plug object referenced from two parts of the item. This is important for later when I want to be able to update the plug data using `immer`, but also makes things like serializing/unserializing item objects easier.

### CODE REVIEW

**Review by ryan-rushton — APPROVED** [review]

**Review by nev-r — COMMENTED** [review]
Records > Collections > Exotic > Weapons > click an item

`Cannot read property 'isPerk' of undefined`

**Comment by nev-r** [comment]
when there's time i would love to understand more about what this buys us aside from keeping extra references to the socket objects out of category.

obviously it's a bit unintuitive to turn what used to be a array, into a function that loops a series of find()s.
maybe i am missing something. could getSocketsByIndexes not be one filter() then a sortBy()?

i find the getSocketsByIndexes syntax kind of awkward and long and causing extra lines.
seems like it's formatted this way solely because of the unusual case in ItemSocketsWeapons?
everywhere else it just exists to enumerate a full category, and always that within a loop of all categories.
maybe a helper like
`getCategoriesWithSockets(item):{category:DimSocketCategory;sockets:DimSocket[]}` ?
i think this would simplify several of the places getSocketsByIndexes is used

**Comment by bhollis** [comment]
I can take a look at changing the format of the helper. 

The main reason I'm changing this is that I'm working on a function for previewing item perks that'll take an item and a list of socket overrides and produce a new item with stats and sockets adjusted based on the different plug choice. As I did that I realized that I'd have to rewrite the categories' lists of sockets too, to point to the adjusted sockets. But they weren't used very often so it seemed easy enough to redirect it. 

Theoretically this also helps us serialize items to json/IndexedDB but I don't know when I'd want to.

**Comment by bhollis** [comment]
Fixed the collections bug and merged with master. I tried making a `getCategoriesWithSockets` but there was only one place I could use it - feel free to take a crack at it but I think these are reasonable primitives.

**Review by nev-r — APPROVED** [review]

**Pull request merged**
