### PR TITLE
PR preview deployment

### PR DESCRIPTION
**Pull request by bhollis**
This sets up workflows that will deploy PR branches to a preview domain, `pr.destinyitemmanager.com`. The intent is to make it easier to review PRs (just click a button to check it out!) and to make it easier to test branches on mobile.

Since all sites on a domain share localstorage and IDB, you should stay logged in after doing so once. I've configured each PR build to have its own service worker though, so you should be able to test those behaviors as well.

### CODE REVIEW

**Comment by bhollis** [comment]
I'm having some hosting setup problems, but hopefully my host will get everything in place soon...

**Comment by bhollis** [comment]
The bundle size reduction is because I'm building without Sentry now.

**Comment by robojumper** [comment]
* I assume this will only work for PRs opened from the DIM repo, as PRs from forks will not have access to any secrets?
* The `returnPath` thing doesn't seem to quite work yet, it always just stores `/` in the `returnPath`.

**Comment by bhollis** [comment]
> I assume this will only work for PRs opened from the DIM repo, as PRs from forks will not have access to any secrets?

Yup that's my assumption, though I should probably change it to not even attempt to deploy when it's coming from a fork. It's a bit obnoxious because stating the env at the top of the job may make the whole thing fail on a fork, meaning I'd need a whole other copy of the job for forks.

**Comment by delphiactual** [comment]
`github.event.pull_request.head.repo.full_name != github.repository`

https://stackoverflow.com/a/75809743

**Review by robojumper — APPROVED** [review]
Seems to work great! Let's get this in after app promotion.

**Pull request merged**
