### PR TITLE
Fix for a sentry report of not iterable.

### LINKED ISSUE #6738: TypeError: t[o] is not iterable
https://sentry.io/organizations/destiny-item-manager/issues/2389138487/?referrer=github_plugin

```
TypeError: t[o] is not iterable
  at a (webpack://dim/./src/app/loadout-builder/LoadoutBuilder.tsx:214:28)
  at c (webpack://dim/./src/app/loadout-builder/LoadoutBuilder.tsx:207:28)
...
(14 additional frame(s) were not displayed)
```

https://twitter.com/slashwhatever/status/1391139721301172233

### PR DESCRIPTION
**Pull request by ryan-rushton**
Fixes #6738

### CODE REVIEW

**Comment by ryan-rushton** [comment]
Yeah it seems it can happen when people only have armour 1.0 items. I'll update the comment in a bit.

**Comment by dwimmer** [comment]
Could probably just update mapStateToProps to fill in empty arrays then (or just abort the whole thing since we can't build a valid set anyway if a bucket is empty). Then we wouldn't have to check this all over the place in the optimizer.

**Comment by ryan-rushton** [comment]
Yeah I was considering that but I am in two minds as we are using an object to access them without any type lockdown. If it was a prebuilt object with the correct hashes and using a const assertion I would be happier to go that route.

**Comment by ryan-rushton** [comment]
@bhollis going to merge this so we can have it in for release and at least a little testing on it

**Pull request merged**
