### PR TITLE
Move inventory screens to React, and adopt Redux 

### PR DESCRIPTION
**Pull request by bhollis**
This is an in-progress branch I've been working on for a few weeks that transitions the inventory screen over to React. As part of this I've finally taken the plunge to starting to represent our state in Redux. While I'd been able to build some simpler screens with plain React and some RxJS, it became clear that the best way to manage state performantly in the long term is to start using Redux. At this point, I'm sort of straddling the old world and the new, by publishing our existing state into Redux and being sorta careful how it's consumed so things update correctly. As I'm able to move everything over (and get rid of our HTML AngularJS templates) I'll be able to refactor the data further into a normalized shape that will make it easier to manage and more performant.

I'm leveraging [typesafe-actions](https://github.com/piotrwitek/typesafe-actions) to reduce boilerplate on actions and provide nice typing, but the logic is still a bit more indirect, as is the case with all Redux applications. I also anticipate having to use Redux Saga to handle things like inventory moves in the long term, but right now the goal is to just move things away from AngularJS as fast as possible - once everything is TypeScript, refactoring becomes much easier.

As part of this I've also ditched our old store pager for the React one we use on the progress page, so the whole page slides instead of just the header.

Still to do:

* [x] Drag and drop
* [x] Updating on equip/dequip
* [x] Fix moving from D1 to D2 view (need to clear state)
* [x] Separate ratings data
* [x] Separate new-items data
* [x] Separate tags and notes
* [x] Search
* [x] Partial stack move dialog when dragging

### CODE REVIEW

**Comment by bhollis** [comment]
@48klocs I did some nasty stuff in https://github.com/DestinyItemManager/DIM/pull/2943/commits/2d4c5fcf0f4f0516249a44ad84c6567133018c80 to make reviews work. Just something to keep in mind as we add random roll support to D2 reviews.

**Comment by bhollis** [comment]
OK. I think this is ready to go. All the functionality is there, though performance needs work. My goal here was just to get us onto redux and a React inventory screen, so that I can start making incremental progress off a branch. As is, the state modeling and update patterns are just bridges to get things to connect up decently.

I've set it up with a flag so this won't go out to release until we're OK with it, so let's test it this week.

**Comment by SunburnedGoose** [comment]
Sounds good. I'll make sure my icons are behind the flag once this is in.

**Comment by bhollis** [comment]
🤞🤞🤞 Here goes nothing... 🤞🤞🤞

**Pull request merged**
