### PR TITLE
Edit in-game identifiers for DIM loadouts

### LINKED ISSUE #9456: Save in-game identifiers (name/color/icon) with DIM loadouts
https://github.com/DestinyItemManager/dim-api/pull/168

### PR DESCRIPTION
**Pull request by bhollis**
This adds the ability to set an in-game identifier (name, color, icon) for a DIM loadout, with the intention that it's used as the default when copying the loadout to an in-game loadout. Fixes #9456. I may decide to feature flag this out until we actually have the ability to copy to an in-game loadout (which will require all kinds of extra UI and warnings and such) which in turn will have to wait until in-game loadouts are re-enabled.

Screenshot 2023-08-23 at 10 36 48 AM
Screenshot 2023-08-23 at 10 36 17 AM
Screenshot 2023-08-23 at 10 40 22 AM
Screenshot 2023-08-23 at 10 36 05 AM
Screenshot 2023-08-23 at 10 35 47 AM

I'm a bit worried that it takes up too much space on mobile, but I'm not sure where else to put it.

### CODE REVIEW

**Comment by guise** [comment]
Also - I can't remember how the loadout tray behaves when you open a loadout link for a class that you do not have a character for… I remember trying this and being annoyed that I couldn't open the link or something (when I just wanted to inspect the build). Just mentioning this as it might be another case (albeit fringe) that could benefit from showing class info more unambiguously in the loadout tray.

**Comment by bhollis** [comment]
We don't allow you to open a loadout link that can't be used by one of your characters, so it's probably OK.

**Review by vivekhnz — APPROVED** [review]
Looks good! I'm not sure about the plus icon to edit loadout identifiers, but the game doesn't have a good icon to denote identifiers, so probably ok.

**Review by guise — APPROVED** [review]

**Comment by bhollis** [comment]
I'll probably end up having to do something different with how the loadout share works, because we don't auto-select the right class when opening a class-specific loadout.

**Review by nev-r — APPROVED** [review]

**Comment by bhollis** [comment]
I'm leaving this one in limbo until I can get the "save as in-game loadout" button in.

**Comment by bhollis** [comment]
Merged under a disabled feature flag, just so this doesn't keep drifting out of date.

**Pull request merged**
