### PR TITLE
Fix iOS performance by lazy-loading tile images

### PR DESCRIPTION
**Pull request by bhollis**
I hate this, but it gets pretty close to fixing the iOS Safari performance regression in #8436.

The approach is to use an IntersectionObserver to load the item tile, overlays, and badge only when the tile enters the viewport. Further, all images on the tile have been converted to background images. Lazy loading had the biggest impact, but using background images also led to a noticeable improvement in rendering speed. To be clear, this is a regression in iOS Safari itself, not anything we were doing wrong. That said, I think I will apply this lazy-loading to all browsers rather than just iOS, as it does cut down on the complexity of the DOM if you don't scroll.

The placeholders have the same border color, polaroid chin, and background color, so there's not any shocking pop-in, the details just arrive a bit later. As part of this I also moved the calculation of whether to show the badge up so we could switch to strict size containment on item tiles, which should also help with layout.

Sadly, when I've attempted to write a codesandbox that reproduces this so I can file a Webkit bug, I don't see the same issue. Rendering 400 scaled-down 96x96 placekitten photos in a grid layout is perfectly fine, so whatever is causing it is more complex than that.

### CODE REVIEW

**Review by vivekhnz — CHANGES_REQUESTED** [review]
I think this is an OK trade-off. Changes look good and I tried the branch on my Android phone (Chrome 102) and it seemed like the search results drawer was more performant. It doesn't seem to have fixed the hitching when swapping to the Vault tab though.

I noticed two issues:

1. The item tile is 1px taller - not sure if intentional but the hover border is no longer flush with the bottom of the badge:

dim-item-tile-height-change

2. If you scroll down the page slowly, item placeholders won't get replaced until you scroll back up. This is easy to repro by repeatedly tapping the down arrow key (Chrome 102 on Windows 10):

dim-placeholder-scroll-bug

**Comment by nev-r** [comment]
kinda weird on desktop firefox too, scrolling seems ok but uncollapsing a section tends not to load the icons for its top row of items. very weird. sounds like maybe something to gate to just ios

**Comment by bhollis** [comment]
Thanks, let me take a look. I hadn't run into this in testing myself but it sounds like we're missing some event from the intersection observer. Better to fix it everywhere.

**Comment by bhollis** [comment]
I believe I've fixed both issues. After these changes I cannot reproduce cases where a tile fails to become visible. As part of this I switched to using a single IntersectionObserver vs. one per element, following an example from the `react-intersection-observer` library. I couldn't notice any performance difference, but after swapping to that technique the last instance of this happening on Firefox went away.

**Comment by vivekhnz** [comment]
Cool, both of those issues are fixed for me. Another thing I noticed is that the element icons on item tiles are noticeably more aliased when using item tile sizes other than the default 50px (Chrome 103 on Windows 10):

dim-element-icon-aliasing

`background-size: 100%` seems to resolve this, but I haven't comprehensively tested it.

**Comment by bhollis** [comment]
Applied your suggestion - Chrome uses macOS' drawing libraries on macOS which are generally nicer than what's available on Windows, so it makes no different either way for me.

**Review by vivekhnz — APPROVED** [review]
Cool, fixed for me on Chrome.

**Pull request merged**
