### PR TITLE
Move search actions into a kebab dropdown

### LINKED ISSUE #5670: Search action bar
Today when there is a matched search, you can tag/lock or compare from buttons in the search bar. I'd like to replace this with a kebab menu that offers options for tag/lock, but also move, note, organizer, etc. having a menu gives a lot more room for actions. By using downshift we can make this menu keyboard accessible so users can tab, enter, select, enter to execute actions.

### PR DESCRIPTION
**Pull request by bhollis**
To accommodate more actions and labels, this moves all the actions you can perform on an active search into a "kebab menu" that shows up while there's an active search. This uses Downshift so it's keyboard accessible (arrow keys and such work).

I could be convinced the menu should be there always, but with all the items greyed out if there's no search.

Screen Shot 2020-09-21 at 8 34 55 PM

Fixes #5670

### CODE REVIEW

**Review by inexorableAce — APPROVED** [review]
I love this 😍

**Comment by kyleshay** [comment]
Nice! So many useful options!! 

I like the idea of it showing persistently so that users know what options do exist. Could also go either way on it.

**Comment by kyleshay** [comment]
I wonder if we should have a hotkey/action to trigger opening it? I imagine after performing a search if I hit a button (shift + enter? not sure) it would be neat if it opened and I could arrow down to something and apply?

**Comment by kyleshay** [comment]
One other thing if the height was a worry, I wonder if we grouped items by row? Though I'm not sure what we would do for mobile then.

Screen Shot 2020-09-23 at 11 15 02 AM

**Comment by bhollis** [comment]
Right now you can tab over to it and activate it like any other button (or with down-arrow), but I could imagine giving it a special key combo. I'm kind of reserving "enter" or "shift+enter" for "show results"

**Pull request merged**
