### PR TITLE
Automated engram farming

### PR DESCRIPTION
**Pull request by bhollis**
This builds on the ideas from #129. I'm putting this out for comment in an unfinished state - I still need to do styling for the "we're farming engrams" dialog, choose a name for the menu item, and choose a new icon for the farming icon.

This contains two changes. First, there is a new loadout, "gather engrams", that'll grab all engrams onto a single character from everywhere. Pretty straightforward.

screen shot 2016-04-30 at 7 14 28 pm

Then, there's another menu item currently called "Engrams to Vault". When selected, this pops up a little panel at the bottom of the screen that says "Moving [character]'s engrams to vault" with a "Stop" button. This will first move all engrams from the selected character to the vault. Then, it will move items out of the character's inventory so that there's at least one space in every category that could contain an engram, to help prevent engrams going to the Postmaster. Until the "Stop" button is pressed, this will repeat every minute. The stores are reloaded every time to make sure they're fresh, and importantly, this *doesn't* use the tab-visibility stuff we do for normal background refreshes, so it'll keep going even if you have another tab selected or if your machine is locked.

Obviously WIP UI:
screen shot 2016-04-30 at 7 14 56 pm

Please check out the branch and let me know what you think!

### CODE REVIEW

**Comment by kyleshay** [comment]
this is amazing!! i'll pull this down and check it out! thanks!!! 💃 👯

**Comment by Mulchman** [comment]
Loving it so far. The counter doesn't appear to work, though; it has moved
at least 5 engrams and it still says 0.

**Comment by bhollis** [comment]
Yeah, I broke the counter messing around with stuff. Imagine it's working.

**Comment by Mulchman** [comment]
I left things going for a while and then tried Gather Engrams and nothing
was happening.  I didn't check the console, but I had to manually move
everything from vault to character.  I'll try to do better with noticing
errors and what not.  Also, I'm not sure I like it randomly moving an item
from a full section to the vault; I kind of want to be the one to determine
which item to move if a section is full.  It seemed to prioritize lower
tier items, but still, I don't want it to move something I actually might
want to use.  With gunsmith packages and such, I often have 8/9 slots full
in each section and I don't want the app moving something I might decide to
use.

**Comment by Mulchman** [comment]
Also, when Gather Engrams works, I want it to ignore exotic engrams.  I'm
already saving those for the next expansion, and having them come over is
quite annoying.

**Comment by bhollis** [comment]
> I left things going for a while and then tried Gather Engrams and nothing was happening.

Did you stop engram farming before doing that? They'll conflict. I'm going to make a change that cancels farming automatically whenever you apply a loadout.

> Also, I'm not sure I like it randomly moving an item from a full section to the vault; I kind of want to be the one to determine which item to move if a section is full.

Then your engrams are going to the Postmaster. If you don't want DIM to move things it chooses to make room, make room yourself, and it won't have to.

> I want it to ignore exotic engrams.

It'll gather all engrams. You don't need to decrypt them.

**Comment by Mulchman** [comment]
"Did you stop engram farming before doing that? They'll conflict. I'm going
to make a change that cancels farming automatically whenever you apply a
loadout."

Yes, I stopped engram farming (by clicking 'stop' on the counter bar).  I
tried again this morning (after leaving the farm mode on all night) and 2
blue engrams that were in my Vault didn't move after clicking Gather
Engrams multiple times.

"If you don't want DIM to move things it chooses to make room, make room
yourself, and it won't have to."

This is my point.  I want to make room myself, but if I turn the feature on
w/o making room first, I then have to figure out what got moved and then
play a shuffle shell game to get the item back and move something else
away.  Toaster saying a bucket is completely full?  Highlight/outline the
bucket that's completely full?

**Comment by Mulchman** [comment]
This might be why "Gather Engrams" is not working for me-


FARM
dimEngramFarmingService.factory.js?v=3.5.4:46
Nothing to move away.
dimEngramFarmingService.factory.js?v=3.5.4:105
nothing to move to make room
dimEngramFarmingService.factory.js?v=3.5.4:148
STOP FARM
angular.js:13550 TypeError: Cannot create property 'hash' on number '1'
    at d
(chrome-extension://djbjnljljndncokociioilbpmfaaicpk/vendor/angular/angular.min.js?v=3.5.4:12:6)
    at qa
(chrome-extension://djbjnljljndncokociioilbpmfaaicpk/vendor/angular/angular.min.js?v=3.5.4:14:192)
    at Array.map (native)
    at
chrome-extension://djbjnljljndncokociioilbpmfaaicpk/scripts/loadout/dimLoadoutPopup.directive.js?v=3.5.4:267:48
    at Function.m.each.m.forEach
(chrome-extension://djbjnljljndncokociioilbpmfaaicpk/vendor/underscore/underscore-min.js?v=3.5.4:5:2410)
    at LoadoutPopupCtrl.gatherEngramsLoadout
(chrome-extension://djbjnljljndncokociioilbpmfaaicpk/scripts/loadout/dimLoadoutPopup.directive.js?v=3.5.4:266:9)
    at
chrome-extension://djbjnljljndncokociioilbpmfaaicpk/vendor/angular/angular.min.js?v=3.5.4:249:181
    at b
(chrome-extension://djbjnljljndncokociioilbpmfaaicpk/vendor/angular/angular.min.js?v=3.5.4:125:349)
    at e
(chrome-extension://djbjnljljndncokociioilbpmfaaicpk/vendor/angular/angular.min.js?v=3.5.4:272:394)
    at n.$eval
(chrome-extension://djbjnljljndncokociioilbpmfaaicpk/vendor/angular/angular.min.js?v=3.5.4:144:467)

**Comment by Mulchman** [comment]
Just encountered another oddity.  My vault for armor is at close to max.
Engram farming code ended up filling up the armor section, and then once
the vault was full, it did its "FARM" cycle and ended up moving something
to my character (random armor piece) to be able to place the newly received
engram in the vault.

**Comment by bhollis** [comment]
I've fixed the Gather Engrams loadout.

> Toaster saying a bucket is completely full?  Highlight/outline the bucket that's completely full?

I think this still defeats the purpose of having this be an automated tool. If all it does is say "hey, time to make space / move engrams" it's not that much better than just playing with a laptop in front of you and moving things by hand.

> My vault for armor is at close to max. Engram farming code ended up filling up the armor section, and then once the vault was full, it did its "FARM" cycle and ended up moving something to my character (random armor piece) to be able to place the newly received engram in the vault.

That's how DIM works for full inventories in general. It's got to move something out to be able to move something into the vault. It'll do the same if you drag an item onto a full inventory. This is another case where if you don't like what it chooses, you should make sure to have plenty of space.

**Comment by Mulchman** [comment]
"This is another case where if you don't like what it chooses, you should
make sure to have plenty of space."

That's the whole point of a farming mode, though, for it to fill everything
else up first until eventually filling up the current character.  Right?!

* fill vault until full
* fill other characters until full
* start stockpiling current character eventually making the postmaster full

Otherwise, what's the point if user interaction is required after 2-3
engrams?

**Comment by bhollis** [comment]
It'll do that, it just may put things back on the active character. The way it works is that if something needs to be moved out of the vault to make space, other stuff gets moved onto whichever character has the most space.

**Comment by bhollis** [comment]
OK, here's a nicer looking popup, with animations:

screen shot 2016-05-01 at 6 56 38 pm

**Comment by Mulchman** [comment]
Love the improvements.  My only complaint now is that the vault gets full
and then it starts doing the shell game.  I wish it would leave 1 space
free in the vault and prioritize the other characters until they are full,
and then start playing the vault shell game.  Farmed Omnigul for 1.5 hours,
and had to turn it off once it filled the vault and the shell game
started.  For me, it's too obnoxious once it hits that point.

**Comment by bhollis** [comment]
That's fair, though not as easy as you might hope to implement. You can of course avoid it by making room in the vault yourself.

**Comment by bhollis** [comment]
OK, give this a shot. I hacked together something that might work to fill up other characters before starting to swap too bad.

**Comment by Mulchman** [comment]
Saw this late Sunday (12:30 AM PDT).  Won't be able to play with it until
Monday evening PDT.

**Comment by Mulchman** [comment]
Was able to get in some games earlier than expected.  It seems to work
perfectly once vault hits 107/108 for weapons or armor: it started loading
up my other characters and no weird gear swaps were happening.

**Comment by bhollis** [comment]
Rebased on top of the many changes in dev, and added some more cleanup to prevent constant item swapping.

**Comment by Mulchman** [comment]
Have others tested this yet? I'm not 100% certain the case when vault is
full is being handled correctly. Twice now I've found other characters'
gear on the wrong characters.
On May 2, 2016 22:58, "Ben Hollis" <notifications@github.com> wrote:

Merged #496 <https://github.com/DestinyItemManager/DIM/pull/496>.

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/DestinyItemManager/DIM/pull/496#event-648453424>

**Comment by bhollis** [comment]
Could you file a new issue, and elaborate on what exactly you think is
happening wrong?

**Comment by Mulchman** [comment]
https://github.com/DestinyItemManager/DIM/issues/507

**Comment by mtlewis** [comment]
Hey! Thrilled to see that this idea got taken forward and shipped. Great work all. I guess I unwatched this repo at some point, because I totally had no idea that my original PR had gathered any attention. Will be trying this out.

**Pull request merged**
