### PR TITLE
Adds a Randomize Equipped Items button to the Loadouts Popup, per #177

### PR DESCRIPTION
**Pull request by chrisfried**
screenshot 2015-09-13 16 30 11
This probably needs some testing...

### CODE REVIEW

**Comment by chrisfried** [comment]
Right now, it randomizes every equipped slot. Might make sense to allow users to limit it to just weapons, just armor, etc.

**Comment by SunburnedGoose** [comment]
Dangerous click.  Would be nice if there was a confirmation.  Like when you click, an 'apply' button appears on the right in the row.

**Comment by chrisfried** [comment]
Good idea.

Side note to self: Clean up cloned objects after random load out is applied.

**Comment by dustinrue** [comment]
Seconded on the idea of locking randomization to weapons or armor. I'd like to randomize weapons but not armor

**Comment by SunburnedGoose** [comment]
What is we add two columns like we do for edit/delete for loadouts.  Each column is a checkbox and an icon for wep. & armor.  When you click on it, we replace it with an cancel/apply button.

**Comment by chrisfried** [comment]
I like it. If it fits. If not, clicking the button could bring up a modal with those checkboxes and an apply button.

**Comment by chrisfried** [comment]
Alternative solution @dustinrue, throw away all of your other armor. :D

**Comment by SunburnedGoose** [comment]
We don't use modals anywhere else though.......

**Comment by chrisfried** [comment]
Settings and Support DIM?

**Comment by chrisfried** [comment]
If I replace all that text with a Shuffle icon or something, it should fit fine.

**Comment by SunburnedGoose** [comment]
Those are views for content areas.  They will be going away in v4 when we replace them with views that you travel to use.

**Comment by chrisfried** [comment]
I'll play with it more later in the week. Assuming TTK doesn't consume all of my time...

**Comment by SunburnedGoose** [comment]
Truth.

**Comment by chrisfried** [comment]
Could add a Hard Mode that dumps all your other guns in the Vault...

**Comment by SunburnedGoose** [comment]
But with DIM, is there ever a 'hard mode'?  :O

**Comment by SunburnedGoose** [comment]
btw, feel free to make the loadout dialog larger if you need to make room.  It's already overflowing and I'm sure users don't care about design ;)

**Comment by chrisfried** [comment]
screenshot 2015-09-14 10 34 23
screenshot 2015-09-14 10 34 29
That was the closest thing I found to a weapon icon in Font Awesome...

**Comment by SunburnedGoose** [comment]
:)  How do you cancel it?

**Comment by chrisfried** [comment]
You can toggle the Weapon/Armor buttons on and off.

**Comment by SunburnedGoose** [comment]
Maybeeeeee, disable the randomize text until they choose armor or weapons?
Then they can click on the name like they do everything else?

**Comment by chrisfried** [comment]
screenshot 2015-09-14 11 07 52
screenshot 2015-09-14 11 07 59
screenshot 2015-09-14 11 08 56
screenshot 2015-09-14 11 09 15

**Comment by chrisfried** [comment]
I'm surprised Bungie doesn't have weapon/armor icons... Or do they and I'm just failing to find them?

**Comment by SunburnedGoose** [comment]
Dunno.

**Comment by kyleshay** [comment]
maybe we can use something similar to http://fontello.com/

for the icons. allows us to build a custom icon set, can pull from font-awesome, upload our own.. etc

**Comment by SunburnedGoose** [comment]
I do enjoy the irony of a finger gun since you get kicked out of school for
doing that...

**Comment by bhollis** [comment]
Chris, this is great, but I'm not sure there's a lot of clamor for random loadouts. :stuck_out_tongue_winking_eye: I'm going to close this, but as I said in the other issue, keep the ideas coming!

**Pull request closed without merging**
