### PR TITLE
Search: add stack filter

### LINKED ISSUE #2265: Add a search for stackable items
Similar to the behavior of level and light add a search flag for stacked items.

**Examples**
```
stack:<3
stack:>3
stack:>=3
stack:<=3
```

### PR DESCRIPTION
**Pull request by duckmanBR**
tentative to close #2265

### CODE REVIEW

**Comment by bhollis** [comment]
Awesome! Should we call it "amount" instead of "stack"?

We also need to update the filter help page.

**Comment by duckmanBR** [comment]
I'm new to Destiny, so just followed the `is:stackable` nomenclature, also, when people here/discord/reddit talks about this, they usually refer to it as stack, but `amount` is also a good name.

And yes, if this works, I'm planning to update the cheat sheet next. We have some predicates missing, but I would need some help to review the ones not applicable to D1...

**Comment by bhollis** [comment]
Sounds good. Can you add just this to the filter help page, and add a changelog entry?

**Comment by kyleshay** [comment]
Awesome, thanks for doing this!

**Pull request merged**
