### PR TITLE
Compact timers for Progress page bounties

### PR DESCRIPTION
**Pull request by bhollis**
This restyles the expiration timers on bounties to be less offensive - they are now inline with the title, smaller, and use icons/abbreviations instead of lots of words.

Old:
Screen Shot 2019-07-07 at 6 40 12 PM

New:
Screen Shot 2019-07-07 at 6 38 40 PM

### CODE REVIEW

**Comment by inexorableAce** [comment]
Hmm. It looks great, but it’s technically less usable. Without the context of an expired item you really have no way to know what the timers are for now.  As we know any shred of ambiguity can lead to confusion about things. The old timers were very explicit in their purpose and info. Which isn’t a bad thing.

**Comment by sundevour** [comment]
@inexorableAce the full descriptive text is still available by tapping any bounty, so since this is a one-time learning thing ("oh that is the expiration timer") i feel like that is enough.

i am concerned this breaks the expiry styling in the pop-up box though.
old:
image


new:
image

**Comment by inexorableAce** [comment]
Yeah it’ll be fine... we will get asked about it. But it’ll be fine :p

**Comment by bhollis** [comment]
That's my bad, I didn't mean to change it in the popup.

**Pull request merged**
