### PR TITLE
Remove OpenCollective logo, rename "Support"

### PR DESCRIPTION
**Pull request by bhollis**
We've noticed that folks don't necessarily know what the "Support" link does. I also don't think anyone recognizes the OpenCollective logo. This PR removes the logo, and switches the link to say "Backers".

screen shot 2017-05-14 at 12 23 57 am

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Would be nice to put a number next to it to indicate the # of backers.  I can update it monthly when I build the report.

**Comment by bhollis** [comment]
Hmm, not sure how to make that update easily. We could use the badges but I think they'd look out of place:

**Comment by bhollis** [comment]
@kyleshay what do you think?

**Comment by kyleshay** [comment]
What if we labeled it "Contribute" as it's a bit more of a call-to-action (shrug)? We should could link the GitHub repo in the support modal. Maybe something simple like a github flavored "star" button? Gotta build that star count 😎 https://buttons.github.io/  

I suppose it's in the about dialog... would love to somehow only have one, that is also way less text heavy.

The black/green badges are cool, but we already see the nice list of contributors icons... would be nice if there was an easy way to just pull an SVG of the count and put it before the word "Backers/Sponsors"

BTW - Talked with the OC people and it sound like they're working on an in-app modal. Also asked if they could make the one-time contributions a bit simpler to make. 

For reference:
https://github.com/OpenCollective/OpenCollective/issues/339#issuecomment-296262232

**Pull request merged**
