### PR TITLE
[DIM-990] Add option to move item dialog to easily do the math of fil…

### PR DESCRIPTION
**Pull request by Mulchman**
…ling up to a stack

From https://github.com/DestinyItemManager/DIM/issues/990

stacksworth

First attempt at adding an option to the move item dialog that lets us OCD users easily keep a full stack of a particular item on our character without having to do math or multiple-transfer-workarounds.

### CODE REVIEW

**Comment by bhollis** [comment]
Great idea! Might be easier as two buttons than a button and a checkbox. Only one click needed that way!

**Comment by Mulchman** [comment]
@bhollis I like that idea a lot. Here's an idea-

image

**Comment by JakeWhitaker** [comment]
YESS!!!!

**Comment by bhollis** [comment]
Love it!

**Pull request merged**
