### PR TITLE
Sort items by "Stat roll percent" now sorts weapons as well

### LINKED ISSUE #1732: Order by Stat roll Percent
now that weapons have reviews, if the user sets this order mode, should it also order weapons by average review, highest first? would make it easier to quickly scan for your potential best weapons.

### PR DESCRIPTION
**Pull request by kyleshay**
This fixes #1732.

Renamed the sort by “Stat roll percent” to sort by “Rating” which now
includes both the armor (quality rating) and weapon dtr rating.

Sort order would then be:
rating -> prim stat -> abc

The only issue with this is that ratings do not come back instantly,
which means DIM re-orders the items after the request is resolved. This
could be resolved with #1762.

screen shot 2017-06-20 at 10 14 32 am

### CODE REVIEW

**Comment by kyleshay** [comment]
screen shot 2017-06-20 at 10 13 41 am

**Comment by kyleshay** [comment]
screen shot 2017-06-20 at 10 14 32 am

**Comment by kyleshay** [comment]
I also have code if we wanted sort by 'primary' to first sort by rating, which would look something like this*, not totally convinced to add it until we have the caching thing though, just because it does move the items around after ratings come back.  Does make it a little bit easier to scan though.

*screen shot 2017-06-20 at 10 21 42 am

this is how it currently looks without the sort by ratings first for primary sort ->
screen shot 2017-06-20 at 10 25 21 am

**Comment by bhollis** [comment]
Awesome!

**Pull request merged**
