### PR TITLE
eslint-plugin-import

### PR DESCRIPTION
**Pull request by bhollis**
This sets up eslint-plugin-import. Most of its rules are redundant with normal build errors, but this adds a few interesting ones. I've fixed all except the `no-cycle` errors, of which we have 123. We can maybe chip away at them here?

### CODE REVIEW

**Comment by robojumper** [comment]
Hm, some of these imports import only types, so they're not actually a real dependency for bundling / module loading. The workaround seems to be enabling `@typescript-eslint/consistent-type-imports` and turning all of these into `import type` statements...

**Comment by robojumper** [comment]
See https://github.com/DestinyItemManager/DIM/compare/eslint-import...robojumper:DIM:eslint-import for `import type`. Apparently const enums, even with the const enum optimization, are still detected as a dependency for module importing, which seems incorrect to me and makes some of these more annoying than they need to be.

**Comment by bhollis** [comment]
Gotcha. I figured we'd want to turn on the type imports at some point, but they really don't offer much of any value outside of this.

**Comment by bhollis** [comment]
At the end of the day this is what's stopped me from using this plugin in the past - it has to recreate all the knowledge that both TypeScript and Webpack have in order to make sense of things.

**Pull request closed without merging**
