### PR TITLE
Configure prettier

### PR DESCRIPTION
**Pull request by bhollis**
This adopts prettier, an automatic code formatting tool. I don't love everything it does, but I do love having absolute consistency automatically, and being able to write unformatted code and have it magically format itself when I save.

This configured VSCode to format on save, and sets up a precommit hook that'll format automatically as well, in case you forget.

I'll format all the code before merging this, once it's approved.

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
I'm a big fan of this. We do it at work.

**Comment by duckmanBR** [comment]
Anything that doesn't let me break DIM when coding is a :+1:

**Comment by 48klocs** [comment]
I'm in to it.

**Comment by ckhicks** [comment]
It's a hassle if you're not used to it, but having it turned on every day at work is, eh, humbling when I go back to old project files now. 👍

**Comment by ckhicks** [comment]
We use 80 at work and it feels a little cramped, but it also saves you from a lot of headaches if you get too nested in your code. Reminds me of learning (read: breaking) SCSS in the early days...

**Comment by kyleshay** [comment]
Hmm, if we assume developers are running > 1440px monitors I'd say bump it, as that size would support side-by-side on github diffs without wrapping.

**Comment by kyleshay** [comment]
Agreed @ckhicks - Either way, prettier has some really great rules and is able to format 80 width nicely. The 20 extra characters does make a difference though. Maybe run prettier over the codebase and see how things look with 80 first? We have a lot of long variable/service/manifest names.

Just a random snippet:

95 width:
```
    defs.Vendor.get(1037843411).acceptedItems.forEach((items) => {
      vaultMappings[items.acceptedInventoryBucketHash] = items.destinationInventoryBucketHash;
    });
```

**Comment by kyleshay** [comment]
On the bright side we only need to discuss this once... 😇

**Comment by ckhicks** [comment]
Love it - pushing past 80 would be cool but the Github limitation is a really good point.

_Tell us to use long variable names and hashes, they said. Tell us our lines are too long, they said._ 😆

**Comment by bhollis** [comment]
I ended up going with a line length of 100, it feels OK!

**Pull request merged**
