### PR TITLE
Sort shaders by rarity, amount, then name

### PR DESCRIPTION
**Pull request by kyleshay**
Can't remember why we only sorted them by name. Figure seeing it by rarity, amount, then name would be the most useful.

### CODE REVIEW

**Comment by delphiactual** [comment]
Why not let the custom sort actually sort shaders?

**Comment by kyleshay** [comment]
Could, but there isn't an option for amount..

**Comment by kyleshay** [comment]
yeah, I think that makes more sense. 
screen shot 2018-11-12 at 5 01 05 pm

**Comment by duckmanBR** [comment]
If we break it, we could add location, season (or anything like it) as an option

**Comment by kyleshay** [comment]
They're the same in the sense that they're both the primary stat on the item. Maybe I could change the text back to "Primary Stat (Attack/Defense)", but make it something like "Primary Stat (Power/Amount)"

**Comment by bhollis** [comment]
I don't think they're really the same though. A power 600 item is more powerful than a power 500 item, but a stack of 50 shaders is not a better shader than a stack of 4 shaders (in fact, often the opposite).

**Comment by kyleshay** [comment]
That's true. Updated & added an amount option: 
screen shot 2018-11-30 at 1 55 25 pm

**Pull request merged**
