### PR TITLE
Slot independent seasonal mods for LO

### PR DESCRIPTION
**Pull request by ryan-rushton**
Ok this is a MVP cut of slot independent seasonal mods for LO. Basically I am just keeping track of seasonal mods that have been selected in an array and using those for filtering generated sets.

It figures out which mods are seasonal based off the category stuff that sun had implemented for the holds mod style filters.

There is definitely more that could be done but I wanted to see what people think of this before I go too far.

image

image

Edit: If this looks fine I might make one more update to basically assign mods to armour pieces so that a slot can’t be double stacked. Let me know though.

### CODE REVIEW

**Comment by inexorableAce** [comment]
I'd personally rather just see ALL mods be indipendant.. Not just seasonals. Now that affitiny means nothing we likley also shouldn't filter items based on mods either. Truly we should likley just reassies the entire workflow and rebuild. Armor and mods hav changed fairly substancially since this was built.

**Comment by ryan-rushton** [comment]
@inexorableAce But all mods aren't independent. There is actually only a few. For example All targeting mods are still helmet mods, and all loader mods are gauntlet mods. The seasonal and things like minor resistance are independent.

The next step after this might be to exclude those from the armour categories slots but I can imagine people don't care so much as all armour can take a minor resistance or something similar.

**Comment by inexorableAce** [comment]
Yeah that’s not the point. The point is as a person saying I want x y and z I should t have to go through the process of knowing that. I just pick the mods I want and DIM should figure out the rest

**Comment by ryan-rushton** [comment]
Ah, yeah I see what you're saying. It's doable but I think you would still want some separation to make finding them easier. There are a lot of mods and sticking them all in the one panel is definitely not something that I would want. Search or filtering of mods would be needed at a minimum.

**Comment by inexorableAce** [comment]
Yeah just a simple searchable dropdown is all that’s needed. Preferably one that we could recommend things on based on your previous selections.

**Comment by ryan-rushton** [comment]
Ok, well I am happy to do something like that but I wouldn't mind splitting the PR's rather than doing it all in one big go. Will be good to get @bhollis's opinion on this too.

**Comment by bhollis** [comment]
We could certainly try it. The perk picker is already searchable, but this would basically force you to always search.

**Comment by inexorableAce** [comment]
that's true I guess it is searchable already... so I suppose this works as long we move the non-slot based things to similar section. things like mobility mods and what not, so insead of "seasonal" section it would just be a general slot-independant section.

**Comment by bhollis** [comment]
It would be good to have this work on all slot-independent mods instead of just seasonal though - it's weird to have this be all about seasonal mods.

**Comment by ryan-rushton** [comment]
I can if you like but adding in the other slot independent mods adds no value. We are talking minor resistance or a mobility mod which any armour 2.0 piece can take. To make it worth while for those we would have to be able to say “I want 2 major resist and 3 other general mods” then just make sure they have less than the number of armour 2.0 pieces in the set. 

Also if you do want them still do you want them in the same bucket in the drawer or create a general section so that it has the same separation as the destiny UI?

**Comment by bhollis** [comment]
OK. I guess I haven’t played around with the mods that much to know the difference. I can take a look at the code today.

**Comment by ryan-rushton** [comment]
Basically how I see mods these days is each armour piece has 3 or 4 mod slots. 

The first one is that general mod slot I mention above. It takes resist mods, stat mods (except traction), and the artifact's resource/glimmer mods.

Slots two and three are the slot dependent mods, so targeting mods on helmets or loader mods on arms. Class items have their own slot dependent stuff too and boots have traction which slot this spot from memory.

The fourth slot (if the piece even has a fourth) is the seasonal.

Destiny sets has a good split of all the mods and where they fit if you want something to visualise it all, https://destinysets.com/mods.

**Comment by bhollis** [comment]
Wow, that's a nice reference, I hadn't seen Josh add that.

**Comment by ryan-rushton** [comment]
Switching element costs the same as whatever upgrading the piece cost plus an upgrade module. So if you have a masterworked item, its expensive but for anything 7 or lower its relatively cheap.

I am not sold one way or the other whether we should match on element so I am happy to include it if you want. Ideally I would personally like the option to add/ignore element but I think thats another scope of work.

**Pull request merged**
