### PR TITLE
Dialog components

### LINKED ISSUE #9062: Bulk Action "Set Note" prompt does not appear in Vivaldi PWA
### DIM Version

Version 7.55.0 (release), built on 2/5/2023, 6:16:56 PM Chrome 108.0.0.0 - Windows 10

### Browser Details

Vivaldi 5.6.2867.62

### OS Details

Windows 11

### Describe the bug

Using the "app" browser version of the DIM interface, when I enter in search parameters then select Bulk Actions (three vertical dots) and click "Set Note", there is no pop-up window to type out the note.
image

However, when I open it up in Vivladi browser directly (not as an app), it works as intended.
image

I'm not sure the exact terminology I should be using for "app", so to elaborate. Vivaldi, in a manner similar to chrome, can install DIM as an app rather than just working directly in the browser. This version that I normally use is the version that cannot generate the Java Popup window.

### Logs

```shell
app] DIM v7.55.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:124 Language Detected: en-us
instrument.ts:124 Language Assigned: en
www.google-analytics.com/analytics.js:1          Failed to load resource: net::ERR_UNSAFE_REDIRECT
instrument.ts:124 [dim sync] globalSettings Object
instrument.ts:124 [d2-stores] Loaded cached profile from IndexedDB
instrument.ts:124 [d2-stores] Cached profile is older than Bungie.net cache time, proceeding. 199991
(anonymous) @ instrument.ts:124
log.ts:58 Load manifest: 3408.940185546875 ms
instrument.ts:124 [d2-stores] Profile from Bungie.net was newer than cached profile, using it. 201074 201074 Tue Feb 07 2023 20:02:04 GMT-0800 (Pacific Standard Time) Tue Feb 07 2023 19:58:43 GMT-0800 (Pacific Standard Time)
log.ts:58 Process inventory: 152.033203125 ms
log.ts:58 Inventory state update: 12.01318359375 ms
instrument.ts:124 [dim sync] Saving profile data to IDB
log.ts:58 prepareUpdateQueue: 0.664794921875 ms
instrument.ts:124 [flushUpdates] Flushing queue of 1 updates
instrument.ts:124 [flushUpdates] got results Array(1) Array(1)
instrument.ts:124 [dim sync] Saving profile data to IDB
```

### PR DESCRIPTION
**Pull request by bhollis**
Implement an accessible dialog component that can be used to build richer modals than what the browser comes with. For now, I've only replaced all usage of `prompt`/`confirm`, but we can build more complex stuff once this is in. The focus is on developer convenience - the prompt functions work much like the browser equivalents, with some differences only because you can't pause main thread execution like the builtins do.

image

I'd love @liminalAce or @vivekhnz's expert eyes on the styling.

@esotuvaka this is what I had in mind for dialogs 😁 

Fixes #9062

### CODE REVIEW

**Comment by esotuvaka** [comment]
@bhollis Ah I see. In my excitement I forgot that a modal HTML element already exists haha! Glad to see you've got one going. Unless you need some modal theorycrafting I'll look into another issue :)

**Comment by vivekhnz** [comment]
Nice, this seems useful! I'll take a closer look once maintenance is finished.

One thought - in which scenarios would we opt for a modal over a sheet and vice-versa? Is the modal only intended for a short interactions that require an explicit action to dismiss (e.g. 'Cancel' button)?

The sheet UX (animate in from bottom, swipe down to dismiss) feels pretty good on a phone or tablet, but is uncommon in desktop UIs. Maybe the modal would be a more suitable container when on desktop?

**Comment by bhollis** [comment]
> One thought - in which scenarios would we opt for a modal over a sheet and vice-versa?

I've been thinking about this and TBH I think we almost always want a sheet. These dialogs do a good job for the confirm/prompt case though - I don't know that we should do a sheet for confirm, and prompt plus some custom buttons or an extra checkbox maybe could be better as a dialog?

**Comment by liminalAce** [comment]
image

Visually, I'd remove the banding and add some weight to the "ok" option since that's what people likely opened this form to do it should have more weight than cancel. "ok" should also probably be more specific like... "append note" or "add note" etc.

**Comment by bhollis** [comment]
> "ok" should also probably be more specific like... "append note" or "add note" etc. Notes could probably also stand to be a textarea at this point, specially with how many notes it takes to really describe a loadout.

Yeah these are all followups

> add some weight to the "ok" option

I really thought we had a "primary" button class but we don't yet. I'd like to do a general button overhaul soon.

**Pull request merged**
