### PR TITLE
Add stat bars to loadouts that include equipped armor

### PR DESCRIPTION
**Pull request by bhollis**
This is an implementation of the feature request in issue #1545.

loadout-stats

One thing I'd like to discuss - this currently only really makes sense for a "complete" loadout - otherwise, you're seeing just the portion of the stat bars you'd get by equipping that loadout, without knowing what the other pieces would include. I could probably tweak this so it only showed up for a loadout that included equipped helmet, gauntlets, chest, boots, ghost, artifact, and class item, though that may hinder its discoverability.

### CODE REVIEW

**Comment by bhollis** [comment]
I popped in a second commit that implements the "only complete sets" logic - depending on the outcome of the discussion I can keep it or drop it.

**Comment by kyleshay** [comment]
Nice! Actually pretty cool. Was leaning toward only having it show if it is a 'complete set' but for those building set ad-hoc, it could be a nice and quicker alternative to the (T12) loadout builder.

What if it was a different color (or a slight opacity) if it isn't a full set?

**Comment by bhollis** [comment]
loadout-stats2

I like the idea of greying it out. I actually went for a pretty extreme opacity rather than a slight dimming, to really drive home that it isn't complete. What do you think?

**Comment by kyleshay** [comment]
Perfect! 👍

**Comment by kyleshay** [comment]
Do we hide the stat bars for weapon-only/no armor loadouts?

**Comment by bhollis** [comment]
Good call, I fixed it to hide the bars for no-armor loadouts.

**Pull request merged**
