### PR TITLE
Add is:lfr and is:hmg aliases for item categories

### PR DESCRIPTION
**Pull request by bhollis**
These are common enough in the lingo of players to be useful search aliases, maybe?

### CODE REVIEW

**Comment by robojumper** [comment]
LFR is relatively common but I've never heard anyone use "HMG".

**Review by nev-r — COMMENTED** [review]
the more common one from searching and experience is LMG

**Review by nev-r — COMMENTED** [review]
smg should probably be moved to this alias table

**Comment by bhollis** [comment]
Gotcha, renamed it to lmg

**Pull request merged**
