### PR TITLE
Italian translations

### PR DESCRIPTION
**Pull request by simonefranza**
I added some Italian translations to the file and fixed a few spellings. I think there could be some layout problems, because some words are longer than they are in English

### CODE REVIEW

**Comment by delphiactual** [comment]
@simonefranza check out [Atom](https://atom.io/), or [Sublime](https://www.sublimetext.com) they can assist you with these eslint errors prior to submitting your patch. They are both awesome text editors

**Comment by delphiactual** [comment]
@simonefranza Also please check in `app\views\it\` and translate the html files if you have the time.

**Comment by simonefranza** [comment]
@delphiactual Hi, it's the first time I'm submitting something so I'm not so sure about what I should do. I downloaded Atom. Is there something to check the style or anything like that?
I'll translate the html files tomorrow :)

**Comment by delphiactual** [comment]
https://vwannabe.com/2016/05/26/how-to-use-github-and-atom/

**Comment by delphiactual** [comment]
@simonefranza join our [Slack](www.slack.com) @ https://thisisdimslack.stamplayapp.com/ I can assist you easier through the application

**Pull request closed without merging**
