### PR TITLE
Load accounts at startup to validate which have characters (+ messy refactors)

### LINKED ISSUE #2365: Multi-Console Handling
When swapping between consoles, it lists that I've got a Destiny 1 account on PlayStation when I don't. If I accidentally click on Destiny 1 PlayStation then the webpage needs to be reloaded as the option for Destiny 2 PlayStation is removed. Ideally, this would be fixed so that if the account doesn't have any items it doesn't show up in the list. If this is more difficult then hopefully you can fix the bug as is and allow us to swap to the other consoles without having to re-load the page.

### PR DESCRIPTION
**Pull request by bhollis**
I started off trying to modify DIM to actually load accounts at startup, so we could eliminate accounts that have no characters (for example, my phantom Xbox account, or the "D1" account for people who never played D1). This wasn't too hard to wire up, but then I fell into a rabbit hole of plumbing through the model, and then went to get rid of some of our event-based spaghetti code...

The end result is I've cleaned up a bunch of old cruft that coupled things together with events, in favor of RxJS and other patterns we're more into these days. I think it makes things better, but I need somebody w/ multiple accounts to test this out before I even think of merging.

This'll fix #2365.

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
I'll pull this tomorrow and test.  I have 5 accounts across D1 and D2.

**Comment by bhollis** [comment]
@SunburnedGoose get a chance to check this out?

**Comment by SunburnedGoose** [comment]
I don't see any accounts.  
image

**Comment by bhollis** [comment]
With some help from @SunburnedGoose I was able to make this a lot better, finally using Observables for accounts.

**Pull request merged**
