### PR TITLE
i18n updates

### PR DESCRIPTION
**Pull request by delphiactual**
This addresses #1422...

It is nigh impossible to send `<a href>` through json so I adjusted `support.html` to account for this... Another option would be to add iconography to the header area with links to the appropriate sites.

### CODE REVIEW

**Comment by bhollis** [comment]
Recent changes have moved everything around - would you mind rebasing on dev, then I'll merge?

**Comment by delphiactual** [comment]
@bhollis rebased... Some whitespace issues in the conflicted files...

**Comment by delphiactual** [comment]
As you can see with https://github.com/DestinyItemManager/DIM/pull/1427/files?w=1 there isnt anything major being changed in `dimAppCtrl.controller.js` or `dimSettingsCtrl.controller.js`

//cc @bhollis

**Comment by kyleshay** [comment]
looks great, thanks @delphiactual. much nicer to use strings instead of maintaining multiple HTML files.

**Pull request merged**
