### PR TITLE
Add a note about item sizing

### PR DESCRIPTION
**Pull request by bhollis**
screen shot 2018-11-28 at 12 16 23 am

Just so people know, I guess?

### CODE REVIEW

**Comment by duckmanBR** [comment]
I still think we should allow people to go bellow 48 if they want...  Since we now have a "best size" in 50px, an "any size below 50 may look cramped" message may be enough to cover any complaints.
Having to resort to zoom out in the browser on "small" monitors shouldn't be mandatory...

**Comment by inexorableAce** [comment]
People can go as low as they want. CTRL -

**Comment by duckmanBR** [comment]
Ace, using your logic, we shouldn't even need the slider then...

**Comment by inexorableAce** [comment]
Now you’re talking!

**Comment by duckmanBR** [comment]
:laughing: 
the problem is that the browser zoom affects the whole app and not just the icon.

**Comment by bhollis** [comment]
Goong below 48 requires us to change the ratings text to not crowd the label as much.

**Comment by bhollis** [comment]
@duckmanBR what size screen are you zooming to, what size would you choose to make it fit, and what does it look like at that size?

**Pull request merged**
