### PR TITLE
Handle new emblems

### PR DESCRIPTION
**Pull request by bhollis**
screen shot 2018-03-01 at 10 13 14 pm

Fixes https://github.com/DestinyItemManager/DIM/issues/2660. I had to remove the flavor objective when there are actually other objectives with the same hash, and handle "integer" display style differently.

/cc @duckmanBR

### CODE REVIEW

**Comment by duckmanBR** [comment]
I was planning to do something different but this week I couldn't even play yet to check how the new stuff behaves, so when I have the time, I'll do a mockup...
Other than that, don't we have the max value for each objective? (I actually have no idea)

**Comment by bhollis** [comment]
This is just the minimum to get the objectives displaying. There is a max defined, but it’s “1” in this case because with “Integer” display the max makes no sense.

**Comment by duckmanBR** [comment]
So there's no "gotta catch them all" number mocking you?
Now I'm sad with those emblems... :laughing: 

But yeah, sorry if I wasn't clear, but of course we couldn't let it be the way we show them now.
And I actually just discovered that those objectives have no relation to the customizations available, so my initial idea would make no sense.

But if I understood it correctly, the game let's you choose one of those objectives to show as "flavour objective" (on the sense that we had before), right?  So we should at least mark which one is currently selected.

Can't see how we could improve it further...

**Comment by bhollis** [comment]
Oh that’s interesting. I haven’t actually booted the game in weeks...

**Comment by duckmanBR** [comment]
Just one last thing...
We should remove the "complete" tag/border from them...

**Comment by bhollis** [comment]
Good call

**Comment by bhollis** [comment]
Got rid of the border!

**Comment by philkernick** [comment]
Removing the complete tag is good, but removing the line from the header that says "0% Complete" would have been better!  :-)

**Pull request merged**
