### PR TITLE
Mods in loadouts, first cut.

### PR DESCRIPTION
**Pull request by ryan-rushton**
There is still definitely a lot to do but this makes a start. 

One thing that bothers me is the bucket names and mod categories sometimes lining up.

image

Part of #6094

### CODE REVIEW

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/issues/5255

**Comment by kyleshay** [comment]
Yeah, I love it!! I wonder if the mods should show up next to the item similar to the display on the organizer? Just because it may be less ambiguous to what items you intended to apply them to?

In a subsequent PR I think it would be cool if eventually when you apply the loadout but don't have all of the mods applied, we show a toast notification with a button/cta on it that opens a new drawer that shows what mods are mis-matched so you can fix it in-game.

**Comment by bhollis** [comment]
The reason I like them being along the bottom is specifically so we can have operations on the "mod set" itself - like showing what you need to change, or sharing the mod set as a link.

**Comment by ryan-rushton** [comment]
@kyleshay the comparing of mods so you can fix them is definitely planned. I am going to attempt to do something so that it also tells you the cheapest possible way to apply them.

**Review by bhollis — APPROVED** [review]

**Pull request merged**
