### PR TITLE
More testing and tweaking the PR build

### PR DESCRIPTION
**Pull request by ryan-rushton**

### CODE REVIEW

**Comment by ryan-rushton** [comment]
Ok so now I am extracting all the details properly, this is for the opening event.

```
chore/yet-another-fresh-pr-build-test
074da011463472ad8680db32ab38bb4eb3e532d1
ryan.rushton79@gmail.com
Squashed all the commits
1610514315
544962d66ce4791b0f593c87a80c682ebe3dbe01
```

**Comment by bhollis** [comment]
No config I know about that'd prevent the report. Might want to ask packtracker support, but my guess is we still don't have enough info for it to identify the PR. Like, how does it know which fork the PR is from?

**Comment by ryan-rushton** [comment]
@bhollis I am tempted to just merge this as I am sure its more correct than what we have now. I haven't heard back from the packtracker guy.

**Comment by bhollis** [comment]
Sounds good to me.

**Pull request merged**
