### PR TITLE
Rethink mobile store swiping

### PR DESCRIPTION
**Pull request by bhollis**
I've been struggling a bit with how to page between stores on the new iteration of the mobile view. I tried to make it all one big pager, but that broke scrolling pretty bad. This version has two separate pagers - one for the header and one for the body, and either one can be used to swap. It doesn't look too bad (ignore the hitches, I haven't gotten to any performance optimizations so React is re-rendering the whole world all the time):

swipe

Unfortunately, I can't figure out how to get drag and drop to work with this. You can start dragging, but you can't drag anywhere because it moves the pager around. It's conceivable I can patch the pager to disable itself when we're dragging but it's pretty complicated working between several different libraries that each do their own touch handling.

I decided for now the right thing to do is probably to just disable drag and drop. It was only really useful for equipping, but even then it was somewhat awkward. However, without dragging, the terrible move popup mobile design really stands out. So, I decided to bite the bullet and just move the buttons to the top of the popup:

screen shot 2018-09-12 at 12 08 04 am

Hopefully this is all temporary until we can get a new move popup.

### CODE REVIEW

**Comment by bhollis** [comment]
The other option would be to keep things basically the way they were - you can swipe the header, but can't swipe back and forth on the inventory, but you can drag, and there's a hidden swipe gesture to move between stores. I can certainly make that happen again.

**Comment by kyleshay** [comment]
What if the start of a swipe is on an item it enables drag/drop, but anywhere else it swipes the page? Or is that what you were trying to do but were running into issues with? 

In a different iteration maybe we could figure out a way to swap between characters/vaults without using swipes? Dropdown/buttons might be less work to get from a far left character to the vault, for example. 

BTW - have you played with the new application switcher on latest android? It's kind of a cool way to swap between things. It's a horizontal swipe/scroll that feels like snaps to a grid, where each tick is a different app.

**Comment by bhollis** [comment]
Yeah I wasn’t able to get item dragging to cancel store swiping.

**Comment by bhollis** [comment]
Btw, for reference, other apps (companion, Ishtar) have no dragging and swiping switches between inventory screens.

**Comment by duckmanBR** [comment]
>basically the way they were -  you can swipe the header, but can't swipe back and forth on the inventory

They were when? Because I can swipe back/forth on the inventory (prod).  Swiping on the inventory just doesn't show the "drag animation" but it works (at least on Android).

What I can only do on header is tap the "peek" to change.  And that will probably going end on the design revamp.

**Comment by bhollis** [comment]
OK, I ended up reimplementing nearly identical behavior from the old layout. I'll work on improvements separately.

**Pull request merged**
