### PR TITLE
Factor out an ItemDescription component

### PR DESCRIPTION
**Pull request by bhollis**
Another one from the in-progress item popup redesign. This replaces the always-open notes field with a smaller but more understandable "Add a Note" button.

Screen Shot 2019-05-27 at 3 37 31 PM
Screen Shot 2019-05-27 at 3 37 43 PM
Screen Shot 2019-05-27 at 3 37 53 PM

### CODE REVIEW

**Comment by inexorableAce** [comment]
can we bold the "add a note" and "notes" text, it all kinda blends together at the moment. either needs some of that dreaded white space or some other thing to give it some hierarchy. At the moment it's not really clear that it's even actionable since it looks just like other text that isn't actionable.

**Comment by bhollis** [comment]
Sounds good. I’ve been saving underlined links for external stuff, but maybe we can make it more obvious. Partly what I’m trying to do here is save space so spacing everything out will be hard.

**Comment by bhollis** [comment]
How's this look?

Screen Shot 2019-05-31 at 11 24 21 PM
Screen Shot 2019-05-31 at 11 24 27 PM

**Comment by inexorableAce** [comment]
Much better 😀

**Pull request merged**
