### PR TITLE
Link to lowlines' map from Collections

### PR DESCRIPTION
**Pull request by bhollis**
The map is great, and handles the checklist stuff really well!

screen shot 2018-07-01 at 4 55 22 pm

/cc @lowlines

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Looks good.

**Comment by 48klocs** [comment]
@bhollis @lowlines map is super cool (and is way slicker than throwing the manifest bits up) so I'm in to it.

It doesn't track Leviathan raid lair completions (they're tracked account-wide), which isn't that big of a deal.

**Comment by 48klocs** [comment]
@bhollis on second thought, what about putting that link on the progress page, under the account milestones where I put the checklist link in #2909 ?

**Comment by bhollis** [comment]
Hmm, don't the ghost scans and stuff seem more like collectibles than character progression?

**Comment by duckmanBR** [comment]
Both.  Ghost Scans, Chests, etc are Collectibles, but memories and nodes are progression...
But then I believe that it should be inside the checklist page and not on the progress.

**Pull request merged**
