### PR TITLE
Group milestones by power bonus

### LINKED ISSUE #7221: Group milestones by reward
It might be nice to group milestones by what kind of engram they produce, with pinnacles on the top, etc

### PR DESCRIPTION
**Pull request by bhollis**
Thought this'd be fun to get in before the next season drops (though who knows, maybe Milestones will be totally overhauled...)

It groups the "Milestones & Challenges" by the power bonus their rewards provide. This automatically adjusts as you reach the cap - for example, in the beginning pinnacles and tier 3 powerfuls will be grouped together as +5, tier 2 powerfuls will get their own group at +4, and the rest of the powerfuls will be +3. But once you hit the soft cap as I have, you only have +2 pinnacles and +0 everything else.

Fixes #7221

localhost_8080_4611686018433092312_d2_progress

### CODE REVIEW

**Comment by nev-r** [comment]
missed a file maybe?
ERROR in ./src/app/progress/Milestones.tsx 16:0-41
Module not found: Error: Can't resolve './Milestones.m.scss'

**Review by robojumper — APPROVED** [review]
Seems reasonable (although all my rewards are +0 but that's expected for me). One thing worth keeping in mind is that this probably still reports +1 pinnacles from the playlist sources as +2 because the API doesn't have different reward items?

**Comment by nev-r** [comment]
yeah this will definitely rouse people to let us know which info is wrong

**Comment by bhollis** [comment]
Unfortunately there is no distinction in the API between +1 and +2 pinnacles.

**Pull request merged**
