### PR TITLE
Fixed Fynch rank level on Vendors page.

### PR DESCRIPTION
**Pull request by asinusi**
Fixes issue #8016

### CODE REVIEW

**Comment by bhollis** [comment]
Can we make sure to validate that all the other vendors show the correct version?

**Comment by asinusi** [comment]
All other vendors still show the correct version. I opted to go with this since all other vendors have the correct `vendor.progression.level` so using the `vendor.seasonalRank` seemed redundant. I could add a check for `vendor.progression.level` if it exists and is higher than `vendor.seasonalRank`, otherwise continue doing what it was already. For example:
```typescript
 const getVendorRank = (vendor: DestinyVendorComponent | undefined, factionProgress: DestinyProgression): number => {
    if (vendor?.progression?.level
      && vendor?.seasonalRank
      && vendor.progression.level > vendor.seasonalRank) {
      return level;
    }
    return vendor?.seasonalRank ?? factionProgress.level;
  }
  const level = getVendorRank(vendor, factionProgress) + 1;
  ```

**Comment by bhollis** [comment]
Are we sure that progression.level and seasonalRank are the same? Does the former not reset after each season?

**Comment by asinusi** [comment]
Given that for all the vendors (except Fynch) have the same value for both these properties I'm assuming that they both reset after each season, hence making `progression.level` the ideal property to use. Here is a comparison of the old expression vs new:

| **Vendor**                	| **Old** 	| **New** 	|
|---------------------------	|---------	|---------	|
| Conscientious Objector    	| 1       	| 39      	|
| Purveyor of Strange Goods 	| 11      	| 11      	|
| Vanguard Operations       	| 14      	| 14      	|
| Gunsmith                  	| 12      	| 12      	|
| Vanguard Tactical         	| 15      	| 15      	|
| Rogue Lightbearer         	| 7       	| 7       	|
| Hero of Six Fronts        	| 6       	| 6       	|
| The Crucible              	| 14      	| 14      	|
| Dead Zone Scout           	| 0       	| 0       	|
| Exodus Black AI           	| 0       	| 0       	|

**Comment by bhollis** [comment]
Gotcha. Guessing they're synonymous but the new one didn't get wired up.

**Review by bhollis — APPROVED** [review]

**Pull request merged**
