### PR TITLE
Initial stab at generic parameters for search

### PR DESCRIPTION
**Pull request by bhollis**
This doesn't do anything but it's the start of making it possible to have different search configs for searching different kinds of things. @ryan-rushton I figured it'd be useful if you wanted to hack around on that.

### CODE REVIEW

**Comment by ryan-rushton** [comment]
Yup this was what I was thinking for the search suff I have been playing around with. Might use this and my search bar PR to see if I can get a loadouts version working

**Comment by bhollis** [comment]
The one thing I'm not sure about is how to smash together the existing item search with loadout/vendor specific search

**Comment by ryan-rushton** [comment]
I'm not convinced we do smash them together yet but the idea has crossed my mind. My first attempt will be at pulling them apart so maybe we see what that looks like then if it sucks we can try put it all together.

**Review by ryan-rushton — APPROVED** [review]
LGTM

**Pull request merged**
