### PR TITLE
gradient tweaks, richer color, more blue, darker

### PR DESCRIPTION
**Pull request by inexorableAce**
tweaking the new background a bit based on some feedback about it being a bit to washed and non-contrasty. also added the gradient as a var so it can be reused / edited more easily as it spans multiple elements.  

BEFORE
image

AFTER
image

### CODE REVIEW

**Comment by bhollis** [comment]
Trying this out - I love the actual color, but it being so dark, there really isn't enough contrast for the item popup.

**Comment by bhollis** [comment]
BTW I'm planning on turning on the gradient background for our Nov. 8th release, in whatever state it happens to be in in Beta.

**Comment by inexorableAce** [comment]
I don't disagree. We have light elements on the tiles borders that need contrast with the BG and the dark sheets and pop-ups which also need it. That's why the original works better, even if it does look a bit washed, that medium time is just what's required for contrast on both.

**Comment by bhollis** [comment]
Maybe there's a way to retain that mid-level value but still saturate the color a bit more? And maybe tweaking the difference across the gradient (or varying hue instead of lightness) would help us combat the value change over the page?

**Pull request closed without merging**
