### PR TITLE
Show armor stats

### PR DESCRIPTION
**Pull request by kyleshay**
refactor reload character meta stats, show int/dis/str. the 'on-hover' shows alt text of the cooldown.

someday we should go through the app and replace all the `title` attributes with a directive that shows a tooltip with a much shorter timeout. until then.

how it looks, open to suggestions:

screen shot 2016-02-23 at 10 08 36 pm

demo

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Love it.

**Comment by kyleshay** [comment]
### 5 character column
screen shot 2016-02-24 at 10 22 27 am
### 4 character column
screen shot 2016-02-24 at 10 22 44 am
### 3 character column
screen shot 2016-02-24 at 10 22 55 am

**Comment by jkissell** [comment]
NICE!

**Comment by SunburnedGoose** [comment]
Are these updating in in realtime with changes to the character?

**Comment by kyleshay** [comment]
yeah, they do -- 

demo

**Comment by ritcheyer** [comment]
I feel the solid white a bit too much.. what do you think about adding in some opacity? say something like:

```
.characater .stats { opacity: .8; }
```

Although a sweet feature that I can't wait to use, it seems like the whole area is getting too busy --- especially when you scroll and the header locks into place.

**Comment by kyleshay** [comment]
@ritcheyer yup love how that looks.

demo

**Comment by ritcheyer** [comment]
:+1:

**Comment by kyleshay** [comment]
> Although a sweet feature that I can't wait to use, it seems like the whole area is getting too busy --- especially when you scroll and the header locks into place.

I struggled with that also, where to draw the line. Any additional info will need to go somewhere else, we're at `141px` for a fixed header. Suppose I could make it a bit thinner.

However, @SunburnedGoose this does open up a bit more space in the vault section. so that if we ever wanted to move some more information up there (like the vault capacities) and out of the headers, we could be on our way to rearranging/hiding the rows

**Comment by bhollis** [comment]
This is great!

**Comment by SunburnedGoose** [comment]
Do we show the individual stats for items?

**Comment by kyleshay** [comment]
like so? screen shot 2016-02-24 at 1 43 12 pm

**Comment by SunburnedGoose** [comment]
Derp.  I was looking at weapons.  I am ashamed.

**Comment by kyleshay** [comment]
haha all good. actually good you asked about it. didn't realize till now that armor doesn't show the red/green bar stat diff similar to how the weapons do. in that picture i linked it dosn't show how it compares to the equipped item aside from green/red apposed to a weapon showing something like this:

screen shot 2016-02-24 at 1 57 19 pm

**Comment by bhollis** [comment]
Armor should show the red/green comparison bars. I fixed that.

**Comment by bhollis** [comment]
Wait, I clearly messed that up. Filed an issue for myself: #417

**Pull request merged**
