### PR TITLE
Update Tooltips

### PR DESCRIPTION
**Pull request by bhollis**
Popper.js got an overhaul, and in upgrading I wanted to simplify how we handle tooltips, so I consolidated them both to the same mechanism. So now both the item popup and PressTip are done directly with popper.

### CODE REVIEW

**Comment by delphiactual** [comment]
This also fixes #5033

**Comment by bhollis** [comment]
Cool!

**Comment by sundevour** [comment]
713v32
926pcI
globally, the stem spawns off-center for hover, then centers itself if you click

**Comment by sundevour** [comment]
the stem wiggles a little bit on item-popup as well, but i'm unclear how to duplicate. maybe some race condition or specific mouse movement i'm doing beforehand. it's by the seemingly same offset, so likely same as above

**Comment by bhollis** [comment]
Yeah, it’s some difference in the way it’s being measured. In the old tooltip we had some timing hacks in place that I removed, maybe there’s something like that going on.

**Pull request merged**
