### PR TITLE
Loadout by perks

### PR DESCRIPTION
**Pull request by ericnelson0**
This is the PR that will allow the loadout builder to build loadouts by selection a set of perks instead of specific armor. It is still a WIP, but enough functionality is there that I wanted to try and get some feedback on it.

The perks are loaded based on the gear that the selected guardian has.

In reference to issue #776 and there were other places this was suggested, but I can't seem to find them.

example-loadout-by-perks

Planned remaining tasks:
- [x] Easier closing mechanism for perk selection box
- [x] Close other perk selection boxes when a new one is opened
- [x] Stop processing sets when locked perks change
- [x] Add ability to "and" perks instead of only "or" (maybe by shift-clicking?)
- [x] Clear locked perks on character/platform switch
- [x] Some notification of currently selected perks

EDIT:
This also fixes issue #834

### CODE REVIEW

**Comment by kyleshay** [comment]
NICELY done!! I love where this is heading! :)

**Comment by wein3967** [comment]
That looks really awesome.

**Comment by ericnelson0** [comment]
I think this is in a pretty good place now. The purple means those perks will be "and'ed" whereas orange perks will be "or'ed". You can shift+click to "and" perks.

The latest looks like:

example-loadout-by-perks2

I'm eager to hear any feedback/thoughts/ideas. I'm still looking for a better way to display when multiple perks are selected.

**Comment by ericnelson0** [comment]
@kyleshay @SunburnedGoose You guys mind if I merge this in so people can start testing?

**Comment by SunburnedGoose** [comment]
Go for it.  I'm still wrecked from the trip.

**Pull request merged**
