### PR TITLE
More saturated gradient options

### PR DESCRIPTION
**Pull request by bhollis**
Playing with the gradient a bit. This reduces the overall change in lightness, while also saturating the background color more.

Original:
Screen Shot 2020-11-07 at 10 40 56 PM

Option 4 - the original gradient, but with a less bright center:

Screen Shot 2020-11-08 at 1 47 13 PM

Option 1:

Screen Shot 2020-11-07 at 10 41 04 PM

Option 2 (a bit lighter, a bit less saturated):

Screen Shot 2020-11-07 at 10 45 41 PM

Not-really-an-option 3 (vary hue/saturation instead of lightness, looks dreadful):

Screen Shot 2020-11-07 at 10 49 00 PM

### CODE REVIEW

**Comment by bhollis** [comment]
I'll note that going from Option 2 back to Beta after a minute makes Beta feel extremely dreary and dull. But then, after being away from both of them for a bit, Beta feels fine. I wonder if the brighter colors would cause fatigue over time, like Best Buy TVs all having their saturation cranked just to sell them.

**Comment by inexorableAce** [comment]
I guess of these 2 is the best of the changes but it's brighter than the original or appears to be and i think? Maybe we just need to darken the light part of the gradient to closer match the dark part?

**Comment by nev-r** [comment]
i'm somewhere between 1 and 2. i would like to see it not be a gradient between different saturations but different brightnesses or hues. greying feels inherently boring

**Comment by bhollis** [comment]
Option 2 only varies brightness, option 3 only varies hue. Option 1 varies both brightness and saturation. (I changed the colors to HSL to make that easier to tweak)

**Comment by bhollis** [comment]
Option 4 - the original gradient, but with a less bright center:

Screen Shot 2020-11-08 at 1 47 13 PM

**Review by nev-r — APPROVED** [review]

**Pull request merged**
