### PR TITLE
Explain assume masterwork

### PR DESCRIPTION
**Pull request by bhollis**
This replaces the tooltips on the Assume Masterwork widget with text underneath that explains the options - the hope is that this is clearer / more discoverable. I also tweaked the wording of the title and one of the options, and put the whole thing in a box similar to the loadout edit sections.

Before:
Screenshot 2023-11-05 at 5 11 05 PM

After:
Screenshot 2023-11-05 at 5 09 02 PM

### CODE REVIEW

**Comment by lowPolySkeleton** [comment]
Love this!

**Review by robojumper — APPROVED** [review]

**Review by guise — APPROVED** [review]
+1 for making this more obvious. 

IMO the title/description are a little verbose/repetitive and could be made more concise/explicit. 

Suggestion:

Title
> Assume Masterwork

None: 
> Use current armor stats 

Legendary
> Legendary armor is +2 in each stat

All:
> Exotic and legendary armor is +2 in each stat 

Fixed descriptor for all? 
> Non-masterworked armor is assumed energy level 9. 

Aside: Does `{{minLoItemEnergy}}` need to be variable? Not sure if i'm being dense here but I can't see when this would change based on the LO parameters?

**Comment by robojumper** [comment]
> Aside: Does {{minLoItemEnergy}} need to be variable? Not sure if i'm being dense here but I can't see when this would change based on the LO parameters?

This used to be 7, hardcoded in localization, but in #10037 I increased it from 7 to 9 and made it variable in case we ever change our mind about this again,.

**Comment by bhollis** [comment]
The tough part about those shorter strings is that I really want to clearly get across the idea that this is controlling both *stat bonuses* and *energy limits*. Thus the change in both the title and the explanation text. I'd love to simplify them but I need to get that info across.

**Comment by guise** [comment]
IMO brevity could help explain the behaviour more concisely by making the description easier to skim read/parse. 

My intention was to condense each sentence to fit on a single line making it easier to scan. Perhaps something more like this? 

image

Re: title shortening - this was more of a personal preference for shorter titles (again, for scan-ability) and from the perspective that energy/stat changes are implicit in masterworking so this is somewhat redundant given we're explaining the specific behaviour in the description.

**Comment by bhollis** [comment]
Cool, I went with that wording.

**Pull request merged**
