### PR TITLE
CodeClimate

### PR DESCRIPTION
**Pull request by delphiactual**
Fixes failure during build for eslint
Cleanup `.eslintignore`

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Would love it if we ran this when the developer uses git push to avoid blowing up my notifications when hound is angry.

**Comment by delphiactual** [comment]
The failure was because codeclimate assumes `eslint v1.10.3` if none is specified.

**Comment by bhollis** [comment]
@delphiactual, could you explain a bit more about what you're proposing here? Are you suggesting we switch to CodeClimate instead of Hound? @SunburnedGoose, for context, at least the last time I used it, CodeClimate is a service similar to Hound (the only reason I didn't use it in the first place was that it didn't support eslint at that time).

**Comment by delphiactual** [comment]
CodeClimate can be used in conjunction with hound, as it also will expose other weak areas(complicated or dupe) of code. 
This was being used by someone, they may or may not of been on the team. It worked until the eslint was added. This small change will just allow codeclimate to update its scoring and will not affect anything else. An integration is also possible like hound or travis-ci but I do not have experience in that area at all.

https://codeclimate.com/github/DestinyItemManager/DIM/

**Comment by bhollis** [comment]
OK, cool. This seems fine, then.

**Pull request merged**
