### PR TITLE
Switch AnimatedValue to Framer Motion

### PR DESCRIPTION
**Pull request by bhollis**
It's not as pretty but it's one less place we use react-spring.

### CODE REVIEW

**Review by ryan-rushton — APPROVED** [review]

**Review by nev-r — APPROVED** [review]
definitely works. the number animation itself seems really noticeably chunkier, but it's low stakes

**Comment by bhollis** [comment]
I made a sandbox to compare them - perhaps the spring parameters just need to be tweaked: https://codesandbox.io/s/tender-water-zd3ei

**Comment by nev-r** [comment]
https://user-images.githubusercontent.com/68782081/148718470-05d80283-0ec3-4c32-beca-f6b76bdbfd3d.mp4

there's just a weird easing curve to it, where it does the majority in one burst, then an odd pause before the last digit clicks over

**Comment by bhollis** [comment]
Take another look, I tweaked the animation curves.

**Pull request merged**
