### PR TITLE
Implement pull-to-refresh for mobile

### PR DESCRIPTION
**Pull request by bhollis**
This is a stab at a native-like "pull to refresh" behavior for mobile.

Note that it's kind of weird to have refresh both in the header and in pull-to-refresh. Personally I'd be OK with removing it from the header if we had some other way of indicating "DIM is doing something". @inexorableAce got any good ideas?

ptr

### CODE REVIEW

**Comment by inexorableAce** [comment]
I’d probably leave it, pull to refresh is cool and it works well for this, but it’s a new pattern for DIM so having the familiarity of the button to refresh for users is good. Also since it serves as the loading indicator for now. 

In the future as the pattern becomes more clear, it would be nice to up our status indication game though. Give some more information about what’s happening when like “pulling fresh information for your character” or “transferring search results now” etc, these could also serve as a replacement for the pop ups we have now.

**Comment by duckmanBR** [comment]
It **is** cool, but don't know if it's desired to block users to do a "real" refresh of the app.

**Comment by bhollis** [comment]
@duckmanBR do you know if the Android pull-to-refresh can be customized?

**Comment by duckmanBR** [comment]
No idea

**Comment by delphiactual** [comment]
@duckmanBR how does pull to refresh "block" a real refresh?

**Comment by duckmanBR** [comment]
When you add to desktop (on Android) you loose any Chrome menu.  Any way to page refresh is the pull down.
You also could kill the app and reopen it (it's what I've been doing when the app recuses to update to a new version).

**Comment by inexorableAce** [comment]
So the pull to refresh is no different than what we have now the for your example situation?

**Comment by duckmanBR** [comment]
Built in pull to page refresh (at least on chrome).
This PR is for a pull to app refresh.

**Comment by inexorableAce** [comment]
Gotcha, so when you say “block a real refresh” you’re referring to blocking the native pull to page refresh that andriod (on chrome) has by default. That’s what I was getting at. 

And yeah I guess that’s an issue. If some OS / browsers have a native pull - refresh we would likely want to keep that.

**Comment by delphiactual** [comment]
https://developers.google.com/web/updates/2017/11/overscroll-behavior#p2r

**Comment by bhollis** [comment]
@duckmanBR wait when does it refuse to update?

**Comment by duckmanBR** [comment]
From time to time taping the "update DIM" does nothing.  A force close (going to open apps/square and swiping left/tight) and than reopening the app does the trick.

**Comment by bhollis** [comment]
Does it at least reload the page?

**Comment by duckmanBR** [comment]
The kill procedure? Loads the new/updated version.
The pull-to-refresh opens from cache.  At least it's whats looks like, since it doesn't update DIM.

**Comment by bhollis** [comment]
No I mean tapping the “Update DIM” button.

**Comment by duckmanBR** [comment]
oh sorry.  yes.  reloads the page but opens on the same version.

**Comment by bhollis** [comment]
I'll probably fix this up and merge it now that Android pull to reload is disabled.

**Pull request closed without merging**
