### PR TITLE
Update ESLint rules

### PR DESCRIPTION
**Pull request by bhollis**
This enables a handful more ESLint rules, and runs the auto-fixer to fix violations. The big ones are moving fully away from `var` to `const` and `let`, switching to arrow functions where possible, and using property and method shorthand where possible. Almost all of the changes to the actual code were done automatically, and I've changed `npm run lint` to also auto-fix.

### CODE REVIEW

**Comment by bhollis** [comment]
FWIW I'm not sure how comfortable I am with the property and method shorthands. Just not that used to them.

**Comment by bhollis** [comment]
Updated to include the new reviews stuff, and also to add an Angular lint plugin that can detect unused DI injections and other bad patterns.

**Comment by delphiactual** [comment]
possibly add `angular/no-inline-template`

https://github.com/Gillespie59/eslint-plugin-angular/blob/master/docs/no-inline-template.md

**Comment by delphiactual** [comment]
https://github.com/houndci/linters/issues/127

**Comment by bhollis** [comment]
I rolled back the object shorthand rule since it felt too weird, we can always try it later.

**Pull request merged**
