### PR TITLE
Rearrange factions and grey out unavailable ones

### PR DESCRIPTION
**Pull request by bhollis**
I found a property that tells us whether a given faction has a vendor available for a character. Using that, I greyed out unavailable factions (event vendors, etc). I also rearranged things a bit more to put event vendors on the bottom:

screen shot 2018-01-09 at 11 18 32 pm

### CODE REVIEW

**Comment by bhollis** [comment]
The other option would be to hide them entirely when they're not available. Thoughts?

**Comment by SunburnedGoose** [comment]
Would it make sense to hide the available engram on factions that are disabled?  Do we have a reason to show it?

**Comment by bhollis** [comment]
If we want to hide that we should just hide the whole thing. The only value is for people to know what they *could* do when the event rolls around.

**Comment by kyleshay** [comment]
I say show all the things... If we don't then people will ask to see it. Plus it's nice that it makes it a single place to see everything

**Comment by kyleshay** [comment]
Only comment might be instead of making it fixee, giving grayed out things a weight, so they fall to the bottom?

**Comment by bhollis** [comment]
How about this?

screen shot 2018-01-11 at 8 32 14 pm

I'm still showing everything, but I'm sorting the unavailable ones to the bottom too. I also figured out how to get the vendors' names, which I think look better than the faction name. For unavailable vendors I kind of have to guess (each faction can have multiple possible vendors, like the Gunsmith bot in the farm vs. Banshee).

**Comment by bhollis** [comment]
Oh, also, I moved the rather useless XP numbers into a tooltip.

**Comment by duckmanBR** [comment]
I was going to say I was against the re-sorting to keep the greyed ones to the bottom, them I realized that all the ones that would keep changing status would change to all the characters at the same time, so it's ok.

Another idea, specific to the FWC/NM/DO (since they are "special" in the way their progression reset at the end of the event, and we can only pledge to one of them per character):
- hide them outside of the event
- show the 3 while you have 0 reputation
- hide the other two, if one of the factions get any progression value, or after pledge, if the API is able to inform through factionVendorIndex.

**Pull request merged**
