### PR TITLE
Add Dockerfile so we can develop in a Docker container

### PR DESCRIPTION
**Pull request by jsatk**
Adding a Dockerfile to allow for development to be done in a Docker container. 

This PR assumes this PR has been merged https://github.com/DestinyItemManager/DIM/pull/847. If for whatever reason that PR does not get merged but we still want to merge this Dockerfile PR then a few minor updates will need to be made to this Dockerfile.

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
I don't know how this benefits DIM.  Can you explain?

**Comment by jsatk** [comment]
@SunburnedGoose it would allow other developers to more easily work with and contribute to DIM because they would not be required to install anything on their machine. This also allows for this development on this repo to work across a broader range of environments. 

It's a minor addition and one that would not affect the extension itself in anyway and is meant strictly to help any developers who wish to contribute to this project (like myself).

**Comment by SunburnedGoose** [comment]
I'm unfamiliar with Docker, and how DIM would be developed/used within that environment.  Is it just a shell that keeps changes to your OS isolated somehow?

**Comment by jsatk** [comment]
@SunburnedGoose Docker is a tool that's gained a lot of popularity over the past year or so. It allows you to run and develop apps in a "container", which is a local linux instance on your machine. Docker works with OS X, Windows, and Linux. One of its primary goals is to eliminate "works on my machine" issues as well as allow a unified installation/setup process for all developers.

I'm new to this project. If this project doesn't see a lot of contributors this PR may not be worth it. But if it does, some folks may appreciate being able to run this in a Docker container. 

Totally your call. I have no ego attached to this PR. Just thought it might benefit some folks and make contributions to this repo easier. 😁

**Comment by SunburnedGoose** [comment]
It's fine, I just want to know how it works because I've heard of it, but haven't seen it.  Don't mind dropping config for dev environments, but if I wanted to test this, I'd need to see how it would work and atm I don't know step one :)

**Comment by kyleshay** [comment]
looks good

**Pull request merged**
