### PR TITLE
Constraint shorthand

### PR DESCRIPTION
**Pull request by bhollis**
This adds the "constraint shorthand" we show under armor to represent stat constraints to the stat constraint editor rows. The intention is to teach what these mean.

I also swapped from "T10-" and "T4+" to "≤T10" and "≥T4". I'm not sure if those are better or not - they're in a separate commit in case folks hate them.

Screenshot 2023-11-04 at 6 27 33 PM
Screenshot 2023-11-04 at 6 30 15 PM

### CODE REVIEW

**Review by lowPolySkeleton — APPROVED** [review]
I do think this is better than the old Symbols for sure I never fully grasped those. This is nice also in that it's showing it as you select things to help make the connection.

**Comment by guise** [comment]
I'm not sure about this one… 

When you have selected a tier this makes sense. My concern is displaying stats with `0` selected as `≤T10` as this risks being confusing: 

- _At a glance_ the '10' is the most prominent identifier making it look like you're targeting T10
-  In the Loadouts list this gets exaggerated because the font size is smaller and you lack the context of the visually highlighted stat tiers in the LO 
- If you have a loadout targeting T10 + T0, the only differentiator becomes the operator character 

Possible alternatives: 

- Showing `>0` would be more visually distinct and have a direct correlation to the value you've selected for the stat. It may not necessarily be how the LO logic is evaluated, but it feels like it would more clearly depict the idea of "I want to include this stat"
- Reduce the font-weight of the operator/tier to make it more legible
- Or consider potentially swapping the operator character for an icon that could be made a little larger/spaced out?

*** 

Small html char rendering issue, also appears in the LO selected T10:

image

**Comment by bhollis** [comment]
Yeah, this was intentional but maybe too subtle. I could show ≥T0 in that case, but my worry is that it looks "worse" than showing T10 - even though leaving the stat minimum at 0 is probably the *best* way to get good stats. So my thought was to invert it so it looks enticing.

**Comment by bhollis** [comment]
This one is definitely not a home run, but with icons it looks better at least:
Screenshot 2023-11-07 at 9 02 07 PM

I'm still not sure people won't see `>=T0` and think "T0!? That sucks!"

**Comment by guise** [comment]
Spit-balling some other idea…  

Dropping the 'T' - numbers scan clearer, but comes at the expense of context (and may not work on loadouts list page)
image

Color change on the tier number - eww
image

Using `font-variant: small-caps` on the T so it 'gets out the way' a bit — could work? 
image

**Comment by bhollis** [comment]
I'm going to merge this to update the loadout parameters display, but wait on showing it in the stat constraint editor.

**Pull request merged**
