### PR TITLE
Add the option to show elemental damage icons on weapons.

### LINKED ISSUE #427: DIM is not colorblind friendly
Apparently these colors are different (boy it's fun being colorblind): its so fun being colorblind

As they show in the item view, a colorblind person still can't tell the difference: yay so fun

Personally, I'd love it if the element icon was on an item somehow, instead of using a title bar background fill, or primary stat background fill, or tiny triangle fill when primary stat is not turned on.

### PR DESCRIPTION
**Pull request by bhollis**
We will also always show elemental damage icons in the popup title. This should fix #427. Paging @mulchman for an opinion.

screen shot 2016-04-24 at 4 10 47 pm

screen shot 2016-04-24 at 4 12 25 pm

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
They are so small that the arc and void blend. They need color.

**Comment by Mulchman** [comment]
I think this looks great!  (I am viewing it via email on a phone, though,
so Rick's comment about size might be relevant when on a desktop monitor.).

I know you guys aren't fond of a plethora of icons on items in the various
listings and lots of settings, so maybe this could be a button toggle type
thing like in game when you hold L2/LT in the inventory screen to see the
element types? (eg. the user holds Left Control and the icons are rendered
vs. dedicated settings option.).

Either route is great as I can now tell void from arc!

**Comment by bhollis** [comment]
@Mulchman it's an option in the settings.

@SunburnedGoose I thought about that, but they're actually pretty easy to tell apart because of their shape. I can add color but we already have a color cue (in the background of the primary stat) and this is addressing the problem of folks who can't rely on that color.

**Comment by SunburnedGoose** [comment]
I'll look. The opacity makes arc look like voi dwhen the background is
purple, and its causing friction. You're making me have to concentrate too
much when I'm just trying to glance.

**Comment by bhollis** [comment]
screen shot 2016-04-24 at 7 27 31 pm

Full opacity helps with that, but is pretty jarring.

**Comment by bhollis** [comment]
Any opinion on the full-strength icons?

**Comment by kyleshay** [comment]
looks good to me! thanks for including the toggle.

👍

**Pull request merged**
