### PR TITLE
better compare buttons

### LINKED ISSUE #4435: Include energy type in duplicate calculations
Hey guys great idea in putting the energy on all the armor. I think it would be a great idea to also include them when I am comparing all duplicate items in the "compare items" so I know what I should trash... 

thanks for listening and please keep up the good work!

### PR DESCRIPTION
**Pull request by sundevour**
more detailed compare-all-of buttons for the more discerning comparer

armors offer:
sameElementDupes
dupes
sameClassPieceAndElement
sameClassAndPiece

weapons offer:
sameWeapon
sameWeaponTypeAndArchetype
sameWeaponTypeAndElement
sameWeaponTypeAndSlot
sameWeaponType

re:i18n @delphiactual i'm sorry i did it again

closes #4435

### CODE REVIEW

**Comment by bhollis** [comment]
We might want to merge this after the Sunday release.

**Comment by sundevour** [comment]
yeah delphi has provided an exhaustive report of archetype idiosyncrasies and a week in beta would be nice.
ultimately going to spawn sheet with "exactest dupes" pre-populated

**Comment by inexorableAce** [comment]
So my main thought on this is that I actually never click compare from an item I specifically want to compare. 

I’m typically just looking to compare that gun in general, or that armor type in general and pick the first one I find to hit compare button on. 

So that means I’d need 3 times the buttons you have or, that they would need to change as I closed things? I guess? Or that I’d have to put a lot more thought and effort into what I’m comparing before I go in. 

But I’d imagine compare is a fairly generalized tool for most, you get to it from one item but from there what you’re doing changes as you start to compare. 

I think this a great time to just ditch what our current understanding of compare is and make a better tool that can do more, that’s gonna take a lot more time to think through though. 

My first major thought on this and that instead of more buttons we could just add affinity as a sort option in with the other stats.

**Comment by sundevour** [comment]
i don't fully understand if this is feedback or compare-related musings, a bunch of it confuses me in either context

**Comment by inexorableAce** [comment]
Bit of both? Basically having buttons that correspond to where you started (e.g. I clicked compare from a solar affinity armor, so my buttons only allow solar specification) I think is limiting and odd per the use case. I know it seems right but It’s quite limiting if the goal is just a general comparison of items. 

And if I use comp on a solar item, then remove all the solar items in that comparison... it’s pretty odd to have a button to bring them all back? So if we have buttons for everything, I think they need to be dynamic based on what is in compare at that moment, filters basically. 

The other side is that this all seems really stop gap a lot of what we are doing as of late is very stop gap, just shoving stuff in to have it. Comp tool has needed an overhaul for a while, why not just take the time and do that now instead of putting in a stop gap solution for affinity?

**Comment by sundevour** [comment]
because presumably these comparison types will be useful even in a redesigned compare tool

**Comment by inexorableAce** [comment]
Sure. No worries, go for it.

**Comment by sundevour** [comment]
this effectively just adds a button, it's not taking the place of any effort to overhaul compare tool, or preventing/slowing a redesign

**Comment by bhollis** [comment]
Feel free to merge this!

**Comment by sundevour** [comment]
tyvm to @delphiactual for feedback and testing, updated to
• be a little less picky, and allow e.g. heavy snipers to be compared to special snipers, because there's nothing else to compare weird-ammo-type exotics to. just avoid allowing heavy GLs to compare to special.
• automatically start with a "most specific group" comparison
• not cross the UI beams if there's no button in the sheet header

**Pull request merged**
