### PR TITLE
Styling touchups to compare tool

### LINKED ISSUE #1247: Displaced label positions in item comparison section
Hi,

the row labels are slightly displaced (one row too far down.)

Browser: Chrome, 54.0.2840.98, Mac 
DIM Version: 3.14.1

bildschirmfoto 2016-12-12 um 10 58 51

### LINKED ISSUE #1284: [Item Comparison] Add light level and burn modifier to comparison window
As the title states, it would be great if light level and burn modifier (where applicable) could be added to the comparison window.

### PR DESCRIPTION
**Pull request by bhollis**
This is a handful of style tweaks to the compare tool. The changes are:

1. Add attack/defense stat.
3. If all the stats of a type are the same, show them in white rather than blue (there's nothing different, so it's not worth focusing on).
4. Show a picture of the item (with its completion border and tag icon).
5. When you click on the title of an item (but sadly not the picture - the click-to-sort-stat interfered) the item will be scrolled into view and a little "pop" animation will play. This really helps find the one item among many you're looking for.
6. Rows are always aligned, no matter if tags are enabled or not.
7. Overall things have been tweaked (a pixel here, a pixel there).
8. Fixed excessive space on the bottom of the talent grid.
1. Replace complicated style expressions with a filter.

screen shot 2017-01-08 at 10 42 46 pm

These items' stats are all the same, so they're white:
screen shot 2017-01-08 at 10 52 34 pm

Pop when clicking the title:
screen shot 2017-01-08 at 10 36 27 pm

Fixes #1284 by adding atk/defense - burn is unnecessary since it's in the talent grid (I added it but then removed it again once I realized that).
Fixes #1247 and #1213.

### CODE REVIEW

**Comment by kyleshay** [comment]
Fantastic work! Love the click animation. That will be so useful!

**Comment by kohum** [comment]
Thanks Kyle. Any chance of showing the burn modifier as well?

**Comment by kohum** [comment]
Oops.  I meant that comment to bhollis

**Comment by wein3967** [comment]
Wow, really nice stuff. I really like that pop idea. Super helpful.

**Comment by bhollis** [comment]
@kohum the elemental damage type is already in the talent grid. First node.

**Pull request merged**
