### PR TITLE
Introduce support for CSS modules

### PR DESCRIPTION
**Pull request by bhollis**
https://css-tricks.com/css-modules-part-1-need/

This introduces the ability to make `.m.scss` files which export class names as TypeScript constants and don't pollute the global CSS scope. This allows us to use shallower class hierarchies and to be clearer about what is and isn't used. I'd like to propose that we start using this for some of the new components, and to clean up some of the more tangled old styles.

I've included a very simple demo of how the usage works.

There is one major downside - the classes look "messy" and may be a bit longer than they were before (e.g. `LockButton-m_inProgress-hQr6M`), though we no longer need to prefix everything ourselves (e.g. `loadout-builder-item`,` loadout-builder-items`, `loadout-builder-lock`). Note that it's `LockButton-m_inProgress` instead of `LockButton-inProgress` because the filename is `Lockbutton.m.scss`.

This also effectively standardizes us on camelCase class names since those will look nicer in TypeScript.

### CODE REVIEW

**Comment by bhollis** [comment]
The other annoyance is that you're meant to check in the `.m.scss.d.ts` files.

**Comment by kyleshay** [comment]
very coool! 

- Do we have any type of "dead-code" linting for defined styles (exports) that aren't being imported anywhere? :o
- Just curious, could the classnames be just a short hash, any reason preserve the file/class names since we have will have source maps?
- `.m.scss.d.ts` 😱 hahaa. Though, why do they need to be checked in if they are auto generated?

**Comment by bhollis** [comment]
> Do we have any type of "dead-code" linting for defined styles (exports) that aren't being imported anywhere? :o

It's theoretically possible to tree-shake the styles that aren't used, because of the scoping rules, and to have tools that highlight unused styles. I don't know if that's happening though.

> Just curious, could the classnames be just a short hash, any reason preserve the file/class names since we have will have source maps?

Mostly just to make them easier to debug. I'll change it to a short hash in beta/prod, and the longer name in dev.

> .m.scss.d.ts 😱 hahaa. Though, why do they need to be checked in if they are auto generated?

Yeah pretty gross, but I needed a way to distinguish modules from our existing scss. They don't really need to be checked in, but it makes the CI builds faster.

**Comment by delphiactual** [comment]
https://www.purgecss.com/#webpack

**Comment by bhollis** [comment]
There's also https://github.com/purifycss/purifycss

**Pull request merged**
