### PR TITLE
Set Double Click Action in settings

### PR DESCRIPTION
**Pull request by phillipspc**
The "double click to equip" feature is nice, but often times I wish I could simply move the item to my character (if I plan to dismantle it for example).

This introduces a new field in settings `dblClickAction` which has two selectable options: "Equip" and "Move", and does what you'd expect.

I don't have a ton of Angular experience, so any feedback is welcome.

### CODE REVIEW

**Comment by cotto** [comment]
I like this feature.  It'll be helpful when dealing with the occasional green item that gets picked up while farming.  It won't affect how double-clicking on blue engrams works but that's my main use case anyway so it's nice to make that non-equipping behavior explicit.

**Comment by bhollis** [comment]
Thanks for making a PR! Personally I'd rather avoid the extra setting, though. If you want to move an item to a character, you can always still drag or use the button in the popup.

**Comment by SunburnedGoose** [comment]
I'd echo @bhollis. DIM is trbding towards fewer settings. The feature of double click is intended for those hurried equips just before a match starts. You have several options to move items that take little effort to complete so I would pass on this PR. 

I'm very thankful for the effort that you put into this. If you have any more ideas or places where you feel friction, I would create an issue first to discuss it with the team before creating a PR. It let's everyone have a chance to offer their opinion before code is written.

**Comment by phillipspc** [comment]
Thanks for the feedback @cotto @bhollis @SunburnedGoose !
I considered making an issue first, but frankly was looking for an excuse to get my hands dirty with DIM 😆  I'll do that in the future.

Feel free to close unless anyone else wants to weigh in.

**Comment by kyleshay** [comment]
Nice work on this! As other have mentioned we are trying to keep the number of settings to a minimum. It seems silly, but without any governance they can add up quite quickly.

Another way that would be nice to solve moving things you wish to dismantle is by using the search/filter box by typing something like `is:green` then on each character you can click the button to move those items to any character in the loadout dropdown. 

Things will get easier once we [support saving those types of searches. ](https://github.com/DestinyItemManager/DIM/issues/397)

Another nice way to solve this would be [multi-select](https://github.com/DestinyItemManager/DIM/issues/318).

**Pull request closed without merging**
