### PR TITLE
RFC: Try highlighting items w/ power mods

### PR DESCRIPTION
**Pull request by bhollis**
This is half-baked, but the idea is to add a border to items that have a mod that affects their power. We could follow up by also explaining this in the move popup. I also added a search for these.

Calculating base power isn't super cheap, but it isn't bad.

screen shot 2017-09-17 at 4 18 03 pm

### CODE REVIEW

**Comment by bhollis** [comment]
@SunburnedGoose @kyleshay what do you think? Is this good enough for now?

**Comment by kyleshay** [comment]
I think that highlighting is good. I just wonder if there ever going to be item mods that are different than +5, and if so then knowing what type of mod on a weapon might be useful.

If so, then I wonder if making the primary stat badge be the base stat + mod, for example: `273+5`

If that isn't the case then this is perfect!

**Comment by lightmaster** [comment]
I like seeing a colored box around +5 modded items, but I'd also like to have the base power shown too. Using your screenshot, if your bad at math and in a hurry, subtracting 5 from 282 to get 277 isn't too easy.

**Comment by bhollis** [comment]
I played around with adding the mod value:

screen shot 2017-09-19 at 12 02 59 am

Doing it like "(270) 275" took two much space and wrapped to two lines.

In the end, I think it's too much. Better to just know that, for now, mods are +5.

**Comment by bhollis** [comment]
For reference, at the smallest item display size (which is what I use):
screen shot 2017-09-19 at 12 05 45 am

**Comment by lightmaster** [comment]
What about an option that enables this, and when enabled, 282 becomes (+5)277

**Comment by bhollis** [comment]
I think it'll be enough to know "gold box is better than white box".

**Comment by bhollis** [comment]
We don't generally like adding options like that.

Note, if you're interested in the exact value for infusion purposes, the Infusion Fuel Finder is taking mods into account.

**Comment by bhollis** [comment]
For completeness sake:

screen shot 2017-09-19 at 12 09 36 am

This one isn't too bad, but the real power level is what matters in the end, and I'd rather show that than have to do math to add them up.

**Comment by lightmaster** [comment]
I see pros in both ways, but seeing how it actually looks I agree on showing the other way (+5)282. Be simpler if Bungie would just use your current power level, but yea.... lol

**Comment by lightmaster** [comment]
What about in the tooltip for the item, include "base power 277" somewhere at the top?

**Comment by kyleshay** [comment]
> I think it'll be enough to know "gold box is better than white box".

lets do that for now and then if they start dropping other mods lets revisit

**Pull request merged**
