### PR TITLE
Minor imports fixes

### PR DESCRIPTION
**Pull request by bhollis**
Some of the imports changes from #9568, specifically changing to individual imports from `React` and removing some duplicate imports.

### CODE REVIEW

**Comment by robojumper** [comment]
I don't think I entirely understand the value in some of these, in fact I do like that it's clearly visible that `lazy` and `memo` are coming from React and aren't just some utility function, but no real objections from me.

**Comment by bhollis** [comment]
I think the idea is that if React were ever to become tree-shakable we could limit our usage to only those functions we make use of.

**Comment by robojumper** [comment]
Sounds good to me. Any reason not to enable a lint for these together with this PR? Or are we still unsure about eslint-plugin-import in general, even with no-cycle turned off?

**Comment by bhollis** [comment]
I figure we can enable the import plugin in that other PR, this just got some of the changes out of the way early.

**Pull request merged**
