### PR TITLE
Manual scroll compare

### LINKED ISSUE #7706: Can't scroll Compare with one finger on iPhone
It's probably time to just listen for touch events and scroll using JS.

### PR DESCRIPTION
**Pull request by bhollis**
Fixes #7706. I couldn't find any way to get real, natural scrolling to work on this, so I just reimplemented scrolling myself with pointer events. It's a bit jankier than the natural scroll, but it's better than not working. I'm leaving it on for desktop too, I think it's kind of nice.

### CODE REVIEW

**Comment by nev-r** [comment]
this does some nutty stuff in firefox, when using the scrollbar, which is the only sane way to scroll sideways on a desktop

https://user-images.githubusercontent.com/68782081/160052445-7de1fea6-1ad1-4f86-9a32-8bb9d5b82adc.mp4

**Comment by nev-r** [comment]
in very related news, vertical scrollbars always have this behavior on desktop. if you use mouse on a sheet's scrollbar to, say, scroll down, the sheet thinks you're also trying to close it. it would be nice to disable drag controls in general on desktop sheets, but someone's tablet pc is guaranteed not sending touch events and this will ruin their day.

**Comment by bhollis** [comment]
I also almost exclusively drag to close sheets on desktop.

**Comment by nev-r** [comment]
you're a madman

**Comment by bhollis** [comment]
The scrollbar behavior you're describing is definitely a Firefox thing. It makes no sense that dragging a system-provided scrollbar would bubble its touch event down to the page.

**Review by nev-r — APPROVED** [review]
that's a marked improvement over the vertical scrolling problem in beta/prod right now, thank you

it also seems to enable mouse-based dragging in windows, where only touchscreen would do it before

weird unrelated thing i noticed that's not different in this PR just odd in master branch,.
in firefox, "mouseup" alone counts as a "click", for the purposes of, for instance, opening the socket selection sheet. so dragging the compare sheet back and forth can unintentionally spawn a "deeper" sheet

**Comment by bhollis** [comment]
Try as I might, I couldn't convince Firefox to not fire a click on `pointerup`. I have in mind an insane scheme involving dynamically setting `pointerevents` but it's gonna have to wait for a different PR.

**Pull request merged**
