### PR TITLE
Switch to ts-loader

### PR DESCRIPTION
**Pull request by bhollis**
We used to use awesome-typescript-loader, but that doesn't appear to be maintained anymore. ts-loader is a little faster and has active development (including pending support for TypeScript's new incremental build cache).

### CODE REVIEW

**Comment by bhollis** [comment]
Hmm, there's an issue here related to `const enum`.

**Comment by delphiactual** [comment]
https://github.com/TypeStrong/ts-loader/issues/331

**Comment by bhollis** [comment]
The reality is we really have to ditch `const enum` - it doesn't work with a lot of newer TS tooling.

**Comment by bhollis** [comment]
Well, I got it to work, but it's not any faster than awesome-typescript-loader since I wasn't able to use `transpileOnly`. I also tried a babel-based build but that doesn't support const enums either.

I'm tempted to merge this anyway, since ts-loader will have better ongoing support.

**Pull request merged**
