### PR TITLE
Switch to flexbox layout on a per-bucket basis

### PR DESCRIPTION
**Pull request by bhollis**
This includes all the changes from #595.

@SunburnedGoose will recognize the basic pattern here, though it's all done up from scratch again. This uses the bucket definitions to restructure our DOM into rows instead of columns, which then allows me to use flexbox to lay out basically everything. In the process we drop a ton of code and CSS. There's a lot more in here, such as keeping track of items by buckets in the store (no need to filter through for a specific bucket anymore) and keeping track of vault full-ness as we add and remove items. Lots and lots changed.

User-facing, what you'll see is: 
* Items in the postmaster now have quality ratings, can use the infusion fuel finder, show up in the infusion fuel finder, compare against currently equipped items, etc. They behave just like a normal item except you can't move them and they're in a different spot.
* The vault width preference has been removed - the vault now always takes up all the remaining space on the screen.
* Section headers don't repeat themselves anymore.
* Returning from the min-max tool no longer greets you with a blank, item-less screen.

I had to do a bunch of hacking around to the minmax tool in order to get things working again (and for my own sanity). I also pulled all the inline styles into their own SCSS file.

As I mentioned in the other PR, this is a major, major change, and things are guaranteed to be broken. Lots of testing needed on this one.

### CODE REVIEW

**Comment by bhollis** [comment]
Aside from the section headers (which now always go full width, and do not say ARMOR ARMOR ARMOR ARMOR anymore), everything looks exactly the same. It's faster though.

**Comment by Mulchman** [comment]
Pretty cool! I have a couple minor things I noticed-

* Character order -> when selecting 'fixed' a full extension refresh is required [as It doesn't update dynamically like regular DIM].
* There's extra padding on the far right vs. regular DIM (DIM-regular on top, DIM-flexbox on bottom): http://imgur.com/a/qP87v

**Comment by kyleshay** [comment]
@Mulchman it depends on your window width -- 

demo3

**Comment by ericnelson0** [comment]
There are a ton of great changes in this PR. Nice work!

Sorry about some of the mess in the min/max tool and thanks for cleaning some of it up. 

One bug I ran into was when i tried to transfer an item to a character that was full of that particular item type (e.g. chest armor). When I tried to do this all of the chest armor that was on the character was moved to the vault instead of just one piece to make room. 

I'll try to pin down the exact details to reproduce.

**Comment by bhollis** [comment]
@Mulchman I've fixed your unrelated character-order bug in 077b20370a61777bb0af457be91b4f8dc3959cd7. As Kyle pointed out, the "padding" is just a result of non-even division of the width by the item width - it's just going to happen that way.

@ericnelson0 I bet I can repro that, and I bet I know how to fix it. Let me look.

**Comment by bhollis** [comment]
@ericnelson0 fixed. Pull and keep testing! This is great!

**Comment by ericnelson0** [comment]
@bhollis Thanks and will do.

**Comment by ericnelson0** [comment]
In the minmax tool we need to add two styles:

Add
```
margin-left:10px;
```
to <code>.minmax .item-container</code>

and add:
```
flex-wrap: wrap;
```
to <code>.minmax .itemQuality</code>

This will fix an issue where too many items will cause the stats to not be aligned to the left of the items: 

Before:
image

After:
image

**Comment by bhollis** [comment]
Thanks, got it. I don't have that much armor ;-)

**Comment by kyleshay** [comment]
Can't seem to drag & drop subclasses

**Comment by bhollis** [comment]
Ah, interesting - they're not transferable!

**Comment by bhollis** [comment]
Fixed

**Comment by kyleshay** [comment]
very minor thing -- the highlighted drop area for equipped items has the same height as unequipped section. (see red lines)

a possible fix might just be to add `align-items: flex-start;` to the `.sub-section` class. 

screen shot 2016-06-15 at 1 39 07 pm 2

still keeping an eye out, but i'm only finding these incredibly minor things... which is an awesome sign :) 👍

**Comment by kyleshay** [comment]
another minor thing is that searching with the 'hide unfiltered items when searching' doesn't look so hot.

i'm fine with it for now. that feature needs some work anyway, in my opinion. i'd like to see that option collapse as much as possible for sections that nothing is found. in theory-- that should be easier now that we're constructing this view a bit differently.

screen shot 2016-06-15 at 1 49 49 pm

**Comment by ericnelson0** [comment]
This is pretty small and I'm not sure that we can/want to do anything about it, but if the windows width is small then the headers for each character and the vault doesn't line up with the columns of items.

image

**Comment by bhollis** [comment]
@kyleshay I had the equipped item drop zones fixed to look exactly the same, but then I realized that I like them taller - it makes it much easier to drop items to equip them. What do you think?

@ericnelson0 I'll fix that by setting some minimum widths.

**Comment by bhollis** [comment]
OK, I've fixed both styling issues, and then some:

1. You can't smash the headers up anymore, nor make the vault narrower than its header.
2. Drop zones are always the full height of the row, and the full width of their cell, even if they're not filled all the way. Easy dropping everywhere!
3. `ScrollToFixed.js` has been removed in favor of much simpler styling for the fixed header. Maybe I'm imagining things, but it seems like the scroll perf is better now.

**Comment by bhollis** [comment]
And now, when you select "hide unfiltered items", the layout stays pretty and clean.

**Comment by kyleshay** [comment]
woah! the sticky header looks and feels amazing, nice!! 

> Drop zones are always the full height of the row, and the full width of their cell, even if they're not filled all the way. Easy dropping everywhere!

👍  looks and works great!

great additions @bhollis, thank you!

**Comment by ericnelson0** [comment]
With the new minimum widths should the headers horizontally scroll with the columns?

example_issue

**Comment by bhollis** [comment]
They probably not should, though the fixed position in makes that tough! I
can do it though.

**Comment by bhollis** [comment]
OK, now the header scrolls horizontally. I also made the DIM toolbar full-width - it looked weird centered.

**Comment by delphiactual** [comment]
@bhollis With the new flexbox layout if the vault bucket is empty it will not collapse during searches with 'Hide unfiltered items when searching'

flexboxsearch

**Comment by kyleshay** [comment]
@delphiactual that's new functionality that we're tracking in #613, even today the headers don't collapse.

**Comment by bhollis** [comment]
OK, I've merged `dev` into this branch so we can merge and test in Beta. The only casualty was the minmax stuff, which is sadly too byzantine for me to merge effectively. At @kyleshay's request, I've just kept my fixed version, and he can port over the changes that have appeared in the interim.

**Comment by bhollis** [comment]
Merged. Commence heavy testing!

**Pull request merged**
