### PR TITLE
Redesign stats

### PR DESCRIPTION
**Pull request by bhollis**
Screen Shot 2019-09-14 at 5 04 58 PM
Screen Shot 2019-09-14 at 5 05 05 PM

This redesigns the stats display to use a separate bar for comparisons, instead of incrementally adding red/green to the existing bar. IMO it makes it clearer what your actual stats look like. The downside is I don't know how clear the red/green is now - you'll get longer bars colored red because your stat is worse than that one. It lines up with the numbers' coloring but it's a bit weird.

I also added comparison to recoil direction, including understanding that higher isn't just better for recoil - closer to the center is.

And I added icons for armor stats, since they're represented with icons in game.

### CODE REVIEW

**Comment by kyleshay** [comment]
The armor stat icons are a great idea! Another place to show them so that they make more sense on the loadout optimizer page.

I wonder how useful the compare option is in the item details? It is likely misleading or unhelpful to compare to your equipped item in DIM... many times it's a different weapon type anyway. Wonder if we could actually remove it? It was originally added to match in-game, but I don't think I've personally really used that feature in DIM. We have the compare tool which is much better for comparing?

**Comment by sundevour** [comment]
+1 for dumping comparisons.
even getting them to display requires equipping which is a weird thing to force someone to do just to look at numbers.

**Comment by phillipspc** [comment]
Just to throw out another idea on this (since its tangentially related to #4193), I also think that the value added by the comparison bars may not justify them being shown by default. But if we re-worked it as a toggle, that would more closely mirror the in-game experience, and might help to simplify some things. (for example, when comparing, just show the comparison bars rather than trying to combine them with masterworks, mods, etc.)

**Comment by bhollis** [comment]
Overall we're not super into toggles and settings - they're hard to manage.

**Comment by bhollis** [comment]
Overall I'd be overjoyed to get rid of the comparisons. Frees us up to do more interesting things.

**Comment by phillipspc** [comment]
@bhollis maybe "toggle" wasnt the best descriptor... not talking about an additional setting, moreso like a button on the item view that would bring up the comparison bars temporarily (similar to how you toggle this on an item in game). But yeah, just a thought. I'm fine with whatever direction you guys choose.

**Comment by sundevour** [comment]
item comparison isn't even good **in game**, it's poor UI.
it's not great visual representation of A vs B
(@bhollis's is better, though i'd want green&red swapped)
and it allows comparison between weapon types, which is useless & misleading

slightly aside,
i think comparison popup should be made easier to casually use to compare intended things,
to replace this style of comparison

compare button should pop up a sheet with only that gun,
so you can click another to immediately compare.
comparison buttons should a little more explanatory,
and better for specifying "what does this compete with"
image

**Comment by kyleshay** [comment]
went with #4234

**Pull request closed without merging**
