### PR TITLE
Disable collapsing on non-postmaster inventory sections

### PR DESCRIPTION
**Pull request by bhollis**
This removes the ability to collapse inventory sections, except for Postmaster. In doing so I bifurcated the two components, which makes them a bit easier to manage, especially with all the Postmaster-specific stuff. My reasoning is that most people don't care to hide any sections except for the postmaster, and it causes a lot of confusion still.

Screen Shot 2022-10-15 at 5 56 06 PM

### CODE REVIEW

**Review by nev-r — APPROVED** [review]
i care to, but :shrug:

**Review by robojumper — APPROVED** [review]
I don't mind this being removed because/but I never used it.

**Comment by nev-r** [comment]
i really find it a bit of a bummer. i use this for perf reasons because dim is heavy and slow to scroll, because the new image loader makes scrolling jerkier, because General section is absolutely useless and is somehow taller than my 400+ weapons, because sometimes i need to work while looking at postmaster and armor, ...

**Comment by bhollis** [comment]
Collapsing sections so you could only work on the ones you cared about was definitely the original intention of the feature, but it seems to be just inescapably baffling for some percentage of users.

BTW please file issues for the perf stuff - I haven't noticed anything like that and the new image loaders exist specifically to work around serious performance issues in some browsers.

**Pull request closed without merging**
