### PR TITLE
Hint that items can be drag/dropped versus move dialog

### PR DESCRIPTION
**Pull request by kyleshay**
It seems some users are still unaware that items can be moved via drag and drop versus the move dialog. This PR adds a simple toaster that hints the other functionality. There is a function to 'not show the tip again'.

Functions just as the version bump toaster does.

demo2

If we don't think this is necessary we can kill this PR.

### CODE REVIEW

**Comment by kyleshay** [comment]
@SunburnedGoose we can now use the `dimInfoService` to show the release popups.

interface is (in this example):

```
      dimInfoService.show('movebox', {
        title: 'Did you know?',
        body: ['<p>Items can be dragged and dropped between different characters/vault columns.</p>',
               '<p>Try it out next time!<p>'].join(''),
        hide: 'Don\'t show this tip again'
      });
```

**Comment by SunburnedGoose** [comment]
Thanks.  That's been a todo for a while.

**Comment by kyleshay** [comment]
just went ahead and made it support loading from the view out of the box as well

```
        dimInfoService.show('20160411v35', {
          title: 'DIM v3.5.4 Released',
          view: 'views/changelog-toaster.html?v=v3.5.4',
        });
```

**Comment by bhollis** [comment]
This is great! I'm merging.

**Pull request merged**
