### PR TITLE
Cleanup input/search boxes

### PR DESCRIPTION
**Pull request by bhollis**
A bunch of random changes here, to clean up the look of our text inputs (of which we have very few!). @guise I also made the mobile search box look like the desktop one, as you'd suggested. I'm a touch worried that it's even more crowded, but the correct solution there is probably to move some of the buttons out and auto-grow the search field itself.

I also made it so the loadout popup search field clears on Esc, and then closes the dialog on a second Esc.

Before (focused):
Screenshot 2023-09-01 at 3 16 17 PM
Screenshot 2023-09-01 at 3 16 21 PM

After (focused):
Screenshot 2023-09-01 at 3 16 07 PM
Screenshot 2023-09-01 at 3 16 28 PM

Before:
Screenshot 2023-09-01 at 3 16 37 PM

After:
Screenshot 2023-09-01 at 3 16 33 PM

Before:
Screenshot 2023-09-01 at 3 17 08 PM

After:
Screenshot 2023-09-01 at 3 17 01 PM

Before:
Screenshot 2023-09-01 at 3 17 41 PM
Screenshot 2023-09-01 at 3 17 48 PM

After:
Screenshot 2023-09-01 at 3 17 27 PM
Screenshot 2023-09-01 at 3 17 33 PM

### CODE REVIEW

**Comment by guise** [comment]
I've proposed some fixes on PR #9840

- Tidy up the search box styles to work better on themes with non-black mobile headers
- Better colour-match the search dropdown border (if set) 

Search box padding before/after:
image image

Search dropdown border before/after:
image image

**Comment by guise** [comment]
> I'm a touch worried that it's even more crowded, but the correct solution there is probably to move some of the buttons out and auto-grow the search field itself.

An alternative could be to display the search ontop-of or even replace the header/header elements. When you're searching for something, that stuff is superfluous and it frees up a lot of vertical space for results. 

We could also get hide the disclosure control for the dropdown so that results are always shown. 

dim-search-fixed

**Comment by bhollis** [comment]
I like playing with the idea of showing the search bar over the header, but that makes it even more crowded. I could also see hiding the disclosure arrow, as long as we think mobile users would realize you can tap the input to open/close the suggestions.

**Comment by bhollis** [comment]
Gonna merge this, given there were no more comments on it

**Pull request merged**
