### PR TITLE
use babel-plugin-transform-imports to deepLink icons from font awesome

### PR DESCRIPTION
**Pull request by delphiactual**
https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking

### CODE REVIEW

**Comment by delphiactual** [comment]
Before: fortawesome - 1.34MB https://app.packtracker.io/organizations/159/projects/136/commits/17e8cc17e72b3645e0f4bb699469b4519ae21e7f/explore

After: fortawesome - 162kB
https://app.packtracker.io/organizations/159/projects/136/commits/93461a0716ecde9f71f24b82880d696071aeebe1/explore

**Comment by bhollis** [comment]
Fantastic!

One option to make this less manual would be to leverage https://www.npmjs.com/package/babel-plugin-transform-imports - would that work?

**Comment by delphiactual** [comment]
yes I believe it will

**Comment by delphiactual** [comment]
and it does

we can possible use a regex instead of 3 matching patterns, but I could not get it to work
https://www.npmjs.com/package/babel-plugin-transform-imports#using-regular-expressions

**Pull request merged**
