### PR TITLE
When comparing dupes with statlower, be slightly more exclusive when assigning armor groups

### PR DESCRIPTION
**Pull request by Makeshift**
I suspect this change might be subjective, but I noticed that `statlower` was comparing the stats of armor that has intrinsics vs non-intrinsics.
I made the armor grouping a bit more exclusive, based a bit on how https://github.com/DestinyItemManager/DIM/blob/cdca9b6a64e87b072f472675c5d82efe0579dcd9/src/app/item-triage/triage-utils.tsx does it.

### CODE REVIEW

**Comment by robojumper** [comment]
Can't say I'm a huge fan of changing the default behavior like this because I don't really care about raid mod slots, so it'd make the filter less useful for me. Maybe we could add a separate `statlower:withmodslots` filter syntax that uses more restrictive grouping? @nev-r thoughts?

**Comment by nev-r** [comment]
triage specifically *distinguishes* between "worse stats" and "just worse" and yeah statlower should continue to do exactly what it says it will. add an is:worse filter if you want, always meant to

**Comment by nev-r** [comment]
i have always avoided claiming statlower is good as a sole criterion for deletion, and been very very careful and specific about verbiage in triage regarding it

**Comment by Makeshift** [comment]
Fair notes! 

I think adding an `is:worse` would encounter a similar issue in that it would encourage immediate deletion instead of using the better-equipped triage tooling as intended. I agree that changing existing behaviour isn't the best idea, and I kind of like `statlower:withmodslots`. I'll have a look around to see how the existing "search term + args" are implemented and see if I can propose something a bit more refined.

**Pull request closed without merging**
