### PR TITLE
Remove stackable info from headers

### PR DESCRIPTION
**Pull request by bhollis**
This removes the "Quantity: 20 (MAX)." text from item headers and puts all the info in the badge. Previously it would just show "MAX" once you maxed a stack. This is part of cleaning out the item headers.

Screen Shot 2019-09-02 at 7 43 39 PM

### CODE REVIEW

**Comment by sundevour** [comment]
not currently an issue but _minor_ forewarning that `9999 MAX` is an awkward fit at minimum icon size, and recent solstice event established 4 digit stacking. only an issue at min size and only if a permanent resource in a coming season allows this.

**Comment by duckmanBR** [comment]
As of Update 2.5.2.2 all Planetary and Gunsmith Materials and PvP Tokens have a stack limit of 9999 (https://www.bungie.net/en/News/Article/48119)

**Comment by sundevour** [comment]
pffffft that came true quickly

**Comment by bhollis** [comment]
Wow yeah. Let me see what I can do.

**Comment by bhollis** [comment]
OK how about removing MAX altogether. People will have a little puzzle to figure out why their maxed out stacks are orange and bold.

**Pull request merged**
