### PR TITLE
Detach character stats from the static header

### PR DESCRIPTION
**Pull request by bhollis**
This takes the character stats (max light and eventually 6 character stats) and moves them to the inventory section instead of being part of the static store header. I think this feels great and gives more room for items. The only weird part is on mobile, scrolling the header leaves behind the stats.

scroll-header-mobile
scroll-header

### CODE REVIEW

**Comment by bhollis** [comment]
Draw it up?

**Comment by inexorableAce** [comment]
quick mock-up to show what I mean. sizing and stuff is likely off here old mock-up and text sizes. basically just giving it it's own section in the inventory. 
image

**Comment by bhollis** [comment]
Makes sense!

**Comment by sundevour** [comment]
...... arguably this doubles the vertical space used up by stats, for the (i assume many) people who want to leave them visible.

this feels like a small blow to desktop, to serve a medium space savings to mobile

**Comment by inexorableAce** [comment]
It doesn’t save space on either. It’s not meant to.

**Comment by duckmanBR** [comment]
Also, any chance on looking at #4332?

**Comment by kyleshay** [comment]
I do like it! More screen real estate for items is nice.


Maybe the "character stats" section could be just "character" and we could include the subclass in it?

**Comment by bhollis** [comment]
@duckmanBR that's unrelated and I'm not sure what's going on there.

**Comment by bhollis** [comment]
OK, here are some updates. I tried left-justifying these on mobile, and it looked pretty bad. So instead I tried centering and it feels much better. Plus, I moved currencies down into there (no, I don't know why the API only sometimes returns Silver).

I think this is enough of a win to ship as is. Thoughts?

Screen Shot 2019-10-22 at 10 55 20 PM
Screen Shot 2019-10-22 at 10 55 30 PM

**Comment by bhollis** [comment]
Also, alternate left-justified instead of full-justified currencies?

image

**Comment by kyleshay** [comment]
Looks great! May possibly need to re adjust when the other 3 stats are added. 

Forgot that postmaster is in-between stats and sub class so combing them actually may not make sense.

**Comment by bhollis** [comment]
Even more alternate griddy version???
image

**Comment by bhollis** [comment]
Left-aligned grid?
image

**Comment by inexorableAce** [comment]
That one “left aligned grid”

**Comment by delphiactual** [comment]
font size is inconsistent between characters and vault

**Comment by bhollis** [comment]
Yeah, it definitely seems like it should be attached but you get used to it pretty fast. I still like this better than any alternative I’ve attempted.

**Comment by bhollis** [comment]
OK, I've formatted this nicely and built a workaround for the missing stats. I'm going to merge this and we can tweak further later.

**Pull request merged**
