### PR TITLE
RFC: Sketch up tiles for item picker

### PR DESCRIPTION
**Pull request by bhollis**
I'm kind of torn over whether I'd want to make this an option, or just make it the default. Obviously the item density is way down, but the amount of info might make up for it. Thoughts?

Screen Shot 2022-03-26 at 6 36 43 PM
Screen Shot 2022-03-26 at 6 37 05 PM

### CODE REVIEW

**Comment by bhollis** [comment]
Screen Shot 2022-03-26 at 6 41 08 PM

**Comment by nev-r** [comment]
seems like an opportunity for https://github.com/DestinyItemManager/DIM/pull/7673

**Comment by bhollis** [comment]
I still don't terribly like info that's stuck behind hovers

**Comment by nev-r** [comment]
armor view is unlovably busy but that's just one opinion

**Comment by bhollis** [comment]
Yeah agree, it's pretty hideous. Works on the item feed where there's only a single column.

**Comment by kyleshay** [comment]
Weapon sheet looks great on mobile/item feed!

Maybe on desktop it the cells could be twice as wide, there is so much space to work with so the lower density may be ok?

- Maybe a toggle at top of sheet to show/hide labels vs a preference in settings? 
- Worth showing the icon for frame type (aggressive/lightweight/etc?) guessing not since no one memorizes that?

Also (though mostly unrelated) is the item sort on sheets the same as inventory?

**Pull request closed without merging**
