### PR TITLE
Loadout share UI

### LINKED ISSUE #7375: Loadout Share UI
### Proposed change

Right now we simply copy a URL when sharing a loadout. I'd prefer to have a dialog that pops up with a few options:

1. A live URL that you can manually copy/paste (ideally short https://github.com/DestinyItemManager/dim-api/issues/65)
2. Checkboxes that let you include or exclude portions of the loadout - for example you could choose to just include the shaders/ornaments, or just the mods.
3. An area for adding freeform notes.

### How does this fit into your workflow?

Sharing is really nascent now but I'd like to see more people adopt it, and easier and more clear sharing is a big part of that.

### LINKED ISSUE #8186: Copy/paste broken on iOS
I'm not sure what changed

### PR DESCRIPTION
**Pull request by bhollis**
Screen Shot 2022-03-20 at 8 49 59 PM

This adds a loadout share UI to replace just copying a URL. I've updated the Loadouts page but not the LO yet.

The new share UI shows up as a sheet and has a text field for copying the loadout URL. It also has a button that will actually work to copy to clipboard, and that button automatically upgrades to a system share button on systems that support it.

There's a little summary of the loadout contents - would love some copy help there.

Fixes #8186 
Fixes #7375

### CODE REVIEW

**Comment by nev-r** [comment]
"recipients will be prompted to select comparable items from their inventory" ?

"recipients will be prompted to select items from their inventory which match these optimizer settings" ?

"recipients will be prompted to select items from their inventory which match these optimizer settings and fit these mods" ?

is this true of weapons? are weapons shared  at all right now? i'd rather specifically call out "armor" than "items"

**Comment by bhollis** [comment]
Yup, weapons are shared with loadouts now. Try it out!

**Review by ryan-rushton — APPROVED** [review]

**Comment by nev-r** [comment]
feels weird that this creates the dim.gg page, irreversibly, before warning/explaining what the loadout would include.
this interface seems intended to dispel misunderstandings about how share works, but then shares before explaining.

i would rather this button image send the xhr, complete the clipboard copy, and populate/appear the text field.

also i can't test this currently because my dim api dev key is constantly becomeing invalidated or just lost or something. does it freeze the hostname for dev keys? this is a problem when my power goes out and dhcp randomizes my house.

**Comment by bhollis** [comment]
I think creating the share URL (uploading the loadout) is low cost if you don't choose to share it. We'll GC them eventually if they have no views. If we don't do that, it'll have to be a workflow where you hit "Share", which opens this sheet, then you hit "Get URL", which populates the field, then you can share/copy the URL.

**Comment by bhollis** [comment]
I'm likely to merge this soon, since sharing loadouts is totally unusable on Safari right now.

**Pull request merged**
