### PR TITLE
handle classified milestoneDef

### PR DESCRIPTION
**Pull request by delphiactual**
https://sentry.io/destiny-item-manager/dim/issues/466920762/
@duckmanBR

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
These null checks catch us often.

**Comment by bhollis** [comment]
They'll keep getting us, even in the TypeScript world. This is because the OpenAPI docs from Bungie don't do a good job of telling us when things can be null. I could generate assuming ALL properties could be null, at which point writing code would be a huge headache, so I generated assuming only things Bungie declares nullable can be null... which is often wrong.

**Comment by duckmanBR** [comment]
what do I have to do with this?!?

**Comment by SunburnedGoose** [comment]
Don't we have the nullish coalescing operator coming in the next ES release?  Babel lets us use it now.

https://github.com/tc39/proposal-nullish-coalescing

**Comment by bhollis** [comment]
We could, though TypeScript runs before Babel, so we’re limited to syntax TS understands.

**Pull request merged**
