### PR TITLE
Expand exotic armor perk

### PR DESCRIPTION
**Pull request by bhollis**
Screen Shot 2021-04-08 at 7 14 31 PM

This gives Exotic armor's perks the same treatment as exotic weapons' archetype does, with the added bonus of showing the full description. Took some refactoring of the sockets display.

### CODE REVIEW

**Review by inexorableAce — APPROVED** [review]
👌

**Review by nev-r — APPROVED** [review]
looks nice. fair warning for future questions, it doesnt work with aeon exotics. they are weird

**Comment by bhollis** [comment]
That's right, aeons use a special exotic mod slot which is at least clever.

**Comment by delphiactual** [comment]
https://data.destinysets.com/i/InventoryItem:1654461647/PlugSet:732

**Comment by bhollis** [comment]
I'll maybe deal with Aeons later, since it'd be a pretty different path.

**Pull request merged**
