### PR TITLE
Collections

### PR DESCRIPTION
**Pull request by bhollis**
Super in-progress branch working on adding Collections (and Triumphs, in the same code) to the app.

screen shot 2018-10-08 at 6 39 21 pm

@inexorableAce if you wanna pick at it let me know. The next thing I was gonna do was to get the unlock counts correct at every level of the tree.

### CODE REVIEW

**Comment by bhollis** [comment]
https://codepen.io/inexorableAce/full/oPRVJg/

**Comment by bhollis** [comment]
screen shot 2018-10-20 at 12 05 07 am

OK, this is at the point where I wouldn't mind pushing it and iterating in further PRs. It has:

1. Heirarchical drilldown of collections.
2. Collection items can be searched, and their popups explain whether they're unlocked and/or in your inventory.

We don't really have:
1. Ratings. They will show if they're already loaded, but there's no function for loading in missing ratings on demand.
2. Badges. We could show them, but I don't.

@inexorableAce I tried to make things fit with your design, but the kind of hierarchical drill-down approach I took didn't really work with it. That said, I could definitely get it going that way, it'd just be kinda odd since the top level wouldn't actually contain its children. I'd love it if you wanted to take a crack at what's there though.

**Comment by inexorableAce** [comment]
Sounds good, I’m still working through my react learnings. I’ll definitely take a look once I get a bit more aquainted. 👍

**Comment by bhollis** [comment]
Let's play with it! Send issues and PRs for feedback.

**Pull request merged**
