### PR TITLE
fixing infusion dlg

### PR DESCRIPTION
**Pull request by cdacamar**
There might be more of these but this one was bugging me.

Perhaps this check _should_ go in a helper somewhere.

### CODE REVIEW

**Comment by kyleshay** [comment]
> Perhaps this check should go in a helper somewhere.

if([angular.isDefined(ga)](https://github.com/angular/angular.js/blob/master/src/Angular.js#L506)) {
}

**Comment by SunburnedGoose** [comment]
In this case, it just needs to be commented out.  I missed it when I was reverting our google analytics update.  I believe that gaq generates a ga object.

**Comment by cdacamar** [comment]
`angular.isDefined()` expects a property.  In our case we're trying to access a variable in some scope somewhere (in this case the window).  You will still get a reference error trying to use the angular function unless we do something like `angular.isDefined(window.ga)` and assume window was brought in with the root scope.

Thoughts?

**Comment by SunburnedGoose** [comment]
You're right.  It would error at the time of accessing it.

**Comment by cdacamar** [comment]
Either way, just going with @SunburnedGoose solution for now.

**Comment by kyleshay** [comment]
fixed in: https://github.com/DestinyItemManager/DIM/commit/5c35fe8c03709e9ca70c868c14ce88c9e9fc73b6

**Pull request closed without merging**
