### PR TITLE
New rich texts

### PR DESCRIPTION
**Pull request by delphiactual**
image

Awaiting https://github.com/justrealmilk/destiny-icons/pull/23 for stasis

### CODE REVIEW

**Comment by delphiactual** [comment]
```
ERROR in /home/runner/work/DIM/DIM/src/app/item-popup/ItemDetails.tsx
./src/app/item-popup/ItemDetails.tsx
[tsl] ERROR in /home/runner/work/DIM/DIM/src/app/item-popup/ItemDetails.tsx(77,36)
      TS2322: Type '{ item: DimItem; defs: D1ManifestDefinitions | D2ManifestDefinitions; }' is not assignable to type 'IntrinsicAttributes & Pick<Props, "item">'.
  Property 'defs' does not exist on type 'IntrinsicAttributes & Pick<Props, "item">'.
 @ ./src/app/item-popup/ItemPopupBody.tsx 7:0-40 31:33-44
 @ ./src/app/item-popup/ItemPopupContainer.tsx 20:0-44 121:33-46
 @ ./src/app/shell/Destiny.tsx 19:0-66 80:30-48
 @ ./src/app/App.tsx 23:0-38 185:28-35
 @ ./src/app/Root.tsx 10:0-24 13:29-32
 @ ./src/Index.tsx 17:0-30 45:29-33
```

**Comment by bhollis** [comment]
You might need to change something to `Pick<Props, "item" | "defs">`

**Review by bhollis — APPROVED** [review]

**Comment by delphiactual** [comment]
now i just need to figure out why i cannot update `destiny-icons`

**Comment by delphiactual** [comment]
image

**Pull request merged**
