### PR TITLE
Translate Progress

### PR DESCRIPTION
**Pull request by delphiactual**
Sourced from bungie.net

### CODE REVIEW

**Comment by delphiactual** [comment]
@bhollis I noticed that Vanguard is not being translated on the Vendors page... I don't know what needs to be changed to fix that.

**Comment by delphiactual** [comment]
Tooltips for reputation are not internationalized...

screenshot 2016-08-14 01 01 14

**Comment by Kev63** [comment]
Hi! I'm Twitter @KevPSG63, I can help you out for French translations ;-).

**Comment by TheVanguardReal** [comment]
Hello, my name is Edson and i'm here to help with the Brazilian Portuguese translation. 
Twitter: @thevanguardreal
Facebook: thevangardreal

**Comment by TheVanguardReal** [comment]
Which are the archives for translation?

**Comment by delphiactual** [comment]
@Kev63 , @TheVanguardReal 

https://github.com/delphiactual/DIM/blob/manifest-service/app/scripts/dimApp.i18n.js

**Comment by bhollis** [comment]
Wow, great work, folks!

@delphiactual, I'll submit a PR to make some of those things translateable - it should make it clear how to make those changes yourself, too.

**Comment by bhollis** [comment]
See #850 for more info on how to do translations for previously hardcoded strings.

**Comment by delphiactual** [comment]
@bhollis, If I convert all the translations into JSON files per language would you be able to make a PR to load them from said JSON files...

**Comment by bhollis** [comment]
I could, but what would be gained from doing that?

**Comment by delphiactual** [comment]
@bhollis Reasoning being once we start translating huge blobs like:


"How does DIM get access to my Destiny data?
Any chrome extension can ask for the data a website stores on your computer. When you log into Bungie.net, you are given a token (a cookie) that is generated uniquely for your account. You use this token to communicate with Bungie securely. The token is more secure than sending your username and password with each request to Bungie's server. DIM uses this token to communicate with Bungie on your behalf."

The strings will start to get really long, and I just think separating them out into english.json, german.json, spanish.json, portuguese-br.json, and japanese.json be beneficial for readability.

**Comment by bhollis** [comment]
@delphiactual I'd rather not translate those as strings - instead, we should probably do those as separate HTML templates that we conditionally include.

I like having everything in one JS (not JSON) file for a couple reasons:

1. It's all in one place, so it's easier to see what's missing, etc.
2. JS doesn't have to quote keys, can have comments, etc.

**Comment by bhollis** [comment]
Would you mind merging from `origin/manifest-service`?

**Comment by delphiactual** [comment]
Closing in lieu of https://github.com/DestinyItemManager/DIM/pull/863

**Pull request closed without merging**
