### PR TITLE
Item Feed

### PR DESCRIPTION
**Pull request by bhollis**
This introduces a new, collapsible sidebar on the desktop inventory page that shows items in acquisition order, by default showing only untagged items. It's meant to help you keep on top of the stream of new gear by easily tagging them.

Screen Shot 2021-11-27 at 2 05 25 PM

### CODE REVIEW

**Comment by bhollis** [comment]
I'm not yet sure about the perks display - it might be worth making the icons smaller but spelling out the name. My intuition remains that the last 2 perks are the "deciders".

What armor looks like:
Screen Shot 2021-11-27 at 2 13 14 PM

**Comment by delphiactual** [comment]
Recommend giving the tab some kind of `glow` until the user clicks it for the very first time... I had a hard time finding it when github.com was down with no screenshots to help.

**Comment by delphiactual** [comment]
doesn't really collapse, when collapsed scrollbars appear. scrolling shows blank `item-feed`
image

**Comment by delphiactual** [comment]
compare shenanigans with item-feed
uncollapsed: (double vertical scrollbars / compare attached at bottom)
image
collapsed: (double horizontal scrollbars / compare detached at bottom)
image

**Comment by bhollis** [comment]
OK I gave up on the animation, which should make it behave a bit more normal.

**Review by nev-r — APPROVED** [review]
works well! a few feedbacks:

the (in my OS) double white scrollbars are ugly and distracting. 
image
could the inner one maybe be set to dark mode and thin/low profile?

this assumes a workflow of "everything tagged" which is going to net a lot of complaints from people whose brains work different. people will definitely ask how to "clear the queue". i think there should be the option to set an instanceId high water mark, to use as the bottom end of the infinite scroll.

prepare for a bunch of (imo, reasonable) requests to be able to put this on the left side instead. it works great as a dual screen game companion, and that means it's important that it be near the game. (if it's on the left side, could we get a secondary refresh button in there? yes i know overall the answer is autorefresh.)

**Comment by bhollis** [comment]
> the (in my OS) double white scrollbars are ugly and distracting

Yikes. I wish I could emulate that on my system, I always forget about it. I'll try styling them to be less awful.

> i think there should be the option to set an instanceId high water mark, to use as the bottom end of the infinite scroll.

Yeah I agree, though I might not do it in this first pass

> put this on the left side instead

I like that, but I'm struggling with where I'd put the button to expand it then. One of the things I really disliked about the "Active Mode" was the toggle sitting in the middle of nowhere that opened and closed the sidebar.

**Review by ryan-rushton — APPROVED** [review]
LGTM, only comment I have really is that it would be nice if there was a slide animation when you opened the side tray, not a deal breaker though.

**Comment by delphiactual** [comment]
> LGTM, only comment I have really is that it would be nice if there was a slide animation when you opened the side tray, not a deal breaker though.

https://github.com/DestinyItemManager/DIM/pull/7331#issuecomment-981201320

**Review by delphiactual — APPROVED** [review]

**Comment by bnb** [comment]
Would be lovely if this also included an auto-tag feature for rarity, enabling auto-tagging of blue weapons as trash.

**Comment by bhollis** [comment]
Good idea but that's a different feature

**Comment by bhollis** [comment]
I wouldn't mind getting this out there for people to give feedback on. I fixed the double scrollbars stuff. Anything else that'd block trying it out?

**Comment by nev-r** [comment]
no objection doesn't hurt anything afaik

**Review by inexorableAce — APPROVED** [review]
yeah, I don't have a lot to say about this really. Seems fine Lets push it and give it some use.

**Pull request merged**
