### PR TITLE
Switch most requires to imports

### PR DESCRIPTION
**Pull request by bhollis**
@SunburnedGoose expressed a desire to prefer ES6 module imports over CommonJS-style `require`. This was just done with a simple `sed` command, and everything still works. The only bits I had to manually modify were `util.js` (since it was our only module that exported something, now it uses ES6 exports) and `.eslintrc` (to set the module option).

We still use `require` for templates and JSON and stuff. I don't know exactly how to move those to ES6 imports since import is a keyword and not a function so I'm not sure it can be used in all the places `require` can be. Looks like there are some sorta awkward workarounds like [this](http://stackoverflow.com/questions/37818401/importing-html-files-with-es6-template-string-loader) but they require all your template requires to be assigned to names like this:

```js
import template from './header.html';
```

It's also worth noting that, at least today, most Webpack examples and help uses `require` instead of `import`.

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
There are a few packages that don't play well with the import keyword because they don't have module.export.  I have them documented.

require('angular-hotkeys');
require('angular-promise-tracker');
require('angular-timer');
require('angular-uuid2/dist/angular-uuid2.js');
require('ng-http-rate-limiter');

**Comment by SunburnedGoose** [comment]
If you want the contents of the file, then use the html-loader otherwise you get the URL to the file as it is packaged.

import template from 'html-loader;./header.html'
vs
import templateUrl from './header.html'

As for dynamic items, you'll have to import each of the permutations manually.

**Comment by bhollis** [comment]
That seems like a bummer all around. What are we getting in return for giving all that up?

-Ben

**Comment by SunburnedGoose** [comment]
You have to be explicit with your imports.

**Comment by bhollis** [comment]
Yeah, I was asking what new thing we get to do or new capability we get from switching to imports from require. Right now we have something that works nicely with require - switching to imports would at the very least have to be a no-op change. It sounds like instead we're giving up some flexibility, familiarity, and compatibility. What do we get?

Regarding ng-http-rate-limiter, what's it missing? It doesn't need to export anything because it's an Angular module, but it knows how to require: https://github.com/bhollis/ng-http-rate-limiter/blob/master/ng-http-rate-limiter.js#L16 (unfortunately ES6 imports are also impossible to add in a forwards-compatible way so there isn't explicit support for them there).

**Comment by SunburnedGoose** [comment]
Convention is to export your module name.

**Comment by bhollis** [comment]
Weird. But is it required?

**Comment by SunburnedGoose** [comment]
Makes this nice...

```
import angular from 'angular';
import aria from 'angular-aria';
import dialog from 'ng-dialog';

angular
  .module('dimApp', [
    aria,
    dialog,
```

**Comment by SunburnedGoose** [comment]
Angular modules as convention return their module name from their IIFE, or module.export.  Nothing is required but it makes it a lot easier to use.

Add some variation of this to your code to make it play well with imports 

http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/

**Comment by bhollis** [comment]
Yup, you can see from the linked code that ng-http-rate-limiter already handles no-module, CommonJS, and AMD in almost exactly the way that article points out (via https://github.com/umdjs/umd). Unfortunately I don't think it's possible to also support the new ES6 module syntax like that in a forwards-compatible way, because it introduces new syntax that older browsers (er... and current browsers) don't support. It works because tools like Webpack know how to load a CommonJS module from an ES6 import, but it isn't really an ES6 module.

**Comment by bhollis** [comment]
I've just pushed an npm update to ng-http-rate-limiter that returns the module name.

**Comment by SunburnedGoose** [comment]
Okay.  Let me look.

**Comment by SunburnedGoose** [comment]
That change worked.  I can't tell you want version I was using earlier, but it was not giving me module name.

**Pull request merged**
