### PR TITLE
notes in "keyword" search

### PR DESCRIPTION
**Pull request by sundevour**
for your consideration?

it's already so general and this would be so useful!

### CODE REVIEW

**Comment by bhollis** [comment]
I've resisted this a bit in the past partly because it's slightly more expensive to look up notes, and it makes the default search start to get hard to understand. But I could see it as being sort of a "do what I mean" search that searches a bunch of text. I think what would make this better is if we added specific name and description searches so folks who really wanted to limit their searches could still do so.

**Comment by bhollis** [comment]
@philkernick you're the most passionate about searchability - what do you think?

**Comment by philkernick** [comment]
The general principle of our search is that an untagged search should search everything.  If you want to limit it, then you apply a tag.

We already have `notes:term` if you only want to search notes, so this change looks good and consistent with the normal DIM approach.

There is one minor edge case to bring up.  All of our searches are absolutely consistent because they only search information from the manifest.  This extends the search into local or Google storage.  That means that the results will vary if you don't have persistent storage connected.  I don't think it's a big deal, but it is worth raising from a UX viewpoint.

**Comment by sundevour** [comment]
included `name:` and `description:` searches.

though they _could_ benefit from minor clarification in `t('Filter.PartialMatch')` they're the same general concept of string search so maybe unnecessary.

**Pull request merged**
