### PR TITLE
added item description to items' object, but for now only showing on Bounties

### PR DESCRIPTION
**Pull request by jflayhart**
I loved the new changes to general items and immediately started to notice the bounties section... I saw that the pop up was lacking with an empty space underneath the name, so I just took the initiative and added a description to Bounties... just a small, simple change for me to get used to the codebase and makes up for the empty space with, what I think, is useful information.

### CODE REVIEW

**Comment by jflayhart** [comment]
Just added a little percentage completed number beside bounty title.

**Comment by jflayhart** [comment]
Sample

**Comment by SunburnedGoose** [comment]
Not a fan of this.  Make that data available on the move dialog of the bounty, similarly to ATK values on weapons.

**Comment by jflayhart** [comment]
I had that initially, @SunburnedGoose, but thought it looked less presentable. Easy to put there, so am happy to do it, just what are you not a fan of exactly with having it displayed on the bounty image? Just curious.

**Comment by SunburnedGoose** [comment]
Its the only thing that has item text in the UI. Sticks out. No context for
the information. Let's talk about it in context with v4 and how we present
data about items in the UI.

In v4 we will move bounties out of the character item list so we can have a
display that is more helpful.

**Comment by jflayhart** [comment]
So this "improvement" is irrelevant then

**Comment by SunburnedGoose** [comment]
Move it inside the move dialog and I'll push it in the next update.

**Comment by jflayhart** [comment]
Added... 
screen shot 2015-08-31 at 11 55 58 am

**Comment by jflayhart** [comment]
This PR is now obsolete because it was part of an old fork.

**Comment by SunburnedGoose** [comment]
Do I need to roll back?

**Comment by jflayhart** [comment]
#192 IS #212 just without the reference... I had deleted the fork #192 was a part of, but it's exactly the same code. This was intended for master branch.

**Comment by SunburnedGoose** [comment]
Contributors don't check into master.  When a feature branch is stable, we merge into /dev, and then when a release is ready to go out, myself or kyle will merge to master.

**Comment by SunburnedGoose** [comment]
The contributor.md might need to be updated. :)

**Comment by jflayhart** [comment]
My bad, so create a PR for dev from now on...

**Pull request merged**
