### PR TITLE
Sketch out a Grunt task to automatically publish beta releases from dev

### PR DESCRIPTION
**Pull request by bhollis**
The idea behind this is to allow us to set up a [Travis CI](https://travis-ci.org/) process that will release a new Beta extension every time we commit to `dev`. This gets changes in the hands of testers faster, so we can get feedback earlier. It should be easy enough to extend to make it possible to publish the official extension more easily (from `master`).

For this to really work, @SunburnedGoose or somebody else with the keys needs to do the following:

1. Following the "how to get it" links on [the grunt-webstore-upload docs](https://github.com/c301/grunt-webstore-upload#accounts-1), find the values for `CHROME_CLIENT_ID`, `CHROME_SECRET`, and `CHROME_REFRESH_TOKEN` for the Beta Chrome Store account.
2. Install the `travis` gem: `gem install travis`.
3. Following [the Travis Secret Environment Variable guide](https://docs.travis-ci.com/user/environment-variables/#Encrypting-Variables-Using-a-Public-Key), encrypt those three values into the `.travis.yml`: `travis encrypt CHROME_CLIENT_ID=super_secret --add env.matrix`, etc.

Doing the above will put some encrypted fields into `.travis.yml` that are only readable by Travis, so they can be checked in. Then we can set up Travis, which will run when there's a commit to `dev`, and it'll be able to build and publish the extension using those encrypted credentials.

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Need to see if it has a window of time that we can define for commits so it has to wait an hour from the last commit before it starts a build. I don't want to spam the web store with builds.

**Comment by bhollis** [comment]
Would it be a problem to publish new builds frequently?

**Comment by SunburnedGoose** [comment]
Yes. The web store can only process one at a time. I believe there is a
throttle on how many can be submitted.

Can we have it perform CI builds on commit and just make one nightly beta
build?

**Comment by bhollis** [comment]
We can always try it out and see what happens - it might be possible to query the store to see if there's something in progress.

**Comment by SunburnedGoose** [comment]
Takes an hour after upload to finish processing. I'm fine just having a
nightly beta deployment if there have been any checkins during the day.

**Comment by SunburnedGoose** [comment]
I haven't seen any way to throttle by searching on my phone. I'll look
closer tonight on my desktop.

**Comment by bhollis** [comment]
Maybe https://nightli.es/ ?

**Comment by SunburnedGoose** [comment]
Other steps to consider for this is to tag github for releases, and create the release.

For example, https://github.com/DestinyItemManager/DIM/releases/tag/v3.3

**Comment by bhollis** [comment]
Yeah I think we can have a slightly different workflow for real releases.

**Comment by bhollis** [comment]
Totally. Do you want to try setting that up with nighti.es? I don't have the keys or permissions to do much beyond what I've already done.

**Comment by SunburnedGoose** [comment]
Yeah.  I'll do it tomorrow.

**Comment by bhollis** [comment]
*poke*

**Comment by SunburnedGoose** [comment]
https://github.com/DestinyItemManager/DIM/commit/9bbde827ddd4e52c5133722c53ddd1ee88c6cca1

I couldn't commit to your repo I guess... So I pushed a branch locally.  Get what you need from it and I'll delete it.

**Comment by SunburnedGoose** [comment]
I've setup the Web Store, Travis, and Nightli.es btw.

**Comment by bhollis** [comment]
OK, I've merged. I've also set up the branch whitelist so it shouldn't do any builds automatically - I'm assuming nightli.es can still do its builds. Let me know!

**Comment by SunburnedGoose** [comment]
I'll see tomorrow.

**Pull request merged**
