### PR TITLE
Added Moments of Triumph progress and steps to item details.

### PR DESCRIPTION
**Pull request by SunburnedGoose**
I can't test a completed MoT item but the in progress seems to be working.

screen shot 2016-07-07 at 10 08 24 pm

### CODE REVIEW

**Comment by kyleshay** [comment]
Looks awesome, love that we get this description on hover! 

Seeing an issue with the SRL book... 
screen shot 2016-07-07 at 11 23 30 pm

**Comment by kyleshay** [comment]
Also, I'm thinking that https://github.com/DestinyItemManager/DIM/pull/658 will fix it so that clicking on any of the MoT's will open the move popup on the right icon instead of only opening on the first.

**Comment by kyleshay** [comment]
Also, I find it odd that the SRL book can be locked but not the MoT2, haha.

**Comment by SunburnedGoose** [comment]
I don't have a SRL book.  Dunno if I really want to buy one atm..

**Comment by SunburnedGoose** [comment]
Actually @kyleshay, I can't buy a SRL book now.  Can you look into this and resolve the issue with the SLR book, or just ignore and we can leave it be...

**Pull request merged**
