### PR TITLE
Fix: Changelog link

### LINKED ISSUE #2254: beta.dim - changelog link invalid
when clicking on the about link on beta.dim it takes you to:
https://github.com/DestinyItemManager/DIM/blob/dev/docs/CHANGELOG.md#next

which is invalid as there is no 'dev' branch.

it should point to:
https://github.com/DestinyItemManager/DIM/blob/master/docs/CHANGELOG.md#next

### PR DESCRIPTION
**Pull request by duckmanBR**
removed the dev/master link since we don't have a branch for dev and included a link to the exact version so people won't see the "what's next" before seeing the changelog for stable version.

This should fix #2254

### CODE REVIEW

**Comment by bhollis** [comment]
Hmm, can you rename?

**Comment by bhollis** [comment]
Sorry, rebase

**Comment by duckmanBR** [comment]
No problem, but don't know how...

**Comment by SunburnedGoose** [comment]
git pull --rebase 

I believe.  It preserves commit history and makes the merge easier to read for changes like this.

**Comment by duckmanBR** [comment]
On the web interface (the only I have access, unfortunately) there's no reference to rebase but I can manually edit the code to solve the conflict.  Done!

**Pull request merged**
