### PR TITLE
Organizer hotkeys

### LINKED ISSUE #7365: Add compare button above organizer table
### Proposed change

Add a compare button above the organizer table to compare items that are currently selected with the checkbox.

### How does this fit into your workflow?

This would mostly be used the same way the compare functionality is currently used, but I think it would be nice to be able to select all of the things you want to compare and then click compare. This also would solve the problem of the compare modal covering up the items at the bottom of the table.

### PR DESCRIPTION
**Pull request by bhollis**
Now that hotkeys don't conflict with each other, I can finally do this:

* Added a "Compare" button to the Organizer to allow focused comparison of selected items.
* Added hotkeys to organizer - bulk tag, note, compare, or move selected items easily.
* Added a new "N" hotkey for editing notes on an item.

Fixes #7365, #5286

### CODE REVIEW

**Comment by robojumper** [comment]
One weird thing in Organizer (Win 10 Edge, Firefox) is that clicking a checkbox focuses that checkbox and makes it capture keyboard input (e.g. so that [space] can toggle the checkbox), which means I have to click outside of the checkbox for shortcuts to start working again.

**Comment by bhollis** [comment]
Yup, I noticed that. I might make the hotkeys ignore that.

**Review by vivekhnz — APPROVED** [review]
Awesome, being able to use the `Shift+number` hotkeys to tag feels great!

One thing I noticed is that the hotkeys can still be used when a dialog is open. It doesn't conflict with the dialog itself, but it does feel weird that I can perform actions associated with UI behind the dialog.

Repro:
1. Select an item in Organizer
2. Press `N` to open the set note dialog
3. Unfocus the note textbox, but don't dismiss the dialog.
4. Press `C` - observe that the compare sheet pops up behind the dialog, which is unexpected.
5. Press `ESC` - observe that the compare sheet is dismissed instead of the dialog. I would have expected the dialog to be dismissed, because it is the front-most element.

**Comment by bhollis** [comment]
Yeah - dialogs and sheets don't really block hotkeys from working. The update I made recently just allows "inner" hotkeys to take precedence over "outer" ones. We'd need to do something extra to disable the item-table-level shortcuts whenever a sheet or dialog was up.

**Pull request merged**
