### PR TITLE
Collapsible sections UI tweaks

### PR DESCRIPTION
**Pull request by bhollis**
I had a couple ideas for how to make the collapse-sections UI a bit less obtrusive. Let me know what you think. Two separate ideas, presented together:

1. Make the buttons only appear on hover, as opposed to all the time.
2. Move the buttons into the margin instead of having them take up space (which looks somewhat weird when they auto-hide.

collapse-ui

### CODE REVIEW

**Comment by kyleshay** [comment]
Actually love them both! I say merge it!

**Comment by kyleshay** [comment]
Actually, looking at it again locally, noticed the categories for the buckets make the margin extending beyond the left seem a bit strange... maybe moving the +/- out for those as well?

flip

**Comment by kyleshay** [comment]
Another consideration -- if the major categories weapons/armor/etc are also collapsed, they should show the [+] as well.

**Comment by joshmedeski** [comment]
I love the idea. I would make sure the `+` and `-` have good contrast so people have better visibility of the state of the toggle. 

Like @kyleshay said, it might be better to always show the`+` on collapsed top level categories.

Check out the [Contrast Rebellion](http://contrastrebellion.com/) website to see what I meant about visibility and contrast.

**Comment by SunburnedGoose** [comment]
Can you highlight on the bucket mouse over?  Not really a touch accordance but something we can do to keep it low visible until it is needed.

**Comment by kyleshay** [comment]
also seems there may now be some some horizontal scroll

**Comment by bhollis** [comment]
@kyleshay agreed about putting the indicators for the sections in the margin too. I'll do that and fix the horizontal scrolling tomorrow.

@joshmedeski good point on the contrast. I'll see if there's something nice we can do.

@SunburnedGoose I'm not sure I understand what you mean by highlight on mouse over. As of this PR, we're *showing* the icon on mouseover.

**Comment by SunburnedGoose** [comment]
They should always be visible since touch users don't have hover.  When we have mouse hover, we can enhance the icon by increasing the brightness.

**Comment by bhollis** [comment]
Then we should just toss this PR

**Comment by joshmedeski** [comment]
It's easy to detect touch devices. You can always show the toggle icons if it's a touch device 😉

**Comment by SunburnedGoose** [comment]
We don't use modernizer so we don't have the body classes to infer touch.  JavaScript touch tests?

**Comment by bhollis** [comment]
How do you detect touch devices?

**Comment by SunburnedGoose** [comment]
`'ontouchstart' in window`

https://github.com/rafrex/detect-touch

`(('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch)`

https://github.com/Modernizr/Modernizr/blob/master/feature-detects/touchevents.js

**Comment by bhollis** [comment]
Does that work for MS surface?

**Comment by joshmedeski** [comment]
I think https://github.com/ten1seven/what-input is a good tool for detecting touch.

**Comment by bhollis** [comment]
I'm not sure I want to bother with having UI that switches around depending on whether you have a touch device or not - since I don't have a Surface or another touch device, I'd never test it in that mode.

**Pull request closed without merging**
