### PR TITLE
Put a yellow border on stacks of three or more rare mods

### PR DESCRIPTION
**Pull request by bhollis**
Somebody on Twitter suggested this, and it seemed like an easy QoL improvement.

screen shot 2017-10-20 at 10 45 41 pm

### CODE REVIEW

**Comment by kyleshay** [comment]
wondering if we should have a has:goldborder filter

**Comment by bhollis** [comment]
Hmm weird. I didn’t do anything to make it work across stacks...

You can use is:complete to select these, but an alias would be helpful 

-Ben

**Comment by duckmanBR** [comment]
@bhollis did you change anything?  Couldn't reproduce the image from @kyleshay, and that would be a nice feature to have, because would be a sign to the user that the lonely mod is the third needed to exchange...
PS: the stack:>=3 would also filter those items...

**Comment by kyleshay** [comment]
Ah, I got it by doing a 'take' on an item in the vault, then dragging 1 off to the inventory.

**Comment by bhollis** [comment]
I found a bug where we would fail to update the border. It’s fixed now. Highlighting across stacks remains a cool idea. 

-Ben

**Pull request merged**
