### PR TITLE
Sort ratings by time

### PR DESCRIPTION
**Pull request by bhollis**
Previously all the ups were before all the downs, which kinda buried things. Sort by time feels better.

### CODE REVIEW

**Comment by 48klocs** [comment]
The rough way it was meant to work was highlighted reviews first, good reviews second, bad reviews last (because hopefully you get useful information out of highlighted/happy users).

Highlighted reviewers aren't a thing in D2 (present, but never actually set), but sorting by newest->oldest good reviews and then newest->oldest bad reviews would certainly make sense.

**Comment by bhollis** [comment]
Hmm, on DTR itself, they sort just by time. I was finding it weird to have to scroll to the bottom to find the bad reviews, while having them on a timeline seemed pretty natural.

**Comment by 48klocs** [comment]
My basic idea with that was to nudge people - putting positive reviews up front hopefully encourages people to stay positive in their reviews.

I don't have any major objection to changing the sort order, just explaining why it's the way it is.

**Comment by bhollis** [comment]
OK. In that case the existing sorting is working as intended.

**Pull request closed without merging**
