### PR TITLE
Couple of small changes to test the forked PR builds.

### PR DESCRIPTION
**Pull request by ryan-rushton**

### CODE REVIEW

**Comment by ryan-rushton** [comment]
Got any idea's why we aren't getting the packtracker reports on the PR? It has both the base commit report and the report for this PR's latest commit.

**Comment by bhollis** [comment]
Are we not setting info about the fork correctly?

**Comment by ryan-rushton** [comment]
The branch is showing up on packtracker itself, https://app.packtracker.io/organizations/159/projects/136?branch=chore%2Ftest-fork-pr-build.

The params that get set are

```
branch | PT_BRANCH | Branch of the commit(default: git rev-parse --abbrev-ref HEAD)
author | PT_AUTHOR | Committer's email (default: git log --format="%aE" -n 1 HEAD)
message | PT_MESSAGE | The commit message (default: git log --format="%B" -n 1 HEAD)
commit | PT_COMMIT | The commit sha (default: git rev-parse HEAD)
committed_at | PT_COMMITTED_AT | Unix timestamp (ms) of the commit(default: git log --format="%ct" -n 1 HEAD)
prior_commit | PT_PRIOR_COMMIT | The previous commit sha (default: git rev-parse HEAD^)
exclude_assets | PT_EXCLUDE_ASSETS | Mirrors the excludeAssets configuration in the webpack stats config (only available to webpack version 3.5.0+) (compiled as RegExp when provided via environment variable)
```

From these we can only set branch and commit correctly, see the payload details below. 

<details>
  <summary>Payload from open event</summary>

```json
{
    "token": "***",
    "job": "build",
    "ref": "refs/pull/6432/merge",
    "sha": "a4224a014a22afd8f0386517c3a09e43d33955ab",
    "repository": "DestinyItemManager/DIM",
    "repository_owner": "DestinyItemManager",
    "repositoryUrl": "git://github.com/DestinyItemManager/DIM.git",
    "run_id": "475039959",
    "run_number": "239",
    "retention_days": "90",
    "actor": "ryan-rushton",
    "workflow": "PR Build",
    "head_ref": "bug/forked-repos-builds-take-4",
    "base_ref": "master",
    "event_name": "pull_request",
    "event": {
        "action": "opened",
        "number": 6432,
        "organization": {
            "avatar_url": "https://avatars3.githubusercontent.com/u/12777189?v=4",
            "description": " Have full control over your armory wherever you are. Our free app lets you focus on playing the game by smartly moving your gear.",
            "events_url": "https://api.github.com/orgs/DestinyItemManager/events",
            "hooks_url": "https://api.github.com/orgs/DestinyItemManager/hooks",
            "id": 12777189,
            "issues_url": "https://api.github.com/orgs/DestinyItemManager/issues",
            "login": "DestinyItemManager",
            "members_url": "https://api.github.com/orgs/DestinyItemManager/members{/member}",
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEyNzc3MTg5",
            "public_members_url": "https://api.github.com/orgs/DestinyItemManager/public_members{/member}",
            "repos_url": "https://api.github.com/orgs/DestinyItemManager/repos",
            "url": "https://api.github.com/orgs/DestinyItemManager"
        },
        "pull_request": {
            "_links": {
                "comments": {
                    "href": "https://api.github.com/repos/DestinyItemManager/DIM/issues/6432/comments"
                },
                "commits": {
                    "href": "https://api.github.com/repos/DestinyItemManager/DIM/pulls/6432/commits"
                },
                "html": {
                    "href": "https://github.com/DestinyItemManager/DIM/pull/6432"
                },
                "issue": {
                    "href": "https://api.github.com/repos/DestinyItemManager/DIM/issues/6432"
                },
                "review_comment": {
                    "href": "https://api.github.com/repos/DestinyItemManager/DIM/pulls/comments{/number}"
                },
                "review_comments": {
                    "href": "https://api.github.com/repos/DestinyItemManager/DIM/pulls/6432/comments"
                },
                "self": {
                    "href": "https://api.github.com/repos/DestinyItemManager/DIM/pulls/6432"
                },
                "statuses": {
                    "href": "https://api.github.com/repos/DestinyItemManager/DIM/statuses/594591f5ebb43ba3c5ea216cdf79d5de192950a3"
                }
            },
            "active_lock_reason": null,
            "additions": 41,
            "assignee": null,
            "assignees": [],
            "author_association": "CONTRIBUTOR",
            "base": {
                "label": "DestinyItemManager:master",
                "ref": "master",
                "repo": {
                    "allow_merge_commit": true,
                    "allow_rebase_merge": false,
                    "allow_squash_merge": true,
                    "archive_url": "https://api.github.com/repos/DestinyItemManager/DIM/{archive_format}{/ref}",
                    "archived": false,
                    "assignees_url": "https://api.github.com/repos/DestinyItemManager/DIM/assignees{/user}",
                    "blobs_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/blobs{/sha}",
                    "branches_url": "https://api.github.com/repos/DestinyItemManager/DIM/branches{/branch}",
                    "clone_url": "https://github.com/DestinyItemManager/DIM.git",
                    "collaborators_url": "https://api.github.com/repos/DestinyItemManager/DIM/collaborators{/collaborator}",
                    "comments_url": "https://api.github.com/repos/DestinyItemManager/DIM/comments{/number}",
                    "commits_url": "https://api.github.com/repos/DestinyItemManager/DIM/commits{/sha}",
                    "compare_url": "https://api.github.com/repos/DestinyItemManager/DIM/compare/{base}...{head}",
                    "contents_url": "https://api.github.com/repos/DestinyItemManager/DIM/contents/{+path}",
                    "contributors_url": "https://api.github.com/repos/DestinyItemManager/DIM/contributors",
                    "created_at": "2015-03-04T21:46:50Z",
                    "default_branch": "master",
                    "delete_branch_on_merge": true,
                    "deployments_url": "https://api.github.com/repos/DestinyItemManager/DIM/deployments",
                    "description": "Destiny Item Manager",
                    "disabled": false,
                    "downloads_url": "https://api.github.com/repos/DestinyItemManager/DIM/downloads",
                    "events_url": "https://api.github.com/repos/DestinyItemManager/DIM/events",
                    "fork": false,
                    "forks": 401,
                    "forks_count": 401,
                    "forks_url": "https://api.github.com/repos/DestinyItemManager/DIM/forks",
                    "full_name": "DestinyItemManager/DIM",
                    "git_commits_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/commits{/sha}",
                    "git_refs_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/refs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/tags{/sha}",
                    "git_url": "git://github.com/DestinyItemManager/DIM.git",
                    "has_downloads": true,
                    "has_issues": true,
                    "has_pages": false,
                    "has_projects": false,
                    "has_wiki": true,
                    "homepage": "https://destinyitemmanager.com",
                    "hooks_url": "https://api.github.com/repos/DestinyItemManager/DIM/hooks",
                    "html_url": "https://github.com/DestinyItemManager/DIM",
                    "id": 31681575,
                    "issue_comment_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues/comments{/number}",
                    "issue_events_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues/events{/number}",
                    "issues_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues{/number}",
                    "keys_url": "https://api.github.com/repos/DestinyItemManager/DIM/keys{/key_id}",
                    "labels_url": "https://api.github.com/repos/DestinyItemManager/DIM/labels{/name}",
                    "language": "TypeScript",
                    "languages_url": "https://api.github.com/repos/DestinyItemManager/DIM/languages",
                    "license": {
                        "key": "mit",
                        "name": "MIT License",
                        "node_id": "MDc6TGljZW5zZTEz",
                        "spdx_id": "MIT",
                        "url": "https://api.github.com/licenses/mit"
                    },
                    "merges_url": "https://api.github.com/repos/DestinyItemManager/DIM/merges",
                    "milestones_url": "https://api.github.com/repos/DestinyItemManager/DIM/milestones{/number}",
                    "mirror_url": null,
                    "name": "DIM",
                    "node_id": "MDEwOlJlcG9zaXRvcnkzMTY4MTU3NQ==",
                    "notifications_url": "https://api.github.com/repos/DestinyItemManager/DIM/notifications{?since,all,participating}",
                    "open_issues": 80,
                    "open_issues_count": 80,
                    "owner": {
                        "avatar_url": "https://avatars3.githubusercontent.com/u/12777189?v=4",
                        "events_url": "https://api.github.com/users/DestinyItemManager/events{/privacy}",
                        "followers_url": "https://api.github.com/users/DestinyItemManager/followers",
                        "following_url": "https://api.github.com/users/DestinyItemManager/following{/other_user}",
                        "gists_url": "https://api.github.com/users/DestinyItemManager/gists{/gist_id}",
                        "gravatar_id": "",
                        "html_url": "https://github.com/DestinyItemManager",
                        "id": 12777189,
                        "login": "DestinyItemManager",
                        "node_id": "MDEyOk9yZ2FuaXphdGlvbjEyNzc3MTg5",
                        "organizations_url": "https://api.github.com/users/DestinyItemManager/orgs",
                        "received_events_url": "https://api.github.com/users/DestinyItemManager/received_events",
                        "repos_url": "https://api.github.com/users/DestinyItemManager/repos",
                        "site_admin": false,
                        "starred_url": "https://api.github.com/users/DestinyItemManager/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/DestinyItemManager/subscriptions",
                        "type": "Organization",
                        "url": "https://api.github.com/users/DestinyItemManager"
                    },
                    "private": false,
                    "pulls_url": "https://api.github.com/repos/DestinyItemManager/DIM/pulls{/number}",
                    "pushed_at": "2021-01-10T04:01:07Z",
                    "releases_url": "https://api.github.com/repos/DestinyItemManager/DIM/releases{/id}",
                    "size": 382121,
                    "ssh_url": "git@github.com:DestinyItemManager/DIM.git",
                    "stargazers_count": 1315,
                    "stargazers_url": "https://api.github.com/repos/DestinyItemManager/DIM/stargazers",
                    "statuses_url": "https://api.github.com/repos/DestinyItemManager/DIM/statuses/{sha}",
                    "subscribers_url": "https://api.github.com/repos/DestinyItemManager/DIM/subscribers",
                    "subscription_url": "https://api.github.com/repos/DestinyItemManager/DIM/subscription",
                    "svn_url": "https://github.com/DestinyItemManager/DIM",
                    "tags_url": "https://api.github.com/repos/DestinyItemManager/DIM/tags",
                    "teams_url": "https://api.github.com/repos/DestinyItemManager/DIM/teams",
                    "trees_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/trees{/sha}",
                    "updated_at": "2021-01-09T21:07:37Z",
                    "url": "https://api.github.com/repos/DestinyItemManager/DIM",
                    "watchers": 1315,
                    "watchers_count": 1315
                },
                "sha": "c4c80fc731b08f0825b666b118efaa7e415ed447",
                "user": {
                    "avatar_url": "https://avatars3.githubusercontent.com/u/12777189?v=4",
                    "events_url": "https://api.github.com/users/DestinyItemManager/events{/privacy}",
                    "followers_url": "https://api.github.com/users/DestinyItemManager/followers",
                    "following_url": "https://api.github.com/users/DestinyItemManager/following{/other_user}",
                    "gists_url": "https://api.github.com/users/DestinyItemManager/gists{/gist_id}",
                    "gravatar_id": "",
                    "html_url": "https://github.com/DestinyItemManager",
                    "id": 12777189,
                    "login": "DestinyItemManager",
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjEyNzc3MTg5",
                    "organizations_url": "https://api.github.com/users/DestinyItemManager/orgs",
                    "received_events_url": "https://api.github.com/users/DestinyItemManager/received_events",
                    "repos_url": "https://api.github.com/users/DestinyItemManager/repos",
                    "site_admin": false,
                    "starred_url": "https://api.github.com/users/DestinyItemManager/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/DestinyItemManager/subscriptions",
                    "type": "Organization",
                    "url": "https://api.github.com/users/DestinyItemManager"
                }
            },
            "body": "",
            "changed_files": 2,
            "closed_at": null,
            "comments": 0,
            "comments_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues/6432/comments",
            "commits": 2,
            "commits_url": "https://api.github.com/repos/DestinyItemManager/DIM/pulls/6432/commits",
            "created_at": "2021-01-10T04:01:51Z",
            "deletions": 21,
            "diff_url": "https://github.com/DestinyItemManager/DIM/pull/6432.diff",
            "draft": false,
            "head": {
                "label": "DestinyItemManager:bug/forked-repos-builds-take-4",
                "ref": "bug/forked-repos-builds-take-4",
                "repo": {
                    "allow_merge_commit": true,
                    "allow_rebase_merge": false,
                    "allow_squash_merge": true,
                    "archive_url": "https://api.github.com/repos/DestinyItemManager/DIM/{archive_format}{/ref}",
                    "archived": false,
                    "assignees_url": "https://api.github.com/repos/DestinyItemManager/DIM/assignees{/user}",
                    "blobs_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/blobs{/sha}",
                    "branches_url": "https://api.github.com/repos/DestinyItemManager/DIM/branches{/branch}",
                    "clone_url": "https://github.com/DestinyItemManager/DIM.git",
                    "collaborators_url": "https://api.github.com/repos/DestinyItemManager/DIM/collaborators{/collaborator}",
                    "comments_url": "https://api.github.com/repos/DestinyItemManager/DIM/comments{/number}",
                    "commits_url": "https://api.github.com/repos/DestinyItemManager/DIM/commits{/sha}",
                    "compare_url": "https://api.github.com/repos/DestinyItemManager/DIM/compare/{base}...{head}",
                    "contents_url": "https://api.github.com/repos/DestinyItemManager/DIM/contents/{+path}",
                    "contributors_url": "https://api.github.com/repos/DestinyItemManager/DIM/contributors",
                    "created_at": "2015-03-04T21:46:50Z",
                    "default_branch": "master",
                    "delete_branch_on_merge": true,
                    "deployments_url": "https://api.github.com/repos/DestinyItemManager/DIM/deployments",
                    "description": "Destiny Item Manager",
                    "disabled": false,
                    "downloads_url": "https://api.github.com/repos/DestinyItemManager/DIM/downloads",
                    "events_url": "https://api.github.com/repos/DestinyItemManager/DIM/events",
                    "fork": false,
                    "forks": 401,
                    "forks_count": 401,
                    "forks_url": "https://api.github.com/repos/DestinyItemManager/DIM/forks",
                    "full_name": "DestinyItemManager/DIM",
                    "git_commits_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/commits{/sha}",
                    "git_refs_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/refs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/tags{/sha}",
                    "git_url": "git://github.com/DestinyItemManager/DIM.git",
                    "has_downloads": true,
                    "has_issues": true,
                    "has_pages": false,
                    "has_projects": false,
                    "has_wiki": true,
                    "homepage": "https://destinyitemmanager.com",
                    "hooks_url": "https://api.github.com/repos/DestinyItemManager/DIM/hooks",
                    "html_url": "https://github.com/DestinyItemManager/DIM",
                    "id": 31681575,
                    "issue_comment_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues/comments{/number}",
                    "issue_events_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues/events{/number}",
                    "issues_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues{/number}",
                    "keys_url": "https://api.github.com/repos/DestinyItemManager/DIM/keys{/key_id}",
                    "labels_url": "https://api.github.com/repos/DestinyItemManager/DIM/labels{/name}",
                    "language": "TypeScript",
                    "languages_url": "https://api.github.com/repos/DestinyItemManager/DIM/languages",
                    "license": {
                        "key": "mit",
                        "name": "MIT License",
                        "node_id": "MDc6TGljZW5zZTEz",
                        "spdx_id": "MIT",
                        "url": "https://api.github.com/licenses/mit"
                    },
                    "merges_url": "https://api.github.com/repos/DestinyItemManager/DIM/merges",
                    "milestones_url": "https://api.github.com/repos/DestinyItemManager/DIM/milestones{/number}",
                    "mirror_url": null,
                    "name": "DIM",
                    "node_id": "MDEwOlJlcG9zaXRvcnkzMTY4MTU3NQ==",
                    "notifications_url": "https://api.github.com/repos/DestinyItemManager/DIM/notifications{?since,all,participating}",
                    "open_issues": 80,
                    "open_issues_count": 80,
                    "owner": {
                        "avatar_url": "https://avatars3.githubusercontent.com/u/12777189?v=4",
                        "events_url": "https://api.github.com/users/DestinyItemManager/events{/privacy}",
                        "followers_url": "https://api.github.com/users/DestinyItemManager/followers",
                        "following_url": "https://api.github.com/users/DestinyItemManager/following{/other_user}",
                        "gists_url": "https://api.github.com/users/DestinyItemManager/gists{/gist_id}",
                        "gravatar_id": "",
                        "html_url": "https://github.com/DestinyItemManager",
                        "id": 12777189,
                        "login": "DestinyItemManager",
                        "node_id": "MDEyOk9yZ2FuaXphdGlvbjEyNzc3MTg5",
                        "organizations_url": "https://api.github.com/users/DestinyItemManager/orgs",
                        "received_events_url": "https://api.github.com/users/DestinyItemManager/received_events",
                        "repos_url": "https://api.github.com/users/DestinyItemManager/repos",
                        "site_admin": false,
                        "starred_url": "https://api.github.com/users/DestinyItemManager/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/DestinyItemManager/subscriptions",
                        "type": "Organization",
                        "url": "https://api.github.com/users/DestinyItemManager"
                    },
                    "private": false,
                    "pulls_url": "https://api.github.com/repos/DestinyItemManager/DIM/pulls{/number}",
                    "pushed_at": "2021-01-10T04:01:07Z",
                    "releases_url": "https://api.github.com/repos/DestinyItemManager/DIM/releases{/id}",
                    "size": 382121,
                    "ssh_url": "git@github.com:DestinyItemManager/DIM.git",
                    "stargazers_count": 1315,
                    "stargazers_url": "https://api.github.com/repos/DestinyItemManager/DIM/stargazers",
                    "statuses_url": "https://api.github.com/repos/DestinyItemManager/DIM/statuses/{sha}",
                    "subscribers_url": "https://api.github.com/repos/DestinyItemManager/DIM/subscribers",
                    "subscription_url": "https://api.github.com/repos/DestinyItemManager/DIM/subscription",
                    "svn_url": "https://github.com/DestinyItemManager/DIM",
                    "tags_url": "https://api.github.com/repos/DestinyItemManager/DIM/tags",
                    "teams_url": "https://api.github.com/repos/DestinyItemManager/DIM/teams",
                    "trees_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/trees{/sha}",
                    "updated_at": "2021-01-09T21:07:37Z",
                    "url": "https://api.github.com/repos/DestinyItemManager/DIM",
                    "watchers": 1315,
                    "watchers_count": 1315
                },
                "sha": "594591f5ebb43ba3c5ea216cdf79d5de192950a3",
                "user": {
                    "avatar_url": "https://avatars3.githubusercontent.com/u/12777189?v=4",
                    "events_url": "https://api.github.com/users/DestinyItemManager/events{/privacy}",
                    "followers_url": "https://api.github.com/users/DestinyItemManager/followers",
                    "following_url": "https://api.github.com/users/DestinyItemManager/following{/other_user}",
                    "gists_url": "https://api.github.com/users/DestinyItemManager/gists{/gist_id}",
                    "gravatar_id": "",
                    "html_url": "https://github.com/DestinyItemManager",
                    "id": 12777189,
                    "login": "DestinyItemManager",
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjEyNzc3MTg5",
                    "organizations_url": "https://api.github.com/users/DestinyItemManager/orgs",
                    "received_events_url": "https://api.github.com/users/DestinyItemManager/received_events",
                    "repos_url": "https://api.github.com/users/DestinyItemManager/repos",
                    "site_admin": false,
                    "starred_url": "https://api.github.com/users/DestinyItemManager/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/DestinyItemManager/subscriptions",
                    "type": "Organization",
                    "url": "https://api.github.com/users/DestinyItemManager"
                }
            },
            "html_url": "https://github.com/DestinyItemManager/DIM/pull/6432",
            "id": 552223687,
            "issue_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues/6432",
            "labels": [],
            "locked": false,
            "maintainer_can_modify": false,
            "merge_commit_sha": null,
            "mergeable": null,
            "mergeable_state": "unknown",
            "merged": false,
            "merged_at": null,
            "merged_by": null,
            "milestone": null,
            "node_id": "MDExOlB1bGxSZXF1ZXN0NTUyMjIzNjg3",
            "number": 6432,
            "patch_url": "https://github.com/DestinyItemManager/DIM/pull/6432.patch",
            "rebaseable": null,
            "requested_reviewers": [],
            "requested_teams": [],
            "review_comment_url": "https://api.github.com/repos/DestinyItemManager/DIM/pulls/comments{/number}",
            "review_comments": 0,
            "review_comments_url": "https://api.github.com/repos/DestinyItemManager/DIM/pulls/6432/comments",
            "state": "open",
            "statuses_url": "https://api.github.com/repos/DestinyItemManager/DIM/statuses/594591f5ebb43ba3c5ea216cdf79d5de192950a3",
            "title": "Fix build for forked repo's",
            "updated_at": "2021-01-10T04:01:51Z",
            "url": "https://api.github.com/repos/DestinyItemManager/DIM/pulls/6432",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/7344652?v=4",
                "events_url": "https://api.github.com/users/ryan-rushton/events{/privacy}",
                "followers_url": "https://api.github.com/users/ryan-rushton/followers",
                "following_url": "https://api.github.com/users/ryan-rushton/following{/other_user}",
                "gists_url": "https://api.github.com/users/ryan-rushton/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ryan-rushton",
                "id": 7344652,
                "login": "ryan-rushton",
                "node_id": "MDQ6VXNlcjczNDQ2NTI=",
                "organizations_url": "https://api.github.com/users/ryan-rushton/orgs",
                "received_events_url": "https://api.github.com/users/ryan-rushton/received_events",
                "repos_url": "https://api.github.com/users/ryan-rushton/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ryan-rushton/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ryan-rushton/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ryan-rushton"
            }
        },
        "repository": {
            "archive_url": "https://api.github.com/repos/DestinyItemManager/DIM/{archive_format}{/ref}",
            "archived": false,
            "assignees_url": "https://api.github.com/repos/DestinyItemManager/DIM/assignees{/user}",
            "blobs_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/blobs{/sha}",
            "branches_url": "https://api.github.com/repos/DestinyItemManager/DIM/branches{/branch}",
            "clone_url": "https://github.com/DestinyItemManager/DIM.git",
            "collaborators_url": "https://api.github.com/repos/DestinyItemManager/DIM/collaborators{/collaborator}",
            "comments_url": "https://api.github.com/repos/DestinyItemManager/DIM/comments{/number}",
            "commits_url": "https://api.github.com/repos/DestinyItemManager/DIM/commits{/sha}",
            "compare_url": "https://api.github.com/repos/DestinyItemManager/DIM/compare/{base}...{head}",
            "contents_url": "https://api.github.com/repos/DestinyItemManager/DIM/contents/{+path}",
            "contributors_url": "https://api.github.com/repos/DestinyItemManager/DIM/contributors",
            "created_at": "2015-03-04T21:46:50Z",
            "default_branch": "master",
            "deployments_url": "https://api.github.com/repos/DestinyItemManager/DIM/deployments",
            "description": "Destiny Item Manager",
            "disabled": false,
            "downloads_url": "https://api.github.com/repos/DestinyItemManager/DIM/downloads",
            "events_url": "https://api.github.com/repos/DestinyItemManager/DIM/events",
            "fork": false,
            "forks": 401,
            "forks_count": 401,
            "forks_url": "https://api.github.com/repos/DestinyItemManager/DIM/forks",
            "full_name": "DestinyItemManager/DIM",
            "git_commits_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/commits{/sha}",
            "git_refs_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/refs{/sha}",
            "git_tags_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/tags{/sha}",
            "git_url": "git://github.com/DestinyItemManager/DIM.git",
            "has_downloads": true,
            "has_issues": true,
            "has_pages": false,
            "has_projects": false,
            "has_wiki": true,
            "homepage": "https://destinyitemmanager.com",
            "hooks_url": "https://api.github.com/repos/DestinyItemManager/DIM/hooks",
            "html_url": "https://github.com/DestinyItemManager/DIM",
            "id": 31681575,
            "issue_comment_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues/comments{/number}",
            "issue_events_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues/events{/number}",
            "issues_url": "https://api.github.com/repos/DestinyItemManager/DIM/issues{/number}",
            "keys_url": "https://api.github.com/repos/DestinyItemManager/DIM/keys{/key_id}",
            "labels_url": "https://api.github.com/repos/DestinyItemManager/DIM/labels{/name}",
            "language": "TypeScript",
            "languages_url": "https://api.github.com/repos/DestinyItemManager/DIM/languages",
            "license": {
                "key": "mit",
                "name": "MIT License",
                "node_id": "MDc6TGljZW5zZTEz",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit"
            },
            "merges_url": "https://api.github.com/repos/DestinyItemManager/DIM/merges",
            "milestones_url": "https://api.github.com/repos/DestinyItemManager/DIM/milestones{/number}",
            "mirror_url": null,
            "name": "DIM",
            "node_id": "MDEwOlJlcG9zaXRvcnkzMTY4MTU3NQ==",
            "notifications_url": "https://api.github.com/repos/DestinyItemManager/DIM/notifications{?since,all,participating}",
            "open_issues": 80,
            "open_issues_count": 80,
            "owner": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/12777189?v=4",
                "events_url": "https://api.github.com/users/DestinyItemManager/events{/privacy}",
                "followers_url": "https://api.github.com/users/DestinyItemManager/followers",
                "following_url": "https://api.github.com/users/DestinyItemManager/following{/other_user}",
                "gists_url": "https://api.github.com/users/DestinyItemManager/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/DestinyItemManager",
                "id": 12777189,
                "login": "DestinyItemManager",
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjEyNzc3MTg5",
                "organizations_url": "https://api.github.com/users/DestinyItemManager/orgs",
                "received_events_url": "https://api.github.com/users/DestinyItemManager/received_events",
                "repos_url": "https://api.github.com/users/DestinyItemManager/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/DestinyItemManager/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/DestinyItemManager/subscriptions",
                "type": "Organization",
                "url": "https://api.github.com/users/DestinyItemManager"
            },
            "private": false,
            "pulls_url": "https://api.github.com/repos/DestinyItemManager/DIM/pulls{/number}",
            "pushed_at": "2021-01-10T04:01:07Z",
            "releases_url": "https://api.github.com/repos/DestinyItemManager/DIM/releases{/id}",
            "size": 382121,
            "ssh_url": "git@github.com:DestinyItemManager/DIM.git",
            "stargazers_count": 1315,
            "stargazers_url": "https://api.github.com/repos/DestinyItemManager/DIM/stargazers",
            "statuses_url": "https://api.github.com/repos/DestinyItemManager/DIM/statuses/{sha}",
            "subscribers_url": "https://api.github.com/repos/DestinyItemManager/DIM/subscribers",
            "subscription_url": "https://api.github.com/repos/DestinyItemManager/DIM/subscription",
            "svn_url": "https://github.com/DestinyItemManager/DIM",
            "tags_url": "https://api.github.com/repos/DestinyItemManager/DIM/tags",
            "teams_url": "https://api.github.com/repos/DestinyItemManager/DIM/teams",
            "trees_url": "https://api.github.com/repos/DestinyItemManager/DIM/git/trees{/sha}",
            "updated_at": "2021-01-09T21:07:37Z",
            "url": "https://api.github.com/repos/DestinyItemManager/DIM",
            "watchers": 1315,
            "watchers_count": 1315
        },
        "sender": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/7344652?v=4",
            "events_url": "https://api.github.com/users/ryan-rushton/events{/privacy}",
            "followers_url": "https://api.github.com/users/ryan-rushton/followers",
            "following_url": "https://api.github.com/users/ryan-rushton/following{/other_user}",
            "gists_url": "https://api.github.com/users/ryan-rushton/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/ryan-rushton",
            "id": 7344652,
            "login": "ryan-rushton",
            "node_id": "MDQ6VXNlcjczNDQ2NTI=",
            "organizations_url": "https://api.github.com/users/ryan-rushton/orgs",
            "received_events_url": "https://api.github.com/users/ryan-rushton/received_events",
            "repos_url": "https://api.github.com/users/ryan-rushton/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/ryan-rushton/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ryan-rushton/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/ryan-rushton"
        }
    },
    "server_url": "https://github.com",
    "api_url": "https://api.github.com",
    "graphql_url": "https://api.github.com/graphql",
    "workspace": "/home/runner/work/DIM/DIM",
    "action": "run8",
    "event_path": "/home/runner/work/_temp/_github_workflow/event.json",
    "action_repository": "",
    "action_ref": "",
    "path": "/home/runner/work/_temp/_runner_file_commands/add_path_f0438c0d-b1f1-4584-80c2-acfac0c8fbad",
    "env": "/home/runner/work/_temp/_runner_file_commands/set_env_f0438c0d-b1f1-4584-80c2-acfac0c8fbad"
}
```
</details>

What is essentially happening is github merges the branch into master locally then runs tests and hides secrets. When packtracker runs those git commands its not getting the details from the forked branch, it gets them from the local one. In saying that it is getting my email correctly in this example. Just not sure what else it could be. I would have thought we would be getting the checks come up but not satisfied if there were issues. The fact they dont show up at all is weird.

**Comment by ryan-rushton** [comment]
I should note that that payload is not from this PR directly but an earlier iteration.

**Comment by bhollis** [comment]
> When packtracker runs those git commands its not getting the details from the forked branch, it gets them from the local one.

Yeah that's why I'm saying you have to provide it overridden values.

**Comment by ryan-rushton** [comment]
We can't get those details from the event payload so I will have to see if I can come up with some git commands for it.

**Comment by ryan-rushton** [comment]
I still think it's odd we don't get unresolved packtracker checks though.

**Comment by ryan-rushton** [comment]
Actually, it won't be those details because if there is an issue with them there would be an issue with builds from the DIM repo too.

**Comment by ryan-rushton** [comment]
Closing this so I can squash the commits and test it for the pull request opened event.

**Pull request closed without merging**
