### PR TITLE
Unwanted i18n cleanup.

### PR DESCRIPTION
**Pull request by ryan-rushton**
It seems some things in the optimiser were going to get cleaned up when they shouldn't.

@bhollis @delphiactual , do you know if the other stuff in this is legit cleanup?

### CODE REVIEW

**Comment by delphiactual** [comment]
Run a `yarn install` and then try a `yarn i18n` again I made a bunch of fixes to the i18next-scanner

**Comment by delphiactual** [comment]
just pushed another fix into the lock file with https://github.com/DestinyItemManager/DIM/commit/ef981cad3c407322714b7b76f41d5d72cc3ad1c3

**Comment by ryan-rushton** [comment]
I'm still getting the same cleanup, I even dropped my node modules and ran i18n.

**Comment by ryan-rushton** [comment]
FYI I don't expect this PR to ever go in but for science I reset it to the latest master, dropped node modules, installed, and ran i18n and what is here is what I am getting.

**Comment by delphiactual** [comment]
Can you run `yarn why i18next` and post results please

**Pull request closed without merging**
