### PR TITLE
Tag dropdown

### PR DESCRIPTION
**Pull request by bhollis**
This replaces our tagging dropdown, which was just a system `<select>` tag, with a new custom Select component. This allows us to display icons and shortcut keys in the menu and gives us generally more control over what we show (for example, when an item is selected, the current tag is replaced with "Clear Tag" in the menu.

I took a bit of styling liberty here by giving this a semitransparent orange outline, since on the Compare screen it can end up with black on black which was hard to see.

Screen Shot 2020-10-03 at 11 16 28 PM
Screen Shot 2020-10-03 at 11 16 38 PM

### CODE REVIEW

**Comment by nev-r** [comment]
functionally awesome! i will test this out later sunday, when i am at a PC, if someone else doesnt get a chance to.

a styling note though:
is it fair to call the shortcut info secondary? like, if people care, they will eventually learn the shortcut, if they don't, they're a bit distracting to me.
the tag name + icon seem an order of magnitude more important, and the shortcuts are somewhat noisy and almost as visually heavy as some of the tags+labels, because of the outline

all this is to say, maybe it could be dimmed? possibly full opacity when highlit/hovered?

**Comment by bhollis** [comment]
Yeah I think they could be toned down. I'm trying to figure out how to move some of this info closer to where people need it but it definitely shouldn't be as heavy as it is now.

**Comment by bhollis** [comment]
This looks mildly disabled, but it isn't so distracting:
image

**Comment by bhollis** [comment]
I could also conceivably drop the border: 
image

**Comment by nev-r** [comment]
either's fine. border makes it look a lot more like keyboard keys instead of arcane notation

**Review by nev-r — APPROVED** [review]
love everything about the functionality, the eraser and the current-option-missing. works smooth for me.

at 1x zoom, the keyboard shortcuts are far smaller than DIM's smallest existing text (header stat numbers)

image
image

**Pull request merged**
