### PR TITLE
Enable the new Loadout editor for release

### PR DESCRIPTION
**Pull request by bhollis**
I'd like to get this into tomorrow's release ahead of Witch Queen.

### CODE REVIEW

**Comment by nev-r** [comment]
i'm honestly a little concerned about lingering usability quirks but i'm just one vote. there's a small list of things i would like to see done beforehand, like notes, the weird little floating season watermark,

and this user's concern addressed.. maybe dynamic column widths depending on global/no and on amount of item contents?
https://cdn.discordapp.com/attachments/333464468241514497/945089482502311976/unknown.png

**Comment by bhollis** [comment]
> the weird little floating season watermark

I haven't been able to find it, except for in that one screenshot you shared

**Comment by robojumper** [comment]
> > the weird little floating season watermark
> 
> I haven't been able to find it, except for in that one screenshot you shared

It appears when the LO parameters have an exotic with a watermark.

**Comment by bhollis** [comment]
My concern is mostly that we'll have a lot of new users coming in for Witch Queen, who will be creating a lot of loadouts, and I'd rather have the better loadout experience than not. But if you think there are serious usability issues then get some tracking issues created.

**Comment by nev-r** [comment]
as i said, quirks. it's whatever, it edits loadouts, merge away. just feels like an invitation to get all the complaints at once while we are presumably playing wq or trying to code wq features.

**Pull request merged**
