### PR TITLE
Enable auto merge for d2ai and dependabot PRs

### LINKED ISSUE #10066: Auto merge dependabot PRs
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

### PR DESCRIPTION
**Pull request by bhollis**
This will flip the "auto merge" bit on D2AI PRs, and Dependabot PRs that update semver minor or patch dependencies. This means that once the tests/lint/build checks pass, the PR will automatically be merged. Might be a bit of chaos, but might also save us some annoyance?

Fixes #10066

### CODE REVIEW

**Review by delphiactual — APPROVED** [review]

**Comment by robojumper** [comment]
One thought - can we get dependabot to open the PRs outside of the weekend to give beta some time to test them before they get promoted to app? Would be kind of annoying to automatically get a bunch of upgrades merged Sunday evening, and then have to hotfix app if it caused regressions...

**Comment by delphiactual** [comment]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval

**Comment by bhollis** [comment]
Right now they're scheduled to open on Monday, though security updates can happen anytime

**Comment by robojumper** [comment]
And we deploy on 1am UTC Monday

https://github.com/DestinyItemManager/DIM/blob/eeaf59a44d0db7ecaca3ec5860a6f085c03afecd/.github/workflows/deploy-prod.yml#L11-L14

not sure what time exactly dependabot's "on Monday" is

**Comment by bhollis** [comment]
Guessing they mean US west coast Monday if I'm gonna bet. We can be more explicit though. Also worth noting that so far Dependabot has failed to evaluate our JS dependencies: https://github.com/DestinyItemManager/DIM/network/updates/316641/jobs

**Comment by bhollis** [comment]
Tweaked it to definitely happen on Monday

**Pull request merged**
