### PR TITLE
"or" filters in search

### PR DESCRIPTION
**Pull request by bhollis**
I was fixing #3177, when I suddenly realized there was an easy way to do "or" filters. So here they are!

This video shows me searching for all my handcannons, shotguns, and autorifles, and then filtering them all by rating. @philkernick is gonna love this I'm sure.

orsearch

### CODE REVIEW

**Comment by bhollis** [comment]
Fixes #2668 and #3177.

**Comment by joshhunt** [comment]
what does `is:autorifle is:energy or is:submachine` match?

**Comment by bhollis** [comment]
There are implicit ANDs between terms and OR has precedence so it would match all auto rifles that are either energy or submachine guns. :-/

Like I said we need a real expression tree.

**Comment by philkernick** [comment]
@bhollis you give the nicest gifts!  A B C or D  --> A && B && (C || D)

But unless I'm reading the code wrong, "C or D or E" isn't going to works as initially expected.
My expectation with or binding tighter than and is: --> (C || D || E) 
But what you actually get is: --> (C || D) && (D || E) 
These are different when C=0, D=0, E=1, and C=1,D=0,E=0

I also think it's going to throw an exception if a filter starts with "or" (there is no previous filter predicate) and will fail if it ends with "or" (no next predicate).  And I'm pretty sure it will get very messed up "by A or or B", since the previous filter is the magic "or" filter.

In the first instance these can be mitigated by not allowing more than one "or" per filter.

**Comment by philkernick** [comment]
You can also handle the leading and trailing "or" by padding the filter with an initial and final token that are always true.

**Comment by philkernick** [comment]
I'll do a bunch of testing as soon as it's pushed into beta.

**Comment by bhollis** [comment]
It's in beta now, give it a shot!

**Comment by philkernick** [comment]
You are a coding god!  I could find nothing that didn't work or threw an exception.

The only conceptual piece that I'm struggling with is OR having a higher precedent than AND.  There is way too much coding in my past!

Until we get a real expression tree or brackets we still can't do things like:
`(is:hunter power>:=540) or (is:warlock power:>=560)`

**Comment by bhollis** [comment]
Yeah, that’s right. It’s weird for it to have higher precedence but it’s kind of a hack :-). I’ll probably write a real expression parser when I rewrite search for the guided search stuff.

**Pull request merged**
