### PR TITLE
better comparison for artifacts

### PR DESCRIPTION
**Pull request by kyleshay**
if the item type is artifacts, and the stat is ‘disc’ then max is 51 instead of 38. this only ever happens on int/dis roll, but we should apply that logic to all artifacts, so that a user can see that an int/dis roll gives them more points than int/str or dis/str.

now, instead of making your int/dis artifacts appear over 100%, they will only ever hit a max of 100%. int/str or dis/str artifacts are going to just always look bad. really bad.

examples:
screen shot 2016-05-25 at 11 20 45 am

is it weird to see 100% and 89%, but the max possible roll is 81%? it's accurate, but strange:
screen shot 2016-05-25 at 11 24 09 am

an int/dis roll will always be the best:
screen shot 2016-05-25 at 11 24 28 am

### CODE REVIEW

**Comment by bhollis** [comment]
@kyleshay did you mean to merge this, rather than close it?

**Comment by kyleshay** [comment]
I did mean to close it per discussion with, @SunburnedGoose 

I can really go both ways. It would stop the confusion... but maybe introduce some new confusion. Not sure the best course of action.

**Comment by SunburnedGoose** [comment]
Which thread were we discussing this?  We can continue the conversation there.  INT/DIS artifacts are the way to T12 and when artifacts throw +100%, these bugged artifacts are highlighted.  

Still need the (WHY?) link in the popup to discuss grading and prevent the questions about +100% artifacts.

**Comment by bhollis** [comment]
In #526 you said the issue was closed per this PR, but this PR isn't merged. So I'm still a bit confused as to the status of >100% artifacts. Personally I'm confused by them, and it just looks like a bug.

**Comment by kyleshay** [comment]
up-to-date with dev if we want to reconsider this.

**Comment by SunburnedGoose** [comment]
What's the behavior here?  Are you capping the rolls at 100%?

**Comment by kyleshay** [comment]
no, basically the change is:

if it's an artifact, and we're looking at the discipline node... then the max for that node is 13 points higher, and the total is also 13 points higher.
```javascript
if (stat.statHash === 1735777505 && type.toLowerCase() === 'artifact') {
          stat.split += 13;
          ret.total.max += 13;
}
```

**Comment by SunburnedGoose** [comment]
I wouldn't make an exception for this node.  Keep it as is, or normalize everything to +13.  Users don't understand that discipline is bugged.  You're telling them that two 100% items are equivalent but they can't recognize that they are in fact very different items.

I still suggest that you keep it as is, and just put a (why?) link and explain artifacts in the wiki.

**Comment by kyleshay** [comment]
sooo.. close in favor of a (?) tooltip if quality % >= 100?

**Comment by SunburnedGoose** [comment]
Yes.

**Pull request closed without merging**
