### PR TITLE
Add new categories for trace rifle and linear fusion rifle

### PR DESCRIPTION
**Pull request by bhollis**
Now that the categories are fixed we can get rid of our workaround and support some more searches.

### CODE REVIEW

**Comment by duckmanBR** [comment]
Did this impact the Trace Rifle infusion?

**Comment by bhollis** [comment]
Could you go into more detail? What's interesting about Trace Rifle infusion? IIRC infusion categories are completely separate from item categories.

**Comment by duckmanBR** [comment]
Sorry, my mistake.  It's not infusion itself, but since trace rifle uses auto rifles as fuel (and we used to use the infusion hash to create categories) trace rifles were highlighted with is:autorifle.
That's why we had the #2535 issue and the #2538 PR...

**Comment by bhollis** [comment]
No, they won't be auto rifles anymore, they'll be trace rifles. I understand that that was the case before, but it doesn't really make sense, does it?

**Comment by bhollis** [comment]
@SunburnedGoose @kyleshay @philkernick so should we keep auto rifle search matching trace rifles, or just show the correct category? We have the new infusion finder that goes both ways, so that solves that problem...

**Comment by philkernick** [comment]
It really depends on your primary usecase for the is:autorifle filter. I only ever use it for infusion reasons, so for me having trace and auto in the same category is my preference. I can’t actually imagine a current usecase for is:tracerifle. 

I also note that this is the same issue as fusion rifles vs linear fusion rifles. 

Perhaps a configuration toggle to allow either option. 

--

**Comment by bhollis** [comment]
In that case we shouldn't call this category search at all, but infusion fuel search - which uses an entire different property. Bu we also have an infusion fuel calculator that understands all the infusion rules. 

-Ben

**Comment by philkernick** [comment]
There is a half-way point, but it's probably more confusing that useful.  I'll use auto/trace as the example, but fusion/linear works the same way.

is:autorifle matches autorifle and tracerifle
is:tracerifle matches tracerifle only

Then...
is:autorifle [matches anything that will infuse into auto and trace]
is:tracerifle [matches just tracerifles if you wanted to find them]
is:autorifle not:tracerifle [matches traditional autorifles but not tracerifles]

This is slightly better that using string searches because while...
is:autorifle trace [matches tracerifles]
There is no "not" operator for strings, so you couldn't match the autorifles that weren't tracerifles.

Combinations are hard as DIM doesn't currently have anything like an "or" operator.

As I said, probably more confusing that necessary.

**Comment by philkernick** [comment]
Given that infusion has fundamentally changed in Forsaken, it might be time to merge this branch in.

Will also need to add is:bow when we know what the hash for it is.

**Comment by duckmanBR** [comment]
Not against it, but should be on our radar that a category search should/must show more than one item type.
Prestige Loadout this week is "Fusion Rifle".  But by that means more than just Fusion Rifles (https://twitter.com/joegoroth/status/1034534236672409601) 
> Fusion can be a linear fusion a regular fusion or a trace rifle

**Comment by delphiactual** [comment]
This is true for the proposed active mode, but not for a specific search.

**Comment by bhollis** [comment]
Makes sense. Let's have a separate issue for how we want to modify the weapon category searches.

**Comment by bhollis** [comment]
We'll add bows once they show up in the manifest.

**Pull request merged**
