### PR TITLE
RFC: Filter mods menu with search pills

### PR DESCRIPTION
**Pull request by bhollis**
Screenshot 2023-03-26 at 4 19 45 PM

Wanted to know what folks thought about this before pushing forward on it. At the very least:

1. We'd probably want to sort these types a bit better.
2. Have to figure out something for Mobile, maybe making it horizontally scrollable (oh no...)
3. Possible some of these categories don't need to exist (e.g. Siphon vs. Orbs)

### CODE REVIEW

**Comment by Gix3612** [comment]
I don't think it's worth it to directly include keywords that are already a part of Bungie's mod naming scheme like targeting, loader, siphon, etc. especially when those mods only exist in a single armor-type slot. The element and ability pills will at least filter things from multiple slots, though how much harder it would be to just type them is a different debate. I think that the real focus should be on things that require reading the description to categorize normally and grouping "like things" from different slots. As for displaying on mobile, my idea would be to create an icon for each category; then when viewed on mobile: display only the icons without text and include a button at the end to open a "symbol key". I already have .SVGs for a number of them from the DIMSymbols font and can easily make others for the ones we don't. For the colored mods I would go with the matching dots or arrows at the bottom of those mods and for the orb filters I was thinking we could use the "orb ring" like you find on the siphon mods, but with a down arrow in the middle for "drops orbs" and an up arrow for "on pick-up".

Screenshot 2023-03-27 214710

### Basic Keyword Filters
- Arc
- Solar
- Void
- Stasis
- Strand
- Harmonic
- Class ability
- Melee
- Grenade
- Super
- Finisher

### Special Filters
- ***Ability cooldown/energy:*** Dynamo, Ashes to Assets, Hands-On, Momentum Transfer, Bolstering Detonation, Impact Induction, Focusing Strike, Innervation, Invigoration, Insulation, Absolution, Orbs of Restoration, Distribution, Outreach, Bomber
- ***Creates orbs:*** Power Preservation, ___ Siphon, Firepower, Heavy Handed, Reaper
- ***On orb pick-up:*** Recuperation, Better Already, Innervation, Invigoration, Insulation, Absolution, Orbs of Restoration, Stacks on Stacks
- ***Armor charge enhancement (green ^^^):*** Radiant Light, Powerful Friends, Shield Break Charge, Charged Up, Stacks on Stacks, Time Dilation, Empowered Finish
- ***Armor charge decay (blue ...):*** Font of ___, ___ Weapon Surge
- ***Consumes armor charge (yellow vvv):*** ___ Kickstart, Emergency Reinforcement, ___ Finisher
- ***Ammo:*** ___ Ammo Finder, ___ Ammo Scout, ___ Reserves, ___ Scavenger
- ***Weapon enhancement:*** ___ Targeting, ___ Loader, ___ Dexterity, Lucent Blades, Unflinching __ Aim, ___ Weapon Surge, ___ Holster

**Comment by liminalAce** [comment]
Just chiming in here, as always, symbols without text are generally meaningless especially on mobile where it's notoriously difficult to get any kind of context out from under your fingers. 

As far as the general pills stuff... yeah I dunno it takes up a ton of space... for so little gain but people really hate typing 3 characters I guess. So I dunno.

**Comment by liminalAce** [comment]
yeah I know what a key is, same thing a hidden guide to your symbols is just another click to something that is supposed increase the speed of this interface... having to consistently open and close a guide to your UI isn't super cash money.

**Comment by bhollis** [comment]
Yeah I think at best symbols would be in addition to the text, not a replacement for it.

**Comment by Gix3612** [comment]
> Yeah I think at best symbols would be in addition to the text, not a replacement for it.

The idea was only meant for mobile resolutions where space is more limited, on desktop it would still use both like your initial example and the key and key button would be hidden completely.

> yeah I know what a key is, same thing a hidden guide to your symbols is just another click to something that is supposed increase the speed of this interface... having to consistently open and close a guide to your UI isn't super cash money.

You wouldn't be opening it consistently, only a few times until you can recognize the symbols or on the off-chance something new is ever added. The symbol-only pills still function as filter pills, no one would ever be required to open the key at all.

Alternatively, you could always group things even further to conserve space, but then there's the concern that it won't actually trim down the list in any meaningful way if the filter is including to much.
- Elemental mods
- Abilities & finishers
- Orbs & armor charge
- Weapons & ammo

**Comment by Gix3612** [comment]
If it's the idea of opening a new panel that is so off-putting, you could change the key button concept to instead just reveal the text portion on the pills—which would expand to flood the screen with the full sized pills—but then have them auto-hide again once something is selected. And of course, they would still be useable as normal while in the short, symbol-only form.

**Comment by bhollis** [comment]
@vivekhnz what do you think? Also, do you have any ideas for how we could present the mods within this menu better?

**Comment by vivekhnz** [comment]
It definitely makes mods more discoverable, although I'm unsure whether it is much of an improvement over search in its current form.

My main pain points with the mod picker are:
- For most builds, many categories of mods are irrelevant to the build, causing noise. When I first start making a loadout, it's easier for me to express the mods that I **don't** want, rather than the ones I do.
  - For example, if I'm making a PvP loadout, I don't care about Finder, Scout, Reserves, Scavenger, Resistance, Finisher or Raid mods.
  - I don't want to see mods for weapon damage types I'm not using.
- Search (and pills) are nice tools for finding a specific category of mod, but since a loadout usually consists of mods from multiple categories (e.g. targeting, loader, Armor Charge etc.), I have to clear the search (or deselect and reselect pills) multiple times to select all the mods I want.

Some ideas:
- For mod pickers launched from Loadout Optimizer, hide all the stat mods if `Automatically add stat mods` is enabled.
- Make the filter pills **exclude** mod categories instead of **include** mod categories
  - The behaviour would be more akin to a list of checkboxes that are all initially checked, rather than radio buttons. Multi-select is the default behaviour, so no need for shift-click.
  - I don't think we have this 'exclude' behaviour anywhere else in DIM, so this may need some different styling.
- Group pills that would typically be excluded together e.g.
  dim-mod-picker-pills
- Damage type pills (Kinetic, Arc etc.) should filter to mods that affect weapons i.e. don't include Resistance mods
  - If the mod picker is launched from Optimizer or the loadout drawer and a subclass has been selected, only display Harmonic mods if the current subclass's weapon damage type pill is selected
  - If the mod picker is launched from the loadout drawer and an equipped weapon has been selected in all slots, pre-select the damage type pills that match equipped weapons
- For mod pickers launched within Loadout Optimizer, remember the mod category excludes that were last set during the current session.
  - We probably don't need to save this into the LO settings, but don't ask the user to exclude the same 4 damage types every time they open the mod picker.
- Maybe we could explore a more compact way to display certain mods e.g.
  dim-weapon-mods

Not sure if this is useful, but I wrote down my thought process when setting up a loadout using the current mod picker, which might help illustrate some shortcomings. There are some details that I've pretended not to be aware of, to be more representative of an average user.

<details>
<summary>Building a loadout - stream of consciousness</summary>

- I want to make a PvP build
- I've already decided on my subclass and weapons
  - Gunslinger w/ Tripmines, Ahamkara's Spine, Void Hand Cannon, Stasis Shotgun
- I'll start with my Primary weapon, since that'll have the highest uptime
  - It's Void, so I'll type "void" into the search
  - I want a Targeting mod, a Loader mod and an Unflinching mod
  - Ideally, I'd like as many of these mods as possible, but I don't know if I'll need the space for other mods just yet
  - I'm going to slot in 3x of them for now, with the knowledge that I'll probably need to get rid of some of them later
- The next most important thing is making sure I've got high uptime on grenades
  - I want to see all the mods that interact with my grenade - use the search box to filter to "grenade"
  - I wish I could see Community Insight for these mods here
  - Grenade Kickstart seems good
    - Can't pick it, it's greyed out
    - Why is it greyed out? No indicator to tell me why.
    - It's because I've already got 3 arms mods. Ok, I'll remove one.
    - The arms mods are displayed together with all the mods in the other slots. Which ones are arms mods? I'll hover over each of them, since the tooltip will tell me.
    - Ok, removed one loader mod. I can add a kickstart now.
    - Should I get rid of one more loader for another kickstart? Wish the mod picker tiles would show the Community Insight so I know the impact of an additional kickstart vs. an additional loader.
    - I'll stick with 2 loaders for now
  - What else will help me get more grenades?
    - "Ashes to Assets" gives me extra super energy on grenade kills. Not really helpful right now, wish I could have filtered to stuff that gives me grenade energy only.
    - same deal with "bolstering detonation"
    - "impact induction" seems useful (reduced grenade cooldown from melee damage).
      - How useful is it? Can't see the community insight in the mod picker tile.
      - Ok, I'll get rid of a loader and add it, so I can hover over it and see the community insight in the tooltip.
      - eh, 10% doesn't seem great. no thanks, remove.
      - I'd like the loader back. Hmm, not there. need to clear out "Grenade" search filter to get back to it.
      - Ok, clear the search box, click 'Void Loader', type "Grenade" back into search box
    - "innervation" reduces grenade cooldown when I pick up an orb.
      - that doesn't happen very often in PvP, but I don't think there's anything on my legs yet, so may as well add it?
      - let's add 3 of them, I'll get rid of them if something better comes along
    - "bomber" reduces grenade cooldown on dodge - nothing on my class item so I'll take 3 of those too
    - "explosive finisher" restores grenades on finisher
      - I'm making a PvP build, so I can't use finishers. This is noise, wish I could have filtered this out
    - raid mods - also noise
- Ok, on to my special weapon.
  - It's stasis, so I'll type "stasis" into the search.
  - I like targeting, dexterity and unflinching on my shotguns
    - need to get rid of a void targeting to slot in a stasis targeting
    - need to get rid of the second void loader to slot the stasis dexterity
      - so needing to decide between a second void loader vs. a second kickstart earlier was a waste of time...
    - need to get rid of a void unflinching to slot in a stasis unflinching
- that's all of the important mods in. is there anything better I could slot?
  - most stackable mods have diminishing returns, so duplicate mods are a good candidate to swap out
  - I click "Select mods" and look at the mod placement for the top generated set
  - my boots have all 3 of the same mod "Innervation", which I only picked because I hadn't come across something better yet
   - are there better options on boots? I click on one of those mods to open the mod picker.
   - there's 29 options here, but 14 of them are for weapon damage types I'm not using. wish I could filter those out.
   - of the 15 remaining, 2 of them are scavenger mods that don't work in PvP. wish those could be filtered out too.
   - after looking at the relevant 13 mods, I'm going with a void holster, stasis holster and absolution
  - my class item has 3x bombers, which I might be able to swap for better options.
    - I click on one of the bomber mods to open the mod picker
    - there's 18 options, but 11 of them are for finishers, which don't work in PvP.
    - after looking at the remaining 7 options, I'm going with 2x bomber and a Reaper mod
  - ok, those mods look good. what are my stats like?
    - pretty good for the stats I care about. but could they be better if I remove some of these mods?
    - a lot of these mods are negotiable, and I might part with them for another stat tier or two.
    - LO has managed to put a +10 stat mod in every slot, so maybe this is the best I can get? would be nice to know for sure, but I don't want to remove each mod one-by-one to figure it out.

</details>

**Comment by Gix3612** [comment]
For your stream of consciousness, you also forgot:
- disciple indirectly affects my grenade uptime so I'll type "discipline" into the search box to see if anything is useful in PvP.

**Pull request closed without merging**
