### PR TITLE
Italian translation of the support file

### PR DESCRIPTION
**Pull request by simonefranza**
I replaced all the "à", "è", "ì", "ò" and "ù" with the corresponding html code ( i.e. "è" = &egrave; ), but I don't know if it's needed.

### CODE REVIEW

**Comment by delphiactual** [comment]
@simonefranza good work, @kyleshay, @bhollis ready for merge

**Comment by kyleshay** [comment]
looks great. it should be OK to use characters with diacritical/accents marks (ex. è) -- if not, we should!

**Comment by simonefranza** [comment]
Okay :) @kyleshay

**Comment by bhollis** [comment]
Yup let's just use Unicode rather than escaping accented characters!

-Ben

**Pull request merged**
