### PR TITLE
fix for primStat classified

### PR DESCRIPTION
**Pull request by delphiactual**

### CODE REVIEW

**Comment by bhollis** [comment]
What was wrong?

**Comment by delphiactual** [comment]
itemDef.primStat never gets checked for assignment, but item.primStat does

**Comment by SunburnedGoose** [comment]
I thought classified items didn't have a itemDef?

**Comment by delphiactual** [comment]
they don't we populate it

**Comment by SunburnedGoose** [comment]
I see.  You're redefining itemDef in the line above.

**Comment by bhollis** [comment]
So wait, what was actually wrong? Items didn't show a primary stat? I'm trying to write a CHANGELOG entry but I have no idea.

**Comment by delphiactual** [comment]
The lysander cry is the only classified item with a primary stat currently and it was not showing it correctly

**Pull request merged**
