### PR TITLE
Moved Ornaments Section

### PR DESCRIPTION
**Pull request by HazyArc14**
Moved Ornaments section in between Consumables and Materials to reflect the in game inventory page. (OCD)

### CODE REVIEW

**Comment by bhollis** [comment]
Thanks! I'm not sure about this though - I don't feel the need to exactly
copy the in game layout, and to me materials are more important than
ornaments. Thoughts?

**Comment by HazyArc14** [comment]
I see what you are saying but maybe they should be between the materials and emblems. Because they are consumables but are also cosmetics. I just think that it flows better if they are in between those sections. But its whatever you decide just wanted to share my suggestion.

**Comment by bhollis** [comment]
I could buy that, yeah! That's a great place to put them. Want to update the PR?

**Comment by HazyArc14** [comment]
Moved between Material and Emblem.

**Pull request merged**
