### PR TITLE
Added Windows Build commands

### PR DESCRIPTION
**Pull request by KiaArmani**
Using the existing commands, you can not build on Windows because the syntax is different. I have added two more commands for this with a "-win" suffix.

### CODE REVIEW

**Comment by delphiactual** [comment]
Build is for sending release to the website. Did you try `yarn start`?

**Comment by KiaArmani** [comment]
I do want to build my own releases as I run my own Instance of DIM. yarn start doesn’t help me with that.

 

Von: Rob Jones <notifications@github.com> 
Gesendet: Sonntag, 13. Oktober 2019 15:42
An: DestinyItemManager/DIM <DIM@noreply.github.com>
Cc: Kia Armani <contact@xi4.me>; Author <author@noreply.github.com>
Betreff: Re: [DestinyItemManager/DIM] Added Windows Build commands (#4454)

 

Build is for sending release to the website. Did you try yarn start?

**Comment by delphiactual** [comment]
Yarn start does exactly what you are asking

**Comment by KiaArmani** [comment]
yarn start starts up a webserver which is undesireable for what I want to do. I just want to package up the site and copy the content of the dist folder to my web server.

**Pull request merged**
