### PR TITLE
Updates based on reddit feedback.

### PR DESCRIPTION
**Pull request by delphiactual**
https://www.reddit.com/r/translator/comments/4xhbrr/english_japanese_need_help_verifying_if_these/

### CODE REVIEW

**Comment by bhollis** [comment]
Interesting. Postmaster and vanguard become phonetic transcriptions of the English words (posutomāsutā, bangādō, etc).

I realized there's another string we should add in there - "Reputation".

**Comment by bhollis** [comment]
@delphiactual would you be willing to take a first stab at a translation guide? As a wiki or maybe just a Markdown file...

**Comment by delphiactual** [comment]
Yeah, should be pretty easy... I'll see what I can come up with

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/wiki/Translations

**Pull request merged**
