### PR TITLE
Adding D2 profile progressions

### PR DESCRIPTION
**Pull request by 48klocs**
Profile progressions were recently added to the API - here's a first pass at getting it drawn on to the Progress tab.

It looks kind of so so because there are no icons for the checklists and there's a lot of items. Maybe this should go on its own page (or be shown after character progressions)?

scrolling-checklist

### CODE REVIEW

**Comment by bhollis** [comment]
Nice! Pretty rough at the moment though. Maybe hit up the #design channel for some help.

**Comment by 48klocs** [comment]
Agree, it's not the most beautiful thing in the world (there's no icons for anything and a bunch of the description texts mostly repeat what their names are).

As an aside, the checklist viewer can also work for the checklist progression data that's kept on each character. I don't know how much interest there would be in finding out what adventures a given toon hasn't done, but it does that.

**Comment by bhollis** [comment]
Maybe we should put this under a feature flag and iterate on it

**Comment by 48klocs** [comment]
Since I noticed that the collections is part of the account progression (!) I touched up the checklist items to display (half-size) images where they exist.

look at my collection

**Comment by bhollis** [comment]
I'm not sure we have a place for this info. Let's resurrect this branch when we have an idea of how to use the data.

**Pull request closed without merging**
