### PR TITLE
Warmind fixes (collections, emotes)

### PR DESCRIPTION
**Pull request by bhollis**
1. Remove the emotes bucket. I can show the emote wheel, but it doesn't look good yet and you can't do anything with it.
2. Leverage the pursuits bucket to accurately fill out quests in the Progress page.
3. Fix duplicate collections bug (from https://github.com/Bungie-net/api/issues/480)

### CODE REVIEW

**Comment by bhollis** [comment]
Note: The collections bug may be due to masterworks - has anyone gotten an exotic masterwork yet?

**Comment by bhollis** [comment]
4. Filter out platform-exclusive items from collections/vendors when they don't match the current platform.

**Comment by bhollis** [comment]
5. Fix masterworks

**Comment by duckmanBR** [comment]
- Masterwork Armors still bugged

**Pull request merged**
