### PR TITLE
Experiment with using raw-loader instead of file-loader

### PR DESCRIPTION
**Pull request by bhollis**
This is a request-for-comment PR. In it, I'm switching from Webpack's file-loader (which generates a separate HTML file, and when you import it you get the path to that file) to raw-loader (which when you import it gives you the actual contents of the template). The idea is that we can save a bunch of requests by inlining all the templates.

The one downside I see is that we now load *all* templates up front as part of the main bundle. We could switch to using a naming pattern to avoid this (so we could choose based on the name whether we generate a separate file or inline) but so far Webpack doesn't seem to have the flexibility to choose on a per-import basis particularly nicely. You can specify loaders when you import, but we have so many carefully-ordered loaders that it'd be a nightmare to replicate them at every import.

Longer term I'd like to see about getting large segments of functionality broken out into their own chunks that get loaded on demand, but that's way more work.

### CODE REVIEW

**Comment by kyleshay** [comment]
I do like the idea of this, is there a way that we could see perf differences? What perf would be useful? First full render/how much more data is coming down, versus loading a template when it is needed?

**Comment by SunburnedGoose** [comment]
LoD is super nice in ng2.  Practically for free...  We bundle at work btw.  Only our development builds load files individually.

**Comment by bhollis** [comment]
```
# Before:
-rw-r--r--+  1 brh  staff   1.2M Apr 15 14:28 authReturn-816cb6.js
-rw-r--r--+  1 brh  staff   1.2M Apr 15 14:28 chunk-0-sqlLib-be3e2b.js
-rw-r--r--+  1 brh  staff   1.6K Apr 15 14:28 index.html
-rw-r--r--+  1 brh  staff   3.3M Apr 15 14:28 main-123973.js
-rw-r--r--+  1 brh  staff   272B Apr 15 14:28 return.html
-rw-r--r--+  1 brh  staff   142K Apr 15 14:28 styles-6ce7ae.css
-rw-r--r--+ 1 brh  staff    2.5K Apr 15 14:28 static/about.template-0ddd98.html
-rw-r--r--+ 1 brh  staff     55B Apr 15 14:28 static/app-48fbc1.html
-rw-r--r--+ 1 brh  staff    9.2K Apr 15 14:28 static/best.template-754711.html
-rw-r--r--+ 1 brh  staff    1.0K Apr 15 14:28 static/changelog-toaster-release-edc7ad.html
-rw-r--r--+ 1 brh  staff    2.4K Apr 15 14:28 static/content-7e33c1.html
-rw-r--r--+ 1 brh  staff    723B Apr 15 14:28 static/debugItem.template-7df120.html
-rw-r--r--+ 1 brh  staff    940B Apr 15 14:28 static/developer.template-194355.html
-rw-r--r--+ 1 brh  staff    1.9K Apr 15 14:28 static/dimFarming.directive.template-c44b10.html
-rw-r--r--+ 1 brh  staff    4.8K Apr 15 14:28 static/dimLoadout.directive.template-416b73.html
-rw-r--r--+ 1 brh  staff    4.4K Apr 15 14:28 static/dimLoadoutPopup.directive.template-7cf2d6.html
-rw-r--r--+ 1 brh  staff    9.6K Apr 15 14:28 static/dimStoreHeading.directive.template-89bf09.html
-rw-r--r--+ 1 brh  staff    2.2K Apr 15 14:28 static/dimStoreItem.directive.template-453efd.html
-rw-r--r--+ 1 brh  staff     16K Apr 15 14:28 static/filters.template-445ce8.html
-rw-r--r--+ 1 brh  staff     10K Apr 15 14:28 static/infuse.template-c27190.html
-rw-r--r--+ 1 brh  staff    288B Apr 15 14:28 static/inventory-23a316.html
-rw-r--r--+ 1 brh  staff    566B Apr 15 14:28 static/login.template-7ff850.html
-rw-r--r--+ 1 brh  staff    5.6K Apr 15 14:28 static/mats-exchange.template-e45def.html
-rw-r--r--+ 1 brh  staff    330B Apr 15 14:28 static/platform-choice-ce14b5.html
-rw-r--r--+ 1 brh  staff    2.2K Apr 15 14:28 static/record-books-61340c.html
-rw-r--r--+ 1 brh  staff     26B Apr 15 14:28 static/return.component.template-7d43e6.html
-rw-r--r--+ 1 brh  staff    6.5K Apr 15 14:28 static/settings.template-4808fc.html
-rw-r--r--+ 1 brh  staff    294B Apr 15 14:28 static/shell-247419.html
-rw-r--r--+ 1 brh  staff    967B Apr 15 14:28 static/support.template-7abe74.html
-rw-r--r--+ 1 brh  staff     40B Apr 15 14:28 static/upgrade-chrome-3ac0dc.html
-rw-r--r--+ 1 brh  staff    2.1K Apr 15 14:28 static/vendors-b4bc2e.html
-rw-r--r--+ 1 brh  staff    343B Apr 15 14:28 static/xur-0641b2.html

# After
-rw-r--r--+ 1 brh  staff   1.2M Apr 15 14:27 authReturn-836bf8.js
-rw-r--r--+ 1 brh  staff   1.2M Apr 15 14:27 chunk-0-sqlLib-be3e2b.js
-rw-r--r--+ 1 brh  staff   1.6K Apr 15 14:27 index.html
-rw-r--r--+ 1 brh  staff   3.4M Apr 15 14:27 main-2ca8ff.js
-rw-r--r--+ 1 brh  staff   272B Apr 15 14:27 return.html
```

In summary, we're moving about 156K of HTML into the main bundle (which will compress better than having them as additional files). We're probably avoiding 9 initial HTML requests - the other 18 HTML files would have been loaded lazily, but it's not a ton of content overall. Probably better to try and break whole routes up into lazy modules.

**Comment by bhollis** [comment]
I'm gonna go for it - I think the value outweighs the costs.

**Pull request merged**
