### PR TITLE
Detect and warn about Clarity

### PR DESCRIPTION
**Pull request by bhollis**
This detects the Clarity extension and warns users to uninstall it. I used a MutationObserver to catch whenever Clarity injects its own menu item. As always, suggestions welcome as to wording.

The other changes are deduplicating the "warning banner" style and fixing some issues that prevent i18next-scanner from running (it doesn't understand TypeScript).

Screenshot 2023-08-18 at 12 16 08 PM

cc @Ice-mourne @StardustD2

### CODE REVIEW

**Comment by StardustD2** [comment]
Love it! And sorry for the inconvenience 😅

**Comment by bhollis** [comment]
No problem, thanks for being cool about it.

**Review by robojumper — APPROVED** [review]
Seems reasonable to me. The i18next-scanner workarounds can now be reverted now though.

**Comment by Ice-mourne** [comment]
it should be inserted werry early before inventory and the other ones are loaded

**Pull request merged**
