### PR TITLE
Clean up Loadout Optimizer

### PR DESCRIPTION
**Pull request by bhollis**
After yesterday's stream I realized a few things could be cleaned up about the loadout optimizer. Mostly changing wording and reorganizing things, but also making the stats more obviously reorderable.

Before:
Screen Shot 2020-10-17 at 12 35 14 PM

After:
Screen Shot 2020-10-17 at 12 32 01 PM

### CODE REVIEW

**Review by delphiactual — APPROVED** [review]

**Comment by kyleshay** [comment]
nice. instructions are much more clear! 

was wondering if it would be worthwhile to have collapsible headers for things on the left to group them? though I'm not exactly sure how they would be grouped. maybe a "more options" section for other workflows where users can set the min power level, etc.

wonder if we should explain that search filters work on the page? otherwise, we can just make sure that's reflected in the user guide to keep the instructions on this page more basic.

**Review by ryan-rushton — APPROVED** [review]
Looks much cleaner. That confirm overwrite is something I was considering at the time but didn't end up doing. I am glad it's in there.

**Comment by ryan-rushton** [comment]
> though I'm not exactly sure how they would be grouped

I have been thinking about this lately @kyleshay. At the moment I think sections based on "This filters results" and "This changes how results are calculated" might be useful. Thoughts?

**Comment by bhollis** [comment]
I'm not sure about having collapsing. Mostly I think we should reduce options (minimum light, etc) and focus around "Tell us what stats you care about" and "Tell us what mods you want to run"

**Comment by ryan-rushton** [comment]
Yeah I would be onboard for that too. Would we preserve the assume masterwork and the stuff James has in around ignoring element affinity? I could see those still being wanted as it fundamentally changes what results are if the cost of changing them doesn't bother you.

**Comment by bhollis** [comment]
Yeah I think that makes sense but it's really a tertiary question, which is "what are you willing to spend?"

**Pull request merged**
