### PR TITLE
Stat effects

### LINKED ISSUE #5500: Show stat effects in tooltips and loadout optimizer
I'm willing to be convinced that maintaining a table of sandbox values is too much trouble, but it'd be helpful especially in the loadout optimizer to understand what each tier actually means. We could do it only for stats that are explained in game (assuming they're accurate) or we could crowdsource: https://i.imgur.com/vzvBuza.png

### PR DESCRIPTION
**Pull request by ryan-rushton**
So far I have just set this up in the store header stats, in inventory, as they already had a press tip. I intend to put them in the optimiser and in the loadouts and compare loadouts drawers.  In the drawers I will definitely do that in another PR as dealing with the drawer and a popup might present challenges.

So far I have just used crowdsourced data, I personally am pretty keen on this unless the bungie guys can get us some exact values.

I am happy to add anything else to this that people think are wanted/necessary.

image

Closes #5500

### CODE REVIEW

**Comment by delphiactual** [comment]
The data file needs to be added in d2ai as well

**Comment by ryan-rushton** [comment]
> The data file needs to be added in d2ai as well

Wasn't aware of that, will do.

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/DIM/blob/master/src/data/d2/README.md

**Comment by delphiactual** [comment]
https://github.com/DestinyItemManager/d2-additional-info/pull/193

**Comment by kyleshay** [comment]
love seeing it!!

**Comment by ryan-rushton** [comment]
I got the loadout drawer for free with the character stats, and the compare drawer for free with the optimiser stats.

I kept the optimiser version to just the effects as we don't have a full DimStat to get everything else. I could probably figure out a way to get more but I am not sure it is needed.

image
image

**Comment by kyleshay** [comment]
One thing that may be useful is (despite the math being easy) seeing the actual value in the tooltip on the LO page.

So hover a `T7` and you'll see `79` or `79 / 100` - useful for people who don't have the concept of what "T#" means (yet.)

Also useful for people who see they're at 79 / 100 and are 'wasting' 9 points,

**Comment by kyleshay** [comment]
wondering now if each of the tooltips should just all show the same info? might make it easier to maintain for updates if things are added in beyond light, just 1 place to update?

**Comment by ryan-rushton** [comment]
Yeah I think I will do that. I will extract it out and make a new component for it.

Thoughts on replicating the Destiny UI you posted?

**Comment by kyleshay** [comment]
ah I don't think redoing all of it is needed, mostly just wanted to post it for context as example. 

mostly the description and the layout of the content below it, excluding the bars (unless we wanted to add em.) also excluding the  tier + 1 info

**Comment by nev-r** [comment]
the game has 2 duplicate displays of the same number (44),
the actual number that matters (1:08),
and a number (next tier) that is not that relevant to DIM ("next tier" is useful when you can quickly sweep your mouse across all your items to check what's item is higher, but not for LO or inventory)

i personally disapprove of DIM showing the game's help text, when it's just as available in-game,
at all times, in the most important menu screen of the game, and once you've learned it, you're good. i think it gets in teh way of quickly getting information.

**Comment by kyleshay** [comment]
ah yeah I could go either way on the desc.

was thinking show the tier and value because we show the tier on LO and value below the character tile, so always show both?

mostly this is the important bit 

Screenshot_20201017-223111

**Comment by ryan-rushton** [comment]
If I get rid of the description I would want a custom translation for each of the cool downs to indicate what they are cooling down. This is fine but I try and keep translations to a minimum if I can and use API data to ease the load on the intl guys.

**Comment by nev-r** [comment]
do you mean just grenade/super/melee versions of this? image

**Comment by ryan-rushton** [comment]
grenade, super, melee, rift, barricade and dodge if I was going all out

**Comment by nev-r** [comment]
rift, barricade and dodge sounds lovely. it's brief, yet *more* informative than the game ui,
which doesn't actually tell you what your class ability is
image

**Comment by ryan-rushton** [comment]
Ok, I will go all out then

**Comment by ryan-rushton** [comment]
Ok new iteration is up. Added the description as we get more consistent tooltip placement with it (it's always on the bottom in the character header) and because it might help little lights.

image
image
image

**Review by kyleshay — APPROVED** [review]
🙌 niceee! looks great, awesome work.

**Comment by nev-r** [comment]
i am still against including really boilerplate & wordy destiny help text,
but the formatting on this is a hundred times better and at least the useless content is no longer in the way :+1: :+1:

**Review by bhollis — APPROVED** [review]
Love it! I think I agree with @nev-r that the descriptions aren't super useful, but they're not hurting anyone too badly.

**Review by bhollis — APPROVED** [review]

**Pull request merged**
