### PR TITLE
Support iOS 9

### PR DESCRIPTION
**Pull request by bhollis**
This supports iOS 9's Mobile Safari by polyfilling IndexedDB using WebSQL, and eliminating our use of `Proxy` in `dimDefinitions`.

It works on my 1st-generation Retina iPad but I wouldn't say it's pleasant. It's barely usable. Other devices that were left behind by iOS 10 include the original iPad Mini. I'm torn - on one hand it's not a lot of changes to support them, on the other, even a cheap Android tablet from now would perform better (note that this isn't a DIM-specific issue... *everything* feels unusably slow on that iPad).

### CODE REVIEW

**Comment by edmiller47** [comment]
Does not work at all on my iPad 2 in chrome or safari. No $$ to buy a new device, so I will have to use Ishtar commander as my mobile item manager for the foreseeable future. I love DIM and will continue using it on my desktop, but the bulk of my use is on mobile.

**Comment by delphiactual** [comment]
@edmiller47 this is not pushed yet, unless you built it manually

**Comment by bhollis** [comment]
Here's a more-capable tablet that costs less than the price of a new game: https://smile.amazon.com/Amazon-Fire-7-Inch-Tablet-8GB/dp/B00TSUGXKE

**Comment by edmiller47** [comment]
Will have to see how it goes once pushed.

**Comment by bhollis** [comment]
Here's a video of what it's like. I'm really not sure it's anything other than frustrating:

https://youtu.be/Nf2J2kTQmaA

**Comment by bhollis** [comment]
I think I'm going to go for it. I've noted in the CHANGELOG that the support is experimental and may be removed in the future, but I'd like to get more feedback on it in the wild.

**Comment by edmiller47** [comment]
Doesn't work on iOS 9..3.5 on iPad 2. Gets as far as "Unzipping latest Destiny info...", error occurs, then back to "Unzipping latest Destiny info...".

Thanks for trying. Bye,

**Pull request merged**
