### PR TITLE
Add heroic resistance type search filter

### LINKED ISSUE #3056: Search doesn't work for Heroic Resistance gear
Unable to search for gear that uses "Heroic Resistance" instead of Void, Solar, or Arc. 
It appears to be a very rare type of resistance available to random-rolled gear 

https://i.imgur.com/TKjXuIt.png
https://i.imgur.com/jnibDZl.jpg

### PR DESCRIPTION
**Pull request by kyleshay**
This resolves #3056

### CODE REVIEW

**Comment by kyleshay** [comment]
Should be wired up properly... but we don't have an icon for .is-heroic so it won't show an icon (should I reuse kinetic on armor, does that make sense?) I don't know how heroic resistance works yet.

**Comment by kyleshay** [comment]
Still seems that it's relatively unknown. There are some posts referencing it, but it's all seemingly from people who were able to get the armor (specifically the scatterhorn set) before the Forsaken launch.

Scatterhorn now drops from doing things on the Tangled Shore (spider weekly bounties.) I've gotten a few parts, but none with the Heroic MW.

Curious to see what it does... If we know someone with it we'll have to get them to try out this PR or test it in the beta build. I think we should be pretty good to go though.

**Comment by KsaRedFx** [comment]
If you can get this into the beta, I can test it.

**Comment by KsaRedFx** [comment]
Works great. 

image

**Pull request merged**
