### PR TITLE
Upgrade google analytics and track image fallbacks

### PR DESCRIPTION
**Pull request by bhollis**
What were the other things we wanted to start tracking?

### CODE REVIEW

**Comment by bhollis** [comment]
Ah, it was tracking the CSV downloads

**Comment by SunburnedGoose** [comment]
I said I'll turn it on.  I wrote the code and now I'm getting all your commits.

**Comment by bhollis** [comment]
There wasn't any tracking code I could find, so I added it.

I've also added "pageview" recording for all of our routes, plus the major popups (xur, infuse, about, support, filters, and settings).

**Comment by SunburnedGoose** [comment]
There was in history.  I removed it when we broke our free plan with ~70m hits because we were tracking classified items looking for latest and greatest. How much load will your changes generate?

**Comment by bhollis** [comment]
Interesting, didn't know there was a free plan limit. It's up to you which of these you want to use. The page view tracking should be some small multiplier on our current pageview rate, whatever that is (I don't have access to the dashboard).

Let me make a quick change that'll prevent spam from the fallback thing.

**Comment by bhollis** [comment]
There we go. Now we'll report image fallback at most once per hour per user. That shouldn't break the bank.

**Pull request merged**
