### PR TITLE
Attempt to handle redacted items better

### LINKED ISSUE #888: Trespasser does not show up in DIM
After receiving the new Trespasser I wasn't able to manage the item or even see it.  In the past when destiny has released a new DLC/Expansion, they would show up as generic 'broken' icon.  However, the trespasser is completely invisible to DIM as well as Bungie's gear manager.  The only reason why I'm asking is because Ishtar Commander shows that it's at least taking up inventory space.

Not sure if you want to address this or wait until Bungie updates the armory and gear manager to make it like the rest.

### PR DESCRIPTION
**Pull request by bhollis**
This could fix #888, but I don't have a Tresspasser or any other redacted item, so I can't test. Anyone else want to give it a go, or know the item hash of Tresspasser?

### CODE REVIEW

**Comment by kyleshay** [comment]
Does anyone have a tresspasser @SunburnedGoose ?

**Comment by SunburnedGoose** [comment]
3938709034

**Comment by kyleshay** [comment]
the power of the interwebs! thanks @SunburnedGoose

**Comment by bhollis** [comment]
Well, I faked it by setting some items to use that hash for their definition, and it all worked out. That's not to say that it'd really work - to test 100% I'd need to see the entire item instance JSON for a redacted item, and I don't have any. But I'm decently confident this'll handle redacted items better than we did before, at least.

**Comment by kyleshay** [comment]
merged to dev-- lets see what happens when a user w/ the weapon loads DIM in the new version.

**Comment by Greg117** [comment]
Hey Guys,
Loaded up the dev branch to check this out.  Here is what the trespasser looks like now.

tresspasser

**Comment by Greg117** [comment]
Here is the full object:

{
  "itemHash": 3938709034,
  "bindStatus": 0,
  "isEquipped": false,
  "itemInstanceId": "6917529095685229915",
  "itemLevel": 50,
  "stackSize": 1,
  "qualityLevel": 32,
  "stats": [],
  "primaryStat": {
    "statHash": 2391494160,
    "value": 39,
    "maximumValue": 0,
    "stat": {
      "statHash": 2391494160,
      "statName": "Light",
      "statDescription": "Light increases your level, increasing the damage your abilities deal against higher-level enemies.",
      "icon": "/common/destiny_content/icons/f39a4e811093b7eed989d91a5d2031e2.png",
      "statIdentifier": "STAT_LIGHT",
      "interpolate": false,
      "hash": 2391494160,
      "index": 0,
      "redacted": false
    }
  },
  "canEquip": false,
  "equipRequiredLevel": 40,
  "unlockFlagHashRequiredToEquip": 2166136261,
  "cannotEquipReason": 0,
  "damageType": 0,
  "damageTypeHash": 0,
  "damageTypeNodeIndex": -1,
  "damageTypeStepIndex": -1,
  "progression": {
    "dailyProgress": 0,
    "weeklyProgress": 0,
    "currentProgress": 13994,
    "level": 7,
    "step": 0,
    "progressToNextLevel": 0,
    "nextLevelAt": 2399,
    "progressionHash": 1813264802
  },
  "talentGridHash": 0,
  "nodes": [],
  "useCustomDyes": false,
  "artRegions": {},
  "isEquipment": false,
  "isGridComplete": false,
  "perks": [],
  "location": 1,
  "transferStatus": 0,
  "locked": false,
  "lockable": false,
  "objectives": [],
  "state": 0,
  "bucket": 2465295065
}

**Comment by bhollis** [comment]
Great, it works! Thank you for verifying!

**Pull request merged**
