### PR TITLE
Prevent invalid vendors from crashing DIM via vendor item tooltip

### PR DESCRIPTION
**Pull request by FlaminSarge**
The text '--' is a placeholder and should ideally be replaced with localized 'Unknown' in the future.

This papers over an issue where the 'Compare' view (and presumably the loadout view) would try to show an item from an invalid vendor, and the tooltip for the shopping cart icon on that item crashes DIM.

As an example, the third item here has the bugged tooltip (this view is from using Compare on Xur's current items):
image
I have not been able to locate where this third item comes from, as I do not believe it's from the new Mara vendor.

### CODE REVIEW

**Comment by FlaminSarge** [comment]
When attempting to run DIM locally (even without this change), I'm getting an error that seems to be an incompatibility between ESLint and the version of NodeJS I have installed, which then seems to go into a rebuild loop:
```
PS D:\GitHub\DIM> pnpm start

> dim@8.7.0 start D:\GitHub\DIM
> pnpm run --stream '/^(watch:i18n|devserver)$/'

. devserver$ nodemon --delay 2 --watch config/webpack.ts --watch config/feature-flags.ts --watch config/content-security-policy.ts --watch pnpm-lock.yaml -e ts,js,json,lock --exec "pnpm install --frozen-lockfile --prefer-offline && webpack serve --config ./config/webpack.ts --env=dev || pnpm touch"
. watch:i18n$ nodemon --watch config/i18n.json --exec "pnpm i18n"
. devserver: [nodemon] 3.0.3
. devserver: [nodemon] to restart at any time, enter `rs`
. devserver: [nodemon] watching path(s): config\webpack.ts config\feature-flags.ts config\content-security-policy.ts pnpm-lock.yaml
. devserver: [nodemon] watching extensions: ts,js,json,lock
. devserver: [nodemon] starting `pnpm install --frozen-lockfile --prefer-offline && webpack serve --config ./config/webpack.ts --env=dev || pnpm touch`
. watch:i18n: [nodemon] 3.0.3
. watch:i18n: [nodemon] to restart at any time, enter `rs`
. watch:i18n: [nodemon] watching path(s): config\i18n.json
. watch:i18n: [nodemon] watching extensions: js,mjs,cjs,json
. watch:i18n: [nodemon] starting `pnpm i18n`
. watch:i18n: > dim@8.7.0 i18n D:\GitHub\DIM
. watch:i18n: > i18next-scanner --config ./i18next-scanner.config.cjs
. devserver: Lockfile is up to date, resolution step is skipped
. devserver: Already up to date
. devserver: > dim@8.7.0 install D:\GitHub\DIM
. devserver: > git submodule update --init --recursive
. devserver: > dim@8.7.0 prepare D:\GitHub\DIM
. devserver: > husky
. devserver: Done in 11.3s
. watch:i18n: [nodemon] clean exit - waiting for changes before restart
. devserver: ==> Webpack is starting to build DIM...
. devserver: <i> [webpack-dev-server] Project is running at:
. devserver: <i> [webpack-dev-server] Loopback: https://localhost:8080/, https://[::1]:8080/
. devserver: <i> [webpack-dev-server] Content not from webpack is served from 'D:\GitHub\DIM\public' directory
. devserver: <i> [webpack-dev-server] 404s will fallback to '/index.html'
. devserver: node:internal/process/promises:289
. devserver:             triggerUncaughtException(err, true /* fromPromise */);
. devserver:             ^
. devserver: Error [ERR_REQUIRE_ESM]: require() of ES Module D:\GitHub\DIM\node_modules\.pnpm\eslint-plugin-array-func@5.0.1_eslint@8.56.0\node_modules\eslint-plugin-array-func\index.js from D:\GitHub\DIM\node_modules\.pnpm\@eslint+eslintrc@2.1.4\node_modules\@eslint\eslintrc\dist\eslintrc.cjs not supported.
. devserver: Instead change the require of index.js in D:\GitHub\DIM\node_modules\.pnpm\@eslint+eslintrc@2.1.4\node_modules\@eslint\eslintrc\dist\eslintrc.cjs to a dynamic import() which is available in all CommonJS modules.
. devserver:     at ConfigArrayFactory._loadPlugin (D:\GitHub\DIM\node_modules\.pnpm\@eslint+eslintrc@2.1.4\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3433:42)
. devserver:     at ConfigArrayFactory._loadExtendedPluginConfig (D:\GitHub\DIM\node_modules\.pnpm\@eslint+eslintrc@2.1.4\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3233:29)
. devserver:     at ConfigArrayFactory._loadExtends (D:\GitHub\DIM\node_modules\.pnpm\@eslint+eslintrc@2.1.4\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3154:29)
. devserver:     at ConfigArrayFactory._normalizeObjectConfigDataBody (D:\GitHub\DIM\node_modules\.pnpm\@eslint+eslintrc@2.1.4\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3095:25)
. devserver:     at _normalizeObjectConfigDataBody.next (<anonymous>)
. devserver: Node.js v20.11.0
. devserver: > dim@8.7.0 touch D:\GitHub\DIM
. devserver: > node -e "require('fs').utimes('config/webpack.ts', new Date(), new Date(), () => {})"
. devserver: [nodemon] clean exit - waiting for changes before restart
. devserver: [nodemon] restarting due to changes...
. devserver: [nodemon] starting `pnpm install --frozen-lockfile --prefer-offline && webpack serve --config ./config/webpack.ts --env=dev || pnpm touch`
. devserver: Lockfile is up to date, resolution step is skipped
. devserver: Already up to date
. devserver: > dim@8.7.0 install D:\GitHub\DIM
. devserver: > git submodule update --init --recursive
. devserver: > dim@8.7.0 prepare D:\GitHub\DIM
. devserver: > husky
. devserver: Done in 3.9s
```
I'm going to try these changes on another machine, but if anyone's able to test these as well, much appreciated.

**Comment by bhollis** [comment]
I think I'd like for us to figure out where these items are coming.

**Comment by FlaminSarge** [comment]
> I think I'd like for us to figure out where these items are coming.

Definitely, but in the meantime, preventing the DIM crash seems a bit important, and figuring out where they're coming from can happen after it no longer crashes clients. I'm currently looking into where they come from.

**Comment by FlaminSarge** [comment]
The vendorHash 0 seems to be coming from [vendorItemForDefinitionItem](https://github.com/DestinyItemManager/DIM/blob/master/src/app/vendors/vendor-item.ts#L191) and the vendors causing issues due to lack of 'sales' seem to be various Engram decryption sources e.g. https://data.destinysets.com/i/InventoryItem:2876818003

[getVendorItems](https://github.com/DestinyItemManager/DIM/blob/master/src/app/vendors/d2-vendors.ts#L199) should be passing the vendorHash to vendorItemForDefinitionItem so that these hashes aren't empty ever, even if they should be considered 'definition' items. That, or definition items should not be used for Compare. Or both.

@bhollis What is your preference for this? There are three separate problems at play:
1) Compare/Loadout view tooltips aren't resilient to vendorHash being 0
2) vendorHash is set to 0 from vendorItemForDefinitionItem (potentially not a problem if the other pieces work fine)
3) certain subvendors like 3319692677 (Witch's Armor) don't get considered for compare (and don't even go through the toVendor() call), but others like 4264351379 (Defiant Armor) do, and run into the bug.

I feel that the first issue should be handled either way just in case something else goes wrong. I'm on the fence about the second issue, since DefinitionItems technically don't _need_ a vendorHash but in this case it makes sense to include them. I'm stumped on how the third issue arises.

**Review by nev-r — APPROVED** [review]
this is plenty of troubleshooting info to follow up, and doesn't suppress the weird armor pieces, let's definitely plug the crash here

**Pull request merged**
