### PR TITLE
remove circut-breaker-js

### PR DESCRIPTION
**Pull request by kyleshay**
Looks like it's not currently being used

### CODE REVIEW

**Comment by bhollis** [comment]
Yikes, it should be! It's what we were using to deal with bungie.net issues, at their request.

**Comment by kyleshay** [comment]
looks like it was previously used for DTR, but we should use it for bnet as well? #4177

**Comment by bhollis** [comment]
I thought I'd also used it for b.net, I'll have to check

**Comment by bhollis** [comment]
Hm yeah looking back we just have backoff, not circuit breaking.

**Pull request merged**
