### PR TITLE
Touch a file on webpack devserver crash to force nodemon to restart it

### PR DESCRIPTION
**Pull request by bhollis**
Sometimes webpack crashes, and nodemon won't restart it because no files have changed. This fixes that by touching the webpack config whenever webpack crashes. I used node to do the touch in hopes that it'd work on Windows.

### CODE REVIEW

**Comment by robojumper** [comment]
In my testing (by deleting `express` from `node_modules`) the `touch` part works, but it doesn't cause a restart:

```
    'D:\\DIM\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
$ node -e "require('fs').utimes('config/webpack.ts', new Date(), new Date(), () => {})"
[nodemon] clean exit - waiting for changes before restart
```

**Comment by bhollis** [comment]
I wonder if there's a timing thing

**Comment by bhollis** [comment]
So I tested this out on my side by introducing a crash from notify-webpack-plugin.ts (append to a string until it overflows) and it properly restarts. So the question is, is this a Windows issue? I can boot up my Windows laptop...

**Comment by bhollis** [comment]
OK turns out it was two issues:

1. Windows / Powershell doesn't understand globs correctly so `--watch 'config/*.ts'` didn't work
2. There's some process creation race condition where nodemon would try to restart and do nothing. Adding a delay fixes that.

**Review by robojumper — APPROVED** [review]

**Pull request merged**
