### PR TITLE
Show the well rested buff

### PR DESCRIPTION
**Pull request by bhollis**
screen shot 2018-01-14 at 10 54 18 pm

This implements a check for the "well rested" buff on each character, which grants 3x XP for the first three levels each week. This doesn't come down directly in the API, so I had to reverse-engineer it from level progression, which is actually sort of annoying. I think I did it correctly, but I'm not sure. https://github.com/Bungie-net/api/issues/308 would help us a lot here.

I put the buff indicator in the character tile, but I'm sort of second-guessing myself. The other option is to add it as a synthetic Milestone in the Progress page (or, to only show it next to character tiles on the Progress page). The thinking there is that this is a progress-related buff, and the only reason you'd care about it is to check which character you should play in order to grind Bright Engrams the fastest. Thoughts?

### CODE REVIEW

**Comment by duckmanBR** [comment]
I liked the idea, but not the location. Maybe put it together with the max power/mob/res/rec?

About the calculation, I read/saw somewhere (maybe on youtube) that the well rested is not for the first 3 levels, so if you started the week at 90% of a level, the buff would be up until you reach 90% of the 3rd lvl and not only until you reach the 3rd lvl.

**Comment by wein3967** [comment]
I believe @duckmanBR is correct. The buff is for "3 levels" from your starting point. This ensures that you can get 3 bright engrams under the buff regardless where you start your week.

**Comment by bhollis** [comment]
I think you’re saying different things? I implemented “first three bright engrams”, but @duckmanBR is suggesting it’s “first three full levels worth of XP” which is actually sort of ambiguous since different levels take different amounts of XP. But it would be more fair.

**Comment by duckmanBR** [comment]
https://www.reddit.com/r/DestinyTheGame/comments/78fj4w/the_wellrested_buff_gives_you_3_full_levels_of_xp/
```The buff looks at how much XP is required for 1 level and then multiplies that number by 3. So if it is actually 80,000XP required for a level like people say, then you need to earn 240,000XP in a week to use up the buff fully. It doesn't look at whether you have leveled up 3 times, but instead it looks at if you have reached your maximum allowance of XP for that week.```

**Comment by bhollis** [comment]
Well, dang, that's way simpler than what I built. I'm still not sure how exactly it works, though. If you need 70,000XP for one level, and 80,000XP for the next level, what's "three levels worth of XP"?

**Comment by bhollis** [comment]
Oh, another question - does it apply if you haven't hit level cap??

**Comment by duckmanBR** [comment]
From what I read, no, only after level cap.
That would solve the "how many xp needed" since after the cap all the levels need the same xp amount.

**Comment by duckmanBR** [comment]
We should also check if people at lvl20 but don't have CoO are receiving the buff...

**Comment by SunburnedGoose** [comment]
160k xp for each level atm.

**Comment by bhollis** [comment]
It's not standardized like that, at least according to the manifest. It steps up for the first 11 Legend levels.

**Comment by bhollis** [comment]
OK, I think I've fixed the logic.

As far as the display, I thought it was too noisy to put it in the character tile everywhere. Since this is really part of the decision of "what character should I grind on" I decided to make it a nice clear "synthetic milestone":

screen shot 2018-01-20 at 12 34 00 pm

**Comment by bhollis** [comment]
screen shot 2018-01-21 at 8 26 31 pm

For the numbers fans, I've added the actual XP values.

**Pull request merged**
