### PR TITLE
Exclude items in loadout builder

### PR DESCRIPTION
**Pull request by ericnelson0**
Issue #646

Looks like:
example_exclude

### CODE REVIEW

**Comment by bhollis** [comment]
Neat!

In the old infusion calculator, we did this by just shift-clicking items. Maybe we could do that rather than having a bunch of big empty buckets?

**Comment by ericnelson0** [comment]
I think i saw that you recommended that in a different thread and I like the idea, but where would you show which items are excluded and how would you undo the exclude if you needed to?

**Comment by bhollis** [comment]
You could still add them to a section and maybe click to remove them. It just wouldn't take up space by default.

I do like that these work with drag and drop, though - especially given the "pinning" functionality that's also drag and drop.

**Comment by ericnelson0** [comment]
New look:

example_exclude2

**Comment by kyleshay** [comment]
Love the look of one bucket for all exclusions!

**Comment by bhollis** [comment]
That's neat!

**Pull request merged**
