### PR TITLE
Spinning logo gear!

### PR DESCRIPTION
**Pull request by chrisfried**
[Video](https://drive.google.com/file/d/0B11-fu6tHAsraGcyRV8zQUVzTFU/view?usp=sharing)

### CODE REVIEW

**Comment by lukefx** [comment]
haha nice! :+1: :shipit:

**Comment by SunburnedGoose** [comment]
whyuno spin all the gears?  Those top gears need love.

**Comment by chrisfried** [comment]
The top gears are a myth.

**Comment by chrisfried** [comment]
[Top gear.](https://drive.google.com/file/d/0B11-fu6tHAsraVVHZnBmbzdRd0U/view?usp=sharing)

**Comment by chrisfried** [comment]
[Humbug.](https://github.com/DestinyItemManager/DIM/pull/249)

**Comment by bhollis** [comment]
Hi Chris, thanks for the PR. I think we're going to try and keep there from being too much going on in the UI for now, and we've already got the spinning reload icon. Don't hesitate to toss out more cool ideas, though!

**Pull request closed without merging**
