### PR TITLE
Remove extra trailing commas

### PR DESCRIPTION
**Pull request by delphiactual**

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
We might need to relax this rule as trailing commas are useful and I think JavaScript handles them well.

**Comment by SunburnedGoose** [comment]
Any thoughts here @bhollis or @kyleshay?

**Comment by delphiactual** [comment]
@SunburnedGoose I'm fine with relaxing the trailing rule, just saw violations and decided to do something useful and mind-numbingly boring at the same-time...

**Comment by delphiactual** [comment]
Closing this as it is not specified in our eslintrc so CodeClimate just assumed... Fixed in #1441

**Comment by SunburnedGoose** [comment]
only-multiline seems permissible.

**Comment by delphiactual** [comment]
adjusted in #1441

**Pull request closed without merging**
