### PR TITLE
Default to current store in LO when loading a global loadout

### LINKED ISSUE #7529: "Optimize Armor" in Loadout details for global loadout opens broken Loadout Optimizer
### DIM Version

Version 6.96.0.1001045 (beta), built on 21.12.2021, 23:03:08

### Browser Details

Firefox 95.0.2

### OS Details

Windows 10 

### Describe the bug

I created a loadout, but accidentally created it as a global loadout (not tied to a particular class) without realizing. When I clicked "Optimize Armor" in the Loadout Drawer header or the Loadouts page, the Loadout Optimizer instance reported 0 sets found and said "No builds found. This is typically because DIM could not assign all selected mods to any armor set.", which greatly confused me. However, this is because LO just doesn't choose a character to operate on and considers 0 armor pieces total.

Not sure if the fix is just to remove that button from global loadouts.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by bhollis**
Fixes #7529

### CODE REVIEW

**Review by nev-r — APPROVED** [review]

**Comment by nev-r** [comment]
technically this fixes but it let me really easily accidentally pin titan arms into a warlock optimizer
maybe `classType === unknown` should first check for uniformity of non-unknown class items, like
```
includedclasses = new Set(loadoutItems.map(i=>i.class).filter(c=>c!==unknown));
if (includedclasses.size===1) {
// select a char that's includedclasses.values.next.value
```

**Comment by bhollis** [comment]
Yeah, that makes sense. The weird multi class loadouts really mess things up.

**Comment by nev-r** [comment]
works better!
- i wonder if we should limit includedClasses to items marked for equipping
- testing this brings up some interesting weird cases that deserve answering eventually
  - should loadout editor sheet have an "optimize armor"  button when it contains no armor? (does rn)
  - actually *should it even have one when it's set to global?*
  - does editor sheet know which char's dropdown it was spawned from? shouldn't that class be carried over to LO if someone clicks Optimize on a global loadout?

i'm really coming away with the optimizer button shouldn't be there for global loadouts, and New Loadout sheet should be classed based on the dropdown that was used, and also maybe multi class loadouts were a mistake and should die before we dig ourselves even deeper with fashion loadouts etc

**Comment by bhollis** [comment]
> i wonder if we should limit includedClasses to items marked for equipping

Yeah, I thought that, but then figured it probably doesn't matter much and this makes it more automatic even if the items aren't equipped.

> should loadout editor sheet have an "optimize armor" button when it contains no armor? (does rn)

My thought was that if you're creating a loadout and want armor, you should go to the LO to do it rather than picking piece by piece.

> actually should it even have one when it's set to global?

Probably not!

> does editor sheet know which char's dropdown it was spawned from?

No, that's something I want to change really soon

**Review by ryan-rushton — APPROVED** [review]

**Pull request merged**
