### PR TITLE
Move away from angular-hotkeys

### PR DESCRIPTION
**Pull request by bhollis**
I'm about halfway through this. Not super satisfied with `react-hotkeys`, I might just write my own thing.

* Cheat sheet doesn't work well (doesn't show all the keys!)
* esc from search field doesn't work right
* focusing search field with "f" also inserts an "f" in the search field...

### CODE REVIEW

**Comment by delphiactual** [comment]
> I'm about halfway through this. Not super satisfied with `react-hotkeys`, I might just write my own thing.
> 
> * Cheat sheet doesn't work well (doesn't show all the keys!)

https://github.com/greena13/react-hotkeys/pull/142
Fix mentioned does not appear to be in v2.0.0-pre4

> * esc from search field doesn't work right
> * focusing search field with "f" also inserts an "f" in the search field...

**Comment by bhollis** [comment]
I went ahead and just directly ported angular-hotkeys to our own React implementation, since it's much simpler. There's ways to improve this but now it works.

That said, who decided to name a keyboard shortcut handling library "mousetrap"??

**Comment by delphiactual** [comment]
`Esc` does not dismiss the cheatsheet

**Comment by bhollis** [comment]
True, question mark does.

**Pull request merged**
