### PR TITLE
Remove rating number

### PR DESCRIPTION
**Pull request by bhollis**
Alternative to https://github.com/DestinyItemManager/DIM/pull/3376. Just the icon doesn't seem nearly as clear to me but it's an option.

screen shot 2018-11-29 at 8 55 30 pm

### CODE REVIEW

**Comment by inexorableAce** [comment]
Just the icon is less accessible as well. If we were to do just icons I’d say ditch the stars and doo thumbs up and thumbs downs

**Comment by kyleshay** [comment]
Hmmm -- what about:

| Symbol | Rating |
| ------------- | ------------- |
| 👎| <= 4.0 |
| 👍| <= 4.6 |
| 🙌or ⭐️| <= 5.0 |

Also, it may help if the icon size matches the power level/burn icon (now that there is space for it without the numbers)

**Comment by inexorableAce** [comment]
4.0 seems too high to be bad...

**Comment by kyleshay** [comment]
ah sure, or whatever we plan the distribution to be.

Just the fact that thumbs up and down would be fine if we can still distinguish them from the best

**Comment by bhollis** [comment]
screen shot 2018-12-01 at 11 59 06 am

I don't think the thumbs icons are easy to see. BTW this is with a split of >4.8 for star, 5.0 for orange star, and 4.0 for thumbs up.

**Comment by bhollis** [comment]
screen shot 2018-12-01 at 12 01 46 pm

For reference here are the original stars, but larger.

**Comment by inexorableAce** [comment]
yeah personally I don't think any scenario where every item has a rating or rating icon is scannable. scannability comes from difference, so if the goal is to have the top layer be for quick scannability i'd say set a good threshold and ONLY have an icon for that threshold, everything else stays empty. 

That would allow you to quickly pick out what is "good". Otherwise it's all a bit too much to scan. 

on the other end only using numbers  #3376 reduces scannability BUT lets users have the data up front and make a better decision albeit a slower one.

**Comment by bhollis** [comment]
screen shot 2018-12-02 at 3 07 06 pm

Here's another stab. It uses red and green arrows for "good" (4.7+) and "bad" (<4.0), omits the range 4.0-4.6 (no icon at all). 5.0 still gets a star, but it's blue because I didn't want it to be reddish.

It's a bit weird having the hole where there's no icon, since it could mean the item has no rating or that it's so-so. An alternative is to use a grey bar:

screen shot 2018-12-02 at 3 11 57 pm

To be honest the whole thing feels pretty busy to me, though, compared to just having the numbers.

**Comment by delphiactual** [comment]
Closes #3374

**Comment by philkernick** [comment]
Simple is better.  From a user perspective a quick scan should tell me "is this a good weapon".  The more complex we make the graphical encoding the more going back to a number looks better as otherwise we have to explain the mapping.

So I'd go with a black thumbs up for 4.0 or more, and a gold thumbs up for 5.0.

That answers the question, is simple, and doesn't stop people using the rating: filter if they really want to know more.

**Comment by bhollis** [comment]
screen shot 2018-12-03 at 11 05 16 pm

@inexorableAce provided different colors. These are pretty scannable.

@philkernick I agree on simplicity, though there are some states that probably need to be distinguished. "not rated" is different from "not particularly good". Also, I've tried the thumbs icon a bunch and it never looks good.

**Comment by inexorableAce** [comment]
Thumbs are actually harder to distinguish at that size we did try them, and in essence they are just arrows which are easier to distinguish. 

Getting colors that work is also an ordeal, they can’t be too bright or they blend into the white, can’t be too close to the elemental icons or you lose them next to those and they have to work over the normal and masterwork colorings.

**Comment by kyleshay** [comment]
For contrast, what about making the border background black, text white & bold? With that configured I can read it from my laptop from a much further distance. Would having a flatter black background help for icons & scanability?

screen shot 2018-12-06 at 8 08 30 am

**Comment by inexorableAce** [comment]
Then you just have the same problem in reverse really can’t use anything too dark. Also dark text over light bg is easier to read, and the lighter borders crest co trust with our dark bg.

**Comment by philkernick** [comment]
What about putting a coloured triangle in the corner - same as we used to do for the elemental burn.

**Comment by inexorableAce** [comment]
Both corners are covered already. Season icon in top left, circle icon in the top right for new items.

**Comment by philkernick** [comment]
I was thing in the tile area at the bottom. The same place the rating currently is.

**Comment by bhollis** [comment]
OK, this is going into Beta. Let's see how people like it.

**Pull request merged**
