### PR TITLE
Add is:infusable search

### PR DESCRIPTION
**Pull request by bhollis**
I was sort of surprised this wasn't already there.

### CODE REVIEW

**Comment by bhollis** [comment]
Oh, and here's another idea: stat type searches. So I added `is:intellect`, `is:discipline`, `is:strength`. Helpful for finding exactly the armor stat mix you're looking for.

**Comment by cotto** [comment]
Both features worked as expected for me.  I can see using this in the future.

**Comment by bhollis** [comment]
I have plans (that may not work) to get the localized manifest in there.
It's tough because there are many places in the code that depend on the
English names of things.

Translating DIM UI would be easier mechanically, but it requires a ton of
work, and we don't have the time or volunteers to translate every
new string before every release. So DIM would always be half-English, which
I assume would be weird?

**Comment by SunburnedGoose** [comment]
A big part of this would be the refactoring of English names to buckethashes with a const?

**Comment by bhollis** [comment]
Yeah, that helps (I wouldn't use bucketHashes, I'd use the non-display but readable bucketIdentifier) but we also look at perk node names, item class names, etc. Most of those can be replaced with hashes or other stable identifiers, but that makes the code way way harder to understand.

**Comment by bhollis** [comment]
Not sure how these comments ended up here, rather than on the localization thread. Regardless, I know what needs to be done to at least get the manifest localized, so we can track that when it comes up.

**Pull request merged**
