### PR TITLE
Packtracker debugging

### PR DESCRIPTION
**Pull request by delphiactual**
it is not uploading the HEAD results to packtracker.io

### CODE REVIEW

**Comment by bhollis** [comment]
In the build it says it has uploaded. I don’t see anything in packtracker’s dashboard though - just the one I uploaded manually.

**Comment by bhollis** [comment]
Perhaps it wants the regular branch and not the PR branch?

**Comment by bhollis** [comment]
I think it’s close but something is still wrong: https://docs.packtracker.io/github-pull-request-checks/forked-repositories

**Comment by bhollis** [comment]
Actually it says it’s waiting for the base commut report, so maybe there was something missing on a master build?

**Comment by bhollis** [comment]
The travis_pull_request variable will get set to “false” when it’s not a PR. 

I think we fixed it but just need to get the fix merged before comparisons will work.

**Comment by delphiactual** [comment]
```
TRAVIS_BRANCH:  master
TRAVIS_PULL_REQUEST_BRANCH:  packtrack-test
TRAVIS_PULL_REQUEST_SHA:  00f74cc262c0b5420d6f3fd1515c41c6b3b8bdf6
TRAVIS_COMMIT:  a12b33d0679f00336990a0cc5a2f7b030d815a79
```

**Pull request merged**
