### PR TITLE
Vendors Revamp

### LINKED ISSUE #939: Decouple Vendors from character loading.
During the ROI maintenance window, the API was available for items, but DIM couldn't load due to Vendors being in maintenance still.

We need to decouple vendors and make that feature one that has it's own loading mechanism to avoid this blocking.

screen shot 2016-09-19 at 1 44 42 pm

### PR DESCRIPTION
**Pull request by bhollis**
This is pretty much a complete rework of how we do vendors, aimed at reducing API traffic and making vendors easier to use.

Unfortunately, right now the vendors API has disappeared again, so the views I could have shown yesterday are reduced to just Eververse. We should probably wait for the API to come back before relaunching this.

screen shot 2016-10-18 at 8 50 30 pm

Here's what's different:

1. We don't call the API as much:
  1. We don't load vendors we won't show. "Vendors" that are really just descriptions of what packages could produce are now ignored. This cuts out hundreds of API calls.
  2. We cache responses in IndexedDB, until the time when they say they'll refresh. This can cache responses for up to a week, making subsequent loads lightning-fast.
  4. It's worth noting that I still have to call the vendor API for all your characters and merge them, so I know what all is available. For example, I have the bonus swords from the "link a friend" promo on one character, but not the others.
3. Vendors are no longer loaded as part of loading character inventory - they're their own separate asynchronous process that doesn't block the main load. They still get kicked off after the stores load so they're ready to go.
2. Each vendor's inventory is merged across characters, rather than being per-character. This reduces a ton of duplication (better for users and for performance). I've allowed Hunter/Warlock/Titan Vanguard to be their own entries again rather than special-casing them - I actually think this works nicely.
3. Vendor information is completely divorced from characters/stores and is entirely in its own service now, rather than being involved with `dimStoreService`. Each vendor presents a processed view of inventory across all characters.
3. Rather than just "armor" and "weapons", we now use the actual categories that are displayed in the game to group items (for example "Iron Banner Rank 3").
4. Consumables and Bounties have been added to the views. You can now use the vendors tab to check out all the bounties available!
3. We show all costs for an item, not just the first. This usually manifests as showing the glimmer cost where we didn't before.
4. The list of characters who have access to an item are now shown in the detail popup.
5. The vendor UI directly watches the map of vendors, rather than working via notification. This works nicely and avoids a lot of controller logic.

There are some tradeoffs that I'd love some feedback on:

1. With the items consolidated, it's a lot easier to browse the vendors. However, it's harder to tell which character something is available on - for example, it may be lit up (unlocked) but only one character has reached the rank to actually purchase it. I attempted to solve this by adding the unlock info to the move popup, but it is certainly less glance-able.
2. It's also somewhat more difficult to pick apart the Hunter armor from the Warlock armor, etc. Searching "is:hunter" still works, but otherwise I'm not sure what to do. I could invent new categories but that could be a pain.
2. Now that I'm aggressively caching vendors, the "unlocked" data itself is potentially stale. This doesn't happen often, but it can happen when, for example, you gain a rank in a faction. We won't light up that row of items until the week rolls over, because we've already cached it. The alternatives are:
  1. Stop showing locked/unlocked anymore.
  2. Refresh vendors all the time (or at least when you go to the vendors page) which is still hard on the API.
  3. Just leave it and deal with it being out of sync with the game.

Here's stuff I still want to do:

1. [x] I may have fixed the Loadout Builder, but that code is difficult for me to understand, and I don't have the full vendors responses, so I can't be sure.
2. [x] I'd like to consolidate the currencies per vendor into a little bar instead of re-stating how much you have under each item.
3. [ ] It'd be nice to make better use of the space - one line per category can be thin sometimes. I'm not sure what a better arrangement would be.
4. [ ] Switch the Xur service to be implemented on top of the new vendor service.
5. [ ] Fill in more error handling.
6. [x] Show vendor loading progress on main page.

This fixes #939 and #904.

### CODE REVIEW

**Comment by kyleshay** [comment]
Killed it! 

> Consumables and Bounties have been added to the views. You can now use the vendors tab to check out all the bounties available!

Really cool! I can foresee some features being added in around that. (Just brainstorming) Maybe a listener that watches for your favorite bounties that you know you can knock out quick. Alerts you when it's active so you can decide to login to play or not. ... Maybe we should have some sort of 'notifications' menu, tooltips are a bit aggressive for some actions we have now.

> With the items consolidated, it's a lot easier to browse the vendors. However, it's harder to tell which character something is available on - for example, it may be lit up (unlocked) but only one character has reached the rank to actually purchase it. I attempted to solve this by adding the unlock info to the move popup, but it is certainly less glance-able.

I'm fine with that. You'll probably be opening the popup anyway to see the item details. I like this solution more than showing the same item up to 3 times.

> It's also somewhat more difficult to pick apart the Hunter armor from the Warlock armor, etc. Searching "is:hunter" still works, but otherwise I'm not sure what to do. I could invent new categories but that could be a pain.

Maybe we could be a bit more clear on our move popup to show what class it's for? Another option is a very small hover tooltip. We've been adverse to them before, but if it **only** showed `name` and `class`... that could actually be quite nice for things at-a-glance.

> Now that I'm aggressively caching vendors, the "unlocked" data itself is potentially stale. This doesn't happen often, but it can happen when, for example, you gain a rank in a faction. We won't light up that row of items until the week rolls over, because we've already cached it. The alternatives are: [...]

It's a bit edge-case, but what if we keep track of the faction ranks, and if one increases by more than 1, we break the cache? We could be really fancy and detect the faction and break the cache for just that one, but I'm fine with resetting the whole thing.

>  It'd be nice to make better use of the space - one line per category can be thin sometimes. I'm not sure what a better arrangement would be.

Lets use masonry to make it look like pinterest.... 💁 

I don't know :/ Maybe grouping similar smaller vendors... Might be easier to think about when we have the vendor API back up again.

**Comment by bhollis** [comment]
Faction rank is only one thing that changes unlock status - there are a lot
of others (for example, getting a shader or exotic unlocks it in the
collection)

**Comment by JakeWhitaker** [comment]
> With the items consolidated, it's a lot easier to browse the vendors. However, it's harder to tell which character something is available on - for example, it may be lit up (unlocked) but only one character has reached the rank to actually purchase it. I attempted to solve this by adding the unlock info to the move popup, but it is certainly less glance-able.

> It's also somewhat more difficult to pick apart the Hunter armor from the Warlock armor, etc. Searching "is:hunter" still works, but otherwise I'm not sure what to do. I could invent new categories but that could be a pain.

Would it be possible to select a character to view vendors? Similar to how #1046 plans to handle it?

> Now that I'm aggressively caching vendors, the "unlocked" data itself is potentially stale. This doesn't happen often, but it can happen when, for example, you gain a rank in a faction. We won't light up that row of items until the week rolls over, because we've already cached it. The alternatives are: [...]

Force refresh the cache?

**Comment by ericnelson0** [comment]
Wow! Great work man.

I can't wait for the vendors API to come back up to give some more detailed feedback.

A few observations upfront though:

1. How does this affect the "include vendors" button in the loadout builder (maybe this is what one of your remaining tasks is referencing?)

2. Bounties on different characters -- Does the "available on" in the move popup work for these too?

3. Maybe we need an option that only shows gear that is available on a specific character?
For example I'm on my hunter and I only want to see gear that I can buy on that character.

4. Is there any ordering to the vendors (Xur, Iron Banner on top)? This is something I've been wanting to do with the previous implementation but didn't get around to.

5. Not sure how to handle the stale-ness of the availability of items. Maybe a manual refresh? But that has a potential to be abused.

Being able to see bounties/everything is going to be awesome, in addition to the speed up and the ability to see all the costs instead of the first cost only.

**Comment by bhollis** [comment]
> How does this affect the "include vendors" button in the loadout builder (maybe this is what one of your remaining tasks is referencing?)

I think it works still, but I'll have to see.

> Bounties on different characters -- Does the "available on" in the move popup work for these too?

Yup.

> Maybe we need an option that only shows gear that is available on a specific character?
For example I'm on my hunter and I only want to see gear that I can buy on that character.

That's one way to do it. Basically just hide items that aren't usable by a certain class. I'll have to think about where to put that UI.

> Is there any ordering to the vendors (Xur, Iron Banner on top)? This is something I've been wanting to do with the previous implementation but didn't get around to.

"Event" vendors are always on top. Otherwise, it's ordered by the (dubious) ordering in the manifest - first by "map area" then using a vendor order that's provided.

> Not sure how to handle the stale-ness of the availability of items. Maybe a manual refresh? But that has a potential to be abused.

Yeah, my only problem with a force refresh button is when should it be used? People might think it's the only way to get updated vendors, for example. All it'll update is unlock status or potentially some specially available items, but otherwise we're really good at updating only at the right time.

**Comment by bhollis** [comment]
OK, vendors API is back up, here's what it looks like:

screen shot 2016-10-19 at 10 58 28 pm
screen shot 2016-10-19 at 10 58 55 pm
screen shot 2016-10-19 at 10 59 10 pm

Yes, the Iron Banner bounties show up as available... that's just what the API is saying!

@ericnelson0 looks like I didn't fix the loadout builder. I don't see vendor items included when I check that box. Not sure why they aren't included. I have a lot of trouble navigating that code - anywhere I should be looking at?

**Comment by bhollis** [comment]
OK, I think I've fixed loadout builder. Weirdly, it looks like the vendors API is only returning Titan gear - this happened before, too, so I've asked about it on the forum: https://www.bungie.net/en/Forums/Post/216019253?sort=0&page=0&path=1

**Comment by ericnelson0** [comment]
@bhollis I just saw this, but it looks like you found the right place.

**Comment by kyleshay** [comment]
> Switch the Xur service to be implemented on top of the new vendor service.

Could we just keep Xur in this new tab, instead of being duplicated in the other?

**Comment by bhollis** [comment]
The only reason I like Xur in his own thing is I forget when he's around...

**Comment by bhollis** [comment]
Looks like Vendors is down again. I'll keep trucking on this, but it's difficult.

My vote is actually to ship this pretty much as-is, and then address a lot of my next steps in subsequent PRs. I think this is enough to be usable and I'd rather get people the basic ability and polish later.

**Comment by JakeWhitaker** [comment]
If you want I could try to mock up a better use of the space. A few questions I have; Do all vendors need to be laid out the same way?; Is it possible to put prices and rank required under the detailed view?; Is price beneath required?

**Comment by bhollis** [comment]
> If you want I could try to mock up a better use of the space.

That'd be great! I've been thinking of just doing a 2-column thing...

> Do all vendors need to be laid out the same way?

No, but if we have different layouts we should have a way to figure out which one to use based on manifest/API data, rather than hardcoded lists.

> Is it possible to put prices and rank required under the detailed view? Is price beneath required?

I don't know what you mean by "rank required" - we don't have that data today, though I could probably figure it out from the manifest data. Not all of them are gated by faction rank either. I could put prices in the move popup, but I actually like seeing them price for each item, so we should show it *somewhere*. I'll be moving the amount of currency you have to a per-vendor display so we don't repeat them as much.

**Comment by delphiactual** [comment]
@bhollis 
Exotic Weapons and Exotic Armor are sorted differently

Armor is shown as Y2 and then Y1
Weapons show Y1 then Y2.

**Comment by JakeWhitaker** [comment]
How do you feel about something along these lines? I grouped items by price so you only have to show it once. Also, in general I think the space between items could be tightened up from the views you showed, including the bounties and shaders. Organized weapons by primary special heavy, and showed armor by how it would appear in inventory. 

> I don't know what you mean by "rank required" 

I literally just meant the section header that said rank 1, rank2, rank 3.

0015 vendor mock

**Comment by bhollis** [comment]
Those headers ("Rank 1", etc) are the categories the vendors use. I'd like to keep them if possible - they can be interesting.

**Comment by bhollis** [comment]
OK, I made some tweaks. Smaller category headers, moved currencies to a little bar per-vendor instead of under each item. This lets me make everything more dense. Here's a screenshot where I fake some more complicated vendors, since the API isn't giving me much to work with.

screen shot 2016-10-22 at 9 18 32 pm

I'll keep experimenting with denser layouts once the API is back and I see what it really looks like.

**Comment by bhollis** [comment]
Let's go!

**Comment by JakeWhitaker** [comment]
http://imgur.com/47Q62Mi.gif
http://imgur.com/Nk1vmTF.gif
Realized I had gone on the assumption that only 1 character would be displayed at once since Titan armor was the only thing shown. Here's a possible use of space to view 3 characters at once. Also, in-game Tess is the only vendor with a distinct store. Just an idea to reflect that in DIM

**Comment by kyleshay** [comment]
we could also make the vendor page wider

**Comment by JakeWhitaker** [comment]
The Vendor function was up yesterday so I checked it out. Just a few comments I have about the layout in the current build. 

There was a lot of scrolling. Like the Armor and Weapons was a long long list. I think, @kyleshay said, a wider page would allow you to group similar vendors together (e.g. the three vanguard representatives, the crucible and crucible armor reps, perhaps petra and variks?

The tabs at the top(armor/weapons, ships/vehicles, etc.) don't seem to really narrow things down intuitively. 99% of time will probably be spent on Weapons and armor, which is also the longest of the lists. Perhaps separating them into (Weapons||Armor||Consumables||Bounties||Kiosk) with Kiosk having subcatagories for (Shader||Emblem||Ship||Sparrow||Emote||[Mask/Holiday?]) This would cut down on the scrolling, and for the individual kiosks you could have the actual kiosk components at the top, and then vendors selling items that fit in those kiosks below
e.g. Shaders
Kiosk Items list
.
.
.
Kiosk items list end
Petra Shaders
Eris Shader(if she still sells them?)
Eva Levante Shaders
etc...

Finally I think that the compressed view looks really good. The tighter distance between objects feels more like DIM than the original view did to me.

**Comment by delphiactual** [comment]
Vendors is up, it's crashing DIM...

**Comment by delphiactual** [comment]
~800 errors all basically the same.
```
dimStoreService.factory.js?v=$DIM_VERSION:774 Error building stats for Gjallarwing Object {itemHash: 201885899, bindStatus: 0, isEquipped: false, itemInstanceId: "0", itemLevel: 0…} Object {itemHash: 201885899, itemName: "Gjallarwing", itemDescription: "Destruction in motion.↵↵This item is nonreturnable.", icon: "/common/destiny_content/icons/45d49e8050b1414ab570265e43c5dd54.jpg", hasIcon: true…} TypeError: Cannot read property 'stat' of undefined(…)
```

**Comment by bhollis** [comment]
Please file bugs/suggestions in a new issue!

**Pull request merged**
