### PR TITLE
Postmaster on top

### PR DESCRIPTION
**Pull request by bhollis**
Now that Inventory is rendered in React, we can have much more complex logic for how to display (and what to display) without necessarily taking a performance hit for doing so. One of the ones I've been most excited about is moving the postmaster to the top of the screen, while being able to completely hide it (and any other inventory buckets) when empty. As a bonus, we can inline the "pull" button right there on the screen:

screen shot 2018-09-13 at 11 44 08 pm

The "special orders" and "messages" buckets are automatically hidden because they don't have anything present on any character.

Note that just like in the loadout popup, the button only shows the number of items that we could successfully move, not the count of all items in the postmaster.

### CODE REVIEW

**Comment by duckmanBR** [comment]
> while being able to completely hide it (and any other inventory buckets) when empty

why didn't you merged it yet?!?!?! :rofl:

**Comment by jbccollins** [comment]
Any chance this could be toggled? Like giving an option to have the postmaster either at the top or at the bottom?

**Comment by bhollis** [comment]
You can always click the title to collapse the postmaster

**Comment by jbccollins** [comment]
I'm aware. I just prefer having the postmaster section at the bottom after having gotten used to it there over the last three years. I'd be willing to write the change if y'all would be cool with merging it.

**Comment by bhollis** [comment]
Thanks, but I don’t think we want to make this configurable.

**Comment by jbccollins** [comment]
☹️

**Pull request merged**
