### PR TITLE
Fix clickoutside area

### PR DESCRIPTION
**Pull request by bhollis**
The click-outside area wasn't always taking the full height of the page, which made it hard to close the item popup when the organizer was filtered to only a couple items.

I also made the toolbar shed tips and buttons at different breakpoints so narrower screens work OK.

### CODE REVIEW

**Comment by sundevour** [comment]
i'm not sure this is having the desired effect??
image

**Comment by bhollis** [comment]
Hmm I'll take a look, maybe I forgot to commit something.

**Comment by bhollis** [comment]
@sundevour I think it's working now

**Comment by sundevour** [comment]
looks good. clicks anywhere now dismiss.

**Pull request merged**
