### PR TITLE
adjusted max statcks

### PR DESCRIPTION
**Pull request by lowPolySkeleton**
added max stack Polaroid colors that were enabled in #9655 and general var clean up in the theme

### CODE REVIEW

**Comment by guise** [comment]
Just wanted to double-check if it was intentional to make the capped items the same colour as masterworked? 

I went with a different 'warning'(ish) tint in the other themes, but I don't see anything wrong with re-using the masterwork tint since they're clearly differentiated from regular items. Assuming this would be to minimise on the number of different colours going on

**Review by guise — APPROVED** [review]

**Comment by lowPolySkeleton** [comment]
> Just wanted to double-check if it was intentional to make the capped items the same colour as masterworked?

Yep, I played with some other things but since it's the DIM dark theme and the Original theme has theme them about the same color as MW I just kept it the same. I thought about going with a more in-game style where just the text changes colors but it didn't feel like enough.

**Comment by robojumper** [comment]
Is this special "capped" style actually something we should keep in general? Before I looked at them closer with the themes I did not know that it's specifically for items with a maximum stack that won't open another stack, and I think we discussed exposing all that info on the item tooltip / with search filters (info being "max stack size", "can this be vaulted", "does this open multiple stacks", "does this overflow to the postmaster").

**Comment by robojumper** [comment]
> The game marks them, so we probably should too. If nothing else, just to keep them consistent with the game.

This is not true. The game makes no visual distinction between a full stack of items and a full stack of items *that won't allow another stack to open*:
grafik
grafik

**Comment by lowPolySkeleton** [comment]
> This is not true. The game makes no visual distinction between a full stack of items and 

Must have misread your initial message. I assumed we just marked max-stacks which I think is useful. We probably don't need 2 states for that.

**Review by bhollis — APPROVED** [review]

**Pull request merged**
