### PR TITLE
Wire up weapon type names and include them in popup titles.

### PR DESCRIPTION
**Pull request by bhollis**
OK, one more change to the item popup. I often can't tell what type a weapon is just by its picture - is that a sidearm or a shotgun? A pulse rifle or an auto rifle? This change adds the weapon type to the title. To protect against the title wrapping, I've used CSS to make it show ellipsis when it's too long - in most cases, you can still tell the weapon type even with just a few characters.

image
image

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Conflicts.  Can you resolve?

**Comment by bhollis** [comment]
Resolved.

**Comment by bhollis** [comment]
:zap:

**Comment by SunburnedGoose** [comment]
The type of weapon in the popup when you expand the details seems to be very close to the stats.  Almost to the point where they touch.  

screen shot 2016-02-15 at 3 40 02 pm

**Comment by bhollis** [comment]
My bad, pushed a fix.

**Pull request merged**
