### PR TITLE
Ornament overrides

### PR DESCRIPTION
**Pull request by bhollis**
This is more what I had in mind for showing ornaments in loadouts - instead of plumbing through a special display override, we can leverage SocketOverrides to create a new version of the item that has the ornament applied. This also sets us up for the future where we may have other socket overrides for items, like manually placed mods or perk selections. As a bonus, the item popup shows the ornament socketed as well: 

Screen Shot 2022-02-19 at 2 28 51 PM

### CODE REVIEW

**Review by robojumper — COMMENTED** [review]
Uh
grafik


Otherwise I like it, although `applySocketOverrides` makes me feel a bit uneasy because lower-level code that actually cares about the existing item then has to always check `actuallyPlugged || plugged`.

The "Apply Perks" name is obviously confusing. Would be nice to have some indication on the square sockets as to which changes "Apply Perks" would be performing, because it'd be plausible that this could also preview the loadout mods from the mod assignment. Feels like there's a bit of a connection to #7377 here.

**Review by ryan-rushton — APPROVED** [review]
Looks good, my first instinct was to use overrides too but I was trying to restrict it to the loadout items more directly.

**Comment by ryan-rushton** [comment]
@robojumper how do you get into that state? I can't seem to reproduce it.

**Comment by bhollis** [comment]
@robojumper good catch, fixed that up. I agree on the "Apply Perks" bit, I think that needs more work separately as part of #7377.

**Pull request merged**
