### PR TITLE
Fix mods and plugsets on collections page

### PR DESCRIPTION
**Pull request by bhollis**
This fixes the collections page post-Shadowkeep:

1. Mods light up when you own them again, even if they're just an unlock.
2. We don't show a ton of useless plugsets in collections.
3. Added Ghost Projections to collections.

### CODE REVIEW

**Comment by sundevour** [comment]
due to character-level artifact mod availability, some of these are "wrong" in that they are greyed out but some of my characters have earned them

it would be extremely cool to separate consumable and reapplyable mods into 2 sections, it's a mishmash that's not extremely useful rn

**Comment by sundevour** [comment]
everything else is generally right though about the earnedness data

**Comment by bhollis** [comment]
Gotcha - I don't really have a clear sense of how this works, I'm mostly trying to just hook them up. It doesn't help that plugSets don't have any display info.

What's the rule for distinguishing consumable from reusable mods?

**Comment by sundevour** [comment]
armor 2.0 mods inventory items have
uiItemDisplayStyle: ui_display_style_energy_mod
plug.energyCost
plug.onActionRecreateSelf:false

**Comment by bhollis** [comment]
Let me poke at that in a followup

**Pull request merged**
