### PR TITLE
added hound config

### PR DESCRIPTION
**Pull request by kyleshay**
created houndci config file.

https://houndci.com/configuration#eslint

### CODE REVIEW

**Comment by kyleshay** [comment]
> No violations found. Woof!

:)

**Comment by kyleshay** [comment]
b-e-a-utiful.

awesome suggestion, @bhollis!

**Comment by bhollis** [comment]
I'm not sure I'm into sasslint. Wanna disable?

**Comment by bhollis** [comment]
I just went ahead and turned off the scss checks.

**Pull request merged**
