### PR TITLE
Simplify Loadout Optimizer

### PR DESCRIPTION
**Pull request by bhollis**
Before:
Screen Shot 2021-09-02 at 9 46 37 PM

After:
Screen Shot 2021-09-02 at 9 45 03 PM

Besides some code simplification, this rewords the help text for LO and strips out all the other information that distracted from explaining how it worked.

### CODE REVIEW

**Review by nev-r — COMMENTED** [review]
would love to see these sentences/paragraphs broken out into separate i18n keys for more formatting flexibility. the one lonnnnnng line is awful to read.

for i18n purposes less sentence/clause complexity is always desirable, so keep in mind some of the following suggestions aren't just for the sake of making changes to make changes.

> Drag stats into the order you want,
clearer: "Drag stats into the order of importance"
prefer maybe: "Drag the most [important? desired?] stats to the top"

> and disable the ones you don't care about
correctest english would be "and disable those you don't care about",
simpler would be "and disable stats you don't care about"
would prefer to say "ignore stats you don't care about" but that has a different connotation here. maybe "Set stats you don't care about to Ignore".

> Then choose an exotic, and any mods you want to use.
only feedback here is i would prefer a timing comma after "then"

> Only the stat bonuses from mods you choose are included
the base sentence is "only X is included" and when X is a long, qualified concept it's easy to lose the structure of the sentence. prefer
"[Loadout Optimizer/DIM] only includes the stat bonuses from mods you choose."

> any mods already on the armor are ignored.
the word "any" is kind of filler here

> Further filter eligible items from the search bar.
it's way too late in the sentence i realized filter was a verb. maybe:
"The search bar filters which items [Loadout Optimizer/DIM] [considers/tries/uses]." prefer "uses" probably.

**Comment by bhollis** [comment]
Awesome suggestions. I do have a redesign coming for this that'll break up the instructions, but for now maybe I can make an improvement.

**Comment by bhollis** [comment]
Screen Shot 2021-09-03 at 12 08 41 AM

**Comment by bhollis** [comment]
I suppose I need a line for whatever it is the Armor Upgrade button does too.

**Comment by nev-r** [comment]
looks good. i would kill the `Then,` _if_ the plan is to stick with bullet points

**Comment by bhollis** [comment]
@nev-r what do you think about this for the Armor Upgrades step:

"3. Choose what Armor Upgrades you're willing to do. This includes masterworking armor, or increasing or changing energy to fit the chosen mods."

**Review by ryan-rushton — APPROVED** [review]
Code looks good to me and the simplification of instructions is much nicer. I will let @nev-r make suggestions there as they are much better than me at wording things.

**Comment by nev-r** [comment]
in the light of day, it's weird that there's 3 instructions and one fact. might be better to stay consistent with something like
"Use the search bar to filter the items Loadout Optimizer uses."

> Choose what Armor Upgrades you're willing to do.

"Select" instead of choose more closely matches the button and costs us nothing. helps with quickly finding.
overall, "you're willing" feels.. wheedly? beggy?
overall, maybe something like "Select which Armor Upgrades the Optimizer can spend materials on."

>This includes masterworking armor, or increasing or changing energy to fit the chosen mods

Not into lists of present participles.. 
"The Optimizer may suggest masterworks to increase stats, or energy upgrades and element swaps to fit your requested mods."

considering "requested" because the word "select" was just used and "chosen" is a season name and has a weird "destined" fantasy connotation i can't ignore. maybe "chosen" is better because it matches the verb in bullet point 2. just a weird word.

**Pull request merged**
