### PR TITLE
background gradient cleanup

### PR DESCRIPTION
**Pull request by inexorableAce**
this cleans up some of the pages that didn't look so hot with the new gradient background and fixes a few other contrast issues it had. Also completes the look by adding the gradient to the menu bar. 

before
image

after
image

organizer before
image

organizer after
image

LO before
image

LO after
image

### CODE REVIEW

**Comment by inexorableAce** [comment]
the transparent search bar has some overlap with the navigation on mobile, fixed that.

**Comment by inexorableAce** [comment]
after looking at it a bit on mobile I think the header should stay black there. so I added that.

**Comment by inexorableAce** [comment]
added some extra whitespace to get back some separation between characters and the navigation / character emblems.

before > after
image

**Comment by bhollis** [comment]
This is great - but we'd set it up so that all the changes were behind a flag, so we could keep this on beta and not ship it to prod until we're ready for it.

**Comment by inexorableAce** [comment]
Got all the changes behind the .gradientBackground class 👍

**Comment by inexorableAce** [comment]
fixed up the settings page as well with semi-transparent settings boxes to match the rest of the changes, also toned down the collapsed inventory sections to semi transparent now that it's harder to accidentally collapse things

**Review by bhollis — APPROVED** [review]

**Pull request merged**
