### PR TITLE
Loadout builder updates

### PR DESCRIPTION
**Pull request by ericnelson0**
This PR is a general attempt to clean up the loadout builder and to reduce the memory requirements of it.

The major changes are mostly not front-facing. However, there are two main front-facing changes:
1. The ability to include rare (blue) items is now an option in the advanced section.
2. Sets with the same exact items are no longer displayed separately, instead the different configurations are listed below and can be expanded. 

example-loadout-update

The other changes affect how the sets are stored by only storing one copy of the set with its items. From the profiler I was seeing around 100MB of memory being used on "full" mode. 

Addresses issues:
#868, #861, #670

### CODE REVIEW

**Comment by ericnelson0** [comment]
@SunburnedGoose When you get a chance, can you see if chrome still crashes for you on full mode?

**Comment by kyleshay** [comment]
Nice job cleaning this up!! What are the different configurations for? Multiple ways to hit the same tier selected? Surprising there were so many ways for your 5/5/1 configuration.

Including blue will be really useful. We do need to make sure we're not "scaling" them though, like we do with legendary items (as they can't be infused to higher LL's.)

---

(Just a random thought--) This would be for a future PR, but what do you think of moving the "show all gear" button to instead live inside of the locked item boxes?

For example: you click on the chest plate locked item, and you get the popup like you do now, but instead of just seeing perks, at the top there is an option to switch between perks and items (and vendor item.) 

Just trying to figure out ways to clean up the page. It's an awesome tool, but to first time users might be a bit overwhelming. People are learning though.

**Comment by SunburnedGoose** [comment]
Avoiding scaling will be helpful.  We won't have any for a while.

**Comment by ericnelson0** [comment]
Ok, I'll put in a kill timer for using the "scaled" option the like we did for the item quality code. The different configurations are all the possible ways to configure the bonuses to get a tier with those items. I guess its possible to have at most 128 (2^7) of these. Do they need to be limited to at most 10 or so?

That'd be interesting to have the armor in there. Maybe there could be tabs on the popup for gear, vendor items, and perks?

**Comment by kyleshay** [comment]
Do all of the configurations yield different results (different arrangements of tiers/tier levels?) If so, we should say something about how they're different (or maybe it's not necessary to show them?) Just seeing a list of int/dis/str text might not explain enough. 

Once RoI goes live, and we've figured out the bonuses at each level, we'll need a way to allow exotics and legendaries to scale, but not blues (can't infuse them up, so they don't scale.) Kill timer works in the time being though. 👍 

---

Yeah, that's what I was sort of thinking. Just wondering if there is a way to consolidate the UI. It's an amazing tool, just trying to figure out how to tidy up the UX without losing any functionality or hiding stuff too deep.

**Comment by ericnelson0** [comment]
Oh, right. I forgot about the scaling not working for rare items. I'll work that out in this PR.

I know @SunburnedGoose had some ideas about the future of the builder too, but maybe we can keep discussing this in #872.

**Comment by SunburnedGoose** [comment]
@ericnelson0 Full worked for the first time ever. ;)

**Comment by SunburnedGoose** [comment]
When you get this in, I'll have a VIP that always complained about this test it out.

**Comment by ericnelson0** [comment]
It should be good to go. Just waiting on any more feedback.

**Comment by ericnelson0** [comment]
@kyleshay Those other configurations are hidden by default. Do you think they shouldn't be shown at all? Each one of them could potentially lead to different stats (but the same tier).

**Comment by kyleshay** [comment]
I'm not sure. Typically I am just looking for a specific int/dis/str. If I want to find another combo, I just change the dropdown. Maybe other people use it differently from me-- open to keeping it if people find it useful.

**Comment by SunburnedGoose** [comment]
Well, maybe some more information such as current light and cooldown points...  That's just a wall of text when you show all of them like that.  I'm fine with improving it iteratively so I'd be okay with letting it go for this release.

**Pull request merged**
