### PR TITLE
Upgrade babel

### PR DESCRIPTION
**Pull request by bhollis**

### CODE REVIEW

**Comment by bhollis** [comment]
This is where our 5% increase comes from!

**Comment by merceyz** [comment]
Try adding 
```js
version: require('@babel/runtime/package.json').version
```
here 
https://github.com/DestinyItemManager/DIM/blob/ab6172f7400847ca1977a2adfd351739742d8c5e/babel.config.js#L12

**Comment by merceyz** [comment]
Don't know if this will reduce the bundle size but you can also add 
```
corejs: require('core-js/package.json').version
```
here
https://github.com/DestinyItemManager/DIM/blob/ab6172f7400847ca1977a2adfd351739742d8c5e/babel.config.js#L49-L56
and here
https://github.com/DestinyItemManager/DIM/blob/ab6172f7400847ca1977a2adfd351739742d8c5e/babel.config.js#L58

**Comment by bhollis** [comment]
Nope, looks like that didn't help.

**Comment by bhollis** [comment]
Comparing the sources, it looks like after upgrading babel we're no longer transpiling to latest-browser-supported features. It's going all the way back to es5 - no arrow functions, etc.

**Comment by bhollis** [comment]
Filed https://github.com/babel/babel/issues/10945 - I dug through the babel-preset-env code but I don't see where it could be going wrong in understanding our babel-preset-env query.

**Comment by delphiactual** [comment]
we can temporarily add `"not android <= 79"` to package.json

**Comment by bhollis** [comment]
@delphiactual I have a more comprehensive fix in https://github.com/DestinyItemManager/DIM/pull/4839.

**Pull request closed without merging**
