### PR TITLE
Use font glyphs

### PR DESCRIPTION
**Pull request by nev-r**
this makes the bungie symbols font available instead of injecting SVGs for mid-text icons
image

it still retains the title attributes where possible for replaced text
image
image

is that, alone, valuable enough to be worth it? ehhhhh.
it kind of breaks even right now, but in follow-up changes, it could be a _very_ nice bundle reduction and performance help if we further reduce reliance on destiny-icons, and stop applying invert filter everywhere.
since the font only loads when needed, the vast majority of users will skip it if they don't click into banshee bounties or champion mods.

BUT. my value proposition is: how cool is this? :grin:
image

and who doesn't want this in their notes field
image

this is linked with d2ai https://github.com/DestinyItemManager/d2-additional-info/pull/287
per brief team discussion, this falls well within fair use of statically extracted assets, per TOS

### CODE REVIEW

**Comment by bhollis** [comment]
How do you input them for use in loadouts/notes?

**Review by delphiactual — APPROVED** [review]

**Comment by nev-r** [comment]
there's a bunch of common sites people use to copy the characters for steam names or whatever

**Comment by nev-r** [comment]
oh the other thing is this allows me to make a slug shotgun icon without a custom svg

**Review by bhollis — APPROVED** [review]
I love it!

**Pull request merged**
