### PR TITLE
CSV - wrap id in quotes

### LINKED ISSUE #3526: CSV Import not updating tags/notes
Steps to reproduce
 - Export csv
 - Edit csv file to include a tag and a note
 - Import csv file
 - Check item (tag and notes are not applied)

https://www.reddit.com/r/DestinyItemManager/comments/aczmrp/import_dim_data_from_file/

### PR DESCRIPTION
**Pull request by delphiactual**
Fixes #3526

### CODE REVIEW

**Comment by bhollis** [comment]
I did this another way - can you check out Beta and see if it's fixed?

**Comment by delphiactual** [comment]
It is not wrapping them in quotes, so libreoffice is still rounding them.

[destinyWeapons (3).csv.txt](https://github.com/DestinyItemManager/DIM/files/2731026/destinyWeapons.3.csv.txt)

**Comment by bhollis** [comment]
If you open that file, they definitely are quoted. Are you saying we need to do something else to force even quoted strings to be not treated as numbers?

**Comment by delphiactual** [comment]
Found it: `Format quoted field as text` without that selected it reverts them to numbers.

screenshot from 2019-01-06 17-07-25

**Pull request merged**
