### PR TITLE
Add a dynamic layout for each character that will maximize their light level

### PR DESCRIPTION
**Pull request by bhollis**
This will figure out, across all items in the account, what combination of items will maximize
light for the given character, and equip them as if it were a loadout. It will avoid changing
already equipped equipment if it wouldn't make a difference. It also correctly handles exotics.

### CODE REVIEW

**Comment by bhollis** [comment]
I've been using this to max out light before turning in engrams, and it is very convenient.

**Comment by SunburnedGoose** [comment]
I'll look at this later but Chris started one earlier. Need to check on
that.

**Comment by bhollis** [comment]
Is that https://github.com/DestinyItemManager/DIM/pull/237 ? I think that's different.

**Comment by SunburnedGoose** [comment]
It's different, but I want to make sure these are similar in their implementation.  Just need to check on each.

**Comment by bhollis** [comment]
They're pretty similar - I started from his change.

**Comment by thesamprice** [comment]
This has a bug where it transfers cloaks / class items to wrong classes.

**Comment by bhollis** [comment]
Could you describe some repro steps? 

-Ben

**Comment by bhollis** [comment]
This line should be guaranteeing that only items that match the character's class get included: https://github.com/DestinyItemManager/DIM/pull/298/files#diff-05c08d226cb720f46488bab9fc25296fR126

**Comment by thesamprice** [comment]
I merged your pull request into the master of the DIM, and tried it out.
I pushed what i was using here.
https://github.com/thesamprice/DIM/tree/sams_branch

It keeps transferring the artifact from other classes to the wrong class.
I have a 310 numinous web thats getting moved  to the wrong class. (Hunter/
Titan).
http://db.destinytracker.com/items/327933420-numinous-web


On Tue, Oct 20, 2015 at 2:33 AM, Ben Hollis <notifications@github.com>
wrote:

> This line should be guaranteeing that only items that match the
> character's class get included:
> https://github.com/DestinyItemManager/DIM/pull/298/files#diff-05c08d226cb720f46488bab9fc25296fR126
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DestinyItemManager/DIM/pull/298#issuecomment-149448436>
> .
>



-- 
Thank you,

Sam Price
(707) 742-3726

**Comment by thesamprice** [comment]
1. I think the problem is the artifacts are not containing classtypeName
   so your comparison is failing....
   2. Maybe I can make some sort of dictionary {"Hunter":3} can compare
   against classType?
   3.
   4. amount: 1
   5. ascended: false
   6. classType: 3
   7. classTypeName: "unknown"
   8. classified: undefined
   9. complete: false
   10. description: "A Hunter doesn't leave anything to chance."
   11. dmg: null
   12. equipment: true
   13. equipped: false
   14. hasAscendNode: false
   15. hasReforgeNode: false
   16. hasXP: true
   17. hash: 2815148218
   18. icon:
   "/common/destiny_content/icons/733e0a56b61ce70e5730d85287c2d8da.jpg"
   19. id: "6917529064233428543"
   20. inHoW: false
   21. index: "xxxxxxx"
   22. lockable: true
   23. locked: false
   24. maxStackSize: 1
   25. name: "Two-Sided Coin"
   26. nodes: Array[6]
   27. notransfer: false
   28. owner: "xxxxxxx"
   29. perks: Array[1]
   30. primStat: Object
   31. sort: "General"
   32. stats: Array[3]
   33. talentPerks: Array[12]
   34. tier: "Legendary"
   35. type: "Artifact"
   36. visible: true
   37. weaponClass: ""
   38. xpComplete: 0


On Tue, Oct 20, 2015 at 11:22 AM, Sam Price <thesamprice@gmail.com> wrote:

> I merged your pull request into the master of the DIM, and tried it out.
> I pushed what i was using here.
> https://github.com/thesamprice/DIM/tree/sams_branch
>
> It keeps transferring the artifact from other classes to the wrong class.
> I have a 310 numinous web thats getting moved  to the wrong class.
> (Hunter/ Titan).
> http://db.destinytracker.com/items/327933420-numinous-web
>
>
> On Tue, Oct 20, 2015 at 2:33 AM, Ben Hollis <notifications@github.com>
> wrote:
>
>> This line should be guaranteeing that only items that match the
>> character's class get included:
>> https://github.com/DestinyItemManager/DIM/pull/298/files#diff-05c08d226cb720f46488bab9fc25296fR126
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/DestinyItemManager/DIM/pull/298#issuecomment-149448436>
>> .
>>
>
>
>
> --
> Thank you,
>
> Sam Price
> (707) 742-3726
>



-- 
Thank you,

Sam Price
(707) 742-3726

**Comment by kyleshay** [comment]
I just wanted to say thank you @thesamprice for testing out this feature!

@bhollis I love this implementation, sorry that we have not yet gotten around to merging it in. I had a crazy week last week, but should be a bit more active now.

It's interesting that artifacts don't have a `classType` property on them. How odd...

**Comment by thesamprice** [comment]
Just looked into this, its a problem with your database of objects, not
with this merge request ...

Someone needs to modify api-manifest/items.json

You need to match on the itemTypeNames
"itemTypeName":"Hunter Artifact"
"itemTypeName":"Warlock Artifact"
"Titan Artifact"

and change the classType from 3 to the appropriate class type number.

    var chooseClass = {
      'warlock': 0,
      'titan': 1,
      'hunter': 2
    };

(Class type of 3 means any class I think.)



Only have looked at the dim code for past half hour so ....
Need to get back to work though..


On Tue, Oct 20, 2015 at 11:51 AM, kyle shay <notifications@github.com>
wrote:

> I just wanted to say thank you @thesamprice
> <https://github.com/thesamprice> for testing out this feature!
>
> @bhollis <https://github.com/bhollis> I love this implementation, sorry
> that we have not yet gotten around to merging it in. I had a crazy week
> last week, but should be a bit more active now.
>
> It's interesting that artifacts don't have a classType property on them.
> How odd...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DestinyItemManager/DIM/pull/298#issuecomment-149611743>
> .
>



-- 
Thank you,

Sam Price
(707) 742-3726

**Comment by bhollis** [comment]
I can hack on that (separate) patch tonight

**Comment by thesamprice** [comment]
It looks like items.js is built from
build/processBungieManifest.js

So you would need to hack that..
Not sure how
build/processBungieManifest.js is run though...

On Tue, Oct 20, 2015 at 12:01 PM, Ben Hollis <notifications@github.com>
wrote:

> I can hack on that (separate) patch tonight
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DestinyItemManager/DIM/pull/298#issuecomment-149615935>
> .
>



-- 
Thank you,

Sam Price
(707) 742-3726

**Comment by kyleshay** [comment]
most of the special cases for post-processing particular items usually ends up in the `dimStoreService.factory.js`

**Comment by thesamprice** [comment]
https://github.com/DestinyItemManager/DIM/pull/315

Not sure if I coded it up the best way, javascript is not my normal
language.

My stuff is still not getting max light lvl though.

On Tue, Oct 20, 2015 at 5:17 PM, kyle shay <notifications@github.com> wrote:

> most of the special cases for post-processing particular items usually
> ends up in the dimStoreService.factory.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DestinyItemManager/DIM/pull/298#issuecomment-149706189>
> .
>



-- 
Thank you,

Sam Price
(707) 742-3726

**Comment by kyleshay** [comment]
Thanks @thesamprice I'm looking at this now... I have two 303 ghosts (which are also my best) and it seems to want to move the one from my hunter instead of the one that's already on my warlock (on who I applied the max light loadout on)

My level 25 titan also ran in to a lot of errors applying a loadout, which I was expecting.

I want to get this feature in, because it's already working so well and it's *so* **awesome**! I no longer have to look in my vault or across character before trading in engrams. But, I can see users running into some issues with it. 

I'll leave this PR open for now, for anyone that wishes to work on it. 

Otherwise, I would be happy to create a max-light loadout branch so that multiple people can contribute to it. That way our dev branch stays clean.

**Comment by thesamprice** [comment]
It moves over 2 primary slots for me (Touch of Malice 310, 306 raid rifle), then stops.  I wonder if one of my special case weapon (Touch, Necro, sleeper) is messing with the code.

**Comment by thesamprice** [comment]
Change Line 165 and it works for me, along with the other mod.
                    var nonExotics = _.reject(itemsByType[otherType],
isExotic);



On Tue, Oct 20, 2015 at 6:12 PM, kyle shay <notifications@github.com> wrote:

> Thanks @thesamprice <https://github.com/thesamprice> I'm looking at this
> now... I have two 303 ghosts (which are also my best) and it seems to want
> to move the one from my hunter instead of the one that's already on my
> warlock (on who I applied the max light loadout on)
>
> My level 25 titan also ran in to a lot of errors applying a loadout, which
> I was expecting.
>
> I want to get this feature in, because it's already working so well and
> it's *so* *awesome*! I no longer have to look in my vault or across
> character before trading in engrams. But, I can see users running into some
> issues with it.
>
> I'll leave this PR open for now, for anyone that wishes to work on it.
>
> Otherwise, I would be happy to create a max-light loadout branch so that
> multiple people can contribute to it. That way our dev branch stays clean.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DestinyItemManager/DIM/pull/298#issuecomment-149717776>
> .
>



-- 
Thank you,

Sam Price
(707) 742-3726

**Comment by bhollis** [comment]
> One other thing I noticed; I have two 303 ghosts (which are also my best) and it seems to want to move the one from my hunter instead of the one that's already on my warlock (on who I applied the max light loadout on)

Hmm, it has a special provision for preferring the currently-equipped item if two items are of the same level, but if you just have the two ghosts hanging out (not equipped) it may choose one from another character (randomly). If that's what you're seeing, I think I can fix it.

> Change Line 165 and it works for me, along with the other mod.

Whoops, good catch! I'll patch that right away.

**Comment by bhollis** [comment]
OK, here's a commit that fixes the issues you folks pointed out and makes a couple other enhancements (see commit message).

**Comment by bhollis** [comment]
@kyleshay try it now - it should work the way you (and I) want now.

**Comment by kyleshay** [comment]
What are your thoughts on pulling from the vault before pulling from another character?

Something like; `ret -= (item.owner === 'vault') 0.1 : 0.2;`

Other than that- indeed it does! I pulled down the branch and am really happy with how this functions. 

------

We're currently undergoing some major refactoring to respond to the speed issues people have been experiencing in the app. @SunburnedGoose has made some major progress with that. We hope to merge that code in soon, and once that happens I'll go through and accept the PR's. I do want to prioritize the optimizations over some other PR's (I hope no one is offended.) 

I just do not want to continue losing our fans to other tools because they're currently experiencing a slower app than normal. I hope you can understand. I promise in the future that it won't be as difficult to get a PR accepted :( :+1:

**Comment by bhollis** [comment]
That makes tons of sense to me. Is there somewhere that you're coordinating all this? I have some perf improvements that I was going to go after as well, and some major new features as well.

**Comment by bhollis** [comment]
OK, now the tiebreaker preference for same-stat items is:

equipped by this character > owned by this character > vault > owned by another character

**Comment by SunburnedGoose** [comment]
@bhollis This is the issue that I'm using to track perf updates.  https://github.com/DestinyItemManager/DIM/issues/308

**Comment by bhollis** [comment]
Looks like Bungie got their own item manager out, with a very similar Maximize Light command.

**Comment by bhollis** [comment]
It's tempting to imagine Bungie copied this code, since it has the same bug regarding Artifacts as my code does...

**Comment by thesamprice** [comment]
I thought i fixed that.  Its probably related to the fact that artifacts
don't show the character class correctly in the item database.

On Mon, Nov 23, 2015 at 3:59 PM, Ben Hollis <notifications@github.com>
wrote:

> It's tempting to imagine Bungie copied this code, since it has the same
> bug regarding Artifacts as my code does...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DestinyItemManager/DIM/pull/298#issuecomment-159062434>
> .
>



-- 
Thank you,

Sam Price
(707) 742-3726

**Comment by bhollis** [comment]
That wasn't merged yet, unfortunately. (Also, I am of course joking about Bungie copying the code).

**Comment by SunburnedGoose** [comment]
There is a thread about it on Bnet about the artifacts lacking the class
affinity.

**Comment by bhollis** [comment]
Rebased to `origin/dev`. This should be merge-able. Since it's been over 2 months that this PR is open, I'd like it if this could be merged while the `perf` work continues, rather than waiting for it to land.

**Comment by bhollis** [comment]
I chatted with @SunburnedGoose and offered to merge a bunch of the open PRs and get a release ready. So here we go!

**Pull request merged**
