### PR TITLE
Rework item talent handling

### PR DESCRIPTION
**Pull request by bhollis**
This is a relatively big change that redoes all the talent grid stuff for items. I started off just wanting to fix `is:xpcomplete` but ended up redoing everything having to do with the talent grid. It should be much easier to get talent information now, and an especially important change is that the new info only considers talents that are actually on the item. Previously, we often included talents that *could* appear on that item in different rolls.

* [X] Refactor talent handling to produce a boiled-down view of the talent grid containing only talents that are actually on the item.
* [X] Change all existing code to use the new `talentGrid` object rather than the old properties that have been replaced or consolidated into it.
* [X] Show off the new info by displaying ~~the full~~ an abbreviated talent grid in the item info popup, with XP progress bars!

The new `talentGrid` property on items looks like this:

```javascript
{
  nodes: [...],
  xpComplete: true,
  totalXPRequired: 1000,
  totalXP: 12345,
  hasAscendNode: false,
  ascended: false,
  hasReforgeNode: false,
  infusable: true
}
```

Each node in the grid looks like this:

```javascript
{
  name: "Counterbalance",
  description: "blah blah",
  icon: "/someurl",
  xp: 500,
  xpRequired: 1684,
  column: 3,
  row: 1,
  activated: false,
  activatedAtGridLevel: 0,
  exclusiveInColumn: false,
  xpRequirementMet: false,
  unlocked: false
}
```

### CODE REVIEW

**Comment by bhollis** [comment]
image

Here's the only real visual change. I've changed the talent grid so it displays both active and inactive nodes, minus some boring nodes (like Year 1's endless damage/defense upgrades), plus the partial XP for inactive nodes.

**Comment by bhollis** [comment]
Here's one more potential tweak - an XP bar for the item as a whole, right under the item title. @kyleshay , @SunburnedGoose, what do you think?

image
image

**Comment by bhollis** [comment]
OK, here's another thought. This displays the full talent grid, exactly as it's shown in the game:
image

Because I'm generating this as an inline SVG image, I can set it to scale itself down to fit if it's too wide for the popup:
image

What do you think? You can check out this PR and give it a spin...

**Comment by bhollis** [comment]
I think this is pretty cool too:
image

**Comment by Mulchman** [comment]
Yeah, that's pretty dope. It's too bad the API doesn't let you change
subclass perks; it'd be a killer feature to save perks into loadouts.

**Comment by bhollis** [comment]
@Mulchman wouldn't it? It's also annoying that subclasses don't report their agility/armor/recovery stats.

**Comment by dheif** [comment]
+1 on the latest idea (full talent grid).

**Comment by SunburnedGoose** [comment]
Are there any changes to the filtering that we can do with all this extra data?  filtering by perk?

**Comment by bhollis** [comment]
We certainly can do that. I plan on doing a ton with search pretty soon.

**Comment by SunburnedGoose** [comment]
Would love to hear your thoughts and see how they can work with mobile.  There's a lot of capability there that has to be discoverable with mouse and fat fingers.

**Pull request merged**
