### PR TITLE
Webpack.

### PR DESCRIPTION
**Pull request by joshhunt**
Opening this PR now because I think this is in a pretty good state to get merged in.

From my understanding, there's only two blockers now:

- [x] Update travis config to build for Webpack
- [x] Resolve merge conflicts

### CODE REVIEW

**Comment by bhollis** [comment]
I'm super into it. Let's get one more release out then merge this.

**Comment by bhollis** [comment]
I pushed a merge and some fixes. I can't see any difference between this and the dev branch. Any last checks?

**Comment by joshhunt** [comment]
There's no limitation now requiring all the template files to be named blah.template.html anymore - do we want to renamed them to the shorter blah.html, or just leave them as is? I'm happy to do this

**Comment by bhollis** [comment]
Oh, that'd be nice!

**Comment by bhollis** [comment]
Woohoo, it's merged! Let's concentrate on cleaning up the last bits and moving ahead in our glorious Webpack-only future!

@SunburnedGoose I tagged the commit just before this as `before-webpack` in case you need to look it up quickly.

**Pull request merged**
