### PR TITLE
Handful more fixes

### PR DESCRIPTION
**Pull request by bhollis**
* Fix the error when equipping multiple items.
* Show an error message (and leave the progress up) if loading manifest fails.
* Update changelog

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Looks good.

**Comment by kyleshay** [comment]
no errors on load, nice @bhollis !! :D

**Comment by kyleshay** [comment]
shame we can't easily get record book info if it's in the vault..

**Comment by kyleshay** [comment]
this fixes #871 ?

**Comment by bhollis** [comment]
I commented on that... it sorta fixes it, sometimes.

**Pull request merged**
