### PR TITLE
Adding support for spreadsheet downloads

### PR DESCRIPTION
**Pull request by dcaslin**
This one should be good to go, I'll abandon the other PR.

### CODE REVIEW

**Comment by kyleshay** [comment]
@bhollis: let's get this merged in. functions really well. it does touch the settings page and I know some of that has been reworked slightly in #637 up to you if you want to merge this then settings, or vice versa.

**Comment by kyleshay** [comment]
@dcaslin in your console, would you mind running + fixing the eslint task?

`grunt eslint`

let me know if you have issues running that.

**Comment by bhollis** [comment]
Yeah if this passes eslint I'd like to merge. I can fix my stuff to not
conflict

**Comment by dcaslin** [comment]
Cool, didn't realize eslint handled all the style work. Should be good to go now, thanks!

**Comment by kyleshay** [comment]
thanks @dcaslin!! :)

**Pull request merged**
