### PR TITLE
Organizer tweaks

### PR DESCRIPTION
**Pull request by bhollis**
This switches the column selection to work off of the selected category, not the selected items. It also makes use of the wonderful new ItemCategoryHashes enum.

### CODE REVIEW

**Comment by bhollis** [comment]
Add a location column, fixes #5298

Screen Shot 2020-09-19 at 7 48 09 PM

**Comment by nev-r** [comment]
aaaaa location looks cool

**Review by nev-r — APPROVED** [review]

**Review by delphiactual — APPROVED** [review]
missing commit of 'src/app/organizer/DropDown.m.sc.d.ts'

**Comment by bhollis** [comment]
Wow that was confusing - it looks like at some point one CSS file imported a totally other one, which duplicated all the CSS and exported selectors.

**Pull request merged**
