### PR TITLE
[Webpack] Update with Dev

### PR DESCRIPTION
**Pull request by joshhunt**
My stab at merging in the dev branch and resolving the conflicts.

I'm not too sure what state the oAuth stuff is in, but 'regular' auth appears to work fine.

### CODE REVIEW

**Comment by delphiactual** [comment]
@joshhunt sorry about that was trying to pull this to my repo the way I normally do...

**Comment by bhollis** [comment]
Seems good. Wanna merge?

**Comment by bhollis** [comment]
I'd be happy to get this all merged to dev ASAP. What do folks think?

**Comment by SunburnedGoose** [comment]
Go for it.  Can you squash the commits or tag DEV before you do it so I can have an easy place to branch if I have to make the release for 3.16.  Don't trust making a build with this for production just yet.

**Comment by joshhunt** [comment]
OAuth and the Grunt task for making the Chrome extension should hopefully work now.

This should be able to go into dev now.

**Comment by bhollis** [comment]
Nice!

@SunburnedGoose you can always branch off the  merge commit's branch parent if you want a release (<commit>~). I think most Git UIs except for the GitHub commit log will show the graph. 

-Ben

**Pull request merged**
