### PR TITLE
Account for classified items in Vault

### PR DESCRIPTION
**Pull request by delphiactual**
Set Classified Weapons as `Heavy`
Set Classified Armor as `ClassItem`
Set Classified General as `Artifact`

### CODE REVIEW

**Comment by bhollis** [comment]
I'm afraid I don't have enough context about what problem you're solving to understand what this PR is doing. Could you explain the issue?

**Comment by delphiactual** [comment]
If a classified item is in the vault it does not have a bucket.type assigned therefore the count does not currently increase. This adds a bucket type and shows the classified item in the correct main group, but an assumed sub group, This effectively fixes https://github.com/DestinyItemManager/DIM/issues/1096

**Comment by bhollis** [comment]
Works for me! Could you add an appropriate changelog entry?

**Comment by delphiactual** [comment]
updated CHANGELOG.md

**Comment by bhollis** [comment]
Could you add a more detailed changelog entry? I don't know what "handle items" means.

**Pull request merged**
