### PR TITLE
Socket details viewer

### LINKED ISSUE #4277: PlugSet viewer
We should add a sheet that comes up when you tap a socket that has plug options, which shows all the options (plugsets or otherwise) and lets you preview the effect on stats from installing that mod.

### PR DESCRIPTION
**Pull request by bhollis**
This implements a socket details viewer that pops up when you click on a mod slot. This presents in a sheet that shows all the possible mods that could be socketed into that slot. Clicking on one of the mods shows details about it, its socketing cost, its stats, and what the total applied stat on the item would be.

Note that this completely replaces the tooltip for mods.

Screen Shot 2019-11-02 at 7 37 14 PM
Screen Shot 2019-11-02 at 7 37 33 PM
Screen Shot 2019-11-02 at 7 37 49 PM
Screen Shot 2019-11-02 at 7 37 55 PM

This fixes #4277.

### CODE REVIEW

**Comment by philkernick** [comment]
How is this going to flow on mobile?

**Comment by bhollis** [comment]
Pretty much the same. I can add screenshots later.

**Comment by sundevour** [comment]
this is wonderful

so, ui feedback:
• the whole table shifts a lot when you click around, due to changing apply costs & mod descriptions. a generous min-height on that lower container would be nice
• there's no PC hinting that mod slots are clickable at all. a mouseover highlight or outline, or cursor:pointer, would go a long way
• on desktop, scooting item popup to here
image
so existing stats & plugs are visible, would be absolutely incredible, but i know involves a lot of math
• display blue mod section on bar stats, when rendering the adjusted single stat to the right?

mechanic feedback:
• now or later, sort masterwork options numerically,  filter them down to actually attainable options (only higher numbers than current, only same mw stat for y2 weaps, swappable to other +10s on y1 weaps)

**Comment by bhollis** [comment]
I fixed the height changing, added cursor:pointer to the mods, and for fun made the whole thing keyboard navigable with tab/shift+tab.

Repositioning the tooltip would be awesome but I can't think of a great way to do it.

Adding the blue bar segments for the mod bits I'll leave as an exercise for somebody else.

Sorting and filtering masterworks also sounds like a fun task for somebody else.

**Pull request merged**
