### PR TITLE
This fixes an issue where search wasn't working in the vendor state a…

### PR DESCRIPTION
**Pull request by ericnelson0**
…fter moving the vendors over to a new directive

### CODE REVIEW

**Comment by bhollis** [comment]
Could you rebase on my change?

**Comment by bhollis** [comment]
(I've applied this change to my localized manifest-service branch, too)

**Comment by ericnelson0** [comment]
Looks like this still doesn't fix the problem. I'll look into it later today.

The issue is when stores are reloaded the reference are no longer valid in the components *I believe*

**Comment by ericnelson0** [comment]
I'll create and issue and keep investigating this.

**Pull request closed without merging**
