### PR TITLE
Add a tip for how to scroll Compare on iOS

### PR DESCRIPTION
**Pull request by bhollis**
Not the prettiest, but it puts the information out there.

Screen Shot 2021-09-11 at 12 37 34 PM

### CODE REVIEW

**Comment by delphiactual** [comment]
https://fontawesome.com/v5.9/icons/hand-scissors?style=solid
https://fontawesome.com/v5.9/icons/arrows-alt-h?style=solid

**Review by delphiactual — APPROVED** [review]

**Comment by inexorableAce** [comment]
Yeah I was actually looking for something similar. Would be great if font awesome had a two finger scroll icon. I've see them before. 

This is definitely better than nothing but it's really easy to miss I had to look for a few to find it in the image provided.

**Comment by bhollis** [comment]
Yeah originally I was going to have a little two-finger icon with an animation but...

**Review by nev-r — APPROVED** [review]

**Review by inexorableAce — APPROVED** [review]

**Pull request merged**
