### PR TITLE
Add "max power minus mods" to characters

### PR DESCRIPTION
**Pull request by bhollis**
screen shot 2017-09-16 at 6 35 01 pm

Open to suggestions on how to display or word this - just seemed like something useful to put in that space.

Caveat - I don't know if this stat actually represents your "drop power". It's unnamed, but it seems right (except for on uninitialized characters).

### CODE REVIEW

**Comment by bhollis** [comment]
There's some discussion in the slack, but we're not sure this actually means what we think it means. It appears to change based on what you have equipped.

**Comment by SunburnedGoose** [comment]
This is the value used to evaluate your drops. Max Base Power?

**Comment by bhollis** [comment]
I figured out how to actually do base power (code is in the infusion PR) and it's complicated (basically requires scanning the mods to find ones that boost power and subtracting them out). I've put in some feature requests over at the API project. In the meantime, I could make this accurate, but only if folks had a preference for where and how to display it.

**Comment by lightmaster** [comment]
I like this feature, although my lack of stylish creativity prohibits me from coming up with any suggestions on how to make it look.

**Comment by bhollis** [comment]
I'll rework this tomorrow

**Comment by bhollis** [comment]
Closing - #2201 does this way better.

**Pull request closed without merging**
