### PR TITLE
Pull from Postmaster improvements

### PR DESCRIPTION
**Pull request by bhollis**
1. Fix the bug I introduced where, in fixing the problem of always moving too many items to make room for a postmaster pull, I would accidentally move too few. Now we move just the right amount.
2. For D2, replace the "Make room for postmaster" menu item with "Pull X items from postmaster". The number in the menu helps you know if you need to pull without having to scroll down, and it takes into account things like not saying you can pull emblems when you are already full of emblems. I debated whether this should replace "Make room" or sit aside it, but making the split button didn't leave room for the long labels, and honestly I don't see when you'd want to make room for everything in the postmaster but not take it all. If you only want some things, just transfer them one by one. Never go to the Tower under any circumstances.
3. To go along with the theme of Farming Mode, which is to prevent your Postmaster from filling up, Farming Mode will now pull everything from the Postmaster as a first step, before making room for pickups.

Diffs are getting pretty messy as I'm opportunistically converting things to TypeScript as I encounter them. I did a fair bit of refactoring to move a ton of the auto-loadout and postmaster handling code into their own files instead of being inside the loadout menu component, and I've started using async/await, which is syntactically wonderful even though it generates some scary code (thanks iOS 10).

### CODE REVIEW

**Comment by bhollis** [comment]
screen shot 2018-01-23 at 11 45 45 pm

**Comment by bhollis** [comment]
screen shot 2018-01-25 at 9 06 30 pm
screen shot 2018-01-25 at 9 07 08 pm

Trying to leave "Make Room" as an option is tough - I can barely fix it if I make things a bit confusing, and I bet other localizations will get cut off.

**Comment by SunburnedGoose** [comment]
Can you put the count as a badge over the envelope icon and save the extra pixels?

**Comment by SunburnedGoose** [comment]
What do you see when there are no items in the postmaster?

**Comment by bhollis** [comment]
> Can you put the count as a badge over the envelope icon and save the extra pixels?

I thought of that - let me try it.

> What do you see when there are no items in the postmaster?

I've switched to hiding the whole row when there's nothing it would do.

**Comment by duckmanBR** [comment]
> I actually decided not to do pull during farming. I figure some people use it as extra vault space, and if they keep farming on, it shouldn't get more full.

But then, if the postmaster is full the item is lost, isn't?
Maybe implement a threshold, pulling on farm mode only the nth/n-1th? (i really don't know the size of the postmaster)

**Comment by SunburnedGoose** [comment]
Farming mode does a good job keeping things out of the postmaster while you're active in combat/playing.  If you're at the vendor, and you're spamming tokens, then you need to keep an eye on your overflow.

**Comment by bhollis** [comment]
screen shot 2018-01-28 at 11 55 56 pm

Is this any better? I'm still not sure it'll work on all languages, and it's kind of obtuse. I'm just not sure when anybody would need to only make room without pulling all, where they wouldn't be better served by just pulling from the postmaster one by one.

**Comment by SunburnedGoose** [comment]
It's great.  I'm going to make a couple issues that I'll look at next time I play and reference this.

**Pull request merged**
