### PR TITLE
Adding platform selection

### PR DESCRIPTION
**Pull request by 48klocs**
This adds an (optional) setting. If you're working with Destiny 2 and have either ratings fetch or reviews fetch turned on, you can additionally choose to filter by platform (this change happened on the API side). If it's left unset, the API doesn't care and treats it as though "All" were selected.

If you do change it, we instantly flush all cached ratings and re-fetch based off of the new platform you selected.

If this looks like a weirdly big PR, it's because it was based on top of my branch for perk hinting in D2 (npm still causes pain on branch switching).

shouts-to-my-mouse-heads

### CODE REVIEW

**Comment by duckmanBR** [comment]
How about something like a "same as selected account"?

**Comment by 48klocs** [comment]
That gets messy because people play on multiple platforms.

It could be an enhancement after it lands if it takes into account current platform selection.

**Comment by bhollis** [comment]
Rebase from master? There are a lot of changes from the other PR in here.

`git fetch origin && git rebase origin/master`

**Comment by 48klocs** [comment]
Yikes that's garish. I'll work on tidying it up.

**Comment by 48klocs** [comment]
I'll roll a fresh branch.

**Pull request closed without merging**
