### PR TITLE
Green Dev logo

### PR DESCRIPTION
**Pull request by joshhunt**
Build upon @bhollis's work to restore different logos for prod and beta, as well as introducing a new dev icon :)

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
http://paletton.com/#uid=30G0t0kpXsvg4BWl5uHt3nqwtix

Did you pull a color from a tool like this?

**Comment by joshhunt** [comment]
Logos are from @bhollis's PR https://github.com/DestinyItemManager/DIM/pull/1391

**Comment by joshhunt** [comment]
(see now that because I cherry-picked that commit rather than merging in or branching off it's created a new commit hash with me as the creator. sorry @bhollis!)

**Comment by SunburnedGoose** [comment]
I've followed up over there to see about desaturating the color instead of adding green.

**Comment by bhollis** [comment]
Switched the dev icons to be the same as the beta icons so this can be merged.

**Pull request merged**
