### PR TITLE
Reporting objectively bad reviews

### PR DESCRIPTION
**Pull request by 48klocs**
#1908 brought up the fact that, the internet being what it is, some folks are wont to get into yelling matches for no particularly good reason or cuss about the meta or whatever.

To cut down on the noise, there's a new API for reporting reviews and the UI to support calling it. Flagging and reporting is a two-step process to cut down on accidental clicks. When you report a user, DIM additionally notes the offending reviewer's membership ID and won't show any reviews from them on that or any other item. I'm not trying to build out upvoting or enable people going on weird slapfight crusades, I'm just giving them the tools to make bad reviews from unhappy people go away.

dont-forget-to-flag-and-ignore

In dev mode, the storage pane gives you the ability to clear out all ignored users.

secret-google-cheat-codes

I updated the styling around reporting a bit, because I wasn't happy with red text on dark gray and unstyled buttons. Functionality's the same otherwise.

flagging-with-style

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
I do not agree with clicking on the body of the review to start this operation. Too easy to invoke.

**Comment by 48klocs** [comment]
Which is why I made it a two step operation. I wanted to make it usable for folks on mobile devices as well as desktops, but I also didn't want to make it too easy to accidentally report reviews. I tried making the hamburger menu icon on each review  the only clickable piece, but that is a small area to hit. 

I'm open to suggestions on improving the UI around this workflow.

**Comment by 48klocs** [comment]
OK, UI tweaks are in place - edit review and the bigger flag icon are more obviously links and the flag icon (for starting reporting) is the only place you can click to get the flagging rolling.

You can also see that the review you report immediately disappears from view. That sticks (except in dev mode where you can purge flagged users) and you won't see any more reviews from the offending party ever.

live-coding-up-a-less-error-prone-report-ui

**Comment by bhollis** [comment]
Looks great! Merging!

**Pull request merged**
