### PR TITLE
Replace react-view-pager with Framer Motion

### LINKED ISSUE #5109: Replace react-view-pager
Time to write my own view pager, since react-view-pager is deprecated. See https://github.com/DestinyItemManager/DIM/issues/5100 for an issue this causes.

It'd be great if I could get the new view pager to work for both inventory and character header at the same time - the current setup with hammer swipes for inventory and header drag is janky.

We should also look at whether we should switch from react-spring/react-use-gesture to Framer Motion.

### PR DESCRIPTION
**Pull request by bhollis**
This brings [Framer Motion](https://www.framer.com/api/motion/) into the picture to replace react-view-pager which is no longer supported. This is only step 1, which replaces the previous functionality with as close as I could get to the same behavior. After this is in I'll start having fun with it, by introducing things like a wraparound carousel of tiles and swiping directly on the inventory page. Framer Motion is a big library, but I also plan on replacing our usage of react-spring, react-use-gesture, react-hammerjs, and react-transition-group with it, and using it for a bunch of new features that beg for some nice interactive animation. Framer Motion is incredibly cool and makes a lot of complex animations easy, though for this interaction I had to dive down to a lower level almost immediately and do a bunch of my own logic. Also, as a demo, collapsible headers now animate.

Fixes #5109, and *should* fix issues when switching active character in game and reloading.

I did end up changing a few existing things - most notably, the D1 Loadout Optimizer now uses a PageWithMenu like basically every other DIM page, and there's no longer a horizontal-layout CharacterSelect component:

Before:
Screen Shot 2020-10-14 at 11 30 47 PM

After:
Screen Shot 2020-10-14 at 11 30 41 PM

### CODE REVIEW

**Comment by kyleshay** [comment]
The animation on collapsible tiles is NICE!!

I'm running into some slight problems with the character header on mobile - both on a device and in the chrome browser responsive view. It's responding to my swipes- but while i'm swiping to the side, it wants to bounce back and won't actually perform the swipe.

**Comment by bhollis** [comment]
Hmm, I've run into that too and I don't know why. It'll refuse to swipe for a while, and then suddenly start working again. I have no idea why.

**Comment by bhollis** [comment]
I actually think it might be a conflict w/ HammerJS

**Review by kyleshay — APPROVED** [review]
works great !!!

**Review by nev-r — APPROVED** [review]
working smoothly for me

**Pull request merged**
